// blockedTerms.js (backend, CommonJS) — GENERATED from the frontend canonical
// list at src/moderation/blockedTerms.js. Do not edit by hand; regenerate if the
// frontend list changes. Two tiers / two policies — see the fix/dict-safety report.
// SLURS: never accepted/scored/displayed. PROFANITY: never displayed/generated.
const SLURS = ["nigger","niggers","nigga","niggas","niggaz","negro","negros","negroes","coon","coons","darkie","darkies","darky","jigaboo","jigaboos","sambo","sambos","spearchucker","spearchuckers","porchmonkey","tarbaby","pickaninny","pickaninnies","piccaninny","gook","gooks","chink","chinks","chinky","jap","japs","paki","pakis","raghead","ragheads","towelhead","towelheads","sandnigger","sandniggers","wetback","wetbacks","beaner","beaners","spic","spics","spick","spicks","spik","spiks","wop","wops","dago","dagos","dagoes","guido","kike","kikes","yid","yids","heeb","heebs","hymie","shylock","pikey","pikeys","injun","injuns","redskin","redskins","squaw","squaws","abo","abbo","boong","boongs","chinaman","chinamen","golliwog","golliwogs","golliwogg","quadroon","quadroons","octoroon","octoroons","mulatto","mulattos","mulattoes","polack","polacks","polak","kaffir","kaffirs","kafir","kafirs","faggot","faggots","faggy","fag","fags","fagot","fagots","dyke","dykes","poofter","poofters","shemale","shemales","tranny","trannie","trannies","ladyboy","ladyboys","transvestite","transvestites","retard","retards","retarded","retardo","tard","tards","mongoloid","mongoloids","spastic","spastics","spaz","spazz","spazzes"];
const PROFANITY = ["fuck","fucks","fucker","fuckers","fucking","fucked","fuckin","fuckwit","fuckhead","fuckface","clusterfuck","motherfucker","motherfuckers","motherfucking","mofo","stfu","wtf","shit","shits","shitty","shitting","shitted","shithead","shitheads","shithole","shitholes","shithouse","shitbag","shitface","bullshit","horseshit","dipshit","batshit","dogshit","cunt","cunts","cunty","twat","twats","bitch","bitches","bitchy","bitching","bitched","bastard","bastards","asshole","assholes","arsehole","arseholes","asshat","asshats","asswipe","asswipes","jackass","jackasses","dumbass","dumbasses","smartass","fatass","goddamn","goddamned","goddamnit","douche","douches","douchebag","douchebags","wanker","wankers","wank","tosser","tossers","prick","pricks","bollocks","bollock","piss","pisses","pissed","pissing","pisser","pissflaps","cock","cocks","cocksucker","cocksuckers","dick","dicks","dickhead","dickheads","dickwad","dickface","dickwad","penis","penises","dildo","dildos","dildoes","boner","boners","schlong","schlongs","pussy","pussies","vagina","vaginas","vulva","vulvas","clit","clits","clitoris","clitorises","tit","tits","titty","titties","tittie","tiddies","boob","boobs","boobies","nipple","nipples","scrotum","nutsack","ballsack","cum","cums","cumming","cumshot","cumshots","jizz","jizzed","jism","jizm","sex","sexy","sexed","sexting","fornicate","fornication","masturbate","masturbates","masturbation","masturbating","handjob","handjobs","blowjob","blowjobs","rimjob","rimjobs","rimming","fellatio","cunnilingus","buttfuck","buttfucker","buttplug","buttholes","butthole","fisting","felch","felching","smegma","queef","queefs","orgasm","orgasms","orgasmic","orgy","orgies","horny","erection","erections","boinking","porn","porno","pornos","pornography","hentai","nsfw","xxx","whore","whores","whoring","slut","sluts","slutty","skank","skanks","skanky","hooker","hookers","nympho","nymphos","sodomy","sodomize","sodomise","bestiality","incest","molest","molests","molested","molesting","molester","molesters","molestation","pedophile","pedophiles","paedophile","paedophiles","pedo","rape","rapes","raped","rapist","rapists","raping","turd","turds"];
const ALL_TERMS = [...new Set([...SLURS, ...PROFANITY])];
const SLUR_SET = new Set(SLURS);
const ALL_SET = new Set(ALL_TERMS);
function norm(t){ return String(t).trim().toLowerCase().replace(/[^a-z]/g,""); }
function isSlur(t){ const s=norm(t); return s.length>0 && SLUR_SET.has(s); }
function isBlockedForDisplay(t){ const s=norm(t); return s.length>0 && ALL_SET.has(s); }
function isBlockedAnswer(a, scope){ const set = scope==="accept"?SLUR_SET:ALL_SET; const c=norm(a); if(c&&set.has(c)) return true; const w=String(a).toLowerCase().split(/\s+/).map(norm).filter(Boolean); return w.length===1 && set.has(w[0]); }
module.exports = { SLURS, PROFANITY, ALL_TERMS, isSlur, isBlockedForDisplay, isBlockedAnswer, norm };
