// categoryPacks.js
// Maps every gen9 Category Blitz category name to its pack id, built from the
// gen9.raw.json pack groupings. Used to tag gen9 categories with their pack when
// they are appended to RAW_CATEGORIES in categoryBlitzLogic.js. Keys match the
// gen9 accept-list keys (categoryAnswers/gen9.js) exactly.
const CATEGORY_PACKS = {
  // movies
  "Marvel Cinematic Universe Villains": "movies",
  "Sitcoms": "movies",
  "Animated Movies": "movies",
  "DC Comics Superheroes": "movies",
  "Star Wars Planets": "movies",
  "Anime Villains": "movies",
  "Disney Animated Movie Characters": "movies",
  "James Bond Villains": "movies",
  "Horror Movie Monsters": "movies",
  "Pixar Movies": "movies",
  "Studio Ghibli Movies": "movies",
  "Famous TV Detectives": "movies",
  "Marvel Superheroes": "movies",
  "Video Game Movies": "movies",
  "James Bond Movies": "movies",
  "Friends Characters": "movies",
  "Harry Potter Spells": "movies",
  "Disney Villains": "movies",
  "Star Wars Ships": "movies",
  "Animated Movie Characters": "movies",
  "Animated TV Shows": "movies",
  "Horror Movie Characters": "movies",
  "Harry Potter Characters": "movies",
  "Sitcom Characters": "movies",
  "Lord of the Rings characters": "movies",
  "Breaking Bad characters": "movies",
  "The Office characters": "movies",
  "Batman villains": "movies",
  "Star Wars Characters": "movies",
  "SpongeBob SquarePants Characters": "movies",
  "Batman Characters": "movies",
  // gaming
  "Mario Kart Items": "gaming",
  "Minecraft Mobs": "gaming",
  "Pokemon Gen 1": "gaming",
  "Video game consoles": "gaming",
  "Legend of Zelda characters": "gaming",
  "Street Fighter characters": "gaming",
  "Mario characters": "gaming",
  "Fortnite weapons": "gaming",
  "Sonic the Hedgehog characters": "gaming",
  "Minecraft blocks": "gaming",
  "Overwatch heroes": "gaming",
  "Call of Duty games": "gaming",
  "Super Smash Bros. fighters": "gaming",
  "Grand Theft Auto games": "gaming",
  "Pac-Man ghosts": "gaming",
  "Animal Crossing Villagers": "gaming",
  "League of Legends Champions": "gaming",
  "PlayStation Exclusive Games": "gaming",
  "Mortal Kombat characters": "gaming",
  "Halo weapons": "gaming",
  "Resident Evil games": "gaming",
  "Metroid bosses": "gaming",
  "Street Fighter games": "gaming",
  "Final Fantasy summons": "gaming",
  "Among Us colors": "gaming",
  "Elden Ring bosses": "gaming",
  "Kingdom Hearts characters": "gaming",
  "Genshin Impact playable characters": "gaming",
  "Street Fighter moves": "gaming",
  "Minecraft biomes": "gaming",
  "Portal items and elements": "gaming",
  "Team Fortress 2 classes": "gaming",
  "Half-Life weapons": "gaming",
  "Skyrim races": "gaming",
  "Dark Souls bosses": "gaming",
  "Fall Guys rounds": "gaming",
  "Stardew Valley villagers": "gaming",
  "Among Us maps": "gaming",
  "Fallout factions": "gaming",
  "Dark Souls weapons": "gaming",
  "Super Mario power-ups": "gaming",
  "Mortal Kombat games": "gaming",
  "Call of Duty weapons": "gaming",
  "Roblox games": "gaming",
  "Mortal Kombat fighters": "gaming",
  "Valorant agents": "gaming",
  "Minecraft tools and weapons": "gaming",
  "Angry Birds birds": "gaming",
  "Nintendo consoles and handhelds": "gaming",
  "Half-Life enemies": "gaming",
  "Fallout creatures": "gaming",
  "Among Us tasks": "gaming",
  "Minecraft Ore Blocks": "gaming",
  "Pac-Man Characters": "gaming",
  "Nintendo Switch Games": "gaming",
  "Minecraft potions": "gaming",
  "Pac-Man maze fruits": "gaming",
  "Apex Legends characters": "gaming",
  "The Sims games": "gaming",
  "Donkey Kong characters": "gaming",
  "Tekken characters": "gaming",
  "Fighting game franchises": "gaming",
  "Video game hardware manufacturers": "gaming",
  "Video game hardware": "gaming",
  // food
  "Pizza toppings": "food",
  "Breakfast cereal brands": "food",
  "Types of pasta": "food",
  "Ice cream flavors": "food",
  "Soda brands": "food",
  "Sushi types": "food",
  "Girl Scout cookies": "food",
  "Fast food chains": "food",
  "Types of cheese": "food",
  "Cocktails": "food",
  "Fruits": "food",
  "Sandwich types": "food",
  "Potato chip brands": "food",
  "Coffee drinks": "food",
  "Vegetables": "food",
  "Types of nuts": "food",
  "Bakery items": "food",
  "Types of apples": "food",
  "Candy bars": "food",
  "Popular spices and herbs": "food",
  "Types of pie": "food",
  "Energy drink brands": "food",
  "Types of seafood": "food",
  "Types of tea": "food",
  "Popular condiments": "food",
  "Types of melon": "food",
  "Types of bread": "food",
  "Popular snack cakes": "food",
  "Types of steak": "food",
  "Types of mushrooms": "food",
  "Milk alternatives": "food",
  "Types of pancakes": "food",
  "Popular salad dressings": "food",
  "Types of tacos": "food",
  "Types of peppers": "food",
  "Popular yogurt brands": "food",
  "Types of beans": "food",
  "Types of squash": "food",
  "Types of BBQ meat": "food",
  "Popular food brands": "food",
  "Types of beer": "food",
  "International cuisines": "food",
  "Types of citrus fruit": "food",
  "Types of donuts": "food",
  "Popular sports drinks": "food",
  "Types of rice": "food",
  "Types of berries": "food",
  "Popular dipping sauces": "food",
  "Types of cookies": "food",
  "Types of eggs": "food",
  "Types of potatoes": "food",
  "Types of jerky": "food",
  "Types of soup": "food",
  "Types of cake": "food",
  "Ben & Jerry's flavors": "food",
  "Types of soup dumplings & dim sum": "food",
  "Hot sauce brands": "food",
  "Mexican food dishes": "food",
  "Italian pasta sauces": "food",
  "Herbal teas & infusions": "food",
  "Dried fruits": "food",
  "Frozen treats": "food",
  "Breakfast pastries": "food",
  "Types of BBQ sauce": "food",
  "Types of dried meat": "food",
  "Frozen desserts": "food",
  "Breakfast meats": "food",
  "Indian food dishes": "food",
  "Types of pasta sauces": "food",
  // animals
  "Dog breeds": "animals",
  "Trees": "animals",
  "Gemstones": "animals",
  "Ocean animals": "animals",
  "Dinosaurs": "animals",
  "Cat breeds": "animals",
  "Zoo animals": "animals",
  "Birds": "animals",
  "Flowers": "animals",
  "Insects": "animals",
  "Farm animals": "animals",
  "Reptiles and amphibians": "animals",
  "Marsupials": "animals",
  "Mushrooms and fungi": "animals",
  "Coniferous trees": "animals",
  "Predatory mammals": "animals",
  "Nuts and seeds": "animals",
  "Big cats": "animals",
  "Primates": "animals",
  "Succulents and cacti": "animals",
  "Horses and ponies": "animals",
  "Rodents": "animals",
  "Bears": "animals",
  "Aquarium fish": "animals",
  "Venomous snakes": "animals",
  "Herbs and spices": "animals",
  "Marine mammals": "animals",
  "Wild canines": "animals",
  "Arachnids": "animals",
  "Bovine breeds": "animals",
  "Types of clouds": "animals",
  "Weather phenomena": "animals",
  "Birds of prey": "animals",
  "Houseplants": "animals",
  "Prehistoric creatures": "animals",
  "Edible berries": "animals",
  "Nocturnal animals": "animals",
  "Antelope and deer species": "animals",
  "Types of rocks": "animals",
  "Marine invertebrates": "animals",
  "Citrus fruits": "animals",
  "Landforms": "animals",
  "Freshwater fish": "animals",
  "Flightless birds": "animals",
  "Root vegetables": "animals",
  "Wildflowers": "animals",
  "Types of Sharks": "animals",
  "Types of Natural Disasters": "animals",
  "Wild animals of the savanna": "animals",
  "Butterfly species": "animals",
  "Types of coral": "animals",
  "Farm crops": "animals",
  "Cattle breeds": "animals",
  "Venomous or poisonous animals": "animals",
  "Natural landscape features": "animals",
  "Types of mushrooms and fungi": "animals",
  "Wild animals of the desert": "animals",
  "Types of deciduous trees": "animals",
  // sports
  "NBA teams": "sports",
  "Baseball positions": "sports",
  "NFL teams": "sports",
  "Soccer positions": "sports",
  "Martial arts": "sports",
  "NHL teams": "sports",
  "Tennis equipment": "sports",
  "Cycling disciplines": "sports",
  "Major League Baseball teams": "sports",
  "Water sports": "sports",
  "English Premier League clubs": "sports",
  "Formula 1 constructors": "sports",
  "Gymnastics events": "sports",
  "WNBA teams": "sports",
  "MLS teams": "sports",
  "Golf clubs": "sports",
  "Cricket fielding positions": "sports",
  "Rugby positions": "sports",
  "Track and field events": "sports",
  "Types of sports balls": "sports",
  "College football bowl games": "sports",
  "Active Formula 1 tracks": "sports",
  "Major professional sports leagues": "sports",
  "Professional cycling teams": "sports",
  "Volleyball positions": "sports",
  "Bowling terms": "sports",
  "Boxing weight classes": "sports",
  "NASCAR Cup Series tracks": "sports",
  "Professional wrestling promotions": "sports",
  "NCAA Division I conferences": "sports",
  "Chess pieces": "sports",
  "Swimming strokes": "sports",
  "Events in a decathlon": "sports",
  "Football positions": "sports",
  "Types of sports rackets": "sports",
  "Basketball positions": "sports",
  "Extreme sports": "sports",
  "Ice hockey positions": "sports",
  "Olympic sports": "sports",
  "Active NFL stadiums": "sports",
  "Grand Slam tennis tournaments": "sports",
  "Active NBA Arenas": "sports",
  "Heisman Trophy Winners": "sports",
  "Tour de France Jerseys": "sports",
  "Winter Olympic sports": "sports",
  "Tennis strokes": "sports",
  "Major League Baseball awards": "sports",
  "Professional tennis surface types": "sports",
  "Professional tennis tournaments": "sports",
  "Badminton equipment": "sports",
  "Professional tennis equipment": "sports",
  "Table tennis equipment": "sports",
  "Major League Soccer teams": "sports",
  "Professional wrestling championships": "sports",
  // world
  "Greek gods": "world",
  "South American countries": "world",
  "Planets in our solar system": "world",
  "US states": "world",
  "Norse gods": "world",
  "Famous landmarks": "world",
  "European capitals": "world",
  "US presidents": "world",
  "African countries": "world",
  "Asian countries": "world",
  "Egyptian gods": "world",
  "Major world rivers": "world",
  "Canadian provinces and territories": "world",
  "Roman gods": "world",
  "Oceanian countries": "world",
  "US state capitals": "world",
  "Japanese prefectures": "world",
  "Mythical creatures": "world",
  "Zodiac constellations": "world",
  "World mountain ranges": "world",
  "Latin American countries": "world",
  "US National Parks": "world",
  "Ancient civilizations": "world",
  "Seven Wonders of the Ancient World": "world",
  "US state nicknames": "world",
  "Middle Eastern countries": "world",
  "Arthurian legend characters": "world",
  "US states bordering the Atlantic Ocean": "world",
  "Caribbean countries": "world",
  "Dwarf planets": "world",
  "Greek heroes": "world",
  "Major world deserts": "world",
  "British monarchs": "world",
  "US state abbreviations": "world",
  "Major world islands": "world",
  "Greek monsters and beasts": "world",
  "Great Lakes of North America": "world",
  "Signers of the US Declaration of Independence": "world",
  "Inca deities": "world",
  "World seas": "world",
  "Hindu deities": "world",
  "Australian states and territories": "world",
  "Irish counties": "world",
  "Aztec deities": "world",
  "World oceans": "world",
  "World deserts": "world",
  "Major world peninsulas": "world",
  "South American capitals": "world",
  "US states by name": "world",
  "Scandinavian countries": "world",
  "Historical capitals": "world",
  "Norse mythological realms": "world",
  // music
  "Musical instruments": "music",
  "Music genres": "music",
  "Beatles albums": "music",
  "Orchestra sections": "music",
  "String instruments": "music",
  "Musical notes": "music",
  "Woodwind instruments": "music",
  "Classical composers": "music",
  "Percussion instruments": "music",
  "Brass instruments": "music",
  "Guitar brands": "music",
  "Key signatures": "music",
  "Rolling Stone's 500 Greatest Albums": "music",
  "Rock and Roll Hall of Fame Inductees": "music",
  "Music streaming services": "music",
  "Major record labels": "music",
  "Electronic music subgenres": "music",
  "Standard drum kit components": "music",
  "Keyboard instruments": "music",
  "Music awards": "music",
  "Music notation symbols": "music",
  "Boy bands": "music",
  "Types of guitars": "music",
  "Pink Floyd albums": "music",
  "Electric guitar models": "music",
  "Music tempo markings": "music",
  // science
  "Chemical elements": "science",
  "Human bones": "science",
  "Cell organelles": "science",
  "Noble gases": "science",
  "Types of rock": "science",
  "Human organs": "science",
  "Lab equipment": "science",
  "SI units": "science",
  "Subatomic particles": "science",
  "States of matter": "science",
  "Human body systems": "science",
  "Types of vitamins": "science",
  "Types of fossils": "science",
  "Layers of the atmosphere": "science",
  "Types of biomes": "science",
  "Types of simple machines": "science",
  "Types of chemical bonds": "science",
  "Taxonomic ranks": "science",
  "Types of electromagnetic radiation": "science",
  "Human endocrine glands": "science",
  "Greenhouse gases": "science",
  // history
  "Roman emperors": "history",
  "Ancient wonders": "history",
  "Egyptian pharaohs": "history",
  "World War II battles": "history",
  "US Founding Fathers": "history",
  "Ancient Empires": "history",
  "Renaissance figures": "history",
  "Famous explorers": "history",
  "Medieval English Monarchs": "history",
  "US states by admission order": "history",
  "Japanese Shoguns": "history",
  "Greek City-States": "history",
  "US Civil War Battles": "history",
  "Historical Eras": "history",
  "Ancient Greek city-states": "history",
  "Cold War events": "history",
  "US Civil War Generals": "history",
  "Russian Tsars": "history",
  "Ancient Mesopotamian Civilizations": "history",
  "Ancient Mesopotamian Rulers": "history",
  "Medieval titles": "history",
  "Ancient Persian Kings": "history",
  "US First Ladies": "history",
  // geography
  "Oceans": "geography",
  "The Great Lakes": "geography",
  "Scandinavian and Nordic countries": "geography",
  "Active volcanoes": "geography",
  "Central American countries": "geography",
  "US states bordering Canada": "geography",
  "US states bordering the Pacific Ocean": "geography",
  // mythology
  "Japanese yokai": "mythology",
  "Mythical birds": "mythology",
  "Mythological locations": "mythology",
  "Greek Titans": "mythology",
  "Constellations from myth": "mythology",
  "Celtic myth figures": "mythology",
  "Mythical weapons and artifacts": "mythology",
  "Mesopotamian deities": "mythology",
  "Slavic mythological figures": "mythology",
  "Polynesian mythological figures": "mythology",
  "Inuit mythological figures": "mythology",
  "Mythical creatures by culture": "mythology",
  "Mythical swords and blades": "mythology",
  // literature
  "Shakespeare plays": "literature",
  "Literary genres": "literature",
  "Jane Austen novels": "literature",
  "Roald Dahl books": "literature",
  "Charles Dickens novels": "literature",
  "Literary devices": "literature",
  "Harry Potter books": "literature",
  "Sherlock Holmes stories": "literature",
  "Dystopian novels": "literature",
  "Famous poets": "literature",
  "Greek epics": "literature",
  "Greek tragedies": "literature",
  "Classic dystopian novels": "literature",
  "Greek and Roman mythology figures": "literature",
  "Classic novels": "literature",
  "Literary characters": "literature",
  "Literary Nobel Prize winners": "literature",
  // tech
  "Programming languages": "tech",
  "Web browsers": "tech",
  "Social media platforms": "tech",
  "Computer components": "tech",
  "Operating systems": "tech",
  "Cryptocurrencies": "tech",
  "Apple products": "tech",
  "File formats": "tech",
  "Tech companies": "tech",
  "Keyboard keys": "tech",
  "Video streaming services": "tech",
  "Phone brands": "tech",
  "Smart home devices": "tech",
  "Computer ports and connectors": "tech",
  "Gaming Consoles": "tech",
  "Video Game Genres": "tech",
  "E-commerce websites": "tech",
  "File sharing and cloud storage services": "tech",
  // art
  "Famous painters": "art",
  "Art movements": "art",
  "Painting tools": "art",
  "Famous museums": "art",
  "Sculpture materials": "art",
  "Architecture styles": "art",
  "Art mediums": "art",
  "Drawing tools": "art",
  "Photography terms": "art",
  "Pottery types": "art",
  "Famous sculptures": "art",
  "Famous paintings": "art",
  "Art periods": "art",
  "Printmaking techniques": "art",
  "Art elements": "art",
  // tv
  "Game shows": "tv",
  "HBO series": "tv",
  "Cooking shows": "tv",
  "Streaming original series": "tv",
  "Reality TV shows": "tv",
  "TV networks": "tv",
  "Talk shows": "tv",
  "British sitcoms": "tv",
  "TV award shows": "tv",
  "Sitcoms from the 90s": "tv",
  "TV science fiction series": "tv",
  "TV crime dramas": "tv",
  "TV medical dramas": "tv",
  "TV animation networks": "tv",
  "TV game show hosts": "tv",
  "TV westerns": "tv",
  "TV soap operas": "tv",
};

module.exports = CATEGORY_PACKS;
