// categoryAnswers.js
// Pre-generated accept-lists for Category Blitz, one Set of valid lowercase
// answers per category. These replace live Gemini API calls during gameplay:
// validation is now a synchronous Set lookup (fast, free, deterministic,
// works offline). Keys MUST match the CATEGORIES strings in
// categoryBlitzLogic.js exactly (including 'Shoes brands').
//
// All entries are lowercase. Singular/plural and common alternate forms are
// included on purpose so reasonable answers get accepted. Multi-word answers
// are allowed. gemini.js is intentionally no longer imported by the game
// logic, but is kept in the repo for possible future use.

module.exports = {
  'Things in a kitchen': new Set([
    'knife', 'knives', 'fork', 'forks', 'spoon', 'spoons', 'plate', 'plates',
    'bowl', 'bowls', 'cup', 'cups', 'mug', 'mugs', 'glass', 'glasses', 'pot',
    'pots', 'pan', 'pans', 'frying pan', 'saucepan', 'saucepans', 'kettle',
    'kettles', 'toaster', 'toasters', 'oven', 'ovens', 'stove', 'stoves',
    'microwave', 'microwaves', 'fridge', 'fridges', 'refrigerator',
    'refrigerators', 'freezer', 'freezers', 'dishwasher', 'dishwashers',
    'sink', 'sinks', 'faucet', 'tap', 'taps', 'blender', 'blenders', 'mixer',
    'mixers', 'whisk', 'whisks', 'spatula', 'spatulas', 'ladle', 'ladles',
    'colander', 'strainer', 'grater', 'graters', 'peeler', 'peelers',
    'can opener', 'bottle opener', 'corkscrew', 'cutting board',
    'chopping board', 'rolling pin', 'measuring cup', 'measuring spoon',
    'tongs', 'oven mitt', 'oven mitts', 'pot holder', 'apron', 'aprons',
    'dish towel', 'towel', 'towels', 'sponge', 'sponges', 'dish soap',
    'napkin', 'napkins', 'cabinet', 'cabinets', 'cupboard', 'cupboards',
    'drawer', 'drawers', 'counter', 'countertop', 'pantry', 'spice rack',
    'salt', 'pepper', 'salt shaker', 'pepper grinder', 'sugar bowl', 'teapot',
    'teapots', 'coffee maker', 'coffee machine', 'coffee pot', 'espresso machine',
    'food processor', 'slow cooker', 'crock pot', 'rice cooker',
    'pressure cooker', 'air fryer', 'waffle iron', 'griddle', 'wok', 'woks',
    'baking sheet', 'baking tray', 'cookie sheet', 'muffin tin', 'cake pan',
    'pie dish', 'casserole dish', 'mixing bowl', 'dutch oven', 'skillet',
    'skillets', 'cleaver', 'paring knife', 'bread knife', 'steak knife',
    'butter knife', 'chopsticks', 'saucer', 'saucers', 'bottle', 'bottles',
    'jar', 'jars', 'container', 'containers', 'tupperware', 'lunchbox',
    'thermos', 'trivet', 'timer', 'scale', 'kitchen scale', 'dish rack',
    'trash can', 'garbage can', 'broom', 'mop', 'paper towel', 'foil',
    'aluminum foil', 'plastic wrap', 'parchment paper', 'ice tray',
    'ice cube tray', 'knife block', 'utensil', 'utensils', 'cutlery',
    'silverware', 'tea kettle', 'serving spoon', 'slotted spoon',
    'garlic press', 'zester', 'mortar', 'pestle', 'mandoline', 'nutcracker',
    'potato masher', 'basting brush', 'meat thermometer', 'pizza cutter',
    'cheese grater', 'butter dish', 'bread box', 'cookie jar', 'dish drainer',
    'range', 'range hood', 'stool', 'table', 'chair', 'clock', 'ice maker',
  ]),

  'Countries in Europe': new Set([
    'albania', 'andorra', 'armenia', 'austria', 'azerbaijan', 'belarus',
    'belgium', 'bosnia', 'bosnia and herzegovina', 'herzegovina', 'bulgaria',
    'croatia', 'cyprus', 'czech republic', 'czechia', 'denmark', 'england',
    'estonia', 'faroe islands', 'finland', 'france', 'georgia', 'germany',
    'gibraltar', 'great britain', 'greece', 'guernsey', 'holland', 'hungary',
    'iceland', 'ireland', 'republic of ireland', 'isle of man', 'italy',
    'jersey', 'kazakhstan', 'kosovo', 'latvia', 'liechtenstein', 'lithuania',
    'luxembourg', 'macedonia', 'north macedonia', 'malta', 'moldova', 'monaco',
    'montenegro', 'netherlands', 'the netherlands', 'northern ireland',
    'norway', 'poland', 'portugal', 'romania', 'russia', 'russian federation',
    'san marino', 'scotland', 'serbia', 'slovakia', 'slovenia', 'spain',
    'sweden', 'switzerland', 'turkey', 'turkiye', 'ukraine', 'united kingdom',
    'uk', 'the uk', 'britain', 'vatican', 'vatican city', 'the vatican',
    'holy see', 'wales', 'crimea', 'transnistria', 'svalbard', 'sardinia',
    'sicily', 'corsica', 'greenland', 'catalonia', 'bavaria', 'andalusia',
    'flanders', 'wallonia', 'cornwall',
  ]),

  'Animals that can swim': new Set([
    'fish', 'shark', 'sharks', 'whale', 'whales', 'dolphin', 'dolphins',
    'seal', 'seals', 'sea lion', 'sea lions', 'otter', 'otters', 'beaver',
    'beavers', 'duck', 'ducks', 'goose', 'geese', 'swan', 'swans', 'penguin',
    'penguins', 'turtle', 'turtles', 'sea turtle', 'tortoise', 'frog', 'frogs',
    'toad', 'toads', 'newt', 'salamander', 'crocodile', 'crocodiles',
    'alligator', 'alligators', 'snake', 'snakes', 'sea snake', 'eel', 'eels',
    'octopus', 'octopuses', 'squid', 'jellyfish', 'crab', 'crabs', 'lobster',
    'lobsters', 'shrimp', 'prawn', 'starfish', 'stingray', 'manta ray', 'ray',
    'manatee', 'manatees', 'dugong', 'walrus', 'walruses', 'platypus',
    'hippopotamus', 'hippo', 'hippos', 'elephant', 'elephants', 'tiger',
    'tigers', 'polar bear', 'polar bears', 'bear', 'bears', 'dog', 'dogs',
    'cat', 'cats', 'horse', 'horses', 'pig', 'pigs', 'cow', 'cows', 'goat',
    'goats', 'sheep', 'rat', 'rats', 'mouse', 'mice', 'capybara', 'capybaras',
    'orca', 'orcas', 'killer whale', 'beluga', 'narwhal', 'porpoise',
    'seahorse', 'seahorses', 'salmon', 'tuna', 'cod', 'trout', 'bass',
    'catfish', 'goldfish', 'guppy', 'piranha', 'piranhas', 'swordfish',
    'marlin', 'barracuda', 'clownfish', 'angelfish', 'pufferfish', 'sardine',
    'herring', 'mackerel', 'flounder', 'halibut', 'carp', 'perch', 'pike',
    'minnow', 'koi', 'anchovy', 'mantis shrimp', 'krill', 'urchin',
    'sea urchin', 'sea cucumber', 'cuttlefish', 'nautilus', 'anemone',
    'coral', 'plankton', 'tadpole', 'tadpoles', 'axolotl', 'iguana', 'iguanas',
    'monitor lizard', 'water snake', 'anaconda', 'python', 'moose', 'elk',
    'deer', 'buffalo', 'rhinoceros', 'rhino', 'leopard', 'jaguar', 'gorilla',
    'monkey', 'monkeys', 'water buffalo', 'muskrat', 'mink', 'nutria',
    'pelican', 'flamingo', 'heron', 'loon', 'cormorant', 'puffin', 'albatross',
    'gull', 'seagull', 'kingfisher', 'human', 'humans', 'snail', 'crayfish',
    'lungfish', 'sunfish', 'stickleback', 'tench', 'gar',
  ]),

  'Things that are red': new Set([
    'apple', 'apples', 'tomato', 'tomatoes', 'strawberry', 'strawberries',
    'cherry', 'cherries', 'raspberry', 'raspberries', 'cranberry',
    'pomegranate', 'watermelon', 'rose', 'roses', 'tulip', 'poppy', 'blood',
    'fire', 'fire truck', 'fire engine', 'stop sign', 'stoplight', 'red light',
    'brick', 'bricks', 'ruby', 'rubies', 'lipstick', 'nail polish',
    'ketchup', 'hot sauce', 'chili', 'chili pepper', 'chilli', 'red pepper',
    'bell pepper', 'cayenne', 'paprika', 'salsa', 'marinara', 'tomato sauce',
    'wine', 'red wine', 'cardinal', 'robin', 'ladybug', 'ladybird', 'crab',
    'lobster', 'flamingo', 'santa', 'santa suit', 'santa hat', 'rudolph nose',
    'heart', 'hearts', 'valentine', 'cape', 'matador cape', 'flag', 'red flag',
    'rust', 'lava', 'magma', 'ember', 'embers', 'coal', 'sunset', 'sunburn',
    'rash', 'blush', 'cheeks', 'tongue', 'firetruck', 'ferrari', 'fire hydrant',
    'red car', 'sports car', 'barn', 'red barn', 'london bus', 'double decker bus',
    'telephone box', 'phone booth', 'mailbox', 'postbox', 'red carpet',
    'rug', 'crayon', 'marker', 'pen', 'ink', 'paint', 'red paint', 'balloon',
    'balloons', 'kite', 'beet', 'beetroot', 'radish', 'radishes', 'red onion',
    'kidney bean', 'red bean', 'cranberries', 'currant', 'currants',
    'red grapes', 'rhubarb', 'plum', 'red plum', 'chili sauce', 'sriracha',
    'tabasco', 'pepperoni', 'ham', 'bacon', 'meat', 'steak', 'raw meat',
    'salmon', 'tuna', 'crab shell', 'coral', 'maple leaf', 'autumn leaf',
    'fall leaves', 'poinsettia', 'carnation', 'geranium', 'hibiscus',
    'amaryllis', 'red dress', 'ruby slippers', 'firefighter', 'clown nose',
    'red panda', 'fox', 'cardinal bird', 'scarlet macaw', 'red fox',
    'red velvet', 'red velvet cake', 'cherry pie', 'jam', 'jelly', 'sauce',
    'ruby gem', 'garnet', 'red squirrel', 'tomato soup', 'red apple',
    'fire ant', 'red ant', 'wound', 'scab', 'red eye', 'rosacea', 'sunburned skin',
    'stop button', 'red button', 'fire alarm', 'fire extinguisher',
    'cherry tomato', 'pizza sauce', 'red marker', 'red crayon', 'red shirt',
    'red shoes', 'red sox', 'red riding hood', 'cherry blossom', 'raspberries',
    'cranberries', 'red bull', 'fire truck siren', 'lava lamp',
  ]),

  'Musical instruments': new Set([
    'guitar', 'guitars', 'electric guitar', 'acoustic guitar', 'bass',
    'bass guitar', 'violin', 'violins', 'viola', 'cello', 'cellos',
    'double bass', 'piano', 'pianos', 'keyboard', 'keyboards', 'organ',
    'harpsichord', 'accordion', 'accordions', 'drum', 'drums', 'drum kit',
    'snare drum', 'bass drum', 'bongo', 'bongos', 'conga', 'congas', 'cymbal',
    'cymbals', 'tambourine', 'triangle', 'xylophone', 'marimba', 'vibraphone',
    'glockenspiel', 'timpani', 'maracas', 'castanets', 'gong', 'flute',
    'flutes', 'piccolo', 'clarinet', 'clarinets', 'oboe', 'bassoon',
    'saxophone', 'saxophones', 'sax', 'trumpet', 'trumpets', 'trombone',
    'trombones', 'tuba', 'tubas', 'french horn', 'cornet', 'bugle', 'harmonica',
    'harmonicas', 'harp', 'harps', 'banjo', 'banjos', 'mandolin', 'mandolins',
    'ukulele', 'ukuleles', 'sitar', 'lute', 'lyre', 'zither', 'dulcimer',
    'recorder', 'recorders', 'pan flute', 'panpipes', 'ocarina', 'bagpipes',
    'didgeridoo', 'kazoo', 'whistle', 'tin whistle', 'fiddle', 'cajon',
    'tabla', 'djembe', 'steel drum', 'steelpan', 'cowbell', 'woodblock',
    'chimes', 'wind chimes', 'bells', 'handbell', 'synthesizer', 'synth',
    'theremin', 'melodica', 'concertina', 'harmonium', 'electric piano',
    'grand piano', 'upright piano', 'pipe organ', 'electric organ', 'rhodes',
    'turntable', 'turntables', 'drum machine', 'sampler', 'sequencer',
    'autoharp', 'balalaika', 'bouzouki', 'koto', 'shamisen', 'erhu', 'pipa',
    'guzheng', 'oud', 'charango', 'cavaquinho', 'vihuela', 'theorbo',
    'mbira', 'kalimba', 'shakuhachi', 'dizi', 'nose flute', 'jaw harp',
    "jew's harp", 'rattle', 'shaker', 'claves', 'guiro', 'vibraslap',
    'timbales', 'taiko', 'tom', 'tom tom', 'hi hat', 'ride cymbal',
    'crash cymbal', 'splash cymbal', 'celesta', 'spinet', 'clavichord',
    'flugelhorn', 'euphonium', 'sousaphone', 'alto sax', 'tenor sax',
    'soprano sax', 'baritone sax', 'english horn', 'contrabassoon',
    'bass clarinet', 'slide whistle', 'crumhorn', 'shawm', 'fife',
    'electric violin', 'twelve string guitar', 'slide guitar', 'lap steel',
    'pedal steel', 'theorbo lute', 'hurdy gurdy', 'nyckelharpa', 'washboard',
    'spoons', 'jug', 'kick drum', 'floor tom',
  ]),

  'Things that are round': new Set([
    'ball', 'balls', 'circle', 'sphere', 'wheel', 'wheels', 'tire', 'tires',
    'coin', 'coins', 'plate', 'plates', 'clock', 'wheel', 'donut', 'donuts',
    'doughnut', 'bagel', 'bagels', 'cookie', 'cookies', 'pizza', 'pancake',
    'pancakes', 'orange', 'oranges', 'apple', 'apples', 'grape', 'grapes',
    'melon', 'watermelon', 'cantaloupe', 'pumpkin', 'pumpkins', 'tomato',
    'pea', 'peas', 'cherry', 'cherries', 'blueberry', 'blueberries', 'pearl',
    'pearls', 'marble', 'marbles', 'bubble', 'bubbles', 'balloon', 'balloons',
    'globe', 'globes', 'planet', 'planets', 'earth', 'sun', 'moon', 'star',
    'button', 'buttons', 'ring', 'rings', 'wedding ring', 'hula hoop', 'hoop',
    'tennis ball', 'basketball', 'baseball', 'soccer ball', 'golf ball',
    'volleyball', 'bowling ball', 'beach ball', 'ping pong ball', 'cannonball',
    'eyeball', 'eye', 'pupil', 'wheel of cheese', 'cheese wheel', 'lollipop',
    'gumball', 'jawbreaker', 'meatball', 'meatballs', 'orb', 'dome', 'igloo',
    'ferris wheel', 'steering wheel', 'dial', 'knob', 'doorknob', 'lens',
    'magnifying glass', 'compass', 'cd', 'dvd', 'record', 'vinyl', 'frisbee',
    'plate', 'saucer', 'cymbal', 'tambourine', 'drum', 'manhole cover',
    'manhole', 'coaster', 'wreath', 'halo', 'crown', 'medal', 'medallion',
    'badge', 'sticker', 'pie', 'tart', 'wheel barrow wheel', 'roundabout',
    'porthole', 'window', 'bullseye', 'dartboard', 'target', 'clock face',
    'watch face', 'cap', 'bottle cap', 'lid', 'manhole lid', 'pellet',
    'bb', 'bead', 'beads', 'bouncy ball', 'crystal ball', 'snowball',
    'dough ball', 'rice ball', 'orange ball', 'wheel rim', 'rim', 'tube',
    'pipe', 'ring toss', 'inner tube', 'tire swing', 'wheel of fortune',
    'plate of food', 'pancake stack', 'cookie cake', 'cinnamon roll',
    'onion ring', 'onion rings', 'cheerio', 'cheerios', 'lifesaver',
    'mint', 'pill', 'tablet', 'capsule', 'clockwork', 'gear', 'gears',
    'cog', 'wheel hub', 'curling stone', 'discus', 'shot put', 'pinwheel',
    'satellite dish', 'plate spinner', 'yo yo', 'top', 'spinning top',
    'fishbowl', 'fish bowl', 'aquarium', 'soccerball', 'kickball',
    'medicine ball', 'stress ball', 'crystal', 'pebble', 'boulder', 'rock',
  ]),

  'Sports played with a ball': new Set([
    'soccer', 'football', 'american football', 'basketball', 'baseball',
    'tennis', 'golf', 'volleyball', 'rugby', 'cricket', 'bowling', 'softball',
    'handball', 'dodgeball', 'kickball', 'racquetball', 'squash', 'badminton',
    'table tennis', 'ping pong', 'water polo', 'lacrosse', 'field hockey',
    'polo', 'netball', 'pool', 'billiards', 'snooker', 'bocce', 'bocce ball',
    'petanque', 'futsal', 'beach volleyball', 'beach soccer', 'gaelic football',
    'australian football', 'aussie rules', 'hurling', 'pickleball', 'pelota',
    'jai alai', 'sepak takraw', 'kabaddi', 'tetherball', 'four square',
    'paddleball', 'paddle tennis', 'platform tennis', 'real tennis',
    'fives', 'shinty', 'bandy', 'floorball', 'korfball', 'tchoukball',
    'kin ball', 'speedball', 'wallyball', 'kickabout', 'foosball',
    'table football', 'street ball', 'streetball', 'wiffle ball',
    'stickball', 'rounders', 'teeball', 't ball', 'tee ball', 'cornhole',
    'boules', 'marbles', 'croquet', 'mini golf', 'miniature golf',
    'disc golf', 'goalball', 'sitting volleyball', 'wheelchair basketball',
    'wheelchair rugby', 'fistball', 'broomball', 'underwater rugby',
    'underwater hockey', 'octopush', 'gateball', 'roller derby', 'roller hockey',
    'inline hockey', 'street hockey', 'ball hockey', 'box lacrosse',
    'beach handball', 'indoor soccer', 'indoor cricket', 'paddle',
    'padel', 'frontenis', 'basque pelota', 'canoe polo', 'cycle polo',
    'bike polo', 'elephant polo', 'horse polo', 'water basketball',
    'rugby league', 'rugby union', 'touch rugby', 'touch football',
    'flag football', 'arena football', 'powerchair football', 'blind football',
    'futnet', 'footvolley', 'sepaktakraw', 'throwball', 'newcomb ball',
    'prison ball', 'matball', 'mat ball', 'kanjam', 'spikeball', 'roundnet',
    'bossaball', 'jorkyball', 'cestoball', 'pato', 'hornussen', 'pesapallo',
    'oina', 'lapta', 'brannboll', 'vigoro', 'vitilla', 'goalkeeper drills',
    'tennis ball cricket', 'box ball', 'wall ball', 'handball court',
    'shooty', 'three flies up', 'kickball game', 'association football',
    'gridiron', 'gridiron football', 'tag rugby', 'oztag', 'oz tag',
    'beach tennis', 'soft tennis', 'wheelchair tennis', 'footgolf',
    'foot golf', 'teqball', 'headis', 'stoolball', 'trapball', 'trap ball',
    'danish longball', 'calcio fiorentino', 'calcio storico', 'harpastum',
    'episkyros', 'rounders ball', 'beach cricket', 'street cricket',
    'tennis polo', 'goal ball',
  ]),

  'Things you find at a beach': new Set([
    'sand', 'sandcastle', 'shell', 'shells', 'seashell', 'seashells', 'wave',
    'waves', 'ocean', 'sea', 'water', 'sun', 'sunshine', 'towel', 'towels',
    'beach towel', 'umbrella', 'umbrellas', 'beach umbrella', 'sunscreen',
    'sunblock', 'sunglasses', 'hat', 'sun hat', 'bikini', 'swimsuit',
    'bathing suit', 'swim trunks', 'flip flops', 'flip flop', 'sandals',
    'bucket', 'pail', 'shovel', 'spade', 'beach ball', 'frisbee', 'kite',
    'surfboard', 'surfboards', 'boogie board', 'bodyboard', 'paddleboard',
    'kayak', 'canoe', 'boat', 'boats', 'sailboat', 'jet ski', 'lifeguard',
    'lifeguard tower', 'lifeguard chair', 'pier', 'boardwalk', 'dock',
    'cooler', 'ice chest', 'picnic', 'snorkel', 'mask', 'flippers', 'fins',
    'goggles', 'crab', 'crabs', 'hermit crab', 'starfish', 'sea star',
    'jellyfish', 'fish', 'seagull', 'seagulls', 'gull', 'pelican', 'seaweed',
    'kelp', 'driftwood', 'rock', 'rocks', 'pebble', 'pebbles', 'coral',
    'sand dollar', 'sand dollars', 'tide', 'tide pool', 'lighthouse', 'palm tree',
    'palm trees', 'dune', 'dunes', 'sandbar', 'cliff', 'cove', 'bay', 'lagoon',
    'reef', 'horizon', 'breeze', 'wind', 'beach chair', 'lawn chair',
    'lounge chair', 'hammock', 'tent', 'cabana', 'volleyball', 'volleyball net',
    'sand toys', 'beach bag', 'flag', 'buoy', 'buoys', 'anchor', 'rope',
    'fishing rod', 'fishing pole', 'bait', 'net', 'fishing net', 'message in a bottle',
    'bottle', 'sandals', 'water bottle', 'ice cream', 'popsicle', 'hot dog',
    'snow cone', 'shade', 'sandcastles', 'spray', 'mist', 'foam', 'sea foam',
    'crabs hole', 'footprints', 'beach grass', 'seashore', 'shoreline',
    'breakwater', 'jetty', 'groyne', 'sun lotion', 'beach cart', 'wagon',
    'parasol', 'visor', 'rash guard', 'wetsuit', 'snorkel mask', 'inner tube',
    'float', 'pool float', 'inflatable', 'raft', 'paddle', 'oar', 'oars',
    'sea glass', 'mussel', 'clam', 'clams', 'oyster', 'barnacle', 'urchin',
    'sea urchin', 'anemone', 'minnows', 'turtle', 'dolphin', 'whale',
    'beach umbrella stand', 'sunbather', 'swimmer', 'surfer', 'beach volleyball',
    'sand bucket', 'metal detector', 'kite surfer', 'windsurfer',
  ]),

  'Fruits': new Set([
    'apple', 'apples', 'banana', 'bananas', 'orange', 'oranges', 'grape',
    'grapes', 'strawberry', 'strawberries', 'blueberry', 'blueberries',
    'raspberry', 'raspberries', 'blackberry', 'blackberries', 'cherry',
    'cherries', 'peach', 'peaches', 'pear', 'pears', 'plum', 'plums',
    'pineapple', 'pineapples', 'mango', 'mangoes', 'mangos', 'watermelon',
    'watermelons', 'melon', 'cantaloupe', 'honeydew', 'kiwi', 'kiwis',
    'lemon', 'lemons', 'lime', 'limes', 'grapefruit', 'tangerine',
    'tangerines', 'clementine', 'clementines', 'mandarin', 'apricot',
    'apricots', 'nectarine', 'nectarines', 'pomegranate', 'pomegranates',
    'fig', 'figs', 'date', 'dates', 'coconut', 'coconuts', 'papaya',
    'papayas', 'guava', 'guavas', 'passion fruit', 'dragon fruit',
    'star fruit', 'starfruit', 'lychee', 'lychees', 'longan', 'rambutan',
    'durian', 'jackfruit', 'persimmon', 'persimmons', 'quince', 'cranberry',
    'cranberries', 'gooseberry', 'gooseberries', 'currant', 'currants',
    'elderberry', 'mulberry', 'mulberries', 'boysenberry', 'cloudberry',
    'huckleberry', 'tomato', 'tomatoes', 'avocado', 'avocados', 'olive',
    'olives', 'cucumber', 'plantain', 'plantains', 'tangelo', 'kumquat',
    'kumquats', 'ugli fruit', 'pomelo', 'breadfruit', 'soursop', 'cherimoya',
    'sapodilla', 'tamarind', 'jujube', 'salak', 'mangosteen', 'feijoa',
    'loquat', 'medlar', 'damson', 'greengage', 'sloe', 'rhubarb', 'cantaloupes',
    'red grapes', 'green grapes', 'concord grapes', 'granny smith', 'gala apple',
    'fuji apple', 'honeycrisp', 'macintosh', 'golden delicious', 'red delicious',
    'crab apple', 'crabapple', 'seville orange', 'blood orange', 'navel orange',
    'valencia orange', 'satsuma', 'yuzu', 'bergamot', 'finger lime', 'calamansi',
    'acai', 'goji berry', 'gojis', 'physalis', 'cape gooseberry', 'tamarillo',
    'horned melon', 'kiwano', 'snake fruit', 'wax apple', 'rose apple',
    'custard apple', 'sugar apple', 'ackee', 'bilberry', 'lingonberry',
    'marionberry', 'tayberry', 'loganberry', 'jostaberry', 'serviceberry',
    'chokeberry', 'aronia', 'sea buckthorn', 'pawpaw', 'medlars', 'pumpkin',
    'squash', 'cranberries', 'raisins', 'prunes', 'sultana', 'sultanas',
  ]),

  'Things that fly': new Set([
    'bird', 'birds', 'plane', 'planes', 'airplane', 'airplanes', 'aeroplane',
    'jet', 'jets', 'helicopter', 'helicopters', 'drone', 'drones', 'rocket',
    'rockets', 'spaceship', 'spaceships', 'spacecraft', 'satellite',
    'satellites', 'balloon', 'balloons', 'hot air balloon', 'blimp', 'zeppelin',
    'glider', 'gliders', 'hang glider', 'paraglider', 'kite', 'kites',
    'frisbee', 'boomerang', 'butterfly', 'butterflies', 'moth', 'moths',
    'bee', 'bees', 'wasp', 'wasps', 'hornet', 'fly', 'flies', 'housefly',
    'mosquito', 'mosquitoes', 'dragonfly', 'dragonflies', 'firefly',
    'fireflies', 'ladybug', 'ladybird', 'beetle', 'beetles', 'gnat', 'midge',
    'locust', 'cicada', 'grasshopper', 'eagle', 'eagles', 'hawk', 'hawks',
    'falcon', 'owl', 'owls', 'crow', 'crows', 'raven', 'sparrow', 'sparrows',
    'pigeon', 'pigeons', 'dove', 'doves', 'robin', 'robins', 'cardinal',
    'bluejay', 'blue jay', 'parrot', 'parrots', 'flamingo', 'swan', 'swans',
    'goose', 'geese', 'duck', 'ducks', 'seagull', 'gull', 'pelican',
    'albatross', 'hummingbird', 'hummingbirds', 'woodpecker', 'stork',
    'crane', 'heron', 'vulture', 'condor', 'ostrich', 'penguin', 'bat',
    'bats', 'flying squirrel', 'flying fish', 'pterodactyl', 'pteranodon',
    'dragon', 'dragons', 'phoenix', 'fairy', 'fairies', 'angel', 'angels',
    'witch', 'superman', 'supergirl', 'superhero', 'peter pan', 'tinkerbell',
    'santa', 'reindeer', 'pegasus', 'griffin', 'cupid', 'ufo', 'flying saucer',
    'paper airplane', 'paper plane', 'feather', 'feathers', 'leaf', 'leaves',
    'seed', 'seeds', 'dandelion', 'dandelion seed', 'pollen', 'spore', 'dust',
    'ash', 'ember', 'spark', 'sparks', 'confetti', 'cloud', 'clouds', 'smoke',
    'wind', 'snow', 'snowflake', 'rain', 'hail', 'meteor', 'meteorite',
    'comet', 'asteroid', 'shooting star', 'fighter jet', 'biplane',
    'concorde', 'jumbo jet', 'airliner', 'cargo plane', 'seaplane', 'cropduster',
    'crop duster', 'glider plane', 'model plane', 'kite surfer', 'parachute',
    'parachutist', 'skydiver', 'wingsuit', 'jetpack', 'hovercraft', 'quadcopter',
    'missile', 'arrow', 'arrows', 'dart', 'darts', 'bullet', 'bullets',
    'baseball', 'golf ball', 'tennis ball', 'cannonball', 'spaceship rocket',
    'lunar module', 'space shuttle', 'probe', 'flying ant', 'termite',
    'mayfly', 'horsefly', 'blowfly', 'fruit fly', 'tsetse fly', 'lacewing',
  ]),

  'Board games': new Set([
    'monopoly', 'chess', 'checkers', 'draughts', 'scrabble', 'clue', 'cluedo',
    'risk', 'sorry', 'trouble', 'life', 'the game of life', 'candy land',
    'candyland', 'chutes and ladders', 'snakes and ladders', 'battleship',
    'connect four', 'connect 4', 'operation', 'guess who', 'mouse trap',
    'mousetrap', 'twister', 'jenga', 'yahtzee', 'backgammon', 'go', 'othello',
    'reversi', 'mancala', 'parcheesi', 'pictionary', 'trivial pursuit',
    'catan', 'settlers of catan', 'ticket to ride', 'carcassonne', 'pandemic',
    'dominion', 'agricola', 'puerto rico', 'power grid', 'azul', 'splendor',
    'wingspan', 'gloomhaven', 'scythe', 'terraforming mars', 'codenames',
    'dixit', 'sushi go', 'kingdomino', 'patchwork', 'hive', 'blokus',
    'sequence', 'rummikub', 'dominoes', 'cribbage', 'parchisi', 'ludo',
    'pachisi', 'aggravation', 'chinese checkers', 'stratego', 'axis and allies',
    'diplomacy', 'cranium', 'taboo', 'balderdash', 'apples to apples',
    'cards against humanity', 'exploding kittens', 'uno', 'skip bo', 'phase 10',
    'go fish', 'old maid', 'war', 'crazy eights', 'spades', 'hearts', 'euchre',
    'bridge', 'gin rummy', 'rummy', 'canasta', 'pinochle', 'solitaire',
    'poker', 'blackjack', 'baccarat', 'mahjong', 'mah jongg', 'dominos',
    'shogi', 'xiangqi', 'pente', 'mastermind', 'qwirkle', 'forbidden island',
    'forbidden desert', 'betrayal at house on the hill', 'munchkin',
    'small world', 'king of tokyo', 'love letter', '7 wonders', 'seven wonders',
    'pandemic legacy', 'arkham horror', 'eldritch horror', 'twilight imperium',
    'war of the ring', 'memoir 44', 'descent', 'mage knight', 'root',
    'spirit island', 'brass', 'concordia', 'lords of waterdeep', 'tigris and euphrates',
    'el grande', 'ra', 'modern art', 'acquire', 'cosmic encounter', 'galaxy trucker',
    'robo rally', 'survive', 'camel up', 'las vegas', 'kingsburg', 'stone age',
    'lost cities', 'jaipur', 'hanabi', 'the resistance', 'avalon', 'secret hitler',
    'one night werewolf', 'werewolf', 'mafia', 'mysterium', 'betrayal',
    'forbidden sky', 'pay day', 'payday', 'careers', 'masterpiece', 'hotel',
    'go to the head of the class', 'trivial pursuit junior', 'sorry sliders',
    'don\'t break the ice', 'hungry hungry hippos', 'perfection', 'simon',
    'bop it', 'connect', 'mille bornes', 'fluxx', 'dutch blitz', 'set',
  ]),

  'Desserts': new Set([
    'cake', 'cakes', 'cupcake', 'cupcakes', 'cookie', 'cookies', 'brownie',
    'brownies', 'pie', 'pies', 'apple pie', 'pumpkin pie', 'cherry pie',
    'pecan pie', 'key lime pie', 'ice cream', 'gelato', 'sorbet', 'sherbet',
    'frozen yogurt', 'froyo', 'sundae', 'milkshake', 'shake', 'pudding',
    'custard', 'flan', 'creme brulee', 'panna cotta', 'mousse', 'tiramisu',
    'cheesecake', 'donut', 'donuts', 'doughnut', 'doughnuts', 'eclair',
    'eclairs', 'cream puff', 'profiterole', 'macaron', 'macarons', 'macaroon',
    'macaroons', 'cannoli', 'baklava', 'churro', 'churros', 'funnel cake',
    'cotton candy', 'candy', 'chocolate', 'chocolate bar', 'truffle',
    'truffles', 'fudge', 'toffee', 'caramel', 'butterscotch', 'praline',
    'marshmallow', 'marshmallows', 'gummy bears', 'jelly beans', 'lollipop',
    'lollipops', 'gumdrop', 'licorice', 'taffy', 'nougat', 'peppermint',
    'mint', 'jelly', 'jello', 'gelatin', 'trifle', 'parfait', 'banana split',
    'tart', 'tarts', 'fruit tart', 'lemon tart', 'tartlet', 'galette', 'cobbler',
    'crumble', 'apple crumble', 'crisp', 'apple crisp', 'bread pudding',
    'rice pudding', 'tapioca', 'shortcake', 'strawberry shortcake', 'pound cake',
    'sponge cake', 'angel food cake', 'bundt cake', 'carrot cake', 'red velvet',
    'red velvet cake', 'chocolate cake', 'lava cake', 'fruitcake', 'coffee cake',
    'crumb cake', 'scone', 'scones', 'muffin', 'muffins', 'danish', 'croissant',
    'strudel', 'apple strudel', 'turnover', 'gingerbread', 'shortbread',
    'biscotti', 'wafer', 'wafers', 'meringue', 'pavlova', 'souffle', 'baked alaska',
    'whoopie pie', 'cake pop', 'cake pops', 'fritter', 'beignet', 'beignets',
    'kolache', 'mochi', 'mochi ice cream', 'dango', 'taiyaki', 'gulab jamun',
    'jalebi', 'rasgulla', 'kheer', 'halva', 'halwa', 'rice krispie treat',
    'rice krispies treats', 'smore', 's\'mores', 'smores', 'popsicle',
    'ice pop', 'fudgesicle', 'creamsicle', 'snow cone', 'shaved ice', 'affogato',
    'banoffee pie', 'lemon meringue pie', 'boston cream pie', 'mud pie',
    'whipped cream', 'sundae bar', 'parfait cup', 'fortune cookie',
    'oatmeal cookie', 'sugar cookie', 'snickerdoodle', 'macadamia cookie',
    'chocolate chip cookie', 'peanut butter cookie', 'thumbprint cookie',
    'spritz cookie', 'wedding cookie', 'dessert', 'sweets', 'pastry', 'pastries',
  ]),

  'Things you find in a classroom': new Set([
    'desk', 'desks', 'chair', 'chairs', 'table', 'tables', 'board',
    'chalkboard', 'whiteboard', 'blackboard', 'smartboard', 'chalk', 'eraser',
    'erasers', 'marker', 'markers', 'whiteboard marker', 'dry erase marker',
    'pen', 'pens', 'pencil', 'pencils', 'pencil sharpener', 'sharpener',
    'crayon', 'crayons', 'colored pencils', 'highlighter', 'highlighters',
    'notebook', 'notebooks', 'paper', 'papers', 'notepad', 'binder', 'binders',
    'folder', 'folders', 'textbook', 'textbooks', 'book', 'books', 'workbook',
    'dictionary', 'ruler', 'rulers', 'protractor', 'compass', 'calculator',
    'calculators', 'scissors', 'glue', 'glue stick', 'tape', 'stapler',
    'staples', 'staple remover', 'paper clip', 'paper clips', 'binder clip',
    'rubber band', 'thumbtack', 'pushpin', 'pin', 'sticky notes', 'post it',
    'post its', 'index cards', 'flashcards', 'globe', 'map', 'maps', 'poster',
    'posters', 'bulletin board', 'cork board', 'clock', 'calendar', 'flag',
    'american flag', 'computer', 'computers', 'laptop', 'laptops', 'tablet',
    'tablets', 'projector', 'screen', 'printer', 'mouse', 'keyboard', 'monitor',
    'document camera', 'overhead projector', 'tv', 'television', 'speaker',
    'speakers', 'microphone', 'headphones', 'backpack', 'backpacks', 'bookbag',
    'lunchbox', 'water bottle', 'cubby', 'cubbies', 'locker', 'lockers',
    'shelf', 'shelves', 'bookshelf', 'bookcase', 'cabinet', 'drawer', 'cart',
    'trash can', 'recycling bin', 'pencil case', 'pencil box', 'supply box',
    'tissue box', 'tissues', 'hand sanitizer', 'soap', 'paper towels',
    'window', 'windows', 'door', 'wall', 'floor', 'ceiling', 'light', 'lights',
    'fan', 'thermostat', 'heater', 'air conditioner', 'plant', 'plants',
    'fish tank', 'aquarium', 'hamster', 'class pet', 'alphabet', 'number line',
    'word wall', 'reading corner', 'rug', 'carpet', 'beanbag', 'easel',
    'chart', 'graph', 'periodic table', 'microscope', 'beaker', 'test tube',
    'magnet', 'abacus', 'building blocks', 'art supplies', 'paint', 'paintbrush',
    'construction paper', 'graph paper', 'lined paper', 'whiteboard eraser',
    'hall pass', 'attendance sheet', 'grade book', 'lesson plan', 'agenda',
    'planner', 'homework', 'worksheet', 'quiz', 'test', 'exam', 'report card',
    'sticker', 'stickers', 'gold star', 'name tag', 'desk organizer', 'globe stand',
    'student', 'students', 'teacher', 'teacher desk', 'overhead', 'document holder',
  ]),

  'Car brands': new Set([
    'toyota', 'honda', 'ford', 'chevrolet', 'chevy', 'nissan', 'hyundai',
    'kia', 'subaru', 'mazda', 'volkswagen', 'vw', 'bmw', 'mercedes',
    'mercedes benz', 'audi', 'porsche', 'lexus', 'acura', 'infiniti',
    'cadillac', 'buick', 'gmc', 'jeep', 'dodge', 'chrysler', 'ram', 'lincoln',
    'tesla', 'volvo', 'jaguar', 'land rover', 'range rover', 'mini', 'fiat',
    'alfa romeo', 'maserati', 'ferrari', 'lamborghini', 'bentley',
    'rolls royce', 'aston martin', 'bugatti', 'mclaren', 'lotus', 'peugeot',
    'renault', 'citroen', 'opel', 'vauxhall', 'skoda', 'seat', 'dacia',
    'suzuki', 'mitsubishi', 'isuzu', 'daihatsu', 'genesis', 'saab', 'saturn',
    'pontiac', 'oldsmobile', 'hummer', 'mercury', 'plymouth', 'scion',
    'smart', 'koenigsegg', 'pagani', 'rivian', 'lucid', 'polestar', 'byd',
    'geely', 'chery', 'great wall', 'tata', 'mahindra', 'maruti', 'proton',
    'perodua', 'holden', 'datsun', 'lada', 'ssangyong', 'daewoo', 'morgan',
    'tvr', 'caterham', 'noble', 'spyker', 'fisker', 'delorean', 'studebaker',
    'packard', 'cord', 'duesenberg', 'amc', 'eagle', 'maybach', 'borgward',
    'wartburg', 'trabant', 'gaz', 'uaz', 'zil', 'nio', 'xpeng', 'li auto',
    'hongqi', 'wuling', 'baojun', 'roewe', 'mg', 'vinfast', 'foton',
    'changan', 'dongfeng', 'faw', 'saic', 'jac', 'haval', 'ineos', 'rimac',
    'gumpert', 'wiesmann', 'de tomaso', 'iso', 'lancia', 'abarth', 'autobianchi',
    'innocenti', 'bizzarrini', 'monteverdi', 'bristol', 'jensen', 'austin',
    'morris', 'rover', 'triumph', 'mga', 'sunbeam', 'hillman', 'humber',
    'singer', 'wolseley', 'riley', 'standard', 'daimler', 'panhard', 'simca',
    'talbot', 'matra', 'venturi', 'alpine', 'bandini', 'osca', 'cisitalia',
    'apollo', 'hennessey', 'saleen', 'shelby', 'panoz', 'vector', 'czinger',
    'karma', 'canoo', 'faraday future', 'aptera', 'edsel', 'desoto', 'nash',
    'hudson', 'willys', 'kaiser', 'tucker', 'crosley', 'rambler', 'continental',
  ]),

  'Things that are cold': new Set([
    'ice', 'ice cube', 'ice cubes', 'snow', 'snowflake', 'snowflakes',
    'snowball', 'snowman', 'sleet', 'hail', 'frost', 'icicle', 'icicles',
    'glacier', 'iceberg', 'frostbite', 'winter', 'blizzard', 'freezer',
    'fridge', 'refrigerator', 'ice cream', 'gelato', 'sorbet', 'popsicle',
    'ice pop', 'snow cone', 'slush', 'slushie', 'frozen yogurt', 'milkshake',
    'iced tea', 'iced coffee', 'cold brew', 'lemonade', 'soda', 'ice water',
    'cold water', 'ice bath', 'arctic', 'antarctica', 'north pole', 'south pole',
    'tundra', 'permafrost', 'snow day', 'ski slope', 'ice rink', 'skating rink',
    'igloo', 'frozen lake', 'frozen pond', 'cold front', 'wind chill',
    'air conditioner', 'ac', 'freezer burn', 'frozen pizza', 'frozen peas',
    'frozen vegetables', 'frozen food', 'ice pack', 'cold pack', 'cooler',
    'ice chest', 'dry ice', 'liquid nitrogen', 'cold shower', 'cold drink',
    'cold soda', 'frosty', 'frosty the snowman', 'penguin', 'polar bear',
    'walrus', 'seal', 'snow leopard', 'arctic fox', 'reindeer', 'husky',
    'ice fishing', 'snowboard', 'ski', 'skis', 'sled', 'sleigh', 'toboggan',
    'snowmobile', 'snow plow', 'frozen', 'elsa', 'olaf', 'ice castle',
    'glacial', 'cold weather', 'cold morning', 'chill', 'chilly air',
    'cold hands', 'cold feet', 'cold nose', 'goosebumps', 'shiver', 'freezing',
    'subzero', 'absolute zero', 'space', 'outer space', 'cryotherapy',
    'cryogenics', 'ice cream cone', 'snow globe', 'iced latte', 'frappe',
    'frappuccino', 'smoothie', 'cold pizza', 'leftovers', 'cold cuts',
    'cold soup', 'gazpacho', 'jello', 'ice maker', 'ice tray', 'glacier water',
    'snowstorm', 'flurries', 'frozen lake ice', 'pond ice', 'ice skate',
    'ice skates', 'hockey puck', 'cold pool', 'mountain peak', 'mountaintop',
    'siberia', 'alaska', 'antarctic', 'cold beer', 'ice tea', 'cold milk',
    'refrigerated', 'frozen treat', 'ice block', 'block of ice', 'frozen river',
    'snow bank', 'snowdrift', 'frozen tundra', 'cold snap', 'cold spell',
    'deep freeze', 'walk in freezer', 'meat locker', 'cold storage',
    'air conditioning', 'ceiling fan air', 'cold breeze', 'morning dew',
    'frozen waterfall', 'hailstone', 'hailstones', 'glacier ice', 'pack ice',
    'cold lemonade', 'iced water', 'frozen grapes', 'cold cucumber',
  ]),

  'Things you wear on your head': new Set([
    'hat', 'hats', 'cap', 'caps', 'baseball cap', 'beanie', 'beanies',
    'helmet', 'helmets', 'bike helmet', 'football helmet', 'hard hat',
    'crown', 'crowns', 'tiara', 'tiaras', 'headband', 'headbands', 'bandana',
    'bandanna', 'scarf', 'headscarf', 'hood', 'hoodie hood', 'turban',
    'hijab', 'veil', 'bonnet', 'beret', 'fedora', 'cowboy hat', 'sombrero',
    'top hat', 'bowler hat', 'derby', 'panama hat', 'straw hat', 'sun hat',
    'bucket hat', 'visor', 'sun visor', 'fascinator', 'headdress', 'feather headdress',
    'wig', 'wigs', 'toupee', 'hairpiece', 'extensions', 'hair clip', 'hairpin',
    'bobby pin', 'barrette', 'scrunchie', 'hair tie', 'ponytail holder',
    'hair band', 'tiara crown', 'flower crown', 'halo', 'wreath', 'laurel',
    'laurel wreath', 'mortarboard', 'graduation cap', 'cap and gown', 'fez',
    'yarmulke', 'kippah', 'skullcap', 'do rag', 'durag', 'balaclava',
    'ski mask', 'mask', 'face mask', 'goggles', 'sunglasses', 'glasses',
    'eyeglasses', 'monocle', 'earmuffs', 'ear muffs', 'headphones', 'headset',
    'earbuds', 'earrings', 'nightcap', 'sleeping cap', 'shower cap',
    'swim cap', 'bathing cap', 'chef hat', "chef's hat", 'toque', 'nurse cap',
    'police hat', 'military hat', 'army helmet', 'pith helmet', 'aviator hat',
    'trapper hat', 'ushanka', 'deerstalker', 'newsboy cap', 'flat cap',
    'ivy cap', 'snapback', 'trucker hat', 'dad hat', 'pork pie hat', 'boater',
    'homburg', 'tricorn', 'tricorne', 'bicorne', 'jester hat', 'dunce cap',
    'party hat', 'birthday hat', 'cone hat', 'santa hat', 'elf hat',
    'witch hat', 'wizard hat', 'pointed hat', 'pirate hat', 'captain hat',
    'sailor hat', 'conductor hat', 'crash helmet', 'motorcycle helmet',
    'space helmet', 'astronaut helmet', 'diving helmet', 'viking helmet',
    'horned helmet', 'gladiator helmet', 'knight helmet', 'samurai helmet',
    'visor cap', 'snood', 'kerchief', 'babushka', 'wimple', 'mantilla',
    'coif', 'cloche', 'pillbox hat', 'porkpie', 'tam', 'tam o shanter',
    'cowl', 'capirote', 'sombrero hat', 'rasta hat', 'kufi', 'taqiyah',
    'songkok', 'keffiyeh', 'ghutra', 'crown jewels', 'circlet', 'diadem',
    'feather', 'flower', 'bow', 'ribbon', 'antlers', 'reindeer antlers',
    'bunny ears', 'cat ears', 'mouse ears', 'headlamp', 'miner hat',
  ]),

  'Video games': new Set([
    'minecraft', 'fortnite', 'roblox', 'mario', 'super mario', 'super mario bros',
    'mario kart', 'zelda', 'the legend of zelda', 'pokemon', 'tetris',
    'pac man', 'pacman', 'space invaders', 'donkey kong', 'sonic',
    'sonic the hedgehog', 'metroid', 'kirby', 'star fox', 'pikmin',
    'animal crossing', 'splatoon', 'super smash bros', 'smash bros',
    'call of duty', 'cod', 'warzone', 'halo', 'gears of war', 'forza',
    'grand theft auto', 'gta', 'red dead redemption', 'red dead',
    'the last of us', 'god of war', 'uncharted', 'horizon zero dawn',
    'spider man', 'ratchet and clank', 'gran turismo', 'final fantasy',
    'kingdom hearts', 'dragon quest', 'chrono trigger', 'persona',
    'elden ring', 'dark souls', 'demon souls', 'bloodborne', 'sekiro',
    'monster hunter', 'resident evil', 'silent hill', 'devil may cry',
    'street fighter', 'mortal kombat', 'tekken', 'super street fighter',
    'guilty gear', 'king of fighters', 'injustice', 'soul calibur',
    'the witcher', 'cyberpunk', 'cyberpunk 2077', 'skyrim', 'oblivion',
    'fallout', 'starfield', 'mass effect', 'dragon age', 'baldurs gate',
    "baldur's gate", 'diablo', 'world of warcraft', 'wow', 'starcraft',
    'overwatch', 'hearthstone', 'league of legends', 'lol', 'valorant',
    'counter strike', 'cs go', 'counter-strike', 'dota', 'dota 2', 'apex legends',
    'pubg', 'fall guys', 'among us', 'rocket league', 'rust', 'dayz',
    'terraria', 'stardew valley', 'hollow knight', 'celeste', 'cuphead',
    'undertale', 'hades', 'dead cells', 'binding of isaac', 'spelunky',
    'don\'t starve', 'subnautica', 'no mans sky', "no man's sky", 'valheim',
    'ark', 'ark survival evolved', 'sea of thieves', 'destiny', 'destiny 2',
    'borderlands', 'bioshock', 'half life', 'half-life', 'portal', 'doom',
    'wolfenstein', 'quake', 'team fortress', 'left 4 dead', 'titanfall',
    'battlefield', 'rainbow six', 'rainbow six siege', 'metal gear',
    'metal gear solid', 'death stranding', 'assassins creed', "assassin's creed",
    'far cry', 'watch dogs', 'just cause', 'tomb raider', 'hitman', 'dishonored',
    'prey', 'control', 'alan wake', 'max payne', 'deus ex', 'system shock',
    'fifa', 'madden', 'nba 2k', 'mlb the show', 'nhl', 'wwe 2k', 'pga tour',
    'sims', 'the sims', 'simcity', 'cities skylines', 'civilization', 'civ',
    'age of empires', 'command and conquer', 'total war', 'xcom', 'fire emblem',
    'advance wars', 'plants vs zombies', 'angry birds', 'candy crush',
    'temple run', 'subway surfers', 'clash of clans', 'clash royale',
    'pokemon go', 'genshin impact', 'honkai', 'crossy road', 'flappy bird',
    'cut the rope', 'fruit ninja', 'doodle jump', 'geometry dash', 'osu',
    'beat saber', 'guitar hero', 'rock band', 'dance dance revolution', 'ddr',
    'just dance', 'wii sports', 'wii fit', 'duck hunt', 'centipede', 'asteroids',
    'frogger', 'galaga', 'dig dug', 'qbert', 'pong', 'breakout', 'pinball',
    'castlevania', 'mega man', 'megaman', 'contra', 'metal slug', 'bomberman',
    'crash bandicoot', 'spyro', 'rayman', 'banjo kazooie', 'conker',
    'gex', 'jak and daxter', 'sly cooper', 'little big planet',
  ]),

  'Things made of wood': new Set([
    'table', 'tables', 'chair', 'chairs', 'desk', 'desks', 'bench', 'benches',
    'stool', 'stools', 'shelf', 'shelves', 'bookshelf', 'bookcase', 'cabinet',
    'cabinets', 'dresser', 'wardrobe', 'drawer', 'drawers', 'bed', 'bed frame',
    'crib', 'cradle', 'rocking chair', 'high chair', 'door', 'doors', 'window frame',
    'floor', 'hardwood floor', 'fence', 'fences', 'gate', 'deck', 'porch',
    'staircase', 'stairs', 'banister', 'railing', 'beam', 'plank', 'planks',
    'board', 'boards', 'log', 'logs', 'lumber', 'timber', 'firewood',
    'plywood', 'pole', 'post', 'fence post', 'stake', 'stick', 'sticks',
    'twig', 'branch', 'branches', 'tree', 'trunk', 'pencil', 'pencils',
    'ruler', 'yardstick', 'paintbrush handle', 'broom', 'broomstick',
    'mop handle', 'rake', 'shovel handle', 'axe handle', 'hammer handle',
    'tool handle', 'baseball bat', 'cricket bat', 'hockey stick', 'pool cue',
    'cue stick', 'drumstick', 'drumsticks', 'chopstick', 'chopsticks',
    'spoon', 'wooden spoon', 'spatula', 'cutting board', 'chopping board',
    'rolling pin', 'salad bowl', 'bowl', 'crate', 'crates', 'box', 'wooden box',
    'barrel', 'barrels', 'cask', 'keg', 'bucket', 'pail', 'wooden bucket',
    'ladder', 'wooden ladder', 'easel', 'frame', 'picture frame', 'photo frame',
    'birdhouse', 'doghouse', 'treehouse', 'tree house', 'cabin', 'log cabin',
    'shed', 'barn', 'hut', 'canoe', 'kayak', 'rowboat', 'raft', 'oar', 'oars',
    'paddle', 'mast', 'ship', 'wooden ship', 'pirate ship', 'wagon', 'cart',
    'wheel', 'wagon wheel', 'sled', 'toboggan', 'rocking horse', 'toy', 'toys',
    'wooden toy', 'block', 'blocks', 'building blocks', 'dollhouse',
    'jenga', 'chess board', 'chess set', 'checkers board', 'domino', 'dominoes',
    'guitar', 'violin', 'cello', 'piano', 'ukulele', 'maraca', 'xylophone',
    'recorder', 'flute', 'drum', 'didgeridoo', 'clarinet', 'bassoon',
    'matchstick', 'match', 'matches', 'toothpick', 'toothpicks', 'skewer',
    'popsicle stick', 'craft stick', 'tongue depressor', 'clothespin',
    'clothes peg', 'hanger', 'coat hanger', 'cork', 'wine cork', 'corkboard',
    'mailbox', 'birdhouse roof', 'totem pole', 'totem', 'statue', 'carving',
    'sculpture', 'figurine', 'whittling', 'cane', 'walking stick', 'crutch',
    'spinning wheel', 'wheelbarrow', 'pallet', 'pallets', 'fence panel',
    'gazebo', 'pergola', 'trellis', 'arbor', 'picnic table', 'workbench',
    'sawhorse', 'stepladder', 'footstool', 'ottoman', 'coffee table',
    'nightstand', 'end table', 'sideboard', 'hutch', 'armoire', 'pew',
    'church pew', 'coffin', 'casket', 'cross', 'crucifix', 'door frame',
    'window sill', 'baseboard', 'molding', 'crown molding', 'shingle',
    'shingles', 'fence gate', 'gate post', 'tongue and groove', 'veneer',
    'birch bark', 'bark', 'acorn cap', 'pinecone', 'driftwood', 'kindling',
  ]),

  'Pizza toppings': new Set([
    'cheese', 'mozzarella', 'pepperoni', 'sausage', 'italian sausage', 'bacon',
    'ham', 'prosciutto', 'salami', 'chicken', 'grilled chicken', 'bbq chicken',
    'beef', 'ground beef', 'meatball', 'meatballs', 'anchovy', 'anchovies',
    'tuna', 'shrimp', 'mushroom', 'mushrooms', 'onion', 'onions', 'red onion',
    'pepper', 'peppers', 'bell pepper', 'green pepper', 'banana pepper',
    'jalapeno', 'jalapenos', 'pepperoncini', 'olive', 'olives', 'black olives',
    'green olives', 'tomato', 'tomatoes', 'cherry tomato', 'sun dried tomato',
    'spinach', 'arugula', 'basil', 'fresh basil', 'oregano', 'garlic',
    'roasted garlic', 'pineapple', ' pineapple', 'corn', 'broccoli',
    'artichoke', 'artichokes', 'eggplant', 'zucchini', 'capers', 'pesto',
    'ricotta', 'parmesan', 'feta', 'gorgonzola', 'blue cheese', 'cheddar',
    'provolone', 'goat cheese', 'gouda', 'asiago', 'romano', 'four cheese',
    'tomato sauce', 'marinara', 'bbq sauce', 'white sauce', 'alfredo sauce',
    'ranch', 'buffalo sauce', 'hot sauce', 'pepper flakes', 'red pepper flakes',
    'chili flakes', 'pineapple chunks', 'ham and pineapple', 'hawaiian',
    'pulled pork', 'chorizo', 'pancetta', 'canadian bacon', 'gyro meat',
    'ground sausage', 'crumbled sausage', 'turkey', 'bacon bits',
    'caramelized onion', 'scallion', 'green onion', 'leek', 'shallot',
    'roasted red pepper', 'roasted vegetables', 'grilled vegetables',
    'mixed vegetables', 'veggie', 'spinach and feta', 'mushroom and onion',
    'truffle', 'truffle oil', 'fig', 'pear', 'apple', 'cranberry', 'walnut',
    'pine nut', 'pine nuts', 'almond', 'sesame seeds', 'egg', 'fried egg',
    'potato', 'thinly sliced potato', 'sweet potato', 'butternut squash',
    'kale', 'swiss chard', 'cilantro', 'parsley', 'rosemary', 'thyme',
    'crushed garlic', 'garlic butter', 'olive oil', 'balsamic', 'honey',
    'hot honey', 'sriracha', 'buffalo chicken', 'chicken tikka', 'tandoori',
    'curry', 'kimchi', 'bulgogi', 'teriyaki', 'pickle', 'pickles', 'sauerkraut',
    'coleslaw', 'avocado', 'guacamole', 'jalapeno popper', 'cream cheese',
    'mac and cheese', 'french fries', 'tater tots', 'nacho', 'taco meat',
    'refried beans', 'black beans', 'chickpeas', 'lentils', 'tofu', 'seitan',
    'vegan cheese', 'plant based sausage', 'beyond meat', 'mortadella',
    'capicola', 'soppressata', 'nduja', 'clams', 'mussels', 'crab', 'lobster',
    'caviar', 'smoked salmon', 'lox', 'pickled onion', 'roasted garlic cloves',
    'fresh mozzarella', 'burrata', 'mascarpone', 'fontina', 'manchego',
    'pecorino', 'halloumi', 'paneer', 'queso', 'cotija',
  ]),

  'Things in a bathroom': new Set([
    'toilet', 'toilets', 'sink', 'sinks', 'bathtub', 'tub', 'bath', 'shower',
    'showers', 'shower head', 'shower curtain', 'shower door', 'faucet',
    'tap', 'mirror', 'mirrors', 'medicine cabinet', 'cabinet', 'vanity',
    'towel', 'towels', 'bath towel', 'hand towel', 'washcloth', 'towel rack',
    'towel bar', 'soap', 'bar of soap', 'hand soap', 'body wash', 'shower gel',
    'shampoo', 'conditioner', 'loofah', 'sponge', 'bath mat', 'rug', 'mat',
    'toilet paper', 'tp', 'toilet paper holder', 'toilet brush', 'plunger',
    'toothbrush', 'toothbrushes', 'electric toothbrush', 'toothpaste',
    'mouthwash', 'floss', 'dental floss', 'razor', 'razors', 'shaving cream',
    'shaving gel', 'aftershave', 'comb', 'brush', 'hairbrush', 'hair dryer',
    'blow dryer', 'hairdryer', 'straightener', 'curling iron', 'flat iron',
    'deodorant', 'antiperspirant', 'perfume', 'cologne', 'lotion', 'moisturizer',
    'sunscreen', 'makeup', 'cosmetics', 'lipstick', 'mascara', 'foundation',
    'q tips', 'cotton swabs', 'cotton balls', 'cotton pads', 'tissues',
    'tissue box', 'kleenex', 'nail clippers', 'tweezers', 'nail file',
    'scissors', 'first aid kit', 'band aid', 'bandages', 'thermometer',
    'medicine', 'pills', 'vitamins', 'aspirin', 'scale', 'bathroom scale',
    'weight scale', 'trash can', 'wastebasket', 'garbage can', 'air freshener',
    'candle', 'candles', 'plunger', 'toilet seat', 'toilet lid', 'tank',
    'flush handle', 'bidet', 'urinal', 'drain', 'plug', 'stopper', 'caulk',
    'tile', 'tiles', 'grout', 'soap dish', 'soap dispenser', 'toothbrush holder',
    'cup', 'tumbler', 'water glass', 'shower caddy', 'bath toy', 'rubber duck',
    'rubber ducky', 'bubble bath', 'bath bomb', 'bath salts', 'epsom salt',
    'face wash', 'cleanser', 'toner', 'serum', 'cream', 'exfoliator', 'scrub',
    'pumice stone', 'foot file', 'nail polish', 'nail polish remover',
    'acetone', 'cotton', 'ear plugs', 'shower cap', 'robe', 'bathrobe',
    'slippers', 'hamper', 'laundry basket', 'clothes hamper', 'hook', 'towel hook',
    'robe hook', 'light', 'light switch', 'fan', 'exhaust fan', 'vent',
    'window', 'curtain', 'blinds', 'outlet', 'gfci outlet', 'night light',
    'plunger handle', 'toilet tank', 'flush', 'water', 'steam', 'fog', 'humidity',
    'magnifying mirror', 'hand mirror', 'shaving mirror', 'shelf', 'shelves',
    'basket', 'organizer', 'hairspray', 'gel', 'pomade', 'mousse', 'face mask',
    'sheet mask', 'retainer', 'mouth guard', 'contact lens case', 'eye drops',
    'cotton round', 'makeup remover', 'hand cream', 'foot cream', 'talcum powder',
    'baby powder', 'diaper', 'diapers', 'changing pad', 'step stool',
  ]),

  'Superheroes': new Set([
    'superman', 'batman', 'spider man', 'spiderman', 'iron man', 'ironman',
    'captain america', 'thor', 'hulk', 'the hulk', 'wonder woman', 'flash',
    'the flash', 'green lantern', 'aquaman', 'cyborg', 'black widow',
    'hawkeye', 'black panther', 'doctor strange', 'dr strange', 'ant man',
    'antman', 'the wasp', 'wasp', 'scarlet witch', 'vision', 'falcon',
    'winter soldier', 'bucky', 'star lord', 'gamora', 'drax', 'rocket raccoon',
    'groot', 'nebula', 'mantis', 'captain marvel', 'ms marvel', 'shang chi',
    'moon knight', 'daredevil', 'jessica jones', 'luke cage', 'iron fist',
    'the punisher', 'punisher', 'ghost rider', 'blade', 'deadpool', 'wolverine',
    'cyclops', 'storm', 'jean grey', 'phoenix', 'beast', 'rogue', 'gambit',
    'nightcrawler', 'iceman', 'colossus', 'professor x', 'magneto',
    'jubilee', 'psylocke', 'kitty pryde', 'mystique', 'quicksilver',
    'silver surfer', 'mister fantastic', 'mr fantastic', 'invisible woman',
    'human torch', 'the thing', 'thing', 'nightwing', 'robin', 'batgirl',
    'batwoman', 'red hood', 'green arrow', 'supergirl', 'superboy', 'shazam',
    'martian manhunter', 'hawkgirl', 'zatanna', 'john constantine', 'constantine',
    'swamp thing', 'doctor fate', 'booster gold', 'blue beetle', 'firestorm',
    'atom', 'the atom', 'plastic man', 'animal man', 'black canary',
    'huntress', 'catwoman', 'starfire', 'raven', 'beast boy', 'kid flash',
    'wally west', 'jay garrick', 'wonder girl', 'hawkman', 'green goblin',
    'venom', 'carnage', 'miles morales', 'spider gwen', 'gwen stacy',
    'spider woman', 'silk', 'jessica drew', 'nova', 'wiccan', 'hercules',
    'sentry', 'namor', 'she hulk', 'red hulk', 'war machine', 'rescue',
    'pepper potts', 'valkyrie', 'loki', 'heimdall', 'sif', 'kang', 'thanos',
    'darkseid', 'lex luthor', 'joker', 'the joker', 'harley quinn',
    'poison ivy', 'doomsday', 'bane', 'two face', 'penguin', 'riddler',
    'mr freeze', 'scarecrow', 'ras al ghul', 'deathstroke', 'reverse flash',
    'sinestro', 'brainiac', 'ultron', 'red skull', 'doctor doom', 'dr doom',
    'magik', 'cable', 'domino', 'bishop', 'forge', 'multiple man', 'banshee',
    'sunfire', 'havok', 'polaris', 'emma frost', 'sebastian shaw',
    'the invincible', 'invincible', 'omni man', 'omni-man', 'atom eve',
    'homelander', 'starlight', 'queen maeve', 'a-train', 'black noir',
    'the deep', 'billy butcher', 'hancock', 'mr incredible', 'elastigirl',
    'violet', 'dash', 'frozone', 'syndrome', 'megamind', 'metro man',
    'hellboy', 'spawn', 'kick ass', 'hit girl', 'big daddy', 'darkwing duck',
    'static shock', 'ben 10', 'danny phantom', 'samurai jack',
    'astro boy', 'sailor moon', 'one punch man', 'saitama', 'all might',
    'deku', 'midoriya', 'bakugo', 'todoroki', 'mob', 'mumen rider',
  ]),

  'Things that are green': new Set([
    'grass', 'tree', 'trees', 'leaf', 'leaves', 'plant', 'plants', 'bush',
    'shrub', 'fern', 'moss', 'ivy', 'vine', 'clover', 'shamrock', 'cactus',
    'pine tree', 'evergreen', 'pine needles', 'broccoli', 'lettuce', 'spinach',
    'kale', 'cabbage', 'cucumber', 'cucumbers', 'zucchini', 'celery', 'peas',
    'green beans', 'green bean', 'asparagus', 'brussels sprouts', 'artichoke',
    'green pepper', 'bell pepper', 'jalapeno', 'avocado', 'lime', 'limes',
    'green apple', 'green apples', 'granny smith', 'kiwi', 'honeydew', 'pear',
    'pears', 'green grapes', 'grapes', 'pickle', 'pickles', 'olive', 'olives',
    'edamame', 'okra', 'leek', 'scallion', 'green onion', 'arugula',
    'watercress', 'basil', 'parsley', 'cilantro', 'mint', 'sage', 'thyme',
    'rosemary', 'frog', 'frogs', 'toad', 'turtle', 'lizard', 'iguana',
    'chameleon', 'gecko', 'snake', 'green snake', 'caterpillar', 'grasshopper',
    'praying mantis', 'cricket', 'katydid', 'green beetle', 'emerald',
    'emeralds', 'jade', 'peridot', 'malachite', 'money', 'dollar', 'dollar bill',
    'cash', 'shamrock shake', 'mint ice cream', 'matcha', 'green tea',
    'guacamole', 'pesto', 'wasabi', 'spinach dip', 'kermit', 'kermit the frog',
    'the grinch', 'grinch', 'hulk', 'shrek', 'yoda', 'green goblin', 'gumby',
    'oscar the grouch', 'mike wazowski', 'peter pan', 'green lantern',
    'toy soldier', 'army men', 'green army men', 'recycle bin', 'recycling bin',
    'go sign', 'green light', 'traffic light', 'go light', 'street sign',
    'highway sign', 'exit sign', 'chalkboard', 'felt', 'pool table', 'turf',
    'astroturf', 'golf course', 'fairway', 'putting green', 'field',
    'soccer field', 'football field', 'meadow', 'lawn', 'garden', 'hedge',
    'topiary', 'seaweed', 'algae', 'lily pad', 'lily pads', 'pond scum',
    'mold', 'slime', 'ooze', 'goo', 'booger', 'snot', 'mucus', 'pea soup',
    'green smoothie', 'kale chips', 'spinach salad', 'salad', 'herbs',
    'mistletoe', 'holly', 'christmas tree', 'wreath', 'garland', 'palm leaf',
    'banana leaf', 'aloe', 'aloe vera', 'succulent', 'bamboo', 'wheatgrass',
    'sprouts', 'bean sprouts', 'green crayon', 'green marker', 'green paint',
    'green shirt', 'green car', 'tractor', 'john deere', 'go kart',
    'green bottle', 'sprite bottle', 'mountain dew', 'gatorade', 'pickle juice',
    'lime jello', 'green jello', 'mint leaf', 'four leaf clover',
  ]),

  'Drinks': new Set([
    'water', 'milk', 'juice', 'orange juice', 'apple juice', 'grape juice',
    'cranberry juice', 'pineapple juice', 'tomato juice', 'lemonade',
    'limeade', 'soda', 'pop', 'cola', 'coke', 'coca cola', 'pepsi', 'sprite',
    'fanta', 'mountain dew', 'dr pepper', 'root beer', 'ginger ale',
    'club soda', 'soda water', 'seltzer', 'sparkling water', 'tonic water',
    'tea', 'iced tea', 'sweet tea', 'green tea', 'black tea', 'herbal tea',
    'chamomile tea', 'chai', 'chai tea', 'matcha', 'coffee', 'iced coffee',
    'cold brew', 'espresso', 'latte', 'cappuccino', 'macchiato', 'americano',
    'mocha', 'frappuccino', 'frappe', 'hot chocolate', 'cocoa', 'hot cocoa',
    'milkshake', 'shake', 'smoothie', 'juice box', 'kool aid', 'gatorade',
    'powerade', 'sports drink', 'energy drink', 'red bull', 'monster',
    'kombucha', 'lemon water', 'coconut water', 'almond milk', 'soy milk',
    'oat milk', 'chocolate milk', 'strawberry milk', 'buttermilk', 'eggnog',
    'horchata', 'lassi', 'mango lassi', 'agua fresca', 'slushie', 'slush',
    'frozen lemonade', 'beer', 'lager', 'ale', 'ipa', 'stout', 'pilsner',
    'wine', 'red wine', 'white wine', 'rose', 'champagne', 'prosecco',
    'sangria', 'cider', 'hard cider', 'mead', 'sake', 'vodka', 'whiskey',
    'whisky', 'bourbon', 'scotch', 'rum', 'gin', 'tequila', 'brandy', 'cognac',
    'absinthe', 'liqueur', 'schnapps', 'vermouth', 'martini', 'margarita',
    'mojito', 'daiquiri', 'pina colada', 'cosmopolitan', 'manhattan',
    'old fashioned', 'negroni', 'mai tai', 'bloody mary', 'mimosa', 'bellini',
    'gin and tonic', 'rum and coke', 'whiskey sour', 'screwdriver', 'cuba libre',
    'long island iced tea', 'moscow mule', 'tom collins', 'sidecar', 'sazerac',
    'spritz', 'aperol spritz', 'shandy', 'punch', 'fruit punch', 'hawaiian punch',
    'capri sun', 'yoo hoo', 'ovaltine', 'malt', 'malted milk', 'protein shake',
    'meal replacement', 'electrolyte drink', 'pedialyte', 'tang', 'arnold palmer',
    'shirley temple', 'egg cream', 'cream soda', 'orange soda', 'grape soda',
    'lime soda', 'cherry cola', 'diet coke', 'diet pepsi', 'coke zero',
    'mineral water', 'spring water', 'distilled water', 'tap water', 'ice water',
    'lemon lime', '7up', 'seven up', 'squirt', 'crush', 'a&w', 'sunkist',
    'vitamin water', 'aloe drink', 'boba', 'bubble tea', 'milk tea', 'taro',
    'thai tea', 'turkish coffee', 'irish coffee', 'cortado', 'flat white',
    'affogato', 'nitro cold brew', 'apple cider', 'mulled wine', 'hot toddy',
    'milk punch', 'wassail', 'kvass', 'soju', 'baijiu', 'grappa', 'ouzo',
    'limoncello', 'amaretto', 'kahlua', 'baileys', 'jagermeister',
  ]),

  'Things at a zoo': new Set([
    'lion', 'lions', 'tiger', 'tigers', 'bear', 'bears', 'elephant',
    'elephants', 'giraffe', 'giraffes', 'zebra', 'zebras', 'monkey', 'monkeys',
    'gorilla', 'gorillas', 'chimpanzee', 'chimp', 'orangutan', 'baboon',
    'lemur', 'sloth', 'kangaroo', 'kangaroos', 'koala', 'panda', 'pandas',
    'red panda', 'rhino', 'rhinoceros', 'hippo', 'hippopotamus', 'hippos',
    'leopard', 'cheetah', 'cheetahs', 'jaguar', 'panther', 'cougar', 'puma',
    'lynx', 'bobcat', 'hyena', 'wolf', 'wolves', 'fox', 'foxes', 'coyote',
    'meerkat', 'meerkats', 'otter', 'otters', 'beaver', 'raccoon', 'badger',
    'porcupine', 'hedgehog', 'armadillo', 'anteater', 'aardvark', 'wombat',
    'tasmanian devil', 'platypus', 'echidna', 'camel', 'camels', 'llama',
    'alpaca', 'bison', 'buffalo', 'water buffalo', 'yak', 'ox', 'moose',
    'elk', 'deer', 'antelope', 'gazelle', 'impala', 'wildebeest', 'gnu',
    'warthog', 'boar', 'wild boar', 'tapir', 'okapi', 'okapi', 'capybara',
    'snake', 'snakes', 'python', 'boa', 'cobra', 'rattlesnake', 'anaconda',
    'lizard', 'iguana', 'gecko', 'chameleon', 'monitor lizard', 'komodo dragon',
    'crocodile', 'alligator', 'turtle', 'tortoise', 'frog', 'toad', 'newt',
    'salamander', 'penguin', 'penguins', 'flamingo', 'flamingos', 'peacock',
    'ostrich', 'emu', 'parrot', 'macaw', 'toucan', 'owl', 'eagle', 'hawk',
    'vulture', 'pelican', 'stork', 'crane', 'swan', 'duck', 'goose', 'pheasant',
    'shark', 'sharks', 'dolphin', 'seal', 'sea lion', 'walrus', 'manatee',
    'octopus', 'jellyfish', 'stingray', 'fish', 'piranha', 'eel', 'starfish',
    'aquarium', 'tank', 'reptile house', 'petting zoo', 'aviary', 'enclosure',
    'cage', 'cages', 'habitat', 'exhibit', 'fence', 'moat', 'gift shop',
    'snack bar', 'ticket booth', 'map', 'zookeeper', 'zoo keeper', 'vet',
    'tour guide', 'train', 'zoo train', 'tram', 'bench', 'sign', 'feeding time',
    'butterfly', 'butterflies', 'spider', 'tarantula', 'scorpion', 'insect',
    'bat', 'bats', 'mongoose', 'serval', 'caracal', 'ocelot', 'fennec fox',
    'snow leopard', 'clouded leopard', 'binturong', 'civet', 'wallaby',
    'tamarin', 'marmoset', 'macaque', 'gibbon', 'mandrill', 'colobus',
    'kookaburra', 'cassowary', 'condor', 'falcon', 'kiwi bird', 'puffin',
    'seahorse', 'jelly fish', 'crab', 'lobster', 'turtle pond', 'pond',
  ]),

  'Jobs': new Set([
    'teacher', 'doctor', 'nurse', 'dentist', 'lawyer', 'judge', 'police officer',
    'cop', 'firefighter', 'fireman', 'paramedic', 'emt', 'surgeon', 'pharmacist',
    'veterinarian', 'vet', 'engineer', 'architect', 'accountant', 'banker',
    'cashier', 'clerk', 'salesperson', 'manager', 'ceo', 'secretary',
    'receptionist', 'assistant', 'consultant', 'analyst', 'programmer',
    'software developer', 'developer', 'coder', 'web developer', 'designer',
    'graphic designer', 'artist', 'painter', 'sculptor', 'photographer',
    'writer', 'author', 'journalist', 'reporter', 'editor', 'blogger',
    'musician', 'singer', 'songwriter', 'composer', 'dj', 'actor', 'actress',
    'director', 'producer', 'comedian', 'dancer', 'choreographer', 'chef',
    'cook', 'baker', 'butcher', 'barista', 'bartender', 'waiter', 'waitress',
    'server', 'host', 'dishwasher', 'busser', 'farmer', 'rancher', 'fisherman',
    'gardener', 'landscaper', 'florist', 'plumber', 'electrician', 'carpenter',
    'mechanic', 'welder', 'mason', 'roofer', 'painter', 'construction worker',
    'contractor', 'plasterer', 'locksmith', 'janitor', 'custodian', 'cleaner',
    'maid', 'housekeeper', 'pilot', 'flight attendant', 'air traffic controller',
    'sailor', 'captain', 'truck driver', 'bus driver', 'taxi driver',
    'uber driver', 'delivery driver', 'mail carrier', 'mailman', 'postman',
    'train conductor', 'astronaut', 'scientist', 'biologist', 'chemist',
    'physicist', 'researcher', 'lab technician', 'mathematician', 'statistician',
    'professor', 'principal', 'librarian', 'counselor', 'therapist',
    'psychologist', 'psychiatrist', 'social worker', 'coach', 'trainer',
    'personal trainer', 'athlete', 'soccer player', 'basketball player',
    'baseball player', 'referee', 'umpire', 'lifeguard', 'soldier', 'marine',
    'general', 'sergeant', 'spy', 'detective', 'investigator', 'security guard',
    'bodyguard', 'bouncer', 'politician', 'senator', 'president', 'mayor',
    'governor', 'diplomat', 'ambassador', 'economist', 'real estate agent',
    'realtor', 'insurance agent', 'stockbroker', 'financial advisor',
    'auditor', 'bookkeeper', 'translator', 'interpreter', 'tour guide',
    'travel agent', 'hotel manager', 'concierge', 'optometrist', 'optician',
    'chiropractor', 'physical therapist', 'radiologist', 'anesthesiologist',
    'pediatrician', 'cardiologist', 'dermatologist', 'midwife', 'caregiver',
    'babysitter', 'nanny', 'tutor', 'professor', 'archaeologist', 'geologist',
    'meteorologist', 'zoologist', 'botanist', 'astronomer', 'marine biologist',
    'park ranger', 'forester', 'miner', 'oil worker', 'factory worker',
    'machinist', 'assembler', 'tailor', 'seamstress', 'fashion designer',
    'model', 'makeup artist', 'hairdresser', 'barber', 'stylist', 'manicurist',
    'masseuse', 'masseur', 'esthetician', 'jeweler', 'watchmaker', 'blacksmith',
    'potter', 'glassblower', 'animator', 'illustrator', 'cartoonist',
    'voice actor', 'stunt double', 'magician', 'clown', 'ringmaster',
    'acrobat', 'juggler', 'puppeteer', 'umpire', 'caddie', 'jockey',
    'plumber apprentice', 'apprentice', 'intern', 'volunteer', 'recruiter',
    'hr manager', 'project manager', 'product manager', 'marketer',
    'copywriter', 'public relations', 'lobbyist', 'paralegal', 'notary',
    'court reporter', 'bailiff', 'warden', 'probation officer', 'firefighter chief',
  ]),

  'Things in space': new Set([
    'star', 'stars', 'planet', 'planets', 'moon', 'moons', 'sun', 'galaxy',
    'galaxies', 'comet', 'comets', 'asteroid', 'asteroids', 'meteor',
    'meteors', 'meteorite', 'meteoroid', 'nebula', 'nebulae', 'black hole',
    'black holes', 'supernova', 'quasar', 'pulsar', 'neutron star',
    'white dwarf', 'red giant', 'dwarf planet', 'constellation', 'milky way',
    'solar system', 'universe', 'cosmos', 'mercury', 'venus', 'earth', 'mars',
    'jupiter', 'saturn', 'uranus', 'neptune', 'pluto', 'satellite',
    'satellites', 'space station', 'iss', 'international space station',
    'rocket', 'rockets', 'spaceship', 'spacecraft', 'space shuttle', 'shuttle',
    'capsule', 'lander', 'rover', 'mars rover', 'lunar module', 'probe',
    'space probe', 'telescope', 'space telescope', 'hubble', 'james webb',
    'astronaut', 'astronauts', 'cosmonaut', 'spacewalk', 'spacesuit', 'helmet',
    'alien', 'aliens', 'ufo', 'flying saucer', 'extraterrestrial', 'martian',
    'orbit', 'gravity', 'zero gravity', 'weightlessness', 'vacuum', 'cosmic dust',
    'space dust', 'stardust', 'solar flare', 'solar wind', 'sunspot', 'corona',
    'eclipse', 'solar eclipse', 'lunar eclipse', 'crater', 'craters', 'ring',
    'rings', 'saturns rings', 'asteroid belt', 'kuiper belt', 'oort cloud',
    'big bang', 'dark matter', 'dark energy', 'wormhole', 'event horizon',
    'light year', 'parsec', 'cosmic ray', 'gamma ray', 'shooting star',
    'falling star', 'north star', 'polaris', 'sirius', 'betelgeuse', 'vega',
    'rigel', 'antares', 'proxima centauri', 'alpha centauri', 'andromeda',
    'orion', 'big dipper', 'little dipper', 'ursa major', 'ursa minor',
    'cassiopeia', 'scorpius', 'leo', 'taurus', 'gemini', 'aries', 'cancer',
    'virgo', 'libra', 'sagittarius', 'capricorn', 'aquarius', 'pisces',
    'red dwarf', 'brown dwarf', 'binary star', 'star cluster', 'globular cluster',
    'exoplanet', 'gas giant', 'ice giant', 'terrestrial planet', 'asteroid field',
    'space junk', 'space debris', 'launch pad', 'mission control', 'nasa',
    'spacex', 'rocket booster', 'fuel tank', 'thruster', 'antenna',
    'solar panel', 'solar panels', 'space elevator', 'space colony',
    'space dock', 'starbase', 'mothership', 'space probe voyager', 'voyager',
    'apollo', 'sputnik', 'curiosity', 'perseverance', 'opportunity', 'spirit',
    'falcon 9', 'starship', 'saturn v', 'soyuz', 'titan', 'europa', 'ganymede',
    'io', 'callisto', 'phobos', 'deimos', 'titan moon', 'enceladus', 'triton',
    'ceres', 'eris', 'haumea', 'makemake', 'halleys comet', 'space rock',
  ]),

  'Cartoon characters': new Set([
    'mickey mouse', 'mickey', 'minnie mouse', 'minnie', 'donald duck',
    'daffy duck', 'goofy', 'pluto', 'bugs bunny', 'porky pig', 'tweety',
    'tweety bird', 'sylvester', 'elmer fudd', 'yosemite sam', 'road runner',
    'wile e coyote', 'foghorn leghorn', 'marvin the martian', 'tasmanian devil',
    'taz', 'speedy gonzales', 'pepe le pew', 'tom', 'jerry', 'tom and jerry',
    'scooby doo', 'scooby', 'shaggy', 'fred', 'velma', 'daphne', 'spongebob',
    'spongebob squarepants', 'patrick', 'patrick star', 'squidward',
    'mr krabs', 'sandy cheeks', 'plankton', 'gary', 'bart simpson', 'bart',
    'homer simpson', 'homer', 'marge simpson', 'marge', 'lisa simpson', 'lisa',
    'maggie', 'maggie simpson', 'ned flanders', 'mr burns', 'krusty the clown',
    'peter griffin', 'stewie', 'stewie griffin', 'brian griffin', 'lois griffin',
    'chris griffin', 'meg griffin', 'fred flintstone', 'wilma flintstone',
    'barney rubble', 'betty rubble', 'pebbles', 'dino', 'george jetson',
    'jane jetson', 'elroy', 'judy jetson', 'astro', 'yogi bear', 'boo boo',
    'popeye', 'olive oyl', 'bluto', 'wimpy', 'felix the cat', 'woody woodpecker',
    'mr magoo', 'snoopy', 'charlie brown', 'woodstock', 'linus', 'lucy',
    'peppermint patty', 'pig pen', 'garfield', 'odie', 'jon arbuckle',
    'tom cat', 'pink panther', 'underdog', 'rocky', 'bullwinkle', 'dudley do right',
    'george of the jungle', 'inspector gadget', 'penny', 'brain', 'dr claw',
    'darkwing duck', 'launchpad', 'scrooge mcduck', 'huey', 'dewey', 'louie',
    'chip', 'dale', 'gadget', 'baloo', 'kit cloudkicker', 'tailspin',
    'gummi bears', 'duck tales', 'rescue rangers', 'doug', 'rugrats',
    'tommy pickles', 'chuckie', 'angelica', 'reptar', 'arnold', 'hey arnold',
    'helga', 'gerald', 'the wild thornberrys', 'eliza', 'rocko', 'ren', 'stimpy',
    'ren and stimpy', 'cat dog', 'catdog', 'aaahh real monsters', 'angry beavers',
    'powerpuff girls', 'blossom', 'bubbles', 'buttercup', 'mojo jojo',
    'dexter', "dexter's laboratory", 'dee dee', 'johnny bravo', 'cow and chicken',
    'courage the cowardly dog', 'courage', 'ed edd n eddy', 'ed', 'edd', 'eddy',
    'samurai jack', 'dexters lab', 'ben 10', 'gwen', 'kevin', 'finn', 'jake',
    'jake the dog', 'adventure time', 'princess bubblegum', 'marceline',
    'ice king', 'bmo', 'gumball', 'darwin', 'anais', 'regular show', 'mordecai',
    'rigby', 'benson', 'pops', 'steven universe', 'steven', 'garnet', 'amethyst',
    'pearl', 'gravity falls', 'dipper', 'mabel', 'grunkle stan', 'soos',
    'wendy', 'bill cipher', 'phineas', 'ferb', 'perry the platypus',
    'doofenshmirtz', 'candace', 'kim possible', 'ron stoppable', 'rufus',
    'avatar aang', 'aang', 'katara', 'sokka', 'toph', 'zuko', 'appa', 'momo',
    'korra', 'tom and jerry mouse', 'jerry mouse', 'speed racer', 'astro boy',
    'pikachu', 'ash ketchum', 'naruto', 'goku', 'vegeta', 'sailor moon',
    'totoro', 'doraemon', 'shrek', 'donkey', 'buzz lightyear', 'woody',
    'olaf', 'elsa', 'simba', 'mufasa', 'timon', 'pumbaa', 'aladdin', 'genie',
    'ariel', 'nemo', 'dory', 'mike wazowski', 'sulley', 'wall e', 'wall-e',
  ]),

  'Things that are loud': new Set([
    'thunder', 'explosion', 'bomb', 'gunshot', 'gun', 'firework', 'fireworks',
    'siren', 'ambulance', 'fire truck', 'police siren', 'alarm', 'fire alarm',
    'car alarm', 'alarm clock', 'horn', 'car horn', 'air horn', 'foghorn',
    'train', 'train horn', 'truck', 'motorcycle', 'jet', 'jet engine',
    'airplane', 'helicopter', 'rocket', 'rocket launch', 'engine', 'race car',
    'chainsaw', 'jackhammer', 'drill', 'power drill', 'lawnmower', 'leaf blower',
    'vacuum', 'vacuum cleaner', 'blender', 'garbage disposal', 'dishwasher',
    'washing machine', 'dryer', 'generator', 'compressor', 'air compressor',
    'concert', 'rock concert', 'speaker', 'speakers', 'loudspeaker', 'subwoofer',
    'stereo', 'boombox', 'amplifier', 'amp', 'megaphone', 'bullhorn', 'pa system',
    'music', 'loud music', 'band', 'drum', 'drums', 'drum set', 'cymbal',
    'cymbals', 'guitar', 'electric guitar', 'bass', 'trumpet', 'tuba', 'trombone',
    'bagpipes', 'organ', 'gong', 'bell', 'church bell', 'school bell',
    'doorbell', 'whistle', 'referee whistle', 'train whistle', 'kettle',
    'tea kettle', 'teapot', 'microphone', 'feedback', 'static', 'scream',
    'screaming', 'yell', 'yelling', 'shout', 'shouting', 'crying', 'baby crying',
    'baby', 'crowd', 'stadium', 'cheering', 'crowd cheering', 'applause',
    'clapping', 'boo', 'booing', 'laughter', 'laughing', 'dog barking', 'bark',
    'barking dog', 'dog', 'rooster', 'crow', 'lion roar', 'lion', 'roar',
    'elephant', 'elephant trumpet', 'howler monkey', 'cicada', 'cicadas',
    'parrot', 'macaw', 'seagull', 'geese', 'donkey', 'cow', 'pig', 'goat',
    'cat', 'meow', 'thunderstorm', 'storm', 'lightning', 'avalanche',
    'earthquake', 'volcano', 'eruption', 'waterfall', 'rapids', 'ocean waves',
    'wind', 'tornado', 'hurricane', 'tsunami', 'crash', 'car crash', 'collision',
    'smash', 'bang', 'boom', 'pop', 'snap', 'clap', 'slam', 'door slam',
    'slamming door', 'breaking glass', 'shattering glass', 'glass breaking',
    'cannon', 'cannon fire', 'artillery', 'machine gun', 'rifle', 'shotgun',
    'firecracker', 'firecrackers', 'bottle rocket', 'm80', 'dynamite', 'tnt',
    'jet ski', 'speedboat', 'monster truck', 'drag race', 'nascar',
    'formula 1', 'race track', 'pit crew', 'power tools', 'sander', 'grinder',
    'angle grinder', 'nail gun', 'wood chipper', 'snow blower', 'pressure washer',
    'industrial fan', 'factory', 'construction site', 'demolition', 'wrecking ball',
    'pile driver', 'bulldozer', 'excavator', 'dump truck', 'cement mixer',
    'subway', 'subway train', 'el train', 'freight train', 'locomotive',
    'ship horn', 'cruise ship horn', 'tugboat', 'thunderclap', 'sonic boom',
    'marching band', 'parade', 'drumline', 'orchestra', 'choir', 'opera singer',
    'heavy metal', 'death metal', 'club', 'nightclub', 'rave', 'festival',
  ]),

  'Shoes brands': new Set([
    'nike', 'adidas', 'puma', 'reebok', 'converse', 'vans', 'new balance',
    'asics', 'under armour', 'skechers', 'fila', 'jordan', 'air jordan',
    'timberland', 'dr martens', 'doc martens', 'clarks', 'crocs', 'birkenstock',
    'ugg', 'uggs', 'gucci', 'prada', 'louis vuitton', 'balenciaga', 'versace',
    'dolce and gabbana', 'armani', 'dior', 'chanel', 'yves saint laurent',
    'saint laurent', 'givenchy', 'valentino', 'jimmy choo', 'christian louboutin',
    'louboutin', 'manolo blahnik', 'ferragamo', 'salvatore ferragamo', 'tods',
    'bally', 'cole haan', 'allen edmonds', 'florsheim', 'johnston and murphy',
    'sperry', 'hush puppies', 'rockport', 'merrell', 'salomon', 'columbia',
    'keen', 'teva', 'chaco', 'hoka', 'hoka one one', 'brooks', 'saucony',
    'mizuno', 'on', 'on running', 'altra', 'la sportiva', 'scarpa', 'arc teryx',
    'the north face', 'north face', 'patagonia', 'vivobarefoot', 'allbirds',
    'toms', 'sketchers', 'k swiss', 'kswiss', 'le coq sportif', 'diadora',
    'lotto', 'umbro', 'kappa', 'ellesse', 'lacoste', 'tommy hilfiger',
    'calvin klein', 'ralph lauren', 'polo', 'guess', 'steve madden',
    'aldo', 'nine west', 'michael kors', 'kate spade', 'tory burch',
    'coach', 'stuart weitzman', 'sam edelman', 'vince', 'rothys', 'rothy\'s',
    'cole', 'bata', 'red wing', 'wolverine', 'caterpillar', 'cat footwear',
    'dr scholls', 'dr scholl\'s', 'naturalizer', 'easy spirit', 'clark',
    'reef', 'olukai', 'havaianas', 'crocs literide', 'native', 'sanuk',
    'palladium', 'superga', 'feiyue', 'onitsuka tiger', 'asics tiger',
    'common projects', 'golden goose', 'veja', 'axel arigato', 'koio',
    'greats', 'cariuma', 'thursday boots', 'red back', 'blundstone',
    'wolverine boots', 'danner', 'chippewa', 'justin boots', 'ariat',
    'lucchese', 'tony lama', 'durango', 'georgia boot', 'irish setter',
    'keds', 'tretorn', 'pf flyers', 'sperry top sider', 'bass', 'gh bass',
    'dexter', 'etnies', 'es', 'emerica', 'dc', 'dc shoes', 'globe',
    'lakai', 'supra', 'osiris', 'fallen', 'circa', 'dvs', 'vox', 'ipath',
    'puma suede', 'yeezy', 'off white', 'fear of god', 'essentials',
    'reebok classic', 'saucony jazz', 'new balance 990', 'air max',
    'air force', 'stan smith', 'superstar', 'gazelle', 'chuck taylor',
    'old skool', 'sk8 hi', 'authentic', 'era', 'slip on', 'classic',
    'cloudfoam', 'ultraboost', 'boost', 'react', 'zoom', 'pegasus',
  ]),

  'Things at a party': new Set([
    'balloon', 'balloons', 'cake', 'birthday cake', 'cupcake', 'cupcakes',
    'candles', 'birthday candles', 'confetti', 'streamers', 'banner',
    'birthday banner', 'sign', 'decorations', 'party hat', 'party hats',
    'hat', 'noisemaker', 'noisemakers', 'party favor', 'party favors',
    'goodie bag', 'gift bag', 'present', 'presents', 'gift', 'gifts',
    'gift wrap', 'wrapping paper', 'bow', 'ribbon', 'card', 'birthday card',
    'invitation', 'invitations', 'guest', 'guests', 'host', 'music', 'dj',
    'speaker', 'speakers', 'stereo', 'playlist', 'dance floor', 'dancing',
    'disco ball', 'strobe light', 'lights', 'string lights', 'fairy lights',
    'snacks', 'chips', 'pretzels', 'popcorn', 'crackers', 'dip', 'salsa',
    'guacamole', 'cheese', 'cheese plate', 'veggie tray', 'fruit platter',
    'finger food', 'appetizers', 'hors d oeuvres', 'pizza', 'sandwiches',
    'hot dogs', 'hamburgers', 'sliders', 'wings', 'nachos', 'pigs in a blanket',
    'cookies', 'brownies', 'candy', 'ice cream', 'punch', 'punch bowl',
    'soda', 'pop', 'juice', 'water', 'lemonade', 'drinks', 'beer', 'wine',
    'champagne', 'cocktails', 'cups', 'red cups', 'solo cups', 'plastic cups',
    'paper plates', 'plates', 'napkins', 'plastic utensils', 'forks', 'spoons',
    'straws', 'tablecloth', 'table', 'chairs', 'cooler', 'ice', 'bottle opener',
    'pinata', 'candy from pinata', 'games', 'party games', 'board games',
    'cards', 'karaoke', 'karaoke machine', 'microphone', 'photo booth',
    'props', 'camera', 'balloon animals', 'face paint', 'clown', 'magician',
    'entertainment', 'bounce house', 'jumpy house', 'moon bounce', 'cotton candy',
    'cotton candy machine', 'popcorn machine', 'snow cone machine',
    'party bus', 'limo', 'tent', 'gazebo', 'grill', 'bbq', 'fire pit',
    'sparkler', 'sparklers', 'glow stick', 'glow sticks', 'glow necklace',
    'silly string', 'bubble machine', 'bubbles', 'streamer cannon',
    'party popper', 'party poppers', 'goody bag', 'thank you card',
    'centerpiece', 'flowers', 'bouquet', 'garland', 'bunting', 'paper lantern',
    'lanterns', 'tiki torch', 'mood lighting', 'candle', 'name tags',
    'guest book', 'cake topper', 'plates and cups', 'serving tray', 'platter',
    'beverage dispenser', 'keg', 'shot glasses', 'wine glasses', 'champagne flute',
    'champagne flutes', 'toast', 'speech', 'gift table', 'coat check',
    'dance music', 'birthday song', 'happy birthday', 'celebration',
    'party dress', 'costume', 'costumes', 'mask', 'masks', 'tiara', 'sash',
    'birthday sash', 'crown', 'beads', 'lei', 'leis', 'bunny ears',
    'photo backdrop', 'backdrop', 'balloon arch', 'number balloon',
    'foil balloon', 'helium tank', 'goodie', 'treats', 'dessert table',
    'candy bar', 'sweets table', 'chocolate fountain', 'cake knife',
  ]),
};
