// categoryPacks.js
// Maps every gen9 Category Blitz category name to its pack id, built from the
// gen9.raw.json pack groupings. Used to tag gen9 categories with their pack when
// they are appended to RAW_CATEGORIES in categoryBlitzLogic.js. Keys match the
// gen9 accept-list keys (categoryAnswers/gen9.js) exactly.
const CATEGORY_PACKS = {
  // movies
  "Marvel Cinematic Universe Villains": "movies",
  "Sitcoms": "movies",
  "Animated Movies": "movies",
  "DC Comics Superheroes": "movies",
  "Star Wars Planets": "movies",
  "Anime Villains": "movies",
  "Disney Animated Movie Characters": "movies",
  "James Bond Villains": "movies",
  "Horror Movie Monsters": "movies",
  "Pixar Movies": "movies",
  "Studio Ghibli Movies": "movies",
  "Famous TV Detectives": "movies",
  "Marvel Superheroes": "movies",
  "Video Game Movies": "movies",
  "James Bond Movies": "movies",
  "Friends Characters": "movies",
  "Harry Potter Spells": "movies",
  "Disney Villains": "movies",
  "Star Wars Ships": "movies",
  "Animated Movie Characters": "movies",
  "Animated TV Shows": "movies",
  "Horror Movie Characters": "movies",
  "Harry Potter Characters": "movies",
  "Sitcom Characters": "movies",
  "Lord of the Rings characters": "movies",
  "Breaking Bad characters": "movies",
  "The Office characters": "movies",
  "Batman villains": "movies",
  "Star Wars Characters": "movies",
  "SpongeBob SquarePants Characters": "movies",
  "Batman Characters": "movies",
  // gaming
  "Mario Kart Items": "gaming",
  "Minecraft Mobs": "gaming",
  "Pokemon Gen 1": "gaming",
  "Video game consoles": "gaming",
  "Legend of Zelda characters": "gaming",
  "Street Fighter characters": "gaming",
  "Mario characters": "gaming",
  "Fortnite weapons": "gaming",
  "Sonic the Hedgehog characters": "gaming",
  "Minecraft blocks": "gaming",
  "Overwatch heroes": "gaming",
  "Call of Duty games": "gaming",
  "Super Smash Bros. fighters": "gaming",
  "Grand Theft Auto games": "gaming",
  "Pac-Man ghosts": "gaming",
  "Animal Crossing Villagers": "gaming",
  "League of Legends Champions": "gaming",
  "PlayStation Exclusive Games": "gaming",
  "Mortal Kombat characters": "gaming",
  "Halo weapons": "gaming",
  "Resident Evil games": "gaming",
  "Metroid bosses": "gaming",
  "Street Fighter games": "gaming",
  "Final Fantasy summons": "gaming",
  "Among Us colors": "gaming",
  "Elden Ring bosses": "gaming",
  "Kingdom Hearts characters": "gaming",
  "Genshin Impact playable characters": "gaming",
  "Street Fighter moves": "gaming",
  "Minecraft biomes": "gaming",
  "Portal items and elements": "gaming",
  "Team Fortress 2 classes": "gaming",
  "Half-Life weapons": "gaming",
  "Skyrim races": "gaming",
  "Dark Souls bosses": "gaming",
  "Fall Guys rounds": "gaming",
  "Stardew Valley villagers": "gaming",
  "Among Us maps": "gaming",
  "Fallout factions": "gaming",
  "Dark Souls weapons": "gaming",
  "Super Mario power-ups": "gaming",
  "Mortal Kombat games": "gaming",
  "Call of Duty weapons": "gaming",
  "Roblox games": "gaming",
  "Mortal Kombat fighters": "gaming",
  "Valorant agents": "gaming",
  "Minecraft tools and weapons": "gaming",
  "Angry Birds birds": "gaming",
  "Nintendo consoles and handhelds": "gaming",
  "Half-Life enemies": "gaming",
  "Fallout creatures": "gaming",
  "Among Us tasks": "gaming",
  "Minecraft Ore Blocks": "gaming",
  "Pac-Man Characters": "gaming",
  "Nintendo Switch Games": "gaming",
  "Minecraft potions": "gaming",
  "Pac-Man maze fruits": "gaming",
  "Apex Legends characters": "gaming",
  "The Sims games": "gaming",
  "Donkey Kong characters": "gaming",
  // food
  "Pizza toppings": "food",
  "Breakfast cereal brands": "food",
  "Types of pasta": "food",
  "Ice cream flavors": "food",
  "Soda brands": "food",
  "Sushi types": "food",
  "Girl Scout cookies": "food",
  "Fast food chains": "food",
  "Types of cheese": "food",
  "Cocktails": "food",
  "Fruits": "food",
  "Sandwich types": "food",
  "Potato chip brands": "food",
  "Coffee drinks": "food",
  "Vegetables": "food",
  "Types of nuts": "food",
  "Bakery items": "food",
  "Types of apples": "food",
  "Candy bars": "food",
  "Popular spices and herbs": "food",
  "Types of pie": "food",
  "Energy drink brands": "food",
  "Types of seafood": "food",
  "Types of tea": "food",
  "Popular condiments": "food",
  "Types of melon": "food",
  "Types of bread": "food",
  "Popular snack cakes": "food",
  "Types of steak": "food",
  "Types of mushrooms": "food",
  "Milk alternatives": "food",
  "Types of pancakes": "food",
  "Popular salad dressings": "food",
  "Types of tacos": "food",
  "Types of peppers": "food",
  "Popular yogurt brands": "food",
  "Types of beans": "food",
  "Types of squash": "food",
  "Types of BBQ meat": "food",
  "Popular food brands": "food",
  "Types of beer": "food",
  "International cuisines": "food",
  "Types of citrus fruit": "food",
  "Types of donuts": "food",
  "Popular sports drinks": "food",
  "Types of rice": "food",
  "Types of berries": "food",
  "Popular dipping sauces": "food",
  "Types of cookies": "food",
  "Types of eggs": "food",
  "Types of potatoes": "food",
  "Types of jerky": "food",
  "Types of soup": "food",
  "Types of cake": "food",
  "Ben & Jerry's flavors": "food",
  "Types of soup dumplings & dim sum": "food",
  "Hot sauce brands": "food",
  "Mexican food dishes": "food",
  "Italian pasta sauces": "food",
  "Herbal teas & infusions": "food",
  // animals
  "Dog breeds": "animals",
  "Trees": "animals",
  "Gemstones": "animals",
  "Ocean animals": "animals",
  "Dinosaurs": "animals",
  "Cat breeds": "animals",
  "Zoo animals": "animals",
  "Birds": "animals",
  "Flowers": "animals",
  "Insects": "animals",
  "Farm animals": "animals",
  "Reptiles and amphibians": "animals",
  "Marsupials": "animals",
  "Mushrooms and fungi": "animals",
  "Coniferous trees": "animals",
  "Predatory mammals": "animals",
  "Planets and moons": "animals",
  "Nuts and seeds": "animals",
  "Big cats": "animals",
  "Primates": "animals",
  "Succulents and cacti": "animals",
  "Horses and ponies": "animals",
  "Rodents": "animals",
  "Bears": "animals",
  "Aquarium fish": "animals",
  "Venomous snakes": "animals",
  "Herbs and spices": "animals",
  "Marine mammals": "animals",
  "Wild canines": "animals",
  "Arachnids": "animals",
  "Bovine breeds": "animals",
  "Types of clouds": "animals",
  "Weather phenomena": "animals",
  "Birds of prey": "animals",
  "Houseplants": "animals",
  "Prehistoric creatures": "animals",
  "Edible berries": "animals",
  "Nocturnal animals": "animals",
  "Antelope and deer species": "animals",
  "Types of rocks": "animals",
  "Marine invertebrates": "animals",
  // sports
  "NBA teams": "sports",
  "Baseball positions": "sports",
  "NFL teams": "sports",
  "Soccer positions": "sports",
  "Martial arts": "sports",
  "NHL teams": "sports",
  "Tennis equipment": "sports",
  "Cycling disciplines": "sports",
  "Major League Baseball teams": "sports",
  "Water sports": "sports",
  "English Premier League clubs": "sports",
  "Formula 1 constructors": "sports",
  "Gymnastics events": "sports",
  "WNBA teams": "sports",
  "MLS teams": "sports",
  "Golf clubs": "sports",
  "Cricket fielding positions": "sports",
  "Rugby positions": "sports",
  "Track and field events": "sports",
  "Types of sports balls": "sports",
  "College football bowl games": "sports",
  "Active Formula 1 tracks": "sports",
  "Major professional sports leagues": "sports",
  "Professional cycling teams": "sports",
  "Volleyball positions": "sports",
  "Bowling terms": "sports",
  "Boxing weight classes": "sports",
  "NASCAR Cup Series tracks": "sports",
  "Professional wrestling promotions": "sports",
  "NCAA Division I conferences": "sports",
  "Chess pieces": "sports",
  "Swimming strokes": "sports",
  "Events in a decathlon": "sports",
  "Football positions": "sports",
  "Types of sports rackets": "sports",
  "Basketball positions": "sports",
  "Extreme sports": "sports",
  "Ice hockey positions": "sports",
  "Olympic sports": "sports",
  "Active NFL stadiums": "sports",
  "Grand Slam tennis tournaments": "sports",
  "Active NBA Arenas": "sports",
  "Heisman Trophy Winners": "sports",
  "Tour de France Jerseys": "sports",
  // world
  "Greek gods": "world",
  "South American countries": "world",
  "Planets in our solar system": "world",
  "US states": "world",
  "Norse gods": "world",
  "Famous landmarks": "world",
  "European capitals": "world",
  "US presidents": "world",
  "African countries": "world",
  "Asian countries": "world",
  "Egyptian gods": "world",
  "Major world rivers": "world",
  "Canadian provinces and territories": "world",
  "Roman gods": "world",
  "Oceanian countries": "world",
  "US state capitals": "world",
  "Japanese prefectures": "world",
  "Mythical creatures": "world",
  "Zodiac constellations": "world",
  "World mountain ranges": "world",
  "Latin American countries": "world",
  "US National Parks": "world",
  "Ancient civilizations": "world",
  "Seven Wonders of the Ancient World": "world",
  "US state nicknames": "world",
  "Middle Eastern countries": "world",
  "Arthurian legend characters": "world",
  "US states bordering the Atlantic Ocean": "world",
  "Caribbean countries": "world",
  "Dwarf planets": "world",
  "Greek heroes": "world",
  "Major world deserts": "world",
  "British monarchs": "world",
  "US state abbreviations": "world",
  "Major world islands": "world",
  "Greek monsters and beasts": "world",
  "Great Lakes of North America": "world",
  "Signers of the US Declaration of Independence": "world",
  "Inca deities": "world",
  "World seas": "world",
  "Hindu deities": "world",
  "Australian states and territories": "world",
  "Irish counties": "world",
  "Aztec deities": "world",
  "World oceans": "world",
  "World deserts": "world",
  "Major world peninsulas": "world",
};

module.exports = CATEGORY_PACKS;
