module.exports = {
  'Shoe brands': new Set([
    'nike', 'adidas', 'jordan', 'air jordan', 'new balance', 'vans', 'converse', 'puma', 'reebok', 'asics',
    'crocs', 'skechers', 'timberland', 'timberlands', 'dr martens', 'doc martens', 'doctor martens', 'hoka', 'hoka one one', 'on',
    'on running', 'on cloud', 'salomon', 'brooks', 'saucony', 'under armour', 'fila', 'yeezy', 'birkenstock', 'birkenstocks',
    'ugg', 'uggs', 'clarks', 'merrell', 'keen', 'columbia', 'the north face', 'north face', 'allbirds', 'veja',
    'cole haan', 'sperry', 'sperrys', 'toms', 'gucci', 'prada', 'louis vuitton', 'balenciaga', 'versace', 'dior',
    'chanel', 'jimmy choo', 'christian louboutin', 'louboutin', 'manolo blahnik', 'steve madden', 'aldo', 'nine west', 'vionic', 'dansko',
    'hush puppies', 'rockport', 'florsheim', 'allen edmonds', 'red wing', 'wolverine', 'caterpillar', 'cat', 'palladium', 'lacoste',
    'kswiss', 'k swiss', 'le coq sportif', 'diadora', 'lotto', 'umbro', 'mizuno', 'brooks running', 'newton', 'altra',
    'topo athletic', 'inov8', 'la sportiva', 'scarpa', 'arcteryx', 'mammut', 'lowa', 'danner', 'hunter', 'bogs',
    'sorel', 'kamik', 'muck boots', 'xtratuf', 'vivobarefoot', 'xero shoes', 'feiyue', 'onitsuka tiger', 'reef', 'olukai',
    'havaianas', 'rainbow', 'chaco', 'teva', 'sanuk', 'oofos', 'kizik', 'cariuma', 'greats', 'koio',
    'thursday boot company', 'thursday boots', 'common projects', 'golden goose', 'maison margiela', 'rick owens', 'off white', 'comme des garcons', 'a bathing ape', 'bape',
    'supra', 'osiris', 'dc', 'dc shoes', 'es', 'emerica', 'globe', 'etnies', 'lakai', 'nike sb',
    'vans old skool', 'chuck taylor', 'air force 1', 'air max', 'dunk', 'blazer', 'cortez', 'gazelle', 'stan smith', 'superstar',
    'samba', 'ultraboost', 'nmd', 'forum', 'campus', 'sk8 hi', 'authentic', 'era', 'slip on', 'classic clog',
    'tory burch', 'kate spade', 'michael kors', 'coach', 'marc jacobs', 'ferragamo', 'bally', 'bottega veneta', 'valentino', 'givenchy',
    'fendi', 'burberry', 'hermes', 'celine', 'saint laurent', 'ysl', 'alexander mcqueen', 'stuart weitzman', 'sam edelman', 'jeffrey campbell'
  ]),

  'Car brands': new Set([
    'toyota', 'honda', 'ford', 'chevrolet', 'chevy', 'tesla', 'rivian', 'lucid', 'nissan', 'mazda',
    'subaru', 'mitsubishi', 'suzuki', 'hyundai', 'kia', 'genesis', 'lexus', 'acura', 'infiniti', 'volkswagen',
    'vw', 'audi', 'bmw', 'mercedes', 'mercedes benz', 'porsche', 'mini', 'smart', 'opel', 'seat',
    'skoda', 'fiat', 'alfa romeo', 'lancia', 'maserati', 'ferrari', 'lamborghini', 'pagani', 'bugatti', 'koenigsegg',
    'rolls royce', 'bentley', 'aston martin', 'jaguar', 'land rover', 'range rover', 'mclaren', 'lotus', 'morgan', 'tvr',
    'volvo', 'polestar', 'saab', 'peugeot', 'renault', 'citroen', 'ds', 'dacia', 'bugatti', 'cadillac',
    'buick', 'gmc', 'lincoln', 'chrysler', 'dodge', 'ram', 'jeep', 'plymouth', 'pontiac', 'oldsmobile',
    'saturn', 'hummer', 'mercury', 'eagle', 'amc', 'studebaker', 'packard', 'tucker', 'delorean', 'fisker',
    'karma', 'vinfast', 'byd', 'nio', 'xpeng', 'li auto', 'geely', 'great wall', 'chery', 'haval',
    'mg', 'tata', 'mahindra', 'maruti', 'proton', 'perodua', 'holden', 'datsun', 'isuzu', 'daihatsu',
    'scion', 'daewoo', 'ssangyong', 'lada', 'gaz', 'uaz', 'zaz', 'wartburg', 'trabant', 'skoda auto',
    'cupra', 'abarth', 'maybach', 'amg', 'brabus', 'alpina', 'ruf', 'singer', 'shelby', 'roush',
    'spyker', 'rimac', 'lordstown', 'canoo', 'faraday future', 'aptera', 'bollinger', 'workhorse', 'mullen', 'nikola',
    'wuling', 'hongqi', 'lynk and co', 'zeekr', 'aiways', 'voyah', 'ora', 'leapmotor', 'jac', 'foton',
    'caterham', 'noble', 'ariel', 'koenigsegg', 'gumpert', 'wiesmann', 'donkervoort', 'hennessey', 'saleen', 'panoz',
    'venturi', 'de tomaso', 'iso', 'bizzarrini', 'monteverdi', 'facel vega', 'auburn', 'cord', 'duesenberg', 'hudson',
    'nash', 'willys', 'kaiser', 'crosley', 'edsel', 'desoto', 'rambler', 'checker', 'stutz', 'pierce arrow'
  ]),

  'Fast food chains': new Set([
    'mcdonalds', 'burger king', 'wendys', 'taco bell', 'kfc', 'chick fil a', 'popeyes', 'subway', 'chipotle', 'five guys',
    'in n out', 'in and out', 'whataburger', 'raising canes', 'canes', 'jack in the box', 'sonic', 'arbys', 'dairy queen', 'dq',
    'culvers', 'shake shack', 'panera', 'panera bread', 'jimmy johns', 'jersey mikes', 'firehouse subs', 'quiznos', 'blimpie', 'potbelly',
    'dominos', 'pizza hut', 'papa johns', 'little caesars', 'cicis', 'marcos pizza', 'round table pizza', 'jets pizza', 'papa murphys', 'blaze pizza',
    'mod pizza', 'panda express', 'pf changs', 'pei wei', 'wingstop', 'buffalo wild wings', 'bww', 'zaxbys', 'bojangles', 'church\'s chicken',
    'churchs chicken', 'el pollo loco', 'pollo tropical', 'qdoba', 'moes', 'moes southwest grill', 'del taco', 'taco johns', 'taco cabana', 'rubios',
    'baja fresh', 'chronic tacos', 'freebirds', 'carls jr', 'hardees', 'checkers', 'rallys', 'white castle', 'krystal', 'steak n shake',
    'fatburger', 'the habit', 'habit burger', 'smashburger', 'good times', 'freddys', 'fuddruckers', 'red robin', 'a&w', 'sonic drive in',
    'dennys', 'ihop', 'waffle house', 'cracker barrel', 'bob evans', 'village inn', 'perkins', 'huddle house', 'shoneys', 'frischs',
    'dunkin', 'dunkin donuts', 'starbucks', 'tim hortons', 'krispy kreme', 'einstein bagels', 'caribou coffee', 'dutch bros', 'peets', 'costa coffee',
    'auntie annes', 'wetzels pretzels', 'cinnabon', 'orange julius', 'jamba juice', 'smoothie king', 'tropical smoothie', 'baskin robbins', 'cold stone', 'carvel',
    'dippin dots', 'rita\'s', 'ritas', 'menchies', 'pinkberry', 'yogurtland', 'sweetgreen', 'cava', 'tropical smoothie cafe', 'noodles and company',
    'pret a manger', 'au bon pain', 'corner bakery', 'la madeleine', 'wienerschnitzel', 'portillos', 'nathans', 'nathans famous', 'sbarro', 'fazolis',
    'olive garden', 'red lobster', 'outback', 'applebees', 'chilis', 'tgi fridays', 'longhorn steakhouse', 'texas roadhouse', 'golden corral', 'buffet',
    'hooters', 'twin peaks', 'wahlburgers', 'shake shack burgers', 'whatchamacallit', 'jollibee', 'nandos', 'chowking', 'tacos el gordo', 'taco bueno',
    'hungry jacks', 'greggs', 'wagamama', 'leon', 'pret', 'maccas', 'pizza pizza', 'a&w canada', 'harveys', 'swiss chalet'
  ]),

  'Apps on your phone right now': new Set([
    'instagram', 'tiktok', 'snapchat', 'whatsapp', 'spotify', 'youtube', 'gmail', 'maps', 'google maps', 'apple maps',
    'uber', 'lyft', 'venmo', 'cash app', 'paypal', 'zelle', 'reddit', 'discord', 'netflix', 'candy crush',
    'calculator', 'weather', 'notes', 'clock', 'calendar', 'camera', 'photos', 'messages', 'phone', 'safari',
    'chrome', 'facebook', 'messenger', 'twitter', 'x', 'threads', 'bluesky', 'linkedin', 'pinterest', 'tumblr',
    'wechat', 'telegram', 'signal', 'line', 'kakaotalk', 'viber', 'slack', 'zoom', 'microsoft teams', 'google meet',
    'skype', 'facetime', 'hulu', 'disney plus', 'hbo max', 'max', 'amazon prime video', 'peacock', 'paramount plus', 'apple tv',
    'twitch', 'soundcloud', 'apple music', 'pandora', 'audible', 'amazon music', 'tidal', 'shazam', 'doordash', 'grubhub',
    'ubereats', 'uber eats', 'postmates', 'instacart', 'amazon', 'ebay', 'etsy', 'shein', 'temu', 'wish',
    'target', 'walmart', 'starbucks', 'mcdonalds', 'duolingo', 'wordle', 'chess', 'words with friends', 'subway surfers', 'roblox',
    'minecraft', 'clash of clans', 'clash royale', 'pokemon go', 'genshin impact', 'among us', 'fortnite', 'call of duty mobile', 'coin master', 'royal match',
    'monopoly go', 'gardenscapes', 'homescapes', 'solitaire', 'sudoku', '2048', 'flappy bird', 'temple run', 'fruit ninja', 'angry birds',
    'spotify wrapped', 'be real', 'bereal', 'hinge', 'tinder', 'bumble', 'grindr', 'match', 'okcupid', 'coffee meets bagel',
    'robinhood', 'coinbase', 'cash app investing', 'mint', 'chase', 'bank of america', 'wells fargo', 'capital one', 'fidelity', 'webull',
    'google', 'google drive', 'dropbox', 'onedrive', 'icloud', 'notion', 'evernote', 'todoist', 'trello', 'asana',
    'fitbit', 'strava', 'myfitnesspal', 'apple health', 'headspace', 'calm', 'flo', 'sleep cycle', 'nike run club', 'peloton',
    'waze', 'flighty', 'tripit', 'airbnb', 'booking', 'expedia', 'hotels', 'kayak', 'yelp', 'tripadvisor',
    'venmo', 'splitwise', 'google photos', 'snapseed', 'vsco', 'lightroom', 'canva', 'capcut', 'inshot', 'picsart'
  ]),

  'Things in an Amazon package': new Set([
    'cardboard box', 'packing tape', 'bubble wrap', 'air pillows', 'the item', 'packing slip', 'smile logo', 'shipping label', 'barcode', 'qr code',
    'tissue paper', 'kraft paper', 'crumpled paper', 'foam peanuts', 'packing peanuts', 'foam insert', 'plastic bag', 'poly mailer', 'padded envelope', 'bubble mailer',
    'desiccant packet', 'silica gel', 'do not eat packet', 'instruction manual', 'warranty card', 'return label', 'invoice', 'receipt', 'promo flyer', 'coupon',
    'phone case', 'phone charger', 'charging cable', 'usb cable', 'usb c cable', 'lightning cable', 'wall adapter', 'power bank', 'earbuds', 'headphones',
    'airpods', 'bluetooth speaker', 'echo dot', 'fire tablet', 'fire stick', 'kindle', 'phone screen protector', 'tablet stand', 'laptop sleeve', 'mouse',
    'keyboard', 'mousepad', 'webcam', 'ring light', 'sd card', 'flash drive', 'hard drive', 'hdmi cable', 'ethernet cable', 'surge protector',
    'batteries', 'aa batteries', 'aaa batteries', 'light bulbs', 'led strip', 'extension cord', 'power strip', 'smart plug', 'smart bulb', 'thermostat',
    'book', 'paperback', 'hardcover', 'cookbook', 'journal', 'notebook', 'planner', 'pens', 'pencils', 'markers',
    'sticky notes', 'tape dispenser', 'stapler', 'scissors', 'glue', 'envelopes', 'printer paper', 'ink cartridge', 'label maker', 'binder',
    'water bottle', 'travel mug', 'coffee mug', 'tumbler', 'protein powder', 'vitamins', 'supplements', 'fish oil', 'melatonin', 'electrolytes',
    'phone holder', 'car mount', 'sunglasses', 'watch', 'watch band', 'jewelry', 'socks', 'underwear', 'tshirt', 't shirt',
    'leggings', 'workout shorts', 'sneakers', 'slippers', 'backpack', 'tote bag', 'wallet', 'belt', 'hat', 'beanie',
    'dog toy', 'cat toy', 'dog treats', 'cat litter', 'pet food', 'dog leash', 'collar', 'pet bed', 'litter box', 'aquarium',
    'kitchen gadget', 'spatula', 'measuring cups', 'cutting board', 'knife set', 'air fryer', 'blender', 'coffee maker', 'food storage', 'tupperware',
    'cleaning supplies', 'paper towels', 'toilet paper', 'dish soap', 'laundry detergent', 'trash bags', 'sponges', 'microfiber cloth', 'air freshener', 'candles',
    'toys', 'lego', 'puzzle', 'board game', 'playing cards', 'fidget toy', 'stuffed animal', 'action figure', 'coloring book', 'craft kit',
    'makeup', 'skincare', 'moisturizer', 'sunscreen', 'shampoo', 'conditioner', 'razors', 'toothbrush', 'electric toothbrush', 'hair dryer'
  ]),

  'Things in a Costco': new Set([
    'rotisserie chicken', 'hot dog', 'hot dog combo', 'free samples', 'samples', 'giant teddy bear', 'kirkland water', 'kirkland vodka', 'kirkland toilet paper', 'kirkland paper towels',
    'bulk paper towels', 'sheet cake', 'gas station', 'food court', 'pizza', 'churro', 'frozen yogurt', 'chicken bake', 'turkey wrap', 'caesar salad',
    'mango smoothie', 'berry smoothie', 'acai bowl', 'membership card', 'membership desk', 'flatbed cart', 'shopping cart', 'forklift', 'pallet', 'warehouse shelving',
    'bulk toilet paper', 'bulk water bottles', 'bulk eggs', 'flat of water', 'case of soda', 'giant ketchup', 'huge mayo jar', 'industrial olive oil', 'bulk rice', 'bulk flour',
    'giant bag of chips', 'bulk granola bars', 'variety pack chips', 'snack boxes', 'trail mix', 'mixed nuts', 'cashews', 'almonds', 'protein bars', 'kirkland protein bars',
    'muffins', 'croissants', 'bagels', 'dinner rolls', 'apple pie', 'pumpkin pie', 'cheesecake', 'tiramisu', 'cookies', 'kirkland cookies',
    'frozen pizza', 'frozen lasagna', 'frozen berries', 'frozen chicken', 'frozen shrimp', 'frozen salmon', 'frozen vegetables', 'frozen dumplings', 'frozen mac and cheese', 'frozen burritos',
    'milk', 'eggs', 'cheese', 'butter', 'yogurt', 'greek yogurt', 'cream cheese', 'sour cream', 'orange juice', 'almond milk',
    'ground beef', 'ribeye', 'whole chicken', 'chicken breast', 'salmon fillet', 'bacon', 'sausage', 'deli meat', 'sushi', 'prawns',
    'avocados', 'bananas', 'strawberries', 'blueberries', 'grapes', 'apples', 'oranges', 'spinach', 'salad mix', 'tomatoes',
    'tvs', 'flat screen tv', 'laptop', 'tablet', 'computer monitor', 'printer', 'headphones', 'smartphone', 'kindle', 'gaming console',
    'patio furniture', 'outdoor furniture', 'shed', 'gazebo', 'grill', 'kayak', 'paddleboard', 'trampoline', 'hot tub', 'generator',
    'mattress', 'pillows', 'comforter', 'bed sheets', 'towels', 'area rug', 'office chair', 'standing desk', 'bookshelf', 'recliner',
    'vacuum', 'air purifier', 'space heater', 'fan', 'humidifier', 'kitchenaid mixer', 'instant pot', 'air fryer', 'coffee maker', 'blender',
    'pots and pans', 'cookware set', 'knife set', 'food storage containers', 'baking sheets', 'cast iron skillet', 'dutch oven', 'crock pot', 'slow cooker', 'pressure cooker',
    'vitamins', 'supplements', 'fish oil', 'multivitamins', 'tylenol', 'ibuprofen', 'allergy medicine', 'sunscreen', 'shampoo', 'body wash',
    'laundry detergent', 'dishwasher pods', 'trash bags', 'ziploc bags', 'aluminum foil', 'plastic wrap', 'tires', 'car battery', 'motor oil', 'optical center'
  ]),

  'YouTube video categories': new Set([
    'gaming', 'vlogs', 'unboxing', 'tutorials', 'mukbang', 'asmr', 'reaction', 'reaction video', 'prank', 'pranks',
    'music video', 'podcast', 'shorts', 'try not to laugh', 'challenge', 'challenges', 'how to', 'diy', 'review', 'product review',
    'tech review', 'lets play', 'walkthrough', 'speedrun', 'montage', 'highlights', 'compilation', 'fails', 'best of', 'top 10',
    'tier list', 'storytime', 'story time', 'q and a', 'qanda', 'get ready with me', 'grwm', 'haul', 'clothing haul', 'makeup tutorial',
    'makeup', 'skincare', 'beauty', 'fashion', 'lookbook', 'ootd', 'cooking', 'recipe', 'baking', 'food review',
    'taste test', 'street food', 'travel', 'travel vlog', 'documentary', 'mini documentary', 'video essay', 'explainer', 'educational', 'science',
    'history', 'math', 'philosophy', 'true crime', 'mystery', 'conspiracy', 'paranormal', 'ghost hunting', 'horror', 'creepypasta',
    'animation', 'animated', 'cartoon', 'short film', 'sketch comedy', 'comedy', 'stand up', 'parody', 'meme', 'memes',
    'commentary', 'drama', 'tea', 'exposed', 'apology video', 'response video', 'debate', 'interview', 'fitness', 'workout',
    'yoga', 'meditation', 'study with me', 'lofi', 'music', 'cover song', 'song cover', 'lyric video', 'live performance', 'concert',
    'remix', 'beat making', 'producer', 'guitar lesson', 'piano tutorial', 'singing', 'dance', 'dance tutorial', 'choreography', 'sports',
    'football highlights', 'basketball highlights', 'soccer', 'nba', 'nfl', 'esports', 'tournament', 'fishing', 'hunting', 'camping',
    'survival', 'bushcraft', 'car review', 'car build', 'restoration', 'woodworking', 'gardening', 'home improvement', 'cleaning', 'organization',
    'asmr eating', 'satisfying', 'oddly satisfying', 'slime', 'kinetic sand', 'soap cutting', 'tech', 'coding', 'programming', 'photography',
    'drawing', 'art tutorial', 'speed art', 'time lapse', 'timelapse', 'pet videos', 'dog videos', 'cat videos', 'animal rescue', 'wildlife',
    'kids content', 'nursery rhymes', 'toy review', 'family vlog', 'day in the life', 'morning routine', 'night routine', 'whats in my bag', 'room tour', 'house tour',
    'car vlog', 'gym vlog', 'college vlog', 'apartment tour', 'minecraft', 'fortnite', 'roblox', 'gta', 'fifa', 'speedpaint'
  ]),

  'Things with a drive-through': new Set([
    'mcdonalds', 'burger king', 'wendys', 'taco bell', 'kfc', 'chick fil a', 'popeyes', 'chipotle', 'arbys', 'sonic',
    'dairy queen', 'jack in the box', 'in n out', 'whataburger', 'raising canes', 'culvers', 'carls jr', 'hardees', 'white castle', 'checkers',
    'del taco', 'wingstop', 'panda express', 'starbucks', 'dunkin', 'dutch bros', 'tim hortons', 'caribou coffee', 'scooters coffee', 'krispy kreme',
    'bank', 'drive through bank', 'atm', 'pharmacy', 'cvs', 'walgreens', 'rite aid', 'duane reade', 'liquor store', 'drive thru liquor',
    'car wash', 'oil change', 'jiffy lube', 'valvoline', 'tire shop', 'fast lube', 'coffee stand', 'espresso stand', 'smoothie place', 'jamba juice',
    'wendys frosty', 'cookout', 'bojangles', 'zaxbys', 'church\'s chicken', 'el pollo loco', 'wienerschnitzel', 'a&w', 'steak n shake', 'krystal',
    'taco john\'s', 'qdoba', 'moes', 'jersey mikes', 'jimmy johns', 'firehouse subs', 'subway', 'jamba', 'smoothie king', 'tropical smoothie',
    'baskin robbins', 'cold stone', 'dairy queen blizzard', 'mcflurry stand', 'shake shack', 'sheetz', 'wawa', 'quiktrip', 'casey\'s', 'buc ees',
    'gas station', 'fuel station', 'convenience store', 'wedding chapel', 'las vegas wedding chapel', 'funeral home', 'covid testing', 'flu shot clinic', 'vaccine clinic', 'blood donation',
    'farmacy', 'urgent care', 'prescription pickup', 'post office', 'package pickup', 'dry cleaner', 'dry cleaning', 'photo booth', 'safari park', 'drive thru safari',
    'wildlife park', 'zoo', 'christmas lights', 'holiday light show', 'haunted house', 'food bank', 'soup kitchen', 'voting', 'ballot drop off', 'library book return',
    'fireworks stand', 'produce stand', 'fruit stand', 'tobacco shop', 'vape shop', 'pet store', 'donut shop', 'bagel shop', 'taco truck', 'food truck',
    'beer cave', 'bottle shop', 'cannabis dispensary', 'dispensary', 'cigarette outlet', 'car repair', 'mechanic', 'smog check', 'inspection station', 'toll booth',
    'parking garage', 'parking lot', 'movie theater', 'drive in theater', 'drive in movie', 'amusement park', 'national park', 'bridge toll', 'border crossing', 'ferry',
    'truck stop', 'rest stop', 'weigh station', 'recycling center', 'dump', 'landfill', 'car dealership', 'auto auction', 'fast food', 'milkshake stand'
  ]),

  'Subscription services': new Set([
    'netflix', 'hulu', 'disney plus', 'spotify', 'amazon prime', 'amazon prime video', 'hbo max', 'max', 'youtube premium', 'audible',
    'xbox game pass', 'game pass', 'playstation plus', 'ps plus', 'nintendo switch online', 'ea play', 'ubisoft plus', 'apple arcade', 'apple music', 'apple tv plus',
    'apple one', 'paramount plus', 'peacock', 'showtime', 'starz', 'amc plus', 'discovery plus', 'espn plus', 'crunchyroll', 'funimation',
    'fubotv', 'sling tv', 'youtube tv', 'directv stream', 'philo', 'pluto tv', 'tubi', 'curiositystream', 'nebula', 'mubi',
    'criterion channel', 'shudder', 'britbox', 'acorn tv', 'hallmark movies now', 'tidal', 'amazon music unlimited', 'pandora plus', 'soundcloud go', 'iheartradio plus',
    'audiomack', 'deezer', 'qobuz', 'siriusxm', 'masterclass', 'skillshare', 'coursera plus', 'udemy', 'linkedin learning', 'duolingo plus',
    'duolingo super', 'babbel', 'rosetta stone', 'blinkist', 'scribd', 'kindle unlimited', 'medium', 'substack', 'patreon', 'onlyfans',
    'twitch turbo', 'discord nitro', 'reddit premium', 'youtube music premium', 'icloud plus', 'icloud', 'google one', 'dropbox plus', 'microsoft 365', 'office 365',
    'adobe creative cloud', 'canva pro', 'grammarly premium', 'notion plus', 'evernote premium', 'lastpass', '1password', 'nordvpn', 'expressvpn', 'surfshark',
    'dashlane', 'norton', 'mcafee', 'malwarebytes', 'chatgpt plus', 'claude pro', 'midjourney', 'github copilot', 'perplexity pro', 'amazon prime gaming',
    'hellofresh', 'blue apron', 'home chef', 'factor', 'freshly', 'daily harvest', 'dollar shave club', 'harry\'s', 'birchbox', 'ipsy',
    'fabfitfun', 'bark box', 'barkbox', 'chewy autoship', 'stitch fix', 'rent the runway', 'nuuly', 'thredup', 'trunk club', 'fashion nova',
    'peloton', 'peloton app', 'apple fitness plus', 'strava', 'whoop', 'noom', 'weight watchers', 'myfitnesspal premium', 'calm', 'headspace',
    'better help', 'betterhelp', 'talkspace', 'ritual', 'care of', 'hims', 'hers', 'roman', 'nurx', 'goodrx gold',
    'aaa', 'costco membership', 'sams club', 'bjs', 'amazon prime student', 'walmart plus', 'instacart plus', 'doordash dashpass', 'uber one', 'grubhub plus',
    'lyft pink', 'gym membership', 'planet fitness', 'la fitness', 'equinox', 'orangetheory', 'classpass', 'new york times', 'wall street journal', 'washington post',
    'the athletic', 'bloomberg', 'the economist', 'spotify premium', 'audible plus', 'paramount plus showtime', 'crunchyroll premium', 'vrv', 'hidive', 'gaia'
  ]),

  'Things that come in a vending machine': new Set([
    'coke', 'coca cola', 'pepsi', 'diet coke', 'diet pepsi', 'coke zero', 'sprite', 'mountain dew', 'dr pepper', 'fanta',
    'water', 'bottled water', 'dasani', 'aquafina', 'smartwater', 'sparkling water', 'gatorade', 'powerade', 'vitamin water', 'red bull',
    'monster', 'monster energy', 'rockstar', 'bang', 'celsius', 'arizona iced tea', 'iced tea', 'snapple', 'lemonade', 'minute maid',
    'apple juice', 'orange juice', 'capri sun', 'juice box', 'chocolate milk', 'coffee', 'hot coffee', 'iced coffee', 'hot chocolate', 'tea',
    'chips', 'doritos', 'cheetos', 'lays', 'ruffles', 'fritos', 'pringles', 'sun chips', 'tostitos', 'funyuns',
    'cheez its', 'goldfish', 'pretzels', 'popcorn', 'combos', 'bugles', 'takis', 'hot fries', 'andy capp hot fries', 'chex mix',
    'snickers', 'twix', 'kit kat', 'kitkat', 'reeses', 'reeses peanut butter cups', 'm and ms', 'milky way', 'three musketeers', 'butterfinger',
    'baby ruth', 'hundred grand', '100 grand', 'crunch', 'nestle crunch', 'hersheys', 'hershey bar', 'almond joy', 'mounds', 'payday',
    'skittles', 'starburst', 'sour patch kids', 'swedish fish', 'airheads', 'nerds', 'gushers', 'fruit snacks', 'gummy bears', 'sour worms',
    'gum', 'trident', 'orbit', 'extra', '5 gum', 'juicy fruit', 'bubblicious', 'mentos', 'tic tacs', 'lifesavers',
    'oreos', 'chips ahoy', 'famous amos', 'grandmas cookies', 'pop tarts', 'nutri grain', 'rice krispies treats', 'nutter butter', 'fig newtons', 'animal crackers',
    'granola bar', 'nature valley', 'clif bar', 'kind bar', 'protein bar', 'cheese crackers', 'peanut butter crackers', 'lance crackers', 'ritz crackers', 'saltines',
    'beef jerky', 'slim jim', 'trail mix', 'mixed nuts', 'peanuts', 'cashews', 'sunflower seeds', 'pistachios', 'almonds', 'raisins',
    'ramen', 'cup noodles', 'instant noodles', 'microwave popcorn', 'pop chips', 'veggie straws', 'rice cakes', 'crackers', 'wheat thins', 'triscuits',
    'ice cream', 'ice cream sandwich', 'drumstick', 'klondike bar', 'popsicle', 'fudge bar', 'frozen burrito', 'hot pocket', 'sandwich', 'fresh sandwich',
    'condoms', 'umbrella', 'phone charger', 'earbuds', 'aspirin', 'tylenol', 'advil', 'band aids', 'hand sanitizer', 'face mask',
    'toothbrush', 'deodorant', 'tampons', 'pads', 'pregnancy test', 'lottery ticket', 'stamps', 'cigarettes', 'lighter', 'phone case'
  ])
};
