module.exports = {
  'Valid excuses for being late': new Set([
    'traffic', 'heavy traffic', 'traffic jam', 'accident on the highway', 'road closure', 'detour',
    'alarm didnt go off', 'alarm didn\'t go off', 'i overslept', 'overslept', 'slept through my alarm',
    'flat tire', 'tire blew out', 'car wouldnt start', 'car broke down', 'dead battery', 'out of gas',
    'ran out of gas', 'train was delayed', 'missed the train', 'bus was late', 'missed the bus', 'subway delay',
    'couldnt find parking', 'no parking spots', 'parking was full', 'got lost', 'gps took me the wrong way',
    'wrong directions', 'family emergency', 'medical emergency', 'dog ate my keys', 'lost my keys',
    'couldnt find my keys', 'locked myself out', 'locked out of the house', 'kid was sick', 'child got sick',
    'babysitter cancelled', 'school called', 'daycare drop off took forever', 'spilled coffee on my shirt',
    'had to change clothes', 'couldnt find my shoes', 'couldnt find my phone', 'phone died', 'no signal',
    'power went out', 'blackout', 'internet was down', 'elevator was broken', 'stuck in the elevator',
    'long line at the coffee shop', 'line at starbucks', 'dentist appointment ran late', 'doctor appointment',
    'vet appointment', 'sick pet', 'pet emergency', 'dog ran away', 'cat got out', 'had to walk the dog',
    'it was raining', 'snow', 'snowstorm', 'ice on the roads', 'bad weather', 'fog', 'flooding', 'tornado warning',
    'hurricane', 'road was icy', 'had to shovel snow', 'car got towed', 'forgot my badge', 'forgot my wallet',
    'went back for my laptop', 'forgot something at home', 'construction', 'road work', 'bridge was up',
    'drawbridge', 'train crossing', 'stuck behind a school bus', 'school bus stopped every block',
    'slow driver in front of me', 'someone cut me off', 'fender bender', 'got pulled over', 'speeding ticket',
    'cop stopped me', 'protest blocked the road', 'parade', 'marathon closed the streets', 'street was blocked',
    'car alarm wouldnt stop', 'neighbor blocked my driveway', 'couldnt get out of my driveway',
    'garage door wouldnt open', 'forgot it was a meeting', 'meeting wasnt on my calendar', 'time change',
    'daylight savings', 'forgot to set my clock', 'wrong time zone', 'meeting got moved',
    'thought it started later', 'my watch was slow', 'my clock was wrong', 'my phone clock was off',
    'i was on a call', 'got stuck on a phone call', 'urgent email', 'boss called me', 'last minute task',
    'printer jammed', 'computer crashed', 'laptop wouldnt turn on', 'had to reboot', 'update was installing',
    'system update', 'wifi went down', 'vpn issues', 'couldnt log in', 'forgot my password', 'kid missed the bus',
    'had to drive my kid', 'carpool fell through', 'uber never came', 'lyft cancelled', 'taxi was late',
    'rideshare took forever', 'surge pricing', 'couldnt find an uber', 'my ride bailed', 'had a flat on my bike',
    'bike chain broke', 'tire on my bike popped', 'scooter ran out of battery', 'sidewalk was closed',
    'got a nosebleed', 'felt dizzy', 'low blood sugar', 'migraine', 'headache', 'stomach bug',
    'threw up this morning', 'food poisoning', 'allergic reaction', 'sneezing fit', 'i was helping a stranger',
    'stopped to help someone', 'helped a lost tourist', 'rescued a cat from a tree',
    'pulled over for an ambulance', 'let a fire truck pass', 'funeral procession', 'wide load on the highway',
    'truck spilled cargo', 'oil spill on the road', 'deer crossed the road', 'goose crossing', 'ducks in the road',
    'cows on the road', 'tractor in front of me', 'farm equipment', 'horse on the road', 'runaway shopping cart',
    'mercury was in retrograde', 'the planets were against me', 'my horoscope warned me', 'bad omen',
    'i tried my best', 'i actually left early', 'i was already here yesterday', 'technically not late',
    'depends on whose clock', 'it was a soft start', 'i was early for the next one', 'jet lag', 'red eye flight',
    'flight got delayed', 'flight cancelled', 'airport security', 'tsa line was long', 'lost my boarding pass',
    'gate changed', 'plane sat on the tarmac', 'baggage claim took forever'
  ]),
  "Things you shouldn't microwave": new Set([
    'metal', 'fork', 'a fork', 'spoon', 'knife', 'aluminum foil', 'tin foil', 'foil', 'egg', 'eggs',
    'hard boiled egg', 'whole egg', 'raw egg', 'grapes', 'a grape', 'cd', 'dvd', 'phone', 'smartphone', 'laptop',
    'cell phone', 'battery', 'batteries', 'aaa battery', 'fish', 'styrofoam', 'styrofoam cup', 'plastic',
    'plastic container', 'plastic bag', 'plastic wrap', 'saran wrap', 'cling film', 'water', 'plain water',
    'hot water', 'a cup of water', 'ramen cup', 'cup of noodles', 'styrofoam noodles', 'to go container',
    'takeout container', 'chinese takeout box', 'paper bag', 'brown paper bag', 'newspaper', 'cardboard',
    'pizza box', 'coffee cup', 'paper cup', 'wax paper', 'parchment paper', 'butter wrapper', 'candle', 'wax',
    'crayons', 'soap', 'a bar of soap', 'toothpaste', 'light bulb', 'lightbulb', 'christmas lights', 'led lights',
    'wire', 'wires', 'steel wool', 'scrubber', 'a spoon', 'silverware', 'cutlery', 'metal bowl', 'steel bowl',
    'copper', 'copper pot', 'silver', 'gold ring', 'jewelry', 'ring', 'watch', 'airpods', 'earbuds', 'headphones',
    'remote', 'tv remote', 'keys', 'car keys', 'coins', 'a penny', 'pennies', 'quarters', 'nails', 'screws',
    'bolts', 'paperclips', 'staples', 'thumbtack', 'a balloon', 'balloon', 'helium balloon', 'firework',
    'sparkler', 'match', 'matches', 'lighter', 'aerosol can', 'spray paint', 'hairspray', 'deodorant can',
    'bug spray', 'paint can', 'gasoline', 'gas', 'lighter fluid', 'alcohol', 'rubbing alcohol', 'nail polish',
    'nail polish remover', 'acetone', 'bleach', 'cleaning spray', 'mercury thermometer', 'thermometer',
    'glass thermometer', 'closed jar', 'sealed jar', 'sealed can', 'a can', 'canned food', 'soup can', 'tin can',
    'soda can', 'soda', 'beer can', 'glass bottle', 'wine bottle', 'sealed container', 'airtight container',
    'vacuum sealed bag', 'sealed bag', 'marshmallow', 'peeps', 'a peep', 'hot dog', 'sausage', 'whole potato',
    'potato with no holes', 'frozen meat', 'frozen turkey', 'whole turkey', 'chili pepper', 'hot peppers',
    'dried chili', 'garlic', 'whole garlic', 'chestnuts', 'whole chestnut', 'popcorn for too long', 'grease',
    'oil', 'boiling oil', 'butter for too long', 'leftover oil', 'animal', 'pet', 'hamster', 'goldfish', 'a cat',
    'a dog', 'your hand', 'fingers', 'your face', 'a person', 'live wire', 'christmas ornament', 'tinsel',
    'metallic balloon', 'mylar balloon', 'sparkly mug', 'mug with gold trim', 'plate with metal trim',
    'metallic paint dish', 'disco ball', 'a magnet', 'magnets', 'speaker', 'small speaker', 'calculator',
    'game boy', 'nintendo switch', 'controller', 'usb drive', 'flash drive', 'hard drive', 'sd card',
    'memory card', 'sim card', 'credit card', 'gift card', 'a hotel key card', 'key card', 'rfid card', 'passport',
    'id card', 'dry sponge', 'empty container', 'nothing', 'running it empty', 'an empty microwave',
    'soup with the lid on', 'canned soup unopened'
  ]),
  'Worst superpowers': new Set([
    'invisibility when no one is looking', 'flight one inch off the ground', 'super speed but only backwards',
    'talking to ants', 'turning water into slightly warmer water', 'breathing underwater but only in the bathtub',
    'invincibility for one second a day', 'reading minds of houseplants', 'x-ray vision but only your own hand',
    'super strength but only your left pinky', 'teleporting one foot to the left', 'flying but only while asleep',
    'controlling the weather but only indoors', 'immortality but you age normally',
    'seeing two seconds into the past', 'predicting yesterday', 'talking to dead bugs', 'summoning a single sock',
    'turning invisible only your clothes', 'super hearing but everyone whispers', 'smelling colors',
    'tasting sounds', 'running fast but only in dreams', 'lifting anything under one pound',
    'shooting lukewarm water from your hands', 'glowing slightly in the dark', 'making milk go bad instantly',
    'always finding pennies', 'turning lights off from across the room', 'making it slightly windy',
    'communicating with toast', 'telekinesis on objects you can already reach',
    'super speed but you get tired immediately', 'flight but you cant land', 'time travel to five minutes ago',
    'time travel but only forward at normal speed', 'reading minds but only your own',
    'healing others but it hurts you', 'breathing fire but only when you sneeze', 'ice powers but only ice cubes',
    'super stretch but only one arm', 'shapeshifting into yourself', 'duplicating yourself but the clone is rude',
    'duplicating expired food', 'turning gold into lead', 'turning diamonds into glass', 'controlling pigeons',
    'being a pigeon magnet', 'making people slightly uncomfortable', 'always knowing the wrong answer',
    'perfect memory of boring things', 'never needing sleep but always tired',
    'never getting hungry but always craving', 'super taste for spoiled food',
    'invulnerability to paper cuts only', 'immunity to the common cold once a decade',
    'regenerating only hangnails', 'walking through walls but only ones youve already opened',
    'phasing through closed doors only when unlocked', 'levitating objects you dont want to',
    'controlling traffic lights to red', 'making elevators stop on every floor', 'turning green lights yellow',
    'summoning rain on your wedding day', 'attracting mosquitos', 'repelling only friendly dogs',
    'talking to fish who ignore you', 'understanding cats who insult you', 'super smell for other peoples lunches',
    'seeing the future of commercials', 'knowing when nothing happens', 'teleporting your keys somewhere else',
    'aging milk faster', 'making batteries die', 'draining your own phone', 'turning hot food cold',
    'melting ice cream instantly', 'making bread stale', 'wilting flowers', 'turning wine into grape juice',
    'sobering people up against their will', 'turning coffee into decaf', 'making coffee lukewarm',
    'super speed reading but no comprehension', 'perfect aim for missing', 'invisibility only your shadow',
    'flight only downward', 'super jump but no landing skill', 'bouncing forever',
    'becoming intangible at the worst times', 'growing only your fingernails fast',
    'controlling your own hair growth', 'making your hair grow into your eyes', 'summoning a mild breeze',
    'conjuring a lukewarm cup of tea', 'turning into a slightly larger version of you',
    'shrinking only your left foot', 'enlarging your nose at will', 'breathing in space but you still need a suit',
    'surviving falls under two feet', 'catching things that arent thrown',
    'super reflexes for things that already happened', 'dodging compliments', 'deflecting good news',
    'teleporting but you arrive five minutes later', 'time freeze but you also freeze',
    'stopping time for one ant', 'reading the last page of every book', 'spoiling movies for yourself',
    'knowing the ending of reruns', 'invisible but you smell stronger', 'silent footsteps but loud breathing',
    'super stealth but you glow', 'controlling minds of sleeping people', 'hypnotizing only yourself',
    'persuading no one', 'always being slightly itchy', 'feeling other peoples paper cuts',
    'tasting what your enemies eat', 'smelling the future weather wrong', 'never blinking', 'crying on command',
    'sneezing glitter', 'burping bubbles', 'hiccuping in morse code', 'producing static electricity',
    'attracting lint', 'magnetizing only spoons', 'summoning expired coupons',
    'finding parking spots after you park', 'knowing trivia no one asked', 'remembering passwords you dont use',
    'super flexibility in your earlobes', 'growing a tail that does nothing', 'sprouting wings that dont work',
    'controlling the volume of distant tvs', 'muting only your own voice', 'echolocation but only in silence',
    'glow in the dark teeth', 'luminescent armpits', 'turning invisible when youre alone in a room',
    'flight only when no one believes you', 'strength only to open already-open jars',
    'breaking only opened seals', 'super speed but you cant stop', 'flying but only in circles',
    'reading minds but only when they think about you', 'invisibility but your reflection stays',
    'turning into mist when you sneeze', 'controlling water but only in puddles', 'super strength only underwater',
    'telepathy with mosquitoes', 'seeing through paper only', 'x-ray vision of walls only',
    'shooting confetti from your fingers', 'breathing underwater but you cant swim',
    'flight but you weigh twice as much', 'super speed but only your arms', 'invincible only on tuesdays',
    'immortal but only while standing', 'healing only paper cuts', 'turning small things smaller',
    'enlarging only crumbs', 'duplicating only your bad ideas', 'cloning your worst habits',
    'mind control over goldfish', 'hypnotizing rocks', 'talking to furniture that ignores you',
    'summoning a spoon you already have', 'teleporting only your hat', 'super jump but only when scared',
    'phasing through curtains', 'levitating only when embarrassed', 'turning lights slightly dimmer',
    'making faint static noise', 'generating warm air', 'breathing cold air at people', 'shooting lukewarm coffee',
    'super taste but only for water', 'smelling rain after it stops', 'hearing whispers from far away walls',
    'glowing only your nostrils', 'invisible only your eyebrows', 'flight but you cant steer',
    'super speed but you arrive sweaty', 'predicting the obvious', 'knowing what already happened',
    'remembering tomorrows breakfast wrong', 'aging cheese faster', 'ripening only rotten fruit',
    'freezing only ice cubes further', 'melting only melted things', 'setting fire only to ashes'
  ]),
  'Things that are technically legal but feel illegal': new Set([
    'jaywalking on an empty street', 'taking the hotel pen', 'taking hotel toiletries',
    'keeping the hotel slippers', 'using a fake name at starbucks', 'eating grapes at the grocery store',
    'sampling at the bulk bin', 'returning something youve worn once', 'sneaking snacks into a movie',
    'bringing your own candy to the theater', 'leaving a party without saying bye', 'ghosting a group chat',
    'muting your family group', 'reply all by accident', 'parking in a 15 minute spot for 16 minutes',
    'idling in a loading zone', 'double dipping your own chip', 'eating in the produce aisle',
    'reading a magazine you wont buy', 'sitting in a cafe without buying anything',
    'using the bathroom without buying anything', 'asking for extra sauce', 'taking extra napkins',
    'grabbing a handful of mints', 'taking the free samples twice', 'going back for seconds at a buffet',
    'filling your plate too high at a buffet', 'taking leftovers from a meeting', 'eating the office snacks',
    'taking the last donut', 'finishing the office coffee', 'using someones netflix', 'sharing a password',
    'splitting one subscription five ways', 'using guest wifi forever', 'connecting to your neighbors wifi',
    'screenshotting a paywalled article', 'reading over someones shoulder', 'watching tv at the store',
    'testing the massage chair for an hour', 'trying on clothes you wont buy', 'spraying the perfume samples',
    'using lotion testers', 'squeezing the bread', 'poking the avocados', 'opening a product to look inside',
    'reading the whole book in the store', 'using the library to nap', 'charging your phone at the airport outlet',
    'sitting in first class boarding line', 'boarding early without a reason', 'taking an extra ketchup',
    'grabbing a handful of sugar packets', 'pocketing sweetener packets', 'taking the bread basket home',
    'keeping the restaurant crayons', 'keeping the kids menu', 'taking the to-go cup', 'refilling your soda twice',
    'sneaking a refill', 'asking for water then ordering nothing', 'sitting in a reserved seat that was empty',
    'taking a shopping cart to your car', 'using the express lane with 11 items',
    'self checkout with one extra item', 'weighing yourself at the store scale',
    'testing the bed at the furniture store', 'napping at ikea', 'eating the meatballs without shopping',
    'following the ikea exit shortcut', 'taking the shortcut through a store', 'cutting through a parking lot',
    'u-turn on an empty road', 'rolling stop at 3am', 'driving the speed limit in the fast lane',
    'merging at the last second', 'taking two parking spots', 'parking far from everyone',
    'tailgating someone slowly', 'honking once politely', 'flashing your lights',
    'using your phone at a red light', 'eating while driving', 'taking the scenic detour on the clock',
    'working from a coffee shop', 'clocking out two minutes early', 'taking a long bathroom break',
    'leaving early on a friday', 'calling in well', 'using all your sick days', 'taking a mental health day',
    'replying to an email tomorrow', 'reading a slack message and not responding', 'leaving someone on read',
    'using your work laptop for personal stuff', 'printing personal documents at work', 'taking office pens home',
    'borrowing the stapler forever', 'keeping a found pen', 'returning a library book late', 'recording a tv show',
    'skipping the ads', 'using an ad blocker', 'muting commercials', 'fast forwarding the intro',
    'watching the trailer instead of paying', 'window shopping for hours', 'trying every sample at costco',
    'doing the costco sample loop twice', 'grabbing extra straws', 'taking a stack of free postcards',
    'using the free condiment bar', 'taking extra sugar for home', 'keeping the airplane blanket',
    'keeping the airline headphones', 'taking the airplane snacks', 'asking for the whole can on the plane',
    'reclining your seat all the way', 'using both armrests', 'putting your bag in someone elses overhead bin',
    'boarding with an oversized carry-on', 'sneaking through the open gate', 'using the exit as an entrance',
    'going up the down escalator', 'pressing all the elevator buttons by accident', 'holding the elevator',
    'taking the stairs to skip small talk', 'leaving a one star review honestly',
    'rating something five stars for the coupon', 'using a coupon that almost expired',
    'price matching aggressively', 'asking for the senior discount early', 'using your friends loyalty number',
    'stacking coupons', 'returning the empty bottle for deposit', 'keeping the change from a vending machine',
    'taking the extra item the machine dropped', 'getting two snacks from one push', 'finding money in a coat',
    'keeping found change', 'picking up a penny', 'taking the free newspaper', 'grabbing extra free stickers',
    'eating cereal for dinner', 'having dessert first', 'breakfast at midnight', 'wearing pajamas to the store',
    'going to bed at 8pm', 'taking a nap at noon', 'skipping a line you were already near',
    'asking for a free upgrade', 'mentioning its your birthday for free dessert', 'saying its your anniversary',
    'wearing the same outfit twice', 'rewearing jeans for a week', 'eating the last slice',
    'licking the spoon before its washed', 'double tapping the snooze'
  ]),
  'Reasons to call in sick': new Set([
    'fever', 'high fever', 'i have a fever', 'cold', 'common cold', 'flu', 'the flu', 'stomach bug',
    'stomach ache', 'food poisoning', 'i threw up', 'vomiting', 'nausea', 'feeling nauseous', 'headache',
    'migraine', 'bad headache', 'sore throat', 'strep throat', 'cough', 'bad cough', 'runny nose', 'congestion',
    'sinus infection', 'sinus headache', 'allergies', 'allergy attack', 'pink eye', 'ear infection', 'toothache',
    'dental emergency', 'root canal', 'wisdom teeth', 'i sprained my ankle', 'twisted my ankle',
    'threw out my back', 'back pain', 'my back hurts', 'pulled a muscle', 'neck pain', 'stiff neck', 'slept wrong',
    'pinched nerve', 'knee pain', 'my knee gave out', 'dizziness', 'vertigo', 'lightheaded', 'fainted',
    'low blood pressure', 'high blood pressure', 'chest pain', 'heart palpitations', 'anxiety', 'panic attack',
    'mental health day', 'burnout', 'exhausted', 'no energy', 'didnt sleep', 'insomnia', 'i was up all night',
    'i feel terrible', 'i feel awful', 'under the weather', 'coming down with something',
    'i think im getting sick', 'contagious', 'i dont want to infect everyone', 'doctor said to stay home',
    'doctors appointment', 'urgent care', 'went to the er', 'emergency room', 'specialist appointment',
    'physical therapy', 'blood test', 'lab work', 'getting a scan', 'mri appointment', 'covid', 'tested positive',
    'covid exposure', 'quarantine', 'close contact', 'isolating', 'fever and chills', 'chills', 'body aches',
    'muscle aches', 'everything hurts', 'my whole body hurts', 'joint pain', 'arthritis flare up', 'flare up',
    'chronic pain', 'my condition acted up', 'i need to rest', 'bed rest', 'cant get out of bed',
    'cant stop coughing', 'cant stop sneezing', 'laryngitis', 'lost my voice', 'i cant talk', 'my voice is gone',
    'rash', 'allergic reaction', 'hives', 'swollen face', 'swelling', 'infection', 'i have an infection',
    'cut my hand', 'i got stitches', 'i burned myself', 'i fell', 'i slipped', 'i tripped', 'injured myself',
    'sprained wrist', 'broke my toe', 'stubbed my toe badly', 'dropped something on my foot', 'pulled a hamstring',
    'cramps', 'severe cramps', 'period pain', 'menstrual cramps', 'kidney stone', 'passing a kidney stone',
    'appendix', 'suspected appendicitis', 'gallbladder', 'indigestion', 'acid reflux', 'heartburn', 'bloating',
    'stomach cramps', 'diarrhea', 'dehydrated', 'heat exhaustion', 'heat stroke', 'sunstroke', 'sunburn',
    'frostbite', 'cold sores', 'fever blister', 'swollen glands', 'swollen lymph nodes', 'my eyes are swollen',
    'eye infection', 'stye', 'scratched my cornea', 'cant see straight', 'blurry vision', 'double vision',
    'concussion', 'bumped my head', 'i hit my head', 'dizzy spells', 'blacked out', 'passed out earlier',
    'reaction to medication', 'side effects', 'new medication', 'adjusting to meds', 'allergic to my meds',
    'my kid is sick', 'child is sick', 'taking care of a sick family member', 'family member in the hospital',
    'no childcare', 'daycare closed', 'school closed', 'snowed in', 'car wont start', 'no way to get there',
    'i caught a chill', 'feverish', 'clammy', 'sweating', 'night sweats', 'i feel feverish', 'i feel drained',
    'mentally drained', 'need a recovery day', 'emotional day', 'grieving', 'bereavement', 'lost a pet',
    'pet emergency', 'dog is sick', 'had a bad reaction to dinner', 'something i ate', 'bad sushi', 'bad oysters',
    'bad shellfish', 'gluten reaction', 'dairy reaction', 'lactose issues', 'nut allergy reaction', 'bee sting',
    'allergic to bee stings', 'tick bite', 'poison ivy', 'spider bite', 'infected cut', 'ingrown nail',
    'plantar wart'
  ]),
  'Things you pretend to understand': new Set([
    'taxes', 'how taxes work', 'tax brackets', 'filing taxes', 'the stock market', 'stocks', 'crypto',
    'cryptocurrency', 'bitcoin', 'blockchain', 'nfts', 'the economy', 'inflation', 'interest rates',
    'the federal reserve', 'bonds', '401k', 'retirement plans', 'roth ira', 'mortgages', 'escrow', 'apr',
    'credit scores', 'how credit works', 'wine', 'wine tasting', 'wine pairings', 'tannins',
    'the difference between merlot and cabernet', 'whiskey notes', 'craft beer', 'ipa hops', 'cheese pairings',
    'art', 'modern art', 'abstract art', 'this painting', 'contemporary art', 'poetry', 'jazz', 'jazz music',
    'classical music', 'opera', 'ballet', 'the plot of inception', 'the ending of tenet', 'time travel movies',
    'quantum physics', 'quantum mechanics', 'quantum entanglement', 'relativity', 'black holes', 'the big bang',
    'string theory', 'dark matter', 'astrophysics', 'how planes fly', 'how wifi works', 'how the cloud works',
    'how the internet works', 'how a computer works', 'how electricity works', 'how magnets work',
    'how vaccines work', 'how the brain works', 'how my own body works', 'how my car works',
    'what a catalytic converter does', 'transmissions', 'how an engine works', 'what oil does in a car',
    'horsepower vs torque', 'car specs', 'the metric system', 'celsius', 'converting units', 'algebra', 'calculus',
    'statistics', 'probability', 'standard deviation', 'p-values', 'the scientific method', 'machine learning',
    'artificial intelligence', 'how ai works', 'neural networks', 'large language models', 'algorithms', 'coding',
    'git', 'the terminal', 'regular expressions', 'apis', 'databases', 'cybersecurity', 'encryption', 'vpns',
    'dns', 'the metaverse', 'web3', 'smart contracts', 'gas fees', 'staking', 'mining crypto', 'the news',
    'geopolitics', 'foreign policy', 'trade deals', 'tariffs', 'supply and demand', 'gdp', 'the gold standard',
    'hedge funds', 'venture capital', 'private equity', 'startup valuations', 'equity', 'stock options', 'vesting',
    'dividends', 'etfs', 'index funds', 'compound interest', 'amortization', 'escrow accounts', 'health insurance',
    'deductibles', 'copays', 'premiums', 'hsa', 'fsa', 'medicare', 'my insurance plan', 'the fine print',
    'terms and conditions', 'privacy policies', 'the lease agreement', 'legal contracts', 'my own contract',
    'jargon', 'corporate buzzwords', 'synergy', 'agile', 'scrum', 'sprints', 'kanban', 'okrs', 'kpis', 'roi',
    'b2b vs b2c', 'the org chart', 'what my coworker does', 'what marketing actually does', 'what consultants do',
    'my job description', 'the meeting we just had', 'what the ceo said', 'the strategy', 'the roadmap',
    'the deck', 'that powerpoint', 'the spreadsheet', 'pivot tables', 'vlookup', 'excel formulas', 'macros',
    'the budget', 'the projections', 'philosophy', 'existentialism', 'nihilism', 'stoicism', 'kant', 'nietzsche',
    'plato', 'the trolley problem', 'the meaning of that book', 'the symbolism', 'the metaphor',
    'iambic pentameter', 'grammar rules', 'when to use a semicolon', 'whom vs who', 'affect vs effect',
    'the subjunctive', 'a foreign language i claimed to speak', 'football rules', 'cricket rules', 'rugby rules',
    'the offside rule', 'the infield fly rule', 'golf scoring', 'tennis scoring', 'chess strategy',
    'the rules of mahjong', 'baccarat', 'craps', 'poker odds', 'the standings', 'fantasy football',
    'how the playoffs work', 'the electoral college', 'how bills become laws', 'parliamentary procedure',
    'robert\'s rules', 'the supreme court', 'jurisdiction', 'due process', 'tort law', 'intellectual property',
    'copyright vs trademark', 'time zones', 'daylight savings', 'leap years', 'the gregorian calendar',
    'astrology charts', 'my star sign', 'mercury retrograde', 'the enneagram', 'myers briggs', 'love languages',
    'what gluten is', 'what an antioxidant is', 'probiotics', 'keto', 'intermittent fasting', 'calories',
    'what cholesterol is', 'blood pressure numbers', 'the recipe instructions', 'the assembly instructions',
    'ikea directions', 'the wiring diagram', 'the user manual'
  ]),
  'Things you google at 3am': new Set([
    'is cereal soup', 'how long can you go without sleep', 'symptoms', 'is my headache a tumor',
    'how do magnets work', 'celebrity net worth', 'do fish drink water', 'why cant i sleep',
    'how to fall asleep fast', 'what time is it in japan', 'is a hotdog a sandwich', 'is water wet',
    'how many people are awake right now', 'am i the only one awake', 'what is the meaning of life',
    'why are we here', 'how big is the universe', 'what is on the other side of a black hole',
    'can you die in your sleep', 'how long do humans live', 'how old is the oldest person alive',
    'signs of a stroke', 'signs of a heart attack', 'is this a normal mole', 'why is my heart beating fast',
    'am i dying', 'do i have insomnia', 'how to fix my sleep schedule', 'why do cats purr', 'do dogs dream',
    'can plants feel pain', 'are spiders watching me', 'how many spiders do you eat in your sleep',
    'what was that noise', 'is my house haunted', 'do ghosts exist', 'are aliens real',
    'what would happen if the earth stopped spinning', 'how far is the moon', 'can you breathe in space',
    'is pluto a planet', 'why is the sky blue', 'why is the ocean salty', 'how deep is the ocean',
    'whats at the bottom of the ocean', 'what lives in the mariana trench', 'can sharks smell fear',
    'do animals have feelings', 'what do dogs think about', 'why do we yawn', 'why is yawning contagious',
    'why do we dream', 'what do dreams mean', 'what does it mean when you dream about teeth',
    'why did i dream that', 'can you control your dreams', 'how to lucid dream', 'is deja vu real',
    'what causes deja vu', 'how to whistle', 'how to wink', 'am i an introvert', 'whats my personality type',
    'why am i like this', 'do i have adhd', 'why do i procrastinate', 'how to be productive',
    'how to wake up early', 'best alarm to wake up', 'how much sleep do i need', 'how to stop overthinking',
    'why do i overthink everything', 'is everyone judging me', 'do people like me',
    'how to make friends as an adult', 'why is being an adult so hard', 'how to do taxes', 'am i behind in life',
    'what should i do with my life', 'how to get rich', 'easiest way to make money', 'can you make money online',
    'how much do youtubers make', 'how much does an astronaut make', 'net worth of random celebrity',
    'is this celebrity married', 'how old is this actor', 'is this actor still alive', 'who voiced that cartoon',
    'where have i seen that actor', 'what movie is this from', 'that song that goes like', 'lyrics to that song',
    'who sings this', 'what year did that come out', 'how to cook an egg', 'can you eat raw cookie dough',
    'is this chicken cooked', 'how long is leftover pizza good for', 'is it ok to eat expired',
    'how long can milk sit out', 'can you eat mold', 'what happens if you eat a tide pod',
    'how many calories in air', 'do calories count at night', 'is breakfast the most important meal',
    'is coffee bad for you', 'how much caffeine is too much', 'can you overdose on water',
    'how long can you hold your breath', 'how to whistle with fingers', 'why do i hear ringing',
    'whats that ringing in my ears', 'is tinnitus permanent', 'why is my eye twitching', 'why do my legs hurt',
    'growing pains', 'random sharp pain', 'what is this rash', 'is this contagious', 'how contagious am i',
    'how long until i feel better', 'home remedies for a cold', 'does chicken soup actually help',
    'natural sleep remedies', 'does melatonin work', 'is it bad to nap', 'how to power nap',
    'best position to sleep', 'why do i wake up at 3am', 'spiritual meaning of waking up at 3am',
    'what does it mean to wake up at the same time', 'why is 3am scary', 'is the devils hour real',
    'history of the witching hour', 'why do clocks have roman numerals', 'who invented time', 'how do clocks work',
    'what is time anyway', 'is time travel possible', 'how fast does light travel', 'speed of sound',
    'can you outrun a bear', 'what to do if you see a bear', 'how to survive a shark attack',
    'can you survive a fall into water', 'how to escape a sinking car', 'how to survive quicksand',
    'is quicksand real', 'how to escape a zombie', 'zombie survival plan', 'who would win in a fight',
    'strongest animal in the world', 'can a gorilla beat a bear', 'fastest animal on earth',
    'how do birds know where to fly', 'where do birds go at night', 'do bugs sleep', 'how long do flies live',
    'why are there so many flies', 'how to get rid of a fly', 'what attracts mosquitoes',
    'why do mosquitoes bite me more', 'do trees talk to each other', 'how old is the oldest tree',
    'what was the first word', 'who invented language', 'what came first the chicken or the egg',
    'why do we have eyebrows', 'what is the appendix for', 'why do we have toes', 'can you live without a spleen',
    'how many bones are in the body', 'random body fact', 'why do we hiccup', 'how to cure hiccups',
    'why do we sneeze', 'can you sneeze with your eyes open', 'what happens if you hold in a sneeze',
    'why do we cry'
  ]),
  'Lies on a dating profile': new Set([
    'i love hiking', '6 foot tall', 'fluent in spanish', 'i love to travel', 'social drinker',
    'gym 5 times a week', 'my dog loves everyone', 'i love long walks on the beach',
    'i love trying new restaurants', 'i love cooking', 'i can cook', 'foodie', 'wine connoisseur', 'adventurous',
    'spontaneous', 'laid back', 'easy going', 'low maintenance', 'drama free', 'no games',
    'i love hiking on weekends', 'active lifestyle', 'i go to the gym', 'fitness enthusiast', 'i run marathons',
    'i do yoga', 'i love camping', 'outdoorsy', 'i love the outdoors', 'i love nature', 'i love reading',
    'avid reader', 'i read a lot', 'intellectual', 'well read', 'i love deep conversations', 'great listener',
    'emotionally available', 'i have my life together', 'financially stable', 'entrepreneur',
    'i own my own business', 'ceo', 'self made', 'my own boss', 'works in tech', 'i love my job',
    'passionate about my career', 'just here to make friends', 'not looking for anything serious',
    'looking for something real', 'ready to settle down', 'i have a great sense of humor', 'funny', 'class clown',
    'i love to laugh', 'i dont take myself too seriously', 'recent photo', 'this is a recent photo', '5 foot 11',
    'almost 6 feet', 'tall', 'athletic build', 'fit', 'in shape', 'i love kids', 'great with kids',
    'family oriented', 'close with my family', 'i call my mom every day', 'i love animals', 'dog person',
    'cat person', 'i have a dog', 'my dog is my best friend', 'pet parent', 'i love music', 'i play guitar',
    'i sing', 'musician', 'i dj on the side', 'i love live music', 'i go to concerts', 'i love festivals',
    'world traveler', 'ive been everywhere', 'i love exploring', 'i love new cultures', 'i speak three languages',
    'bilingual', 'i love art', 'i love museums', 'cultured', 'i love wine and cheese', 'sommelier',
    'i make my own pasta', 'i meal prep', 'i eat clean', 'i love salads', 'health conscious', 'i barely drink',
    'occasional drinker', 'i dont really party anymore', 'i have a 9 to 5', 'i wake up early', 'morning person',
    'early riser', 'i hate mornings but try', 'i have my own place', 'i live alone', 'no roommates', 'homeowner',
    'i love my friends', 'huge friend group', 'everyone loves me', 'i get along with everyone', 'people person',
    'extrovert', 'introvert', 'ambivert', 'i love staying in', 'i love going out', 'best of both worlds',
    'i can fix anything', 'handy', 'i do my own car maintenance', 'i love road trips', 'i love spontaneous trips',
    'i love sunsets', 'romantic', 'i love giving gifts', 'thoughtful', 'i remember everything', 'attentive',
    'tall dark and handsome', 'model', 'i used to model', 'almost famous', 'went viral once', 'influencer',
    'verified somewhere', 'i have a podcast', 'aspiring author', 'working on a novel', 'i journal', 'i meditate',
    'mindful', 'spiritual not religious', 'i do crossfit', 'i lift', 'i surf', 'i ski', 'i snowboard',
    'i love skiing', 'i love the beach', 'beach body', 'i have abs', 'i never skip leg day', 'i love running',
    'i did a triathlon', 'i love cooking for others', 'my signature dish', 'i make a mean lasagna', 'i bake',
    'i love baking', 'i grow my own vegetables', 'i have a garden', 'green thumb', 'self sufficient', 'minimalist',
    'i travel light', 'i love the simple things', 'i appreciate the little things', 'grateful',
    'positive vibes only', 'good energy', 'glass half full', 'optimist', 'i never argue', 'conflict free',
    'i communicate well', 'great communicator', 'i text back fast', 'always available', 'reliable', 'dependable',
    'punctual', 'i am never late', 'organized', 'type a', 'i have a five year plan', 'goal oriented', 'driven',
    'ambitious', 'i make six figures', 'i invest', 'crypto investor', 'financially literate', 'debt free',
    'good with money', 'generous', 'i love to spoil', 'gentleman', 'old fashioned values', 'i open doors',
    'i pull out chairs', 'chivalrous', 'i love surprising people', 'i love kids and dogs', 'i want a big family',
    'i love christmas', 'i decorate for every holiday', 'i bring snacks', 'i give good advice',
    'i remember your coffee order', 'low key famous', 'my ex still misses me', 'no baggage',
    'i have no exes that hate me', 'i am drama free for real', 'my photos are unfiltered', 'no filter',
    'natural look'
  ]),
  'Things the weird kid did in class': new Set([
    'ate glue', 'ate the paste', 'ate crayons', 'ate a bug', 'ate paper', 'ate chalk', 'ate an eraser',
    'chewed on pencils', 'chewed pencil erasers', 'licked the window', 'licked the desk', 'licked a battery',
    'licked the glue stick', 'put glue on their hand to peel it off', 'peeled dried glue', 'sniffed markers',
    'huffed the dry erase markers', 'smelled the crayons', 'collected bugs in a jar',
    'kept a worm in their pocket', 'brought a frog to school', 'had a pet rock', 'named their pencil',
    'talked to their pencil', 'talked to themselves', 'had an imaginary friend',
    'argued with the teacher about dinosaurs', 'corrected the teacher', 'raised their hand for everything',
    'answered every question', 'made weird noises', 'barked like a dog', 'meowed during class', 'quacked randomly',
    'hummed constantly', 'tapped the desk nonstop', 'rocked back and forth', 'spun in their chair',
    'fell out of their chair', 'tipped their chair too far back', 'stood on their chair', 'sat under the desk',
    'hid in the cubby', 'crawled under the table', 'wore a cape to school', 'wore a costume every day',
    'wore mismatched socks', 'wore their shirt inside out', 'wore sunglasses inside',
    'wore a helmet for no reason', 'wore gloves all year', 'brought a briefcase', 'carried a stapler everywhere',
    'collected rubber bands', 'made a rubber band ball', 'flicked rubber bands', 'shot spitballs',
    'made paper airplanes', 'folded origami constantly', 'drew on their arms', 'drew on the desk',
    'drew on themselves with marker', 'colored on their face', 'gave themselves a marker mustache',
    'drew comics in class', 'wrote in a secret code', 'had a secret language', 'passed weird notes',
    'collected gum under the desk', 'stuck gum on the chair', 'chewed someone elses gum',
    'dared people to eat things', 'ate the cafeteria mystery meat', 'mixed all their food together',
    'drank the milk in one gulp', 'put milk up their nose', 'snorted laughing', 'laughed at nothing',
    'laughed alone', 'cried over nothing', 'melted down over a pencil', 'threw a tantrum',
    'hid under the teachers desk', 'locked themselves in the closet', 'climbed the bookshelf',
    'hung from the door frame', 'did pull ups on the door', 'did somersaults in the hallway',
    'cartwheeled into class', 'walked on their hands', 'pretended to be a robot', 'spoke in a robot voice',
    'only spoke in movie quotes', 'quoted star wars constantly', 'reenacted scenes from movies',
    'made sound effects for everything', 'narrated their own life', 'talked in third person',
    'insisted they were a dinosaur', 'insisted they were a cat', 'wore cat ears', 'meowed instead of answering',
    'brought weird snacks', 'ate a whole onion', 'ate a lemon like an apple', 'put salt on everything',
    'ate plain butter', 'collected their own boogers', 'ate their boogers', 'picked their nose openly',
    'wiped it under the desk', 'sneezed without covering', 'coughed on purpose', 'faked being sick',
    'faked fainting', 'played dead', 'held their breath until they turned red',
    'stared at people without blinking', 'made intense eye contact', 'stared out the window the whole class',
    'daydreamed loudly', 'fell asleep in class', 'snored', 'drooled on the desk', 'slept under the coats',
    'built a fort out of textbooks', 'stacked everything into towers', 'lined up their pencils perfectly',
    'organized the crayons by color', 'counted the ceiling tiles', 'knew weird facts', 'recited pi',
    'knew every dinosaur name', 'memorized the periodic table', 'knew the capital of every country',
    'corrected your grammar', 'used big words wrong', 'spoke like a tiny professor', 'wore a bow tie',
    'brought a magnifying glass', 'examined everything closely', 'kept a magnifying glass to burn paper',
    'collected dead bugs', 'pressed flowers in books', 'kept a rock collection',
    'showed everyone their rock collection', 'brought a metal detector', 'dug holes at recess',
    'ate dirt at recess', 'made mud pies', 'put a worm in their mouth', 'dared someone to lick the flagpole',
    'licked the flagpole in winter', 'got their tongue stuck', 'put their head through the chair',
    'got their arm stuck in a chair', 'got stuck in a locker', 'climbed into a locker', 'hid in the locker',
    'collected pencil shavings', 'kept the pencil shavings in a bag', 'sharpened a pencil to nothing',
    'broke pencils on purpose', 'snapped crayons in half', 'peeled all the crayon wrappers', 'made wax sculptures',
    'melted crayons on the radiator', 'put things on the radiator', 'warmed their lunch on the heater',
    'traded weird things', 'traded a sandwich for a rock', 'collected milk caps', 'flipped pogs',
    'brought yugioh cards', 'showed everyone their cards', 'brought a beyblade', 'spun a top during the lesson',
    'played with a fidget spinner forever', 'clicked their pen constantly', 'disassembled their pen',
    'took apart the stapler', 'fixed the pencil sharpener', 'volunteered to clean the erasers',
    'clapped the erasers and made a cloud', 'wrote backwards', 'wrote upside down', 'used both hands at once',
    'wrote with their feet', 'signed their name in cursive in kindergarten', 'drew maps of imaginary worlds',
    'invented their own country', 'drew floor plans', 'built paper cities', 'made a diorama no one asked for',
    'brought show and tell every day', 'brought their entire collection', 'explained things no one asked about'
  ]),
  "Things that shouldn't be a sport but are": new Set([
    'cheese rolling', 'competitive cheese rolling', 'cooper\'s hill cheese rolling', 'competitive eating',
    'hot dog eating', 'cornhole', 'bog snorkeling', 'mountain bike bog snorkeling', 'chess boxing', 'curling',
    'darts', 'toe wrestling', 'extreme ironing', 'wife carrying', 'wife carrying championship', 'shin kicking',
    'sepak takraw', 'kabaddi', 'underwater hockey', 'octopush', 'underwater rugby', 'underwater football',
    'quidditch', 'quadball', 'muggle quidditch', 'pillow fighting', 'competitive pillow fighting',
    'pillow fight championship', 'rock paper scissors', 'competitive rock paper scissors', 'thumb wrestling',
    'arm wrestling', 'leg wrestling', 'finger wrestling', 'fingerhakeln', 'toe wrestling championship',
    'nettle eating', 'worm charming', 'ferret legging', 'gurning', 'gurning championship', 'snail racing',
    'crab racing', 'pig racing', 'duck herding', 'sheep herding', 'dog surfing', 'dock diving', 'flyball',
    'disc dog', 'skijoring', 'dog sledding', 'sled dog racing', 'cardboard tube fighting', 'lightsaber dueling',
    'foam sword fighting', 'dagorhir', 'medieval combat', 'buhurt', 'knife throwing', 'axe throwing',
    'competitive axe throwing', 'log rolling', 'lumberjack sports', 'timbersports', 'wood chopping',
    'speed climbing', 'rock climbing', 'bouldering', 'parkour', 'freerunning', 'slacklining', 'highlining',
    'tightrope walking', 'unicycle hockey', 'unicycling', 'mountain unicycling', 'bike polo', 'elephant polo',
    'camel polo', 'yak polo', 'horseball', 'tent pegging', 'jousting', 'mounted archery', 'sumo wrestling',
    'oil wrestling', 'turkish oil wrestling', 'mud wrestling', 'jelly wrestling', 'pole dancing',
    'competitive pole dancing', 'baton twirling', 'jump rope', 'double dutch', 'hula hooping', 'frisbee',
    'ultimate frisbee', 'disc golf', 'frisbee golf', 'footbag', 'hacky sack', 'kan jam', 'spikeball', 'roundnet',
    'pickleball', 'paddleball', 'racquetball', 'squash', 'wallyball', 'table tennis', 'ping pong', 'beer pong',
    'flip cup', 'quarters', 'tug of war', 'tug of war championship', 'caber toss', 'highland games', 'stone put',
    'hammer throw', 'sheaf toss', 'wellie wanging', 'welly throwing', 'rubber boot throwing', 'gumboot throwing',
    'cell phone throwing', 'mobile phone throwing', 'egg throwing', 'egg tossing', 'egg and spoon race',
    'sack race', 'three legged race', 'wheelbarrow race', 'potato sack racing', 'wheelbarrow racing', 'bed racing',
    'bathtub racing', 'outhouse racing', 'lawn mower racing', 'riding mower racing', 'pumpkin chunking',
    'pumpkin chucking', 'watermelon seed spitting', 'cherry pit spitting', 'tobacco spitting', 'spitting contests',
    'quokka selfie', 'black pudding throwing', 'haggis hurling', 'custard pie throwing', 'tomato fighting',
    'la tomatina', 'orange battle', 'food fighting', 'air guitar', 'air guitar championship', 'air sex', 'air sax',
    'beard growing', 'beard and moustache championship', 'whisker growing', 'hair styling', 'staring contest',
    'staring championship', 'blinking contest', 'laughing yoga', 'competitive sudoku', 'speed sudoku',
    'speedcubing', 'rubiks cube speedsolving', 'memory championship', 'spelling bee', 'scrabble',
    'competitive scrabble', 'speed reading', 'typing competition', 'speed typing', 'texting competition',
    'speed texting', 'video gaming', 'esports', 'competitive gaming', 'speedrunning', 'retro gaming', 'pinball',
    'competitive pinball', 'marbles', 'marble racing', 'jenga', 'competitive jenga', 'dominoes', 'domino toppling',
    'card stacking', 'speed stacking', 'sport stacking', 'cup stacking', 'jenga tower building', 'yo yo',
    'competitive yo yo', 'kite fighting', 'kite flying', 'kite surfing', 'land sailing', 'sandboarding',
    'snow kiting', 'ice swimming', 'winter swimming', 'ice climbing', 'ice fishing', 'ice golf', 'snow golf',
    'swamp soccer', 'swamp football', 'mud football', 'bubble soccer', 'bubble football', 'underwater cycling',
    'underwater chess', 'chess marathon', 'speed chess', 'blitz chess', 'bullet chess', 'poker',
    'competitive poker', 'rock skipping', 'stone skimming', 'stone skipping', 'frog jumping',
    'frog jumping contest', 'sandcastle building', 'sand sculpting', 'snow sculpting', 'ice sculpting',
    'lawn bowling', 'bocce', 'petanque', 'boules', 'horseshoes', 'quoits', 'ringtoss', 'shuffleboard',
    'table shuffleboard', 'curling on ice', 'ice stock sport', 'bandy', 'ringette', 'broomball', 'floorball',
    'cycle ball', 'radball', 'bo-taoshi', 'kabaddi pro', 'sepak takraw doubles', 'jai alai', 'pelota', 'fives',
    'real tennis', 'court tennis', 'rackets', 'stoolball', 'rounders', 'kickball', 'dodgeball', 'bench ball',
    'netball', 'korfball', 'tchoukball', 'goalball', 'boccia', 'wheelchair rugby', 'wheelchair tennis',
    'sitting volleyball', 'footgolf', 'foot golf', 'speed walking', 'race walking', 'power walking',
    'nordic walking', 'orienteering', 'rogaining', 'geocaching', 'fox hunting', 'metal detecting',
    'treasure hunting', 'sandbagging', 'strongman', 'log lifting', 'atlas stones', 'tire flipping', 'keg toss',
    'farmers walk', 'yoke carry', 'sandbag carry', 'barrel rolling', 'wine barrel racing', 'cheese chasing',
    'running of the bulls', 'mud running', 'obstacle racing', 'tough mudder', 'spartan racing', 'ninja warrior',
    'obstacle course racing', 'demolition derby', 'monster truck rally', 'tractor pulling', 'truck pulling',
    'mud bogging', 'quad biking', 'motocross', 'supercross', 'speedway', 'flat track racing', 'soapbox derby',
    'gravity racing', 'street luge', 'luge', 'skeleton', 'bobsled', 'bobsledding', 'tobogganing', 'sledding',
    'snow tubing', 'ice cross downhill', 'crashed ice', 'red bull flugtag', 'flugtag', 'human powered flight',
    'birdman rally', 'wing walking'
  ])
};
