// categoryAnswers/expand-econ-2.js  (data/accept-lists — batch 2)
// Union-merged supplement (see categoryAnswers.js). Real, mainstream members + variants
// (lowercase / plurals / partial + full names / alt spellings), all <= 3 words, deduped.
module.exports = {
  // Marvel heroes + famous anti-heroes (players type any Marvel character). ~150 real.
  'Marvel Superheroes': new Set([
    'spider-man', 'spiderman', 'peter parker', 'miles morales', 'spider-gwen', 'gwen stacy',
    'iron man', 'tony stark', 'captain america', 'steve rogers', 'thor', 'hulk', 'bruce banner',
    'black widow', 'natasha romanoff', 'hawkeye', 'clint barton', 'black panther', "t'challa",
    'doctor strange', 'ant-man', 'antman', 'scott lang', 'the wasp', 'wasp', 'hope van dyne',
    'scarlet witch', 'wanda maximoff', 'vision', 'falcon', 'sam wilson', 'winter soldier',
    'bucky barnes', 'war machine', 'star-lord', 'peter quill', 'gamora', 'rocket raccoon', 'rocket',
    'groot', 'drax', 'mantis', 'nebula', 'captain marvel', 'carol danvers', 'ms marvel', 'kamala khan',
    'she-hulk', 'jennifer walters', 'daredevil', 'matt murdock', 'the punisher', 'punisher',
    'frank castle', 'jessica jones', 'luke cage', 'iron fist', 'danny rand', 'moon knight',
    'marc spector', 'blade', 'ghost rider', 'nick fury', 'wolverine', 'logan', 'cyclops', 'scott summers',
    'jean grey', 'phoenix', 'storm', 'ororo munroe', 'beast', 'hank mccoy', 'rogue', 'gambit',
    'nightcrawler', 'colossus', 'iceman', 'professor x', 'charles xavier', 'jubilee', 'kitty pryde',
    'shadowcat', 'psylocke', 'bishop', 'cable', 'domino', 'deadpool', 'wade wilson', 'x-23', 'laura kinney',
    'angel', 'archangel', 'quicksilver', 'pietro maximoff', 'polaris', 'havok', 'banshee', 'forge',
    'dazzler', 'longshot', 'mister fantastic', 'reed richards', 'invisible woman', 'sue storm',
    'human torch', 'johnny storm', 'the thing', 'ben grimm', 'silver surfer', 'namor', 'sub-mariner',
    'wong', 'clea', 'brother voodoo', 'moon girl', 'squirrel girl', 'america chavez', 'kate bishop',
    'valkyrie', 'korg', 'heimdall', 'lady sif', 'sif', 'hercules', 'the sentry', 'adam warlock',
    'quasar', 'nova', 'richard rider', 'photon', 'monica rambeau', 'wiccan', 'speed', 'hulkling',
    'patriot', 'stature', 'ironheart', 'riri williams', 'silk', 'cindy moon', 'spider-woman',
    'jessica drew', 'venom', 'eddie brock', 'agent venom', 'red hulk', 'the maker', 'shang-chi',
    'echo', 'maya lopez', 'white tiger', 'nick fury jr', 'sabra', 'the winter guard', 'the falcon',
    'captain britain', 'union jack', 'spitfire', 'the black knight', 'sersi', 'ikaris', 'thena',
    'gilgamesh', 'makkari', 'phastos', 'kingo', 'sprite', 'the eternals', 'mockingbird', 'bobbi morse',
    'tigra', 'hellcat', 'patsy walker', 'jack of hearts', 'wonder man', 'simon williams', 'firestar',
    'darkhawk', 'sleepwalker', 'ka-zar', 'gorilla-man', 'moon knight',
  ]),

  // Famous, widely-recognised paintings (with common short titles). ~130 real.
  'Famous paintings': new Set([
    'mona lisa', 'the last supper', 'the starry night', 'starry night', 'the scream', 'guernica',
    'girl with a pearl earring', 'the persistence of memory', 'the creation of adam', 'water lilies',
    'the birth of venus', 'american gothic', 'the night watch', 'las meninas', 'the kiss',
    'the great wave', 'the great wave off kanagawa', 'the school of athens', 'nighthawks',
    'the garden of earthly delights', 'a sunday afternoon', 'a sunday on la grande jatte',
    'la grande jatte', 'liberty leading the people', 'the arnolfini portrait', 'whistlers mother',
    "whistler's mother", 'the son of man', 'the treachery of images', 'this is not a pipe',
    'the ambassadors', 'bal du moulin de la galette', 'the swing', 'olympia', 'luncheon on the grass',
    'impression sunrise', 'the dance', 'the potato eaters', 'sunflowers', 'cafe terrace at night',
    'the bedroom', 'irises', 'wheatfield with crows', 'self-portrait', 'the yellow house',
    'the milkmaid', 'the astronomer', 'view of delft', 'the anatomy lesson', 'saturn devouring his son',
    'the third of may', 'the naked maja', 'the clothed maja', 'the raft of the medusa',
    'the death of marat', 'napoleon crossing the alps', 'oath of the horatii', 'the gleaners',
    'the angelus', 'the sower', 'the hay wain', 'the fighting temeraire', 'rain steam and speed',
    'wanderer above the sea of fog', 'the wanderer', 'ophelia', 'the lady of shalott',
    'the fall of icarus', 'the hunters in the snow', 'the tower of babel', 'netherlandish proverbs',
    'the wedding dance', 'the peasant wedding', 'primavera', 'venus of urbino', 'the tempest',
    'sleeping venus', 'bacchus and ariadne', 'the tribute money', 'the calling of st matthew',
    'the entombment', 'judith beheading holofernes', 'medusa', 'the conversion of saint paul',
    'sistine madonna', 'the sistine chapel', 'the transfiguration', 'the coronation of napoleon',
    'the burial of count orgaz', 'view of toledo', 'composition with red blue and yellow', 'broadway boogie woogie',
    'the treachery of images', 'no 5 1948', 'autumn rhythm', 'campbell soup cans', 'marilyn diptych',
    'the son of man', 'les demoiselles davignon', "les demoiselles d'avignon", 'weeping woman',
    'three musicians', 'the old guitarist', 'the weeping woman', 'the dream', 'the two fridas',
    'self-portrait with thorn necklace', 'the broken column', 'nude descending a staircase',
    'the empire of light', 'golconda', 'the human condition', 'christina\'s world', 'the flower carrier',
    'man at the crossroads', 'the lovers', 'and the migration', 'the migration series',
    'a bar at the folies-bergere', 'dogs playing poker', 'washington crossing the delaware',
    'whistlejacket', 'the blue boy', 'pinkie', 'the swing', 'ecce homo', 'salvator mundi',
    'lady with an ermine', 'vitruvian man', 'the virgin of the rocks',
  ]),

  // Disney animated-movie characters (features). ~150 real.
  'Disney Animated Movie Characters': new Set([
    'mickey mouse', 'minnie mouse', 'donald duck', 'daisy duck', 'goofy', 'pluto', 'snow white',
    'the evil queen', 'grumpy', 'dopey', 'doc', 'happy', 'sleepy', 'bashful', 'sneezy', 'cinderella',
    'prince charming', 'the fairy godmother', 'gus', 'jaq', 'lady tremaine', 'lucifer', 'aurora',
    'sleeping beauty', 'maleficent', 'prince phillip', 'flora', 'fauna', 'merryweather', 'alice',
    'the mad hatter', 'the cheshire cat', 'the queen of hearts', 'the white rabbit', 'peter pan',
    'tinker bell', 'wendy', 'captain hook', 'mr smee', 'pinocchio', 'jiminy cricket', 'geppetto',
    'figaro', 'monstro', 'dumbo', 'timothy mouse', 'bambi', 'thumper', 'flower', 'simba', 'nala',
    'mufasa', 'scar', 'timon', 'pumbaa', 'zazu', 'rafiki', 'sarabi', 'aladdin', 'jasmine', 'the genie',
    'jafar', 'iago', 'abu', 'the sultan', 'rajah', 'ariel', 'prince eric', 'ursula', 'sebastian',
    'flounder', 'scuttle', 'king triton', 'flotsam', 'jetsam', 'belle', 'the beast', 'gaston',
    'lumiere', 'cogsworth', 'mrs potts', 'chip', 'lefou', 'maurice', 'pocahontas', 'john smith',
    'meeko', 'flit', 'grandmother willow', 'governor ratcliffe', 'mulan', 'mushu', 'li shang', 'shan yu',
    'cri-kee', 'hercules', 'megara', 'meg', 'hades', 'phil', 'pegasus', 'tarzan', 'jane', 'terk',
    'tantor', 'kerchak', 'kala', 'quasimodo', 'esmeralda', 'frollo', 'phoebus', 'hugo', 'victor',
    'laverne', 'kuzco', 'pacha', 'yzma', 'kronk', 'lilo', 'stitch', 'nani', 'jumba', 'pleakley',
    'kida', 'milo thatch', 'tiana', 'prince naveen', 'dr facilier', 'louis', 'ray', 'charlotte',
    'rapunzel', 'flynn rider', 'eugene', 'mother gothel', 'pascal', 'maximus', 'anna', 'elsa',
    'kristoff', 'olaf', 'sven', 'hans', 'the duke of weselton', 'wreck-it ralph', 'vanellope',
    'fix-it felix', 'sergeant calhoun', 'king candy', 'moana', 'maui', 'heihei', 'pua', 'gramma tala',
    'chief tui', 'tamatoa', 'te fiti', 'judy hopps', 'nick wilde', 'chief bogo', 'flash', 'mr big',
    'clawhauser', 'mayor lionheart', 'bellwether', 'mirabel', 'bruno', 'isabela', 'luisa', 'abuela',
    'antonio', 'dolores', 'camilo', 'julieta', 'felix', 'the mad hatter', 'baymax', 'hiro', 'robin hood',
    'little john', 'maid marian', 'prince john', 'sir hiss', 'friar tuck',
  ]),

  // Harry Potter characters. ~130 real.
  'Harry Potter Characters': new Set([
    'harry potter', 'harry', 'hermione granger', 'hermione', 'ron weasley', 'ron', 'albus dumbledore',
    'dumbledore', 'severus snape', 'snape', 'lord voldemort', 'voldemort', 'tom riddle', 'rubeus hagrid',
    'hagrid', 'minerva mcgonagall', 'mcgonagall', 'draco malfoy', 'draco', 'neville longbottom',
    'neville', 'luna lovegood', 'luna', 'ginny weasley', 'ginny', 'fred weasley', 'george weasley',
    'fred and george', 'percy weasley', 'bill weasley', 'charlie weasley', 'molly weasley',
    'arthur weasley', 'sirius black', 'sirius', 'remus lupin', 'lupin', 'peter pettigrew', 'wormtail',
    'james potter', 'lily potter', 'dobby', 'kreacher', 'bellatrix lestrange', 'bellatrix',
    'lucius malfoy', 'narcissa malfoy', 'dolores umbridge', 'umbridge', 'cornelius fudge', 'fudge',
    'mad-eye moody', 'alastor moody', 'nymphadora tonks', 'tonks', 'kingsley shacklebolt',
    'gilderoy lockhart', 'lockhart', 'quirinus quirrell', 'quirrell', 'horace slughorn', 'slughorn',
    'filius flitwick', 'flitwick', 'pomona sprout', 'professor sprout', 'sybill trelawney', 'trelawney',
    'argus filch', 'filch', 'mrs norris', 'madam pomfrey', 'poppy pomfrey', 'cho chang', 'cedric diggory',
    'cedric', 'viktor krum', 'krum', 'fleur delacour', 'fleur', 'dean thomas', 'seamus finnigan',
    'lavender brown', 'parvati patil', 'padma patil', 'oliver wood', 'lee jordan', 'colin creevey',
    'ernie macmillan', 'hannah abbott', 'susan bones', 'justin finch-fletchley', 'zacharias smith',
    'pansy parkinson', 'gregory goyle', 'goyle', 'vincent crabbe', 'crabbe', 'blaise zabini',
    'marcus flint', 'aberforth dumbledore', 'gellert grindelwald', 'grindelwald', 'newt scamander',
    'nicolas flamel', 'moaning myrtle', 'the fat lady', 'nearly headless nick', 'the bloody baron',
    'the grey lady', 'helena ravenclaw', 'peeves', 'griphook', 'ollivander', 'garrick ollivander',
    'xenophilius lovegood', 'rita skeeter', 'barty crouch', 'barty crouch jr', 'igor karkaroff',
    'madame maxime', 'firenze', 'buckbeak', 'fawkes', 'hedwig', 'crookshanks', 'scabbers', 'nagini',
    'aragog', 'fluffy', 'the basilisk', 'grawp', 'winky', 'salazar slytherin', 'godric gryffindor',
    'rowena ravenclaw', 'helga hufflepuff', 'teddy lupin', 'andromeda tonks', 'ted tonks',
    'amos diggory', 'petunia dursley', 'vernon dursley', 'dudley dursley', 'marge dursley',
  ]),
};
