// categoryAnswers/expand-broad-1.js
// data/accept-lists — broad under-expanded categories, batch 1 (autonomous 2026-08-25).
// Union-merged via the supplements loop in categoryAnswers.js (adds to the existing Set,
// never replaces). REAL, well-known answers only, all lowercase, <=3 words, deduped by the Set.
// Keys must match existing CATEGORIES exactly (verified against categoryAnswers counts).
module.exports = {
  'Naruto characters': [
    'naruto', 'sasuke', 'sakura', 'kakashi', 'hinata', 'shikamaru', 'rock lee', 'gaara',
    'itachi', 'jiraiya', 'tsunade', 'orochimaru', 'madara', 'obito', 'minato', 'kushina',
    'neji', 'tenten', 'ino', 'choji', 'kiba', 'shino', 'temari', 'kankuro', 'killer bee',
    'might guy', 'kabuto', 'pain', 'nagato', 'konan', 'deidara', 'sasori', 'hidan', 'kakuzu',
    'zabuza', 'haku', 'kurama', 'jugo', 'suigetsu', 'karin', 'yamato', 'sai', 'konohamaru',
    'asuma', 'kurenai', 'iruka', 'boruto', 'sarada', 'mitsuki', 'hashirama', 'tobirama',
    'hiruzen', 'danzo', 'kisame', 'yahiko', 'chiyo', 'onoki', 'kimimaro', 'shizune', 'anko',
  ],
  'Dragon Ball characters': [
    'goku', 'vegeta', 'gohan', 'piccolo', 'krillin', 'bulma', 'trunks', 'goten', 'frieza',
    'cell', 'majin buu', 'beerus', 'whis', 'master roshi', 'yamcha', 'tien', 'chiaotzu',
    'chi-chi', 'videl', 'android 17', 'android 18', 'android 16', 'dr gero', 'raditz', 'nappa',
    'captain ginyu', 'king kai', 'mr satan', 'hercule', 'dende', 'mr popo', 'kami', 'nail',
    'broly', 'bardock', 'king vegeta', 'gogeta', 'vegito', 'zamasu', 'goku black', 'hit',
    'jiren', 'toppo', 'cabba', 'kale', 'caulifla', 'pan', 'bardock', 'supreme kai', 'zeno',
    'shenron', 'oolong', 'puar', 'launch', 'mr popo', 'garlic jr', 'cooler', 'turles',
  ],
  'One Piece characters': [
    'luffy', 'zoro', 'nami', 'usopp', 'sanji', 'chopper', 'robin', 'franky', 'brook', 'jinbe',
    'ace', 'sabo', 'shanks', 'whitebeard', 'blackbeard', 'kaido', 'big mom', 'doflamingo',
    'crocodile', 'buggy', 'mihawk', 'boa hancock', 'trafalgar law', 'eustass kid', 'killer',
    'garp', 'sengoku', 'akainu', 'aokiji', 'kizaru', 'fujitora', 'smoker', 'tashigi', 'coby',
    'rayleigh', 'gol d roger', 'dragon', 'ivankov', 'arlong', 'enel', 'moria', 'kuma',
    'katakuri', 'cracker', 'king', 'queen', 'jack', 'yamato', 'momonosuke', 'kinemon', 'oden',
    'perona', 'bartolomeo', 'cavendish', 'rebecca', 'vivi', 'carrot', 'wano', 'marco', 'izo',
  ],
  'Rappers': [
    'eminem', 'jay-z', 'kanye west', 'drake', 'kendrick lamar', 'j cole', 'nas', 'snoop dogg',
    'dr dre', 'ice cube', 'tupac', 'biggie', '50 cent', 'lil wayne', 'nicki minaj', 'cardi b',
    'travis scott', 'future', 'post malone', 'tyler the creator', 'asap rocky', 'childish gambino',
    'chance the rapper', 'logic', 'wiz khalifa', 'mac miller', 'big sean', 'meek mill', 'rick ross',
    'dmx', 'ludacris', 'young thug', '21 savage', 'gucci mane', 'lil baby', 'roddy ricch',
    'megan thee stallion', 'doja cat', 'lil nas x', 'ice spice', 'busta rhymes', 'method man',
    'redman', 'common', 'talib kweli', 'mos def', 'andre 3000', 'big boi', 'ti', 'pusha t',
    'jadakiss', 'fabolous', 'juicy j', 'wale', 'schoolboy q', 'ab-soul', 'joey badass', 'nle choppa',
  ],
  'Airlines': [
    'delta', 'united', 'american airlines', 'southwest', 'jetblue', 'alaska airlines', 'spirit',
    'frontier', 'hawaiian airlines', 'emirates', 'qatar airways', 'singapore airlines', 'lufthansa',
    'british airways', 'air france', 'klm', 'ryanair', 'easyjet', 'turkish airlines', 'etihad',
    'cathay pacific', 'qantas', 'ana', 'japan airlines', 'korean air', 'air canada', 'aeromexico',
    'latam', 'iberia', 'swiss', 'austrian airlines', 'virgin atlantic', 'virgin australia',
    'china eastern', 'china southern', 'air china', 'thai airways', 'malaysia airlines',
    'vietnam airlines', 'philippine airlines', 'aer lingus', 'finnair', 'sas', 'norwegian',
    'wizz air', 'vueling', 'aeroflot', 'saudia', 'egyptair', 'ethiopian airlines', 'kenya airways',
    'air india', 'indigo', 'garuda indonesia', 'avianca', 'copa airlines', 'westjet', 'gol',
  ],
  'Languages': [
    'english', 'spanish', 'mandarin', 'french', 'german', 'italian', 'portuguese', 'russian',
    'japanese', 'korean', 'arabic', 'hindi', 'bengali', 'urdu', 'punjabi', 'tamil', 'telugu',
    'turkish', 'dutch', 'greek', 'polish', 'swedish', 'norwegian', 'danish', 'finnish', 'hungarian',
    'czech', 'romanian', 'ukrainian', 'hebrew', 'thai', 'vietnamese', 'indonesian', 'malay',
    'tagalog', 'swahili', 'zulu', 'afrikaans', 'farsi', 'persian', 'cantonese', 'gujarati',
    'marathi', 'kannada', 'malayalam', 'nepali', 'sinhala', 'burmese', 'khmer', 'lao', 'mongolian',
    'catalan', 'basque', 'welsh', 'irish', 'scottish gaelic', 'icelandic', 'croatian', 'serbian',
    'bulgarian', 'slovak', 'slovenian', 'lithuanian', 'latvian', 'estonian', 'amharic', 'somali',
  ],
  'Clothing brands': [
    'nike', 'adidas', 'puma', 'under armour', 'gucci', 'prada', 'versace', 'chanel',
    'louis vuitton', 'zara', 'h&m', 'uniqlo', 'gap', "levi's", 'calvin klein', 'tommy hilfiger',
    'ralph lauren', 'north face', 'patagonia', 'columbia', 'reebok', 'new balance', 'vans',
    'converse', 'fila', 'champion', 'supreme', 'balenciaga', 'burberry', 'dior', 'armani',
    'hugo boss', 'lacoste', 'forever 21', 'old navy', 'american eagle', 'hollister', 'abercrombie',
    'guess', 'diesel', 'dolce gabbana', 'fendi', 'hermes', 'saint laurent', 'givenchy', 'lululemon',
    'asics', 'skechers', 'crocs', 'timberland', 'dr martens', 'carhartt', 'wrangler', 'gymshark',
  ],
  'Soccer clubs': [
    'real madrid', 'barcelona', 'manchester united', 'manchester city', 'liverpool', 'chelsea',
    'arsenal', 'tottenham', 'bayern munich', 'borussia dortmund', 'juventus', 'ac milan',
    'inter milan', 'napoli', 'roma', 'psg', 'atletico madrid', 'sevilla', 'ajax', 'porto',
    'benfica', 'celtic', 'rangers', 'marseille', 'lyon', 'rb leipzig', 'leicester city',
    'west ham', 'everton', 'aston villa', 'newcastle', 'wolves', 'valencia', 'villarreal',
    'real sociedad', 'fiorentina', 'lazio', 'sporting cp', 'feyenoord', 'psv', 'monaco',
    'atalanta', 'leverkusen', 'sassuolo', 'wolfsburg', 'schalke', 'galatasaray', 'fenerbahce',
    'boca juniors', 'river plate', 'flamengo', 'santos', 'palmeiras', 'corinthians',
  ],
  'Italian dishes': [
    'pizza', 'pasta', 'lasagna', 'spaghetti', 'risotto', 'ravioli', 'gnocchi', 'carbonara',
    'bolognese', 'tiramisu', 'gelato', 'bruschetta', 'minestrone', 'osso buco', 'parmigiana',
    'cannoli', 'focaccia', 'calzone', 'panna cotta', 'fettuccine', 'penne', 'linguine',
    'tortellini', 'prosciutto', 'caprese', 'pesto', 'arancini', 'polenta', 'saltimbocca',
    'panettone', 'biscotti', 'cacio e pepe', 'amatriciana', 'puttanesca', 'margherita',
    'marinara', 'ribollita', 'panzanella', 'affogato', 'stracciatella', 'burrata', 'mozzarella',
    'antipasto', 'caponata', 'vitello tonnato', 'zabaglione', 'sfogliatella', 'tortelloni',
  ],
  'Cooking methods': [
    'boiling', 'frying', 'baking', 'roasting', 'grilling', 'steaming', 'sauteing', 'poaching',
    'braising', 'simmering', 'broiling', 'searing', 'blanching', 'stewing', 'smoking',
    'deep frying', 'stir frying', 'sous vide', 'pan frying', 'toasting', 'caramelizing',
    'fermenting', 'pickling', 'curing', 'marinating', 'basting', 'reducing', 'whisking',
    'kneading', 'proofing', 'flambeing', 'glazing', 'dehydrating', 'confit', 'sweating',
    'deglazing', 'tempering', 'parboiling', 'scrambling', 'charbroiling', 'rotisserie', 'griddling',
  ],
  'Office supplies': [
    'pen', 'pencil', 'stapler', 'paper clip', 'tape', 'scissors', 'ruler', 'eraser',
    'highlighter', 'marker', 'notebook', 'binder', 'folder', 'envelope', 'sticky note',
    'whiteboard', 'calculator', 'hole punch', 'rubber band', 'glue', 'printer', 'ink',
    'paper', 'calendar', 'clipboard', 'thumbtack', 'correction fluid', 'sharpener', 'notepad',
    'index card', 'push pin', 'paper shredder', 'label maker', 'desk organizer', 'tape dispenser',
    'staple remover', 'legal pad', 'file cabinet', 'letter opener', 'binder clip', 'post-it',
    'ballpoint pen', 'fountain pen', 'mechanical pencil', 'ink cartridge', 'toner', 'laminator',
  ],
  'Camping gear': [
    'tent', 'sleeping bag', 'backpack', 'flashlight', 'lantern', 'camping stove', 'cooler',
    'canteen', 'compass', 'map', 'hatchet', 'knife', 'rope', 'tarp', 'matches', 'firewood',
    'hammock', 'headlamp', 'water filter', 'first aid kit', 'bug spray', 'sunscreen',
    'camping chair', 'air mattress', 'sleeping pad', 'multitool', 'paracord', 'trekking poles',
    'water bottle', 'thermos', 'cook set', 'dutch oven', 'fire starter', 'bear spray',
    'sleeping mat', 'ground cloth', 'camp pillow', 'binoculars', 'whistle', 'carabiner',
    'propane', 'cooler bag', 'camp table', 'lighter', 'tent stakes', 'guy lines', 'rain fly',
  ],
  'Social media apps': [
    'facebook', 'instagram', 'twitter', 'tiktok', 'snapchat', 'youtube', 'linkedin', 'reddit',
    'pinterest', 'whatsapp', 'telegram', 'discord', 'tumblr', 'twitch', 'wechat', 'threads',
    'bereal', 'clubhouse', 'mastodon', 'vine', 'myspace', 'x', 'signal', 'line', 'kik',
    'viber', 'weibo', 'douyin', 'vk', 'flickr', 'quora', 'medium', 'nextdoor', 'yik yak',
    'periscope', 'meetup', 'bluesky', 'truth social', 'parler', 'tinder', 'bumble', 'hinge',
  ],
  'Action movie stars': [
    'arnold schwarzenegger', 'sylvester stallone', 'bruce willis', 'jason statham',
    'dwayne johnson', 'vin diesel', 'keanu reeves', 'tom cruise', 'liam neeson',
    'jean-claude van damme', 'chuck norris', 'jackie chan', 'jet li', 'steven seagal',
    'wesley snipes', 'mel gibson', 'harrison ford', 'matt damon', 'daniel craig', 'hugh jackman',
    'chris hemsworth', 'chris evans', 'gerard butler', 'mark wahlberg', 'denzel washington',
    'will smith', 'nicolas cage', 'kurt russell', 'dolph lundgren', 'jason momoa', 'idris elba',
    'charlize theron', 'scarlett johansson', 'angelina jolie', 'milla jovovich', 'michelle yeoh',
    'gal gadot', 'ryan reynolds', 'john cena', 'tom hardy',
  ],
  'Famous DJs': [
    'david guetta', 'calvin harris', 'tiesto', 'avicii', 'martin garrix', 'skrillex', 'deadmau5',
    'marshmello', 'zedd', 'diplo', 'steve aoki', 'armin van buuren', 'hardwell', 'afrojack',
    'kygo', 'alan walker', 'dj snake', 'daft punk', 'swedish house mafia', 'carl cox',
    'paul van dyk', 'above beyond', 'don diablo', 'alesso', 'nicky romero', 'w&w', 'kshmr',
    'oliver heldens', 'fisher', 'illenium', 'flume', 'porter robinson', 'madeon', 'gryffin',
    'seven lions', 'excision', 'zeds dead', 'rezz', 'dj khaled', 'grandmaster flash',
  ],
  'Musical genres of dance': [
    'house', 'techno', 'trance', 'dubstep', 'drum and bass', 'hardstyle', 'disco', 'electro',
    'deep house', 'tech house', 'progressive house', 'big room', 'future bass', 'trap',
    'moombahton', 'acid house', 'uk garage', 'jungle', 'breakbeat', 'electro house',
    'tropical house', 'nu disco', 'hardcore', 'gabber', 'grime', 'edm', 'garage', 'downtempo',
    'ambient', 'synthwave', 'electro swing', 'jersey club', 'hardcore techno', 'minimal techno',
    'psytrance', 'eurodance', 'funk', 'breakcore', 'happy hardcore', 'glitch hop',
  ],
  'Card games': [
    'poker', 'blackjack', 'solitaire', 'go fish', 'uno', 'rummy', 'hearts', 'spades',
    'bridge', 'euchre', 'crazy eights', 'war', 'old maid', 'gin rummy', 'canasta',
    'pinochle', 'cribbage', 'baccarat', 'texas holdem', 'slapjack', 'snap', 'speed',
    'egyptian rat screw', 'president', 'kings corner', 'phase 10', 'skip-bo', 'rook',
    'exploding kittens', 'cards against humanity', 'magic the gathering', 'yugioh',
    'pokemon tcg', 'clock solitaire', 'freecell', 'spider solitaire', 'sheepshead', 'durak',
  ],
};
