// categoryAnswers/expand-broad-6.js
// data/accept-lists-5 batch 3: 20 more broad, open-ended categories that were
// under-expanded (<40 entries). Real, well-known answers only, <=3 words,
// lowercase, union-merged into the existing Sets in categoryAnswers.js (adds,
// never replaces). No inventions, no padding. Keys match existing category
// names exactly (verified against categoryAnswers counts).

module.exports = {
  'Social media platforms': [
    'facebook', 'instagram', 'twitter', 'x', 'tiktok', 'snapchat', 'linkedin', 'pinterest',
    'reddit', 'tumblr', 'youtube', 'whatsapp', 'telegram', 'signal', 'discord', 'twitch',
    'mastodon', 'threads', 'bluesky', 'wechat', 'weibo', 'line', 'kakaotalk', 'vk',
    'clubhouse', 'bereal', 'vine', 'myspace', 'flickr', 'quora', 'nextdoor', 'meetup',
    'friendster', 'google plus', 'periscope', 'likee', 'triller', 'lemon8', 'mewe',
    'truth social', 'rumble', 'patreon', 'onlyfans', 'musically', 'tagged',
  ],
  'Video streaming services': [
    'netflix', 'hulu', 'disney plus', 'disney+', 'hbo max', 'max', 'amazon prime video',
    'prime video', 'apple tv plus', 'apple tv+', 'peacock', 'paramount plus', 'paramount+',
    'discovery plus', 'discovery+', 'crunchyroll', 'funimation', 'tubi', 'pluto tv',
    'sling tv', 'sling', 'youtube tv', 'fubo', 'fubotv', 'starz', 'showtime', 'mubi',
    'criterion channel', 'britbox', 'acorn tv', 'curiositystream', 'shudder', 'hbo go',
    'hbo now', 'vudu', 'plex', 'roku channel', 'hotstar', 'hbo',
  ],
  'Music streaming services': [
    'spotify', 'apple music', 'youtube music', 'amazon music', 'tidal', 'deezer', 'pandora',
    'soundcloud', 'iheartradio', 'napster', 'qobuz', 'audiomack', 'bandcamp', 'gaana',
    'jiosaavn', 'anghami', 'boomplay', 'tencent music', 'kkbox', 'yandex music',
    'google play music', 'amazon music unlimited', 'amazon prime music',
  ],
  'Types of apples': [
    'gala', 'fuji', 'honeycrisp', 'granny smith', 'red delicious', 'golden delicious',
    'mcintosh', 'braeburn', 'pink lady', 'cripps pink', 'jazz', 'envy', 'ambrosia',
    'cortland', 'empire', 'jonagold', 'jonathan', 'cosmic crisp', 'opal', 'pinata',
    'winesap', 'rome', 'macoun', 'gravenstein', 'northern spy', 'cameo', 'kanzi',
    'sweetango', 'ginger gold', 'mutsu', 'crispin', 'arkansas black', 'spartan',
    'idared', 'snapdragon', 'evercrisp', 'koru', 'sansa', 'akane', 'liberty',
    'paula red', 'lady alice', 'honeygold', 'jonamac',
  ],
  'Sushi types': [
    'nigiri', 'sashimi', 'maki', 'uramaki', 'temaki', 'futomaki', 'hosomaki', 'california roll',
    'spicy tuna roll', 'dragon roll', 'rainbow roll', 'philadelphia roll', 'tempura roll',
    'salmon nigiri', 'tuna nigiri', 'unagi', 'eel', 'ebi', 'tamago', 'ikura', 'uni',
    'hamachi', 'chirashi', 'inari', 'gunkan', 'spider roll', 'caterpillar roll', 'tiger roll',
    'boston roll', 'nori', 'gari', 'oshizushi', 'maguro', 'toro', 'hotate', 'tako', 'ika',
    'tobiko', 'masago', 'negitoro', 'hand roll', 'sushi burrito',
  ],
  'Types of cake': [
    'chocolate cake', 'vanilla cake', 'red velvet', 'carrot cake', 'cheesecake', 'pound cake',
    'sponge cake', 'angel food cake', 'bundt cake', 'layer cake', 'marble cake', 'coffee cake',
    'birthday cake', 'wedding cake', 'black forest', 'tres leches', 'german chocolate',
    'funfetti', 'lemon cake', 'banana cake', 'fruitcake', 'ice cream cake', 'upside down cake',
    'victoria sponge', 'genoise', 'chiffon cake', 'devils food', 'molten lava cake', 'opera cake',
    'battenberg', 'madeira cake', 'sachertorte', 'pineapple upside down', 'strawberry shortcake',
    'crumb cake', 'hummingbird cake', 'lamington', 'swiss roll', 'yule log', 'king cake',
    'tiramisu', 'gateau', 'dump cake',
  ],
  'Literary devices': [
    'metaphor', 'simile', 'personification', 'alliteration', 'hyperbole', 'onomatopoeia',
    'imagery', 'symbolism', 'irony', 'foreshadowing', 'metonymy', 'synecdoche', 'oxymoron',
    'paradox', 'allusion', 'assonance', 'consonance', 'euphemism', 'juxtaposition', 'motif',
    'anaphora', 'allegory', 'pun', 'satire', 'understatement', 'litotes', 'epiphany',
    'flashback', 'verbal irony', 'dramatic irony', 'situational irony', 'chiasmus', 'zeugma',
    'apostrophe', 'anthropomorphism', 'cliffhanger', 'in medias res', 'malapropism',
    'repetition', 'parallelism', 'foil', 'meter', 'enjambment', 'caesura', 'refrain', 'sibilance',
  ],
  'Art mediums': [
    'oil paint', 'acrylic', 'watercolor', 'gouache', 'charcoal', 'pastel', 'pencil', 'ink',
    'tempera', 'fresco', 'collage', 'colored pencil', 'chalk', 'spray paint', 'encaustic',
    'pen and ink', 'graphite', 'crayon', 'marker', 'oil pastel', 'clay', 'bronze', 'marble',
    'watercolour', 'digital', 'mixed media', 'gesso', 'conte', 'sanguine', 'silverpoint',
    'egg tempera', 'enamel', 'mosaic', 'stained glass', 'plaster', 'papier mache', 'linocut',
    'woodcut', 'etching', 'lithography',
  ],
  'Donut types': [
    'glazed', 'jelly', 'boston cream', 'old fashioned', 'cake donut', 'cruller', 'french cruller',
    'powdered', 'chocolate glazed', 'sprinkles', 'maple bar', 'bear claw', 'apple fritter',
    'long john', 'bavarian cream', 'custard', 'honey dip', 'sugar', 'cinnamon', 'chocolate frosted',
    'strawberry frosted', 'jelly filled', 'cream filled', 'glazed twist', 'munchkin', 'donut holes',
    'ring donut', 'blueberry cake', 'pumpkin spice', 'cronut', 'sufganiyot',
  ],
  'Types of donuts': [
    'glazed', 'jelly', 'boston cream', 'old fashioned', 'cake donut', 'cruller', 'french cruller',
    'powdered', 'chocolate glazed', 'sprinkles', 'maple bar', 'bear claw', 'apple fritter',
    'long john', 'bavarian cream', 'custard', 'honey dip', 'sugar', 'cinnamon', 'chocolate frosted',
    'strawberry frosted', 'jelly filled', 'cream filled', 'glazed twist', 'munchkin', 'donut holes',
    'ring donut', 'blueberry cake', 'pumpkin spice', 'cronut', 'sufganiyot',
  ],
  'Tech hardware brands': [
    'apple', 'dell', 'hp', 'lenovo', 'asus', 'acer', 'msi', 'samsung', 'sony', 'lg', 'intel',
    'amd', 'nvidia', 'corsair', 'logitech', 'razer', 'gigabyte', 'seagate', 'western digital',
    'kingston', 'crucial', 'toshiba', 'microsoft', 'google', 'huawei', 'xiaomi', 'alienware',
    'cisco', 'ibm', 'sandisk', 'tp-link', 'netgear', 'belkin', 'anker', 'benq', 'viewsonic',
    'epson', 'canon', 'brother', 'zotac', 'evga', 'thermaltake', 'cooler master', 'nzxt',
  ],
  'Music awards': [
    'grammy', 'brit award', 'mtv video music award', 'vma', 'american music award', 'ama',
    'billboard music award', 'country music award', 'cma', 'mercury prize', 'ivor novello',
    'juno award', 'aria award', 'echo award', 'eurovision', 'bet award', 'soul train award',
    'mtv europe music award', 'mobo award', 'grammy award', 'acm award', 'dove award',
    'kids choice award', 'peoples choice award',
  ],
  'Battle royale games': [
    'fortnite', 'pubg', 'apex legends', 'call of duty warzone', 'warzone', 'fall guys',
    'super mario 35', 'tetris 99', 'spellbreak', 'hyper scape', 'realm royale', 'ring of elysium',
    'h1z1', 'garena free fire', 'free fire', 'naraka bladepoint', 'the finals', 'blackout',
    'cod mobile', 'pubg mobile', 'rules of survival', 'knives out', 'darwin project',
    'the culling', 'super animal royale', 'rogue company', 'hunt showdown', 'the culling',
  ],
  'Major record labels': [
    'universal music group', 'sony music', 'warner music', 'capitol records', 'atlantic records',
    'columbia records', 'def jam', 'interscope', 'rca records', 'republic records', 'island records',
    'motown', 'epic records', 'geffen', 'emi', 'virgin records', 'elektra', 'parlophone',
    'blue note', 'roc nation', 'aftermath', 'shady records', 'cash money', 'young money',
    'top dawg', 'dreamville', 'ovo sound', 'sub pop', 'matador', 'xl recordings', 'domino',
    '4ad', 'mercury records', 'decca', 'verve', 'stax', 'warner bros records',
  ],
  'Breakfast pastries': [
    'croissant', 'danish', 'muffin', 'scone', 'bagel', 'donut', 'cinnamon roll', 'turnover',
    'pain au chocolat', 'strudel', 'pop tart', 'toaster strudel', 'kolache', 'brioche', 'palmier',
    'beignet', 'coffee cake', 'crumb cake', 'bear claw', 'sticky bun', 'morning bun',
    'pain aux raisins', 'chocolate croissant', 'almond croissant', 'apple turnover',
    'cheese danish', 'cronut', 'kouign amann', 'financier', 'madeleine', 'rugelach', 'babka',
  ],
  'Farm crops': [
    'corn', 'wheat', 'soybeans', 'rice', 'cotton', 'barley', 'oats', 'sorghum', 'hay', 'alfalfa',
    'potatoes', 'tomatoes', 'lettuce', 'carrots', 'onions', 'cabbage', 'broccoli', 'peas', 'beans',
    'sugarcane', 'sugar beets', 'canola', 'sunflower', 'tobacco', 'peanuts', 'rye', 'millet',
    'flax', 'lentils', 'chickpeas', 'sweet potatoes', 'squash', 'pumpkins', 'cucumbers', 'peppers',
    'spinach', 'kale', 'celery', 'garlic', 'hemp', 'rapeseed', 'cassava', 'yams',
  ],
  'HBO series': [
    'the sopranos', 'the wire', 'game of thrones', 'succession', 'true detective', 'westworld',
    'euphoria', 'the last of us', 'chernobyl', 'band of brothers', 'deadwood', 'six feet under',
    'curb your enthusiasm', 'veep', 'silicon valley', 'barry', 'big little lies', 'watchmen',
    'the white lotus', 'house of the dragon', 'oz', 'entourage', 'girls', 'boardwalk empire',
    'sex and the city', 'true blood', 'rome', 'the newsroom', 'ballers', 'insecure',
    'the leftovers', 'mare of easttown', 'sharp objects', 'i may destroy you', 'the pacific',
    'generation kill', 'the gilded age', 'perry mason', 'lovecraft country', 'we own this city',
  ],
  'Streaming original series': [
    'stranger things', 'the crown', 'ozark', 'wednesday', 'bridgerton', 'squid game', 'the witcher',
    'house of cards', 'orange is the new black', 'the mandalorian', 'the boys',
    'the marvelous mrs maisel', 'ted lasso', 'the morning show', 'severance', 'reacher',
    'jack ryan', 'fleabag', 'the handmaids tale', 'cobra kai', 'you', 'dark', 'money heist',
    'la casa de papel', 'narcos', 'mindhunter', 'the umbrella academy', 'lucifer',
    'the queens gambit', 'love death and robots', 'arcane', 'only murders in the building',
    'hacks', 'the bear', 'shogun', 'fallout', 'dead to me', 'russian doll', 'sex education',
  ],
  'Smart home devices': [
    'amazon echo', 'echo dot', 'google nest', 'nest hub', 'google home', 'apple homepod', 'homepod',
    'ring doorbell', 'nest thermostat', 'ecobee', 'philips hue', 'smart bulb', 'smart plug',
    'wyze cam', 'nest cam', 'arlo', 'august smart lock', 'smart lock', 'smart thermostat', 'roomba',
    'smart speaker', 'alexa', 'chromecast', 'fire tv stick', 'smart tv', 'smart doorbell',
    'nest protect', 'ring alarm', 'smartthings', 'wemo', 'lifx', 'lutron caseta', 'kasa',
    'blink camera', 'eufy', 'rachio', 'sonos',
  ],
};
