// expand-broad-5.js
// data/accept-lists-5 batch 2: 19 more broad, open-ended categories that were
// under-expanded (<40 entries). Real answers only, <=3 words, lowercase,
// union-merged into the existing Sets in categoryAnswers.js (never replaces).
// No inventions, no padding. Keys match existing category names exactly.

module.exports = {
  'Big cats': [
    'lion', 'tiger', 'leopard', 'jaguar', 'cheetah', 'cougar', 'puma', 'mountain lion',
    'snow leopard', 'clouded leopard', 'lynx', 'canada lynx', 'eurasian lynx',
    'iberian lynx', 'bobcat', 'caracal', 'serval', 'ocelot', 'margay', 'oncilla',
    'jaguarundi', 'fishing cat', 'sand cat', 'african golden cat', 'asian golden cat',
    'marbled cat', 'pallas cat', 'manul', 'geoffroys cat', 'rusty-spotted cat',
    'flat-headed cat', 'black-footed cat', 'jungle cat', 'leopard cat', 'kodkod',
    'pampas cat', 'andean mountain cat', 'bay cat', 'liger', 'tigon', 'panther',
    'black panther', 'white tiger', 'bengal tiger', 'siberian tiger',
  ],
  'Printmaking techniques': [
    'etching', 'engraving', 'lithography', 'screen printing', 'silkscreen', 'woodcut',
    'linocut', 'aquatint', 'drypoint', 'mezzotint', 'monotype', 'monoprint', 'relief printing',
    'intaglio', 'collagraph', 'gum bichromate', 'cyanotype', 'letterpress', 'woodblock printing',
    'chine-colle', 'photogravure', 'stone lithography', 'offset lithography', 'block printing',
    'stencil', 'pochoir', 'giclee', 'risograph', 'lino printing', 'wood engraving',
    'soft ground etching', 'hard ground etching', 'sugar lift', 'spit bite', 'carborundum',
    'serigraphy', 'planographic printing', 'digital printing', 'embossing', 'debossing',
    'foil stamping', 'gyotaku', 'reduction print', 'linoleum printing',
  ],
  'Music production software': [
    'ableton live', 'ableton', 'fl studio', 'fruity loops', 'logic pro', 'logic',
    'pro tools', 'cubase', 'reason', 'studio one', 'bitwig', 'bitwig studio',
    'garageband', 'reaper', 'audacity', 'ardour', 'cakewalk', 'sonar', 'nuendo',
    'digital performer', 'renoise', 'maschine', 'bandlab', 'soundtrap', 'audiotool',
    'lmms', 'mixcraft', 'acid pro', 'samplitude', 'waveform', 'tracktion',
    'caustic', 'n-track', 'harrison mixbus', 'presonus studio one',
    'ableton live suite', 'fl studio mobile', 'koala sampler', 'serato studio',
    'magix music maker', 'dorico', 'sibelius', 'finale',
  ],
  'Electric guitar models': [
    'stratocaster', 'telecaster', 'les paul', 'sg', 'flying v', 'explorer', 'firebird',
    'jazzmaster', 'jaguar', 'mustang', 'es-335', '335', 'es-175', 'les paul junior',
    'les paul custom', 'les paul standard', 'rickenbacker 330', 'rickenbacker 360',
    'prs custom 24', 'prs se', 'ibanez rg', 'ibanez jem', 'ibanez js', 'superstrat',
    'gretsch white falcon', 'gretsch country gentleman', 'dan armstrong', 'firebird v',
    'thinline telecaster', 'starcaster', 'mustang bass', 'sg standard', 'sg junior',
    'les paul studio', 'nighthawk', 'esquire', 'broadcaster', 'duo jet', 'jet firebird',
    'jackson soloist', 'jackson dinky', 'charvel', 'schecter hellraiser', 'epiphone casino',
    'dean ml', 'randy rhoads', 'kramer baretta',
  ],
  'Potato chip brands': [
    'lays', 'ruffles', 'pringles', 'doritos', 'cheetos', 'kettle', 'kettle brand',
    'cape cod', 'utz', 'herrs', 'wise', 'tostitos', 'fritos', 'sun chips', 'popchips',
    'terra', 'dirty', 'miss vickies', 'walkers', 'tyrrells', 'pop chips', 'zapps',
    'bugles', 'funyuns', 'takis', 'munchos', 'jays', 'better made', 'old dutch',
    'golden flake', 'route 11', 'deep river', 'boulder canyon', 'good health',
    'lundberg', 'stacys', 'pipers', 'red rock deli', 'garden of eatin', 'snyders',
    'hunky dory', 'seabrook', 'mccoys', 'hula hoops', 'monster munch',
  ],
  'Popular snack cakes': [
    'twinkie', 'ding dong', 'ho ho', 'zinger', 'sno ball', 'swiss roll', 'oatmeal creme pie',
    'nutty buddy', 'star crunch', 'cosmic brownie', 'fudge round', 'honey bun', 'cupcake',
    'moon pie', 'devil dog', 'yodel', 'ring ding', 'funny bone', 'suzy q', 'donettes',
    'fruit pie', 'cherry pie', 'little debbie', 'nutty bar', 'zebra cake', 'cloud cake',
    'chocolate cupcake', 'fudge brownie', 'jelly roll', 'sno balls', 'coffee cake',
    'banana flip', 'cherry cordial', 'marshmallow pie', 'pecan spinwheel', 'raisin creme pie',
    'apple pie', 'cinnamon roll', 'crumb cake', 'gob', 'whoopie pie', 'ambrosia cake',
    'texas cinnamon', 'chocolate roll',
  ],
  'Popular salad dressings': [
    'ranch', 'italian', 'caesar', 'blue cheese', 'thousand island', 'french', 'balsamic',
    'balsamic vinaigrette', 'vinaigrette', 'honey mustard', 'russian', 'greek', 'poppy seed',
    'green goddess', 'catalina', 'buttermilk ranch', 'ginger', 'sesame', 'sesame ginger',
    'tahini', 'lemon vinaigrette', 'raspberry vinaigrette', 'red wine vinaigrette',
    'creamy italian', 'oil and vinegar', 'peppercorn ranch', 'chipotle ranch',
    'avocado', 'cilantro lime', 'ceasar', 'asian', 'miso', 'peanut', 'yogurt dressing',
    'dijon', 'roquefort', 'louis', 'green olive', 'sweet onion', 'bacon ranch',
    'buffalo ranch', 'apple cider vinaigrette', 'champagne vinaigrette', 'mustard vinaigrette',
  ],
  'Breakfast meats': [
    'bacon', 'sausage', 'ham', 'canadian bacon', 'scrapple', 'spam', 'chorizo',
    'corned beef hash', 'black pudding', 'turkey bacon', 'breakfast sausage', 'kielbasa',
    'pancetta', 'prosciutto', 'salami', 'linguica', 'souse', 'taylor ham', 'pork roll',
    'sausage patty', 'sausage link', 'turkey sausage', 'chicken sausage', 'blood sausage',
    'white pudding', 'bangers', 'streaky bacon', 'back bacon', 'gammon', 'lorne sausage',
    'liverwurst', 'braunschweiger', 'country ham', 'city ham', 'smoked sausage',
    'andouille', 'bratwurst', 'longganisa', 'tocino', 'goetta', 'hog jowl',
    'ham steak', 'fried spam', 'vienna sausage',
  ],
  'TV westerns': [
    'gunsmoke', 'bonanza', 'rawhide', 'the rifleman', 'maverick', 'wagon train',
    'have gun will travel', 'the virginian', 'deadwood', 'yellowstone', '1883', '1923',
    'longmire', 'godless', 'hell on wheels', 'the lone ranger', 'the big valley',
    'high chaparral', 'laramie', 'wanted dead or alive', 'the wild wild west',
    'kung fu', 'walker texas ranger', 'lonesome dove', 'dr quinn medicine woman',
    'little house on the prairie', 'daniel boone', 'davy crockett', 'cheyenne',
    'gunsmoke', 'the cisco kid', 'death valley days', 'branded', 'the high chaparral',
    'alias smith and jones', 'the young riders', 'centennial', 'how the west was won',
    'f troop', 'rango', 'westworld', 'the rebel', 'bat masterson', 'trackdown',
  ],
  'Sitcoms from the 90s': [
    'friends', 'seinfeld', 'frasier', 'home improvement', 'the fresh prince of bel-air',
    'fresh prince', 'roseanne', 'married with children', 'full house', 'family matters',
    'boy meets world', 'everybody loves raymond', 'that 70s show', 'will and grace',
    '3rd rock from the sun', 'mad about you', 'spin city', 'news radio', 'wings',
    'coach', 'the nanny', 'sabrina the teenage witch', 'the drew carey show',
    'just shoot me', 'dharma and greg', 'caroline in the city', 'suddenly susan',
    'ellen', 'murphy brown', 'cybill', 'martin', 'living single', 'the wayans bros',
    'sister sister', 'moesha', 'the jamie foxx show', 'in living color', 'grace under fire',
    'the john larroquette show', 'ned and stacey', 'the single guy', 'veronicas closet',
    'becker', 'malcolm and eddie', 'kenan and kel',
  ],
  'Bowling terms': [
    'strike', 'spare', 'turkey', 'gutter', 'gutter ball', 'split', 'frame', 'pin',
    'foul', 'hook', 'curve', 'approach', 'lane', 'pocket', 'brooklyn', 'baby split',
    'four bagger', 'clean game', 'perfect game', 'sandbagger', 'tap', 'sleeper',
    'washout', 'kingpin', 'deadwood', 'anchor', 'leadoff', 'pin action', 'bedposts',
    'double', 'triple', 'open frame', 'mark', 'handicap', 'crossover', 'dutch 200',
    'greek church', 'lily', 'sour apple', 'nose hit', 'ten in the pit', 'cherry',
    'creeper', 'dime store', 'field goal',
  ],
  'Brass instruments': [
    'trumpet', 'trombone', 'tuba', 'french horn', 'cornet', 'flugelhorn', 'euphonium',
    'bugle', 'sousaphone', 'baritone horn', 'piccolo trumpet', 'mellophone', 'alphorn',
    'wagner tuba', 'natural horn', 'pocket trumpet', 'bass trombone', 'contrabass tuba',
    'contrabass trombone', 'valve trombone', 'alto trombone', 'tenor horn', 'saxhorn',
    'cimbasso', 'ophicleide', 'serpent', 'cornett', 'post horn', 'conch', 'shofar',
    'didgeridoo', 'bass trumpet', 'soprano trombone', 'helicon', 'sackbut',
    'fiscorn', 'wagner tube', 'baroque trumpet', 'herald trumpet', 'slide trumpet',
    'marching baritone', 'susaphone', 'vuvuzela', 'lur',
  ],
  'Types of eggs': [
    'chicken egg', 'duck egg', 'quail egg', 'goose egg', 'ostrich egg', 'turkey egg',
    'emu egg', 'pheasant egg', 'guinea fowl egg', 'fried egg', 'scrambled egg',
    'poached egg', 'boiled egg', 'hard boiled', 'soft boiled', 'deviled egg', 'over easy',
    'over medium', 'over hard', 'sunny side up', 'eggs benedict', 'omelette', 'frittata',
    'quiche', 'century egg', 'salted egg', 'tea egg', 'pickled egg', 'coddled egg',
    'basted egg', 'shirred egg', 'scotch egg', 'caviar', 'roe', 'fish roe', 'salmon roe',
    'gull egg', 'plover egg', 'nog', 'balut', 'brown egg', 'white egg', 'free range egg',
    'egg white', 'egg yolk',
  ],
  'Dried fruits': [
    'raisin', 'prune', 'dried apricot', 'date', 'dried fig', 'dried cranberry', 'currant',
    'sultana', 'dried mango', 'dried pineapple', 'banana chip', 'dried apple', 'dried cherry',
    'dried blueberry', 'goji berry', 'dried coconut', 'dried papaya', 'dried peach',
    'dried pear', 'dried kiwi', 'dried strawberry', 'dried plum', 'jujube', 'dried persimmon',
    'dried apricots', 'candied ginger', 'dried guava', 'dried lychee', 'dried longan',
    'dried tomato', 'sun-dried tomato', 'dried cantaloupe', 'dried melon', 'dried orange',
    'dried tamarind', 'dried jackfruit', 'dried mulberry', 'dried elderberry',
    'dried blackberry', 'dried grapes', 'candied cherry', 'zante currant', 'dried rambutan',
    'freeze dried fruit',
  ],
  'Popular yogurt brands': [
    'chobani', 'yoplait', 'dannon', 'fage', 'oikos', 'activia', 'stonyfield', 'siggis',
    'noosa', 'greek gods', 'wallaby', 'brown cow', 'la yogurt', 'muller', 'tillamook',
    'two good', 'ratio', 'light and fit', 'go-gurt', 'danimals', 'skyr', 'icelandic provisions',
    'liberte', 'cabot', 'stonyfield organic', 'horizon', 'kite hill', 'silk', 'so delicious',
    'forager', 'lavva', 'nancys', 'straus', 'wallaby organic', 'yoplait light', 'trix yogurt',
    'yoplait whips', 'clover', 'maple hill', 'powerful yogurt', 'redwood hill', 'coyo',
    'petit filous', 'onken', 'rachels',
  ],
  'British sitcoms': [
    'fawlty towers', 'only fools and horses', 'blackadder', 'the office', 'the it crowd',
    'peep show', 'father ted', 'mr bean', 'keeping up appearances', 'are you being served',
    'allo allo', 'dads army', 'yes minister', 'yes prime minister', 'the young ones',
    'red dwarf', 'black books', 'spaced', 'the inbetweeners', 'gavin and stacey', 'miranda',
    'one foot in the grave', 'porridge', 'open all hours', 'some mothers do ave em',
    'the vicar of dibley', 'to the manor born', 'birds of a feather', 'the good life',
    'hi de hi', 'ever decreasing circles', 'bread', 'men behaving badly', 'the royle family',
    'gimme gimme gimme', 'coupling', 'the thick of it', 'the mighty boosh', 'toast of london',
    'friday night dinner', 'outnumbered', 'derry girls', 'the goes wrong show', 'ghosts',
    'still game',
  ],
  'Types of jerky': [
    'beef jerky', 'turkey jerky', 'chicken jerky', 'salmon jerky', 'bison jerky',
    'venison jerky', 'pork jerky', 'elk jerky', 'kangaroo jerky', 'ostrich jerky',
    'alligator jerky', 'tuna jerky', 'teriyaki jerky', 'peppered jerky', 'biltong',
    'droewors', 'buffalo jerky', 'lamb jerky', 'duck jerky', 'goose jerky', 'emu jerky',
    'wild boar jerky', 'reindeer jerky', 'yak jerky', 'crocodile jerky', 'shark jerky',
    'cod jerky', 'trout jerky', 'goat jerky', 'rabbit jerky', 'sriracha jerky',
    'honey jerky', 'carne seca', 'tofu jerky', 'mushroom jerky', 'jackfruit jerky',
    'seitan jerky', 'coconut jerky', 'banana jerky', 'ghost pepper jerky',
    'bacon jerky', 'chili jerky', 'smoked jerky', 'original jerky',
  ],
  'Roman gods': [
    'jupiter', 'juno', 'neptune', 'pluto', 'mars', 'venus', 'mercury', 'minerva',
    'apollo', 'diana', 'vulcan', 'vesta', 'ceres', 'bacchus', 'cupid', 'saturn',
    'janus', 'flora', 'faunus', 'fortuna', 'bellona', 'proserpina', 'aurora', 'sol',
    'luna', 'terra', 'victoria', 'liber', 'pomona', 'vertumnus', 'quirinus', 'ops',
    'juventas', 'aesculapius', 'somnus', 'nox', 'aeternitas', 'concordia', 'salus',
    'pax', 'discordia', 'invidia', 'nemesis', 'orcus', 'dis pater', 'lares', 'penates',
    'genius', 'silvanus', 'consus',
  ],
  'Greek heroes': [
    'heracles', 'hercules', 'achilles', 'odysseus', 'perseus', 'theseus', 'jason',
    'bellerophon', 'atalanta', 'ajax', 'diomedes', 'hector', 'aeneas', 'orpheus',
    'meleager', 'peleus', 'castor', 'pollux', 'oedipus', 'cadmus', 'orion', 'daedalus',
    'icarus', 'pirithous', 'nestor', 'menelaus', 'agamemnon', 'patroclus', 'philoctetes',
    'idomeneus', 'telamon', 'laertes', 'telemachus', 'neoptolemus', 'antilochus',
    'protesilaus', 'amphitryon', 'iolaus', 'hylas', 'admetus', 'peleus', 'triptolemus',
    'lynceus', 'zetes', 'calais', 'echion',
  ],
};
