// expansion2.js
// Second top-up pass: categories whose first-pass supplements overlapped too
// heavily with the base sets to clear 200, plus the finite-ish domains
// (Pokemon Gen 1 = 151 species, Car brands) which need reasonable misspellings
// and variants to get there. Same union-merge as expansion.js. All lowercase.
module.exports = {
  'Pokemon from Gen 1': new Set([
    'nidoran male', 'nidoran female', 'nidoran m', 'nidoran f', 'mr. mime', 'farfetch d', "farfetch'd", 'pikatchu', 'pickachu', 'charizar', 'charzard', 'charizards', 'squirttle', 'squirtel', 'bulbasour', 'bulbasor', 'venasaur', 'venusuar', 'blastiose', 'blastios', 'geodud', 'geodude', 'gengar', 'genghar', 'machamp', 'machomp', 'snorlax', 'snorlaxx', 'eevee', 'evee', 'eve', 'jigglypuf', 'jiggly puff', 'wigglytuf', 'meowth', 'meoth', 'psyduck', 'psyduk', 'magikarp', 'magicarp', 'gyrados', 'gyarodos', 'dragonite', 'dragonight', 'mewtwo', 'mew two', 'mew 2', 'arcanine', 'arcanin', 'alakazam', 'alakazaam', 'vulpix', 'vulpex', 'ninetales', 'ninetails', 'pidgey', 'pidgy', 'rattata', 'ratata', 'raticate', 'spearow', 'fearow', 'zubat', 'golbat', 'oddish', 'gloom', 'vileplume', 'poliwag', 'poliwhirl', 'poliwrath', 'tentacool', 'tentacruel', 'slowpoke', 'slowbro', 'grimer', 'muk', 'shellder', 'cloyster', 'cubone', 'marowak', 'koffing', 'weezing', 'rhyhorn', 'rhydon', 'chansey', 'kangaskhan', 'horsea', 'seadra', 'goldeen', 'seaking', 'staryu', 'starmie', 'scyther', 'jynx', 'electabuzz', 'magmar', 'pinsir', 'tauros', 'lapras', 'ditto', 'porygon', 'omanyte', 'omastar', 'kabuto', 'kabutops', 'aerodactyl', 'articuno', 'zapdos', 'moltres', 'dratini', 'dragonair', 'pikatchew', 'charizerd', 'squirtal', 'bulbisaur', 'venosaur', 'blastios', 'geadude', 'machaump', 'snorelax', 'eeveee', 'mewto', 'mew tree', 'gyaragos', 'magicarpe', 'onyx', 'abra pokemon', 'kadabra', 'haunter', 'gastly', 'clefary', 'wigglytuf pokemon', 'nidoqueen', 'nidoking', 'primeape', 'rapidash', 'exeggutor', 'cubone pokemon', 'lickitung pokemon', 'tangela pokemon', 'electrode pokemon', 'voltorb pokemon'
  ]),
  'Car brands': new Set([
    'toyata', 'toyoda', 'chevvy', 'chevorlet', 'mercedez', 'mercedez benz', 'porsha', 'porshe', 'porche', 'lambo', 'lamborgini', 'lamborghinni', 'lambourghini', 'ferarri', 'ferari', 'ferrarri', 'volkswagon', 'hyundia', 'hyandai', 'mitsibishi', 'infinity', 'accura', 'subbaru', 'mazada', 'hondda', 'nisssan', 'audii', 'beemer', 'bmw', 'benz', 'vw', 'rimac', 'ineos', 'vinfast', 'karma', 'aptera', 'canoo', 'bollinger', 'faraday future', 'xpeng', 'li auto', 'zeekr', 'lynk and co', 'cupra', 'abarth', 'ds automobiles', 'daihatsu', 'proton', 'perodua', 'ssangyong', 'tvr', 'noble', 'ariel', 'spyker', 'hennessey', 'saleen', 'shelby', 'roush', 'ruf', 'brabus', 'alpina', 'edsel', 'desoto', 'hudson', 'nash', 'willys', 'international harvester', 'freightliner', 'kenworth', 'peterbilt', 'mack', 'volvo trucks', 'scania', 'man', 'iveco', 'tatra', 'zil', 'gaz', 'uaz', 'moskvitch', 'trabant', 'wartburg', 'borgward', 'auto union', 'horch', 'wanderer', 'panhard', 'simca', 'talbot', 'rover', 'austin', 'morris', 'triumph', 'mg', 'sunbeam', 'hillman', 'humber', 'riley', 'wolseley'
  ]),
  'Things at a middle school dance': new Set([
    'a punch bowl', 'spiked punch rumors', 'a dj', 'a bad dj', 'a smoke machine', 'a disco ball', 'flashing lights', 'strobe lights', 'a gym floor', 'streamers', 'balloons', 'a balloon arch', 'a photo booth', 'a backdrop', 'a banner', 'a theme', 'an under the sea theme', 'a masquerade theme', 'chaperones', 'a teacher chaperone', 'the vice principal watching', 'kids on their phones', 'phones out', 'a circle of kids', 'a dance circle', 'no one dancing', 'kids against the wall', 'wallflowers', 'boys on one side', 'girls on the other side', 'an awkward slow dance', 'a slow song', 'arms length dancing', 'the cha cha slide', 'cupid shuffle', 'the cotton eye joe', 'the macarena', 'the wobble', 'the whip', 'the nae nae', 'a conga line', 'the limbo', 'a dance off', 'a sweaty gym', 'a stinky gym', 'too much cologne', 'too much body spray', 'axe body spray', 'a snack table', 'cookies', 'chips', 'soda', 'water bottles', 'a cash box', 'ticket sales', 'glow sticks', 'glow necklaces', 'a coat pile', 'a bathroom break crew', 'drama', 'a breakup', 'a first dance', 'a crush', 'a love note', 'getting asked to dance', 'rejection', 'a group selfie', 'a slow song panic', 'someone crying in the bathroom', 'the last song', 'a teacher saying spread out', 'leave room for jesus', 'a flash mob attempt', 'requests the dj ignores', 'a song everyone screams', 'the lights coming on', 'parents waiting outside', 'a teacher djing', 'a parent volunteer', 'a sign in sheet', 'a coat check', 'sweaty palms', 'a hype song', 'a line dance', 'an awkward shuffle', 'a dance battle', 'a moonwalk attempt', 'someone doing the worm', 'the worm', 'dabbing', 'the floss', 'flossing', 'a soul train line', 'a kid breakdancing', 'a sprinkler dance', 'a fist pump', 'a glow stick necklace', 'a ring pop', 'a corsage', 'a group photo line', 'a hallway hangout', 'a teacher saying break it up'
  ]),
  'Fast food chains': new Set([
    'mcdonalds', 'mcdonald s', 'mickey ds', 'micky ds', 'bk', 'burger king', 'wendys', 'wendy s', 'taco bell', 'kfc', 'chic fil a', 'chick fila', 'chickfila', 'popeyes', 'subway', 'jimmy johns', 'jersey mikes', 'firehouse subs', 'quiznos', 'potbelly', 'wingstop', 'buffalo wild wings', 'b dubs', 'wings to go', 'wing street', 'hooters', 'twin peaks', 'sonic drive in', 'a and w', 'dq', 'dairy queen', 'in and out', 'innout', 'whataburger', 'five guys', 'shake shack', 'smashburger', 'fuddruckers', 'red robin', 'culvers', 'jack in the box', 'carls jr', 'hardees', 'del taco', 'taco johns', 'taco bueno', 'taco cabana', 'white castle', 'krystal', 'checkers', 'rallys', 'raising canes', 'canes', 'zaxbys', 'bojangles', 'churchs', 'churchs chicken', 'bonchon', 'pollo tropical', 'el pollo loco', 'chipotle', 'qdoba', 'moes', 'moes southwest', 'baja fresh', 'rubios', 'long john silvers', 'captain ds', 'arthur treachers', 'steak n shake', 'freddys', 'portillos', 'cookout', 'biscuitville', 'bojangles famous', 'runza', 'braums', 'wienerschnitzel', 'nathans', 'nathans famous', 'auntie annes', 'cinnabon', 'pretzel time', 'wetzels pretzels', 'mrs fields', 'great american cookies', 'baskin robbins', 'cold stone', 'dippin dots', 'orange julius', 'jamba juice', 'smoothie king', 'tropical smoothie', 'panera', 'au bon pain', 'corner bakery', 'noodles and company', 'pei wei', 'panda express', 'pf changs to go', 'blaze pizza', 'mod pizza', 'marcos pizza', 'cicis', 'sbarro', 'fazolis', 'the habit', 'habit burger', 'farmer boys', 'waba grill', 'pita pit', 'which wich', 'schlotzskys', 'blimpie', 'togos', 'mcalisters deli', 'newks', 'jasons deli', 'crown fried chicken', 'kennedy fried chicken', 'lees famous recipe', 'golden chick', 'slim chickens', 'pdq', 'huddle house', 'waffle house', 'dennys', 'ihop', 'cracker barrel', 'golden corral', 'sizzler', 'ci ci s pizza', 'round table pizza', 'mountain mikes', 'jets pizza', 'hungry howies', 'donatos', 'papa murphys'
  ]),
  'Things with a drive-through': new Set([
    'a coffee shop', 'a fast food joint', 'a taco stand', 'a burger joint', 'a donut shop', 'a pharmacy window', 'a bank drive up', 'a drive up atm', 'a car wash tunnel', 'an oil change', 'a quick lube', 'a flu shot clinic', 'a covid test site', 'a christmas lights display', 'a safari park', 'a drive thru zoo', 'a drive in movie', 'a fireworks stand', 'a pumpkin patch', 'a haunted house', 'a wildlife safari', 'a national park gate', 'a toll booth', 'a parking garage gate', 'a recycling center', 'a food bank', 'a pet food store', 'a tobacco outlet', 'a dairy barn', 'a milk barn', 'a smoothie shack', 'a boba shop', 'a coffee hut', 'a coffee kiosk', 'a beer barn', 'a bottle shop', 'a butcher', 'a bbq joint', 'a chicken shack', 'a seafood shack', 'a hot dog stand', 'a pretzel stand', 'an ice cream stand', 'a frozen custard stand', 'a shaved ice stand', 'a snow cone stand', 'a lemonade stand', 'a flower shop', 'a wedding chapel', 'a funeral viewing', 'a prayer booth', 'a confession booth', 'a library pickup', 'a grocery pickup', 'a curbside pickup', 'a package drop', 'a dry cleaner', 'a photo lab', 'a key copy kiosk'
  ]),
  "Things in a 2010 kid's bedroom": new Set([
    'an itouch', 'an ipod classic', 'a click wheel ipod', 'a shuffle', 'a nano', 'an aux cord', 'a cd player', 'a boombox', 'a portable dvd player', 'a wii fit board', 'a wii fit', 'a balance board', 'a kinect', 'a guitar hero set', 'a rock band drum set', 'a dance dance revolution mat', 'a ddr mat', 'club penguin on the family computer', 'a runescape account', 'neopets', 'a neopets account', 'poptropica', 'cool math games', 'an aim screen name', 'aim', 'a webcam on the imac', 'a chunky imac', 'a dell laptop', 'a desktop tower', 'silly bandz everywhere', 'crazy bandz', 'bakugan arena', 'a bakugan card', 'a yugioh deck', 'pokemon cards', 'a binder of cards', 'a beados set', 'aquabeads', 'shrinky dinks', 'a easy bake oven', 'a sky dancer', 'a betty spaghetty', 'a polly pocket', 'a tech deck', 'finger skateboards', 'a stomp rocket', 'a moon shoes', 'a pogo stick', 'a scooter', 'a ripstik', 'a wii sports disc', 'mario galaxy', 'a ds lite', 'a nintendogs game', 'a cooking mama game', 'an ed hardy shirt', 'an aeropostale shirt', 'an abercrombie shirt', 'a hollister shirt', 'jansport backpack', 'a justice outfit', 'a claires necklace', 'a mood ring', 'a webkinz tag', 'a club penguin plush', 'glow stars on the ceiling', 'a chalkboard wall', 'a corkboard', 'a friendship bracelet kit'
  ]),
  'First things you do when you wake up': new Set([
    'check the group chat', 'reply to snaps', 'open snapchat', 'send streaks', 'keep my streaks', 'check my dms', 'check whatsapp', 'reply to my crush', 'check if he texted', 'check if she texted', 'set another alarm', 'snooze three times', 'lie there for an hour', 'scroll for an hour', 'watch a youtube video', 'put on a podcast', 'play music', 'turn on spotify', 'check my screen time', 'regret staying up late', 'check my fantasy team', 'check the scores', 'check stocks', 'check crypto', 'look at memes', 'send a meme', 'check the family group chat', 'ignore my alarm', 'throw my phone', 'cover my eyes', 'hide from the sun', 'pull the blanket over my head', 'beg for five more minutes', 'negotiate with myself', 'check what i missed', 'see who viewed my story', 'post a good morning story', 'check my notes', 'check my reminders', 'remember something i forgot', 'panic about a test', 'remember an assignment', 'check the bus time', 'check google classroom', 'log into canvas', 'check my grades', 'open the blinds', 'let the dog out', 'start the coffee', 'feed myself', 'grab a snack', 'chug water', 'take a deep breath', 'sit on the edge of the bed', 'doomscroll in bed', 'check the date', 'realize its a weekday', 'wish it was saturday'
  ]),
  'Excuses for not texting back': new Set([
    'i was in the shower', 'i was asleep already', 'my phone was upstairs', 'i put it on do not disturb', 'i muted the chat', 'i muted you by accident', 'i was at practice', 'i was at rehearsal', 'i was at church', 'i was at dinner', 'i was helping my mom', 'i was doing chores', 'i was cleaning', 'i was cooking', 'i was on the phone', 'i was on a call', 'my hands were full', 'i was carrying stuff', 'i forgot to hit send', 'it was in my drafts', 'i typed it but didnt send', 'i thought i sent it', 'i swear it sent', 'my phone restarted', 'my phone was updating', 'i had no charger', 'i was at one percent', 'my screen broke', 'i cracked my screen', 'i dropped it in the toilet', 'i dropped it in water', 'i lost my phone in my room', 'i couldnt find my phone', 'it fell under my bed', 'i left it in my locker', 'i left it in my bag', 'i was studying for finals', 'i had a big test', 'i was grinding homework', 'i was locked in', 'i was focused', 'i needed a break from my phone', 'i was doing a digital detox', 'i was touching grass', 'i was outside', 'i had no service in the building', 'no signal at the game', 'i was at a concert', 'i was at the movies', 'phone was off for the movie', 'i was driving home', 'i was on the bus', 'i was at work the whole shift'
  ]),
  'Things confiscated by a teacher': new Set([
    'an apple watch', 'a smart watch', 'a switch lite', 'a 3ds', 'a portable charger', 'an aux cord', 'a bluetooth speaker', 'a mini speaker', 'a phone on the desk', 'a second phone', 'a burner phone', 'a calculator with games', 'a graphing calculator', 'a deck of uno cards', 'uno cards', 'a magic 8 ball', 'a fidget ring', 'a infinity cube', 'a pop tube', 'a squishmallow', 'a squishy', 'a stress toy', 'a clicker pen', 'a clicky pen', 'a four color pen', 'a glitter pen', 'a scented marker', 'scented markers', 'a juul', 'a disposable vape', 'a puff bar', 'a pack of gum', 'a bag of hot cheetos', 'a takis bag', 'a candy stash', 'a lollipop', 'a sucker', 'a ring pop', 'a airhorn', 'a air horn', 'a noise maker', 'a party popper', 'a confetti popper', 'a rubber chicken', 'a finger skateboard', 'a tech deck', 'a beyblade launcher', 'a marble run', 'a slinky', 'a koosh ball', 'a nerf football', 'a foam ball', 'a paper fortune teller', 'a cootie catcher', 'a flip book', 'a mini whiteboard', 'a laser cat toy', 'a remote', 'a tv remote', 'a car key fob', 'a skateboard tool', 'a vape pen', 'a hydro flask sticker collection'
  ]),
  'Subscription services': new Set([
    'crunchyroll premium', 'vrv', 'shudder', 'mubi', 'criterion channel', 'britbox', 'acorn tv', 'curiositystream', 'nebula', 'dropout', 'philo', 'frndly tv', 'directv stream', 'apple arcade', 'google play pass', 'humble bundle monthly', 'humble choice', 'nvidia geforce now', 'playstation now', 'amazon kids plus', 'epic games store', 'spotify premium', 'spotify duo', 'spotify family', 'youtube premium family', 'apple one', 'apple news plus', 'apple fitness', 'calm', 'headspace', 'noom', 'myfitnesspal premium', 'strava', 'whoop', 'peloton app', 'audible plus', 'scribd', 'everand', 'blinkist', 'the athletic', 'nba league pass', 'nfl plus', 'mlb tv', 'espn bundle', 'wwe network', 'twitch sub', 'discord nitro', 'nitro', 'patreon membership', 'substack', 'medium membership', 'new york times games', 'duolingo super', 'babbel', 'rosetta stone', 'brilliant', 'chegg', 'course hero', 'quizlet plus', 'grammarly premium', 'notion plus', 'evernote', 'icloud storage', 'google one storage', 'amazon prime music', 'sirius xm', 'siriusxm', 'a meal kit box', 'a snack box', 'a beauty box', 'a sock subscription'
  ]),
  "Ways to get sent to the principal's office": new Set([
    'flipping off a teacher', 'cursing out a teacher', 'throwing food in the cafeteria', 'starting a cafeteria food fight', 'shoving a kid', 'pushing someone', 'tripping someone on purpose', 'a hallway fight', 'wrestling in the hall', 'running in the halls', 'screaming in class', 'a screaming match', 'a shouting match', 'throwing a textbook', 'flipping a table', 'kicking a door', 'punching a locker', 'slamming a locker', 'spray painting a wall', 'tagging the bathroom', 'clogging a toilet on purpose', 'flooding the bathroom', 'setting off the sprinklers', 'a stink bomb in the hall', 'a fake fire alarm', 'a bomb threat joke', 'a threatening joke', 'a tiktok challenge gone wrong', 'the devious lick', 'stealing soap dispensers', 'stealing a stop sign', 'vandalizing a desk', 'carving into a desk', 'drawing on the walls', 'cheating with a phone', 'taking a photo of the test', 'sharing test answers', 'selling answers', 'forging a hall pass', 'skipping with a fake pass', 'leaving school grounds', 'jumping the fence', 'showing up drunk', 'showing up high', 'bringing alcohol', 'bringing a vape to class', 'getting caught vaping again', 'lighting something on fire', 'a science lab fire', 'mixing chemicals', 'throwing a chair across the room', 'cyberbullying a classmate', 'making a fake account', 'spreading a rumor online', 'recording a teacher', 'posting a teacher online', 'mooning the class', 'streaking', 'a prank war', 'egging the school'
  ]),
  'Apps on your phone right now': new Set([
    'be real', 'bereal', 'threads', 'bluesky', 'mastodon', 'lemon8', 'pinterest lite', 'vsco', 'snapseed', 'capcut', 'inshot', 'splice', 'photoroom', 'remini', 'lapse', 'dispo', 'locket', 'locket widget', 'noteit', 'gas', 'yik yak', 'monkey', 'omegle', 'wizz', 'hoop', 'tinder', 'hinge', 'bumble', 'snap map', 'find my friends', 'life360', 'venmo', 'cash app', 'apple wallet', 'chime', 'cashapp', 'robinhood', 'webull', 'coinbase', 'acorns', 'doordash', 'ubereats', 'postmates', 'instacart', 'starbucks app', 'chipotle app', 'dominos app', 'amazon shopping', 'amazon prime', 'shein app', 'temu app', 'depop', 'mercari', 'poshmark', 'goat', 'stockx', 'nike snkrs', 'snkrs', 'spotify', 'apple music', 'shazam', 'genius', 'soundcloud', 'youtube music', 'wattpad', 'webtoon', 'ao3', 'goodreads', 'libby', 'duolingo', 'photomath', 'symbolab', 'chatgpt', 'gemini', 'character ai', 'snapchat plus', 'discord', 'reddit', 'imgur', 'twitch', 'kick', 'clash royale', 'brawl stars', 'clash of clans', 'pokemon go', 'monopoly go', 'royal match', 'candy crush saga', 'subway surfers', 'roblox', 'minecraft', 'stumble guys', '8 ball pool', 'flashlight', 'measure', 'compass', 'translate', 'google translate'
  ]),
  'Excuses for not doing your homework': new Set([
    'i didnt understand the assignment', 'no one explained it', 'i was confused', 'the directions made no sense', 'i did the wrong assignment', 'i did monday s instead', 'i thought it was group work', 'my partner had it', 'my group never met', 'my tutor cancelled', 'i had a migraine', 'i had a headache', 'my eyes hurt from screens', 'i had too much homework', 'i ran out of time with all my classes', 'i had three tests to study for', 'i had a project due', 'i had practice till nine', 'i had a game out of town', 'i got home at midnight', 'i had a recital', 'i had a competition', 'i was at a tournament', 'i had work till close', 'i picked up an extra shift', 'i was babysitting my siblings', 'i had to cook dinner', 'i had to watch my brother', 'we had a power outage', 'the internet was out all night', 'my hotspot ran out', 'the assignment didnt post', 'it wasnt in google classroom', 'the link was broken', 'the pdf wouldnt open', 'i couldnt access the file', 'the document was view only', 'it logged me out', 'my account got locked', 'i forgot my login', 'i forgot my chromebook', 'my chromebook didnt charge', 'i left my charger at school', 'my laptop got a virus', 'autosave failed', 'it didnt save my work', 'i accidentally deleted it', 'my little cousin closed the tab'
  ]),
  'Things you do when the WiFi goes out': new Set([
    'check every other device', 'see if the phone works', 'switch to data', 'eat your data plan alive', 'turn the hotspot on for everyone', 'become the family hotspot', 'restart the whole house', 'flip every breaker', 'unplug the cable box', 'reboot the modem and router', 'hold the reset button', 'call tech support', 'sit on hold for an hour', 'argue with a robot', 'check downdetector on data', 'refresh the speed test', 'run a speed test', 'walk around looking for bars', 'stand by the window', 'go sit in the driveway', 'mooch the neighbors wifi', 'drive somewhere with wifi', 'finally do the dishes', 'finally clean', 'start a conversation', 'play a board game', 'find a deck of cards', 'do a puzzle', 'go for a walk', 'pet the dog out of boredom', 'reorganize your desk', 'charge all your devices', 'update your apps later', 'stare longingly at the router', 'whisper please to the router', 'unplug it for thirty seconds', 'count to thirty', 'plug it back in', 'watch the lights blink', 'wait for the green light', 'lose your whole game rank', 'get kicked from the match', 'rage at the lag', 'blame whoevers streaming'
  ])
};
