// categoryAnswers/expand-econ-4.js  (data/accept-lists — batch 4, broad expansion)
// Union-merged supplement. Real members + variants only, <=3 words, deduped.
module.exports = {
  'Birds': new Set([
    'robin', 'sparrow', 'crow', 'raven', 'blue jay', 'cardinal', 'finch', 'goldfinch', 'chickadee',
    'wren', 'nuthatch', 'woodpecker', 'hummingbird', 'swallow', 'starling', 'mockingbird', 'oriole',
    'warbler', 'thrush', 'bluebird', 'pigeon', 'dove', 'mourning dove', 'seagull', 'gull', 'tern',
    'pelican', 'cormorant', 'heron', 'great blue heron', 'egret', 'crane', 'stork', 'flamingo', 'ibis',
    'spoonbill', 'duck', 'mallard', 'goose', 'canada goose', 'swan', 'mute swan', 'loon', 'grebe', 'coot',
    'moorhen', 'kingfisher', 'eagle', 'bald eagle', 'golden eagle', 'hawk', 'red-tailed hawk', 'falcon',
    'peregrine falcon', 'kestrel', 'osprey', 'vulture', 'turkey vulture', 'condor', 'owl', 'barn owl',
    'great horned owl', 'snowy owl', 'screech owl', 'kite', 'harrier', 'buzzard', 'chicken', 'rooster',
    'hen', 'turkey', 'peacock', 'peahen', 'pheasant', 'quail', 'partridge', 'grouse', 'guinea fowl',
    'ostrich', 'emu', 'cassowary', 'rhea', 'kiwi', 'penguin', 'emperor penguin', 'puffin', 'albatross',
    'petrel', 'booby', 'frigatebird', 'gannet', 'parrot', 'macaw', 'cockatoo', 'cockatiel', 'parakeet',
    'budgie', 'budgerigar', 'lovebird', 'conure', 'lorikeet', 'toucan', 'hornbill', 'roadrunner', 'cuckoo',
    'nightingale', 'lark', 'skylark', 'meadowlark', 'pipit', 'wagtail', 'swift', 'martin', 'purple martin',
    'phoebe', 'flycatcher', 'kingbird', 'shrike', 'vireo', 'tanager', 'grosbeak', 'bunting', 'towhee',
    'junco', 'chaffinch', 'siskin', 'redpoll', 'crossbill', 'waxwing', 'cedar waxwing', 'catbird',
    'brown thrasher', 'grackle', 'cowbird', 'blackbird', 'red-winged blackbird', 'magpie', 'jackdaw', 'rook',
    'jay', 'stellers jay', 'scrub jay', 'nutcracker', 'chough', 'sandpiper', 'plover', 'killdeer',
    'oystercatcher', 'avocet', 'stilt', 'curlew', 'godwit', 'snipe', 'woodcock', 'lapwing', 'turnstone',
    'dunlin', 'sanderling', 'phalarope', 'rail', 'bittern', 'anhinga', 'merganser', 'teal', 'wigeon',
    'pintail', 'shoveler', 'canvasback', 'redhead', 'bufflehead', 'goldeneye', 'eider', 'scoter',
    'ptarmigan', 'prairie chicken', 'sage grouse', 'bobwhite', 'chukar', 'sunbird', 'weaver', 'bulbul',
    'myna', 'drongo', 'bee-eater', 'roller', 'hoopoe', 'nightjar', 'whip-poor-will', 'secretary bird',
    'shoebill', 'jacana', 'quetzal', 'bird of paradise', 'lyrebird', 'kookaburra', 'lorikeet',
  ]),
  'Human infectious diseases': new Set([
    'flu', 'influenza', 'common cold', 'cold', 'covid', 'covid-19', 'coronavirus', 'pneumonia',
    'bronchitis', 'tuberculosis', 'tb', 'strep throat', 'strep', 'whooping cough', 'pertussis',
    'diphtheria', 'tetanus', 'measles', 'mumps', 'rubella', 'chickenpox', 'chicken pox', 'shingles',
    'smallpox', 'polio', 'poliomyelitis', 'hepatitis', 'hepatitis a', 'hepatitis b', 'hepatitis c',
    'hiv', 'aids', 'malaria', 'dengue', 'dengue fever', 'yellow fever', 'zika', 'zika virus', 'ebola',
    'cholera', 'typhoid', 'typhoid fever', 'dysentery', 'salmonella', 'e coli', 'listeria', 'botulism',
    'norovirus', 'rotavirus', 'gastroenteritis', 'stomach flu', 'food poisoning', 'lyme disease', 'lyme',
    'rabies', 'anthrax', 'plague', 'bubonic plague', 'the black death', 'leprosy', 'scarlet fever',
    'rheumatic fever', 'meningitis', 'encephalitis', 'sepsis', 'staph infection', 'mrsa', 'gangrene',
    'syphilis', 'gonorrhea', 'chlamydia', 'herpes', 'hpv', 'genital warts', 'trichomoniasis', 'candida',
    'yeast infection', 'thrush', 'ringworm', 'athletes foot', 'jock itch', 'impetigo', 'cellulitis',
    'conjunctivitis', 'pink eye', 'ear infection', 'sinus infection', 'sinusitis', 'tonsillitis', 'croup',
    'rsv', 'mononucleosis', 'mono', 'epstein-barr', 'cytomegalovirus', 'west nile virus', 'chikungunya',
    'hantavirus', 'lassa fever', 'marburg', 'sars', 'mers', 'bird flu', 'avian flu', 'swine flu',
    'h1n1', 'legionnaires disease', 'q fever', 'brucellosis', 'leptospirosis', 'toxoplasmosis',
    'giardiasis', 'cryptosporidiosis', 'amoebiasis', 'schistosomiasis', 'hookworm', 'tapeworm', 'roundworm',
    'pinworm', 'trichinosis', 'elephantiasis', 'river blindness', 'sleeping sickness', 'chagas disease',
    'leishmaniasis', 'typhus', 'rocky mountain spotted fever', 'scabies', 'lice', 'head lice',
    'hand foot and mouth', 'fifth disease', 'roseola', 'molluscum', 'warts', 'cold sores', 'oral herpes',
    'valley fever', 'histoplasmosis', 'aspergillosis', 'candidiasis', 'coccidioidomycosis', 'monkeypox',
    'mpox', 'norovirus', 'campylobacter', 'shigella', 'giardia', 'whooping cough', 'measles',
  ]),
  'Minecraft blocks': new Set([
    'dirt', 'grass block', 'stone', 'cobblestone', 'sand', 'gravel', 'clay', 'sandstone', 'gold ore',
    'iron ore', 'coal ore', 'diamond ore', 'redstone ore', 'lapis ore', 'lapis lazuli ore', 'emerald ore',
    'copper ore', 'nether gold ore', 'ancient debris', 'bedrock', 'obsidian', 'netherrack', 'soul sand',
    'soul soil', 'glowstone', 'end stone', 'purpur block', 'quartz block', 'nether quartz ore', 'oak planks',
    'spruce planks', 'birch planks', 'jungle planks', 'acacia planks', 'dark oak planks', 'oak log', 'oak wood',
    'spruce log', 'birch log', 'jungle log', 'acacia log', 'dark oak log', 'mangrove log', 'cherry log',
    'oak leaves', 'spruce leaves', 'birch leaves', 'glass', 'glass pane', 'stained glass', 'wool', 'white wool',
    'black wool', 'red wool', 'blue wool', 'green wool', 'crafting table', 'furnace', 'blast furnace', 'smoker',
    'chest', 'ender chest', 'trapped chest', 'barrel', 'shulker box', 'hopper', 'dispenser', 'dropper',
    'observer', 'piston', 'sticky piston', 'redstone', 'redstone block', 'redstone lamp', 'redstone torch',
    'repeater', 'comparator', 'lever', 'button', 'pressure plate', 'tripwire hook', 'note block', 'jukebox',
    'tnt', 'bookshelf', 'lectern', 'enchanting table', 'anvil', 'grindstone', 'stonecutter', 'loom',
    'cartography table', 'fletching table', 'smithing table', 'brewing stand', 'cauldron', 'beacon',
    'conduit', 'bed', 'torch', 'lantern', 'soul lantern', 'campfire', 'soul campfire', 'ladder', 'scaffolding',
    'fence', 'fence gate', 'wall', 'cobblestone wall', 'door', 'iron door', 'trapdoor', 'stairs', 'slab',
    'bricks', 'brick block', 'stone bricks', 'mossy cobblestone', 'mossy stone bricks', 'cracked stone bricks',
    'chiseled stone bricks', 'nether bricks', 'red nether bricks', 'prismarine', 'sea lantern', 'sponge',
    'wet sponge', 'ice', 'packed ice', 'blue ice', 'snow', 'snow block', 'pumpkin', 'carved pumpkin',
    'jack o lantern', 'melon', 'hay bale', 'target', 'lodestone', 'respawn anchor', 'crying obsidian',
    'magma block', 'blackstone', 'basalt', 'polished basalt', 'gilded blackstone', 'warped planks',
    'crimson planks', 'nether wart block', 'shroomlight', 'honeycomb block', 'honey block', 'slime block',
    'dried kelp block', 'terracotta', 'glazed terracotta', 'concrete', 'concrete powder', 'coarse dirt',
    'podzol', 'mycelium', 'farmland', 'grass path', 'bone block', 'amethyst block', 'budding amethyst',
    'calcite', 'tuff', 'dripstone block', 'moss block', 'azalea', 'deepslate', 'cobbled deepslate',
    'reinforced deepslate', 'sculk', 'sculk sensor', 'sculk catalyst', 'sculk shrieker',
  ]),
  'Human bones': new Set([
    'skull', 'cranium', 'mandible', 'jaw', 'jawbone', 'maxilla', 'nasal bone', 'zygomatic', 'cheekbone',
    'frontal bone', 'parietal bone', 'temporal bone', 'occipital bone', 'sphenoid', 'ethmoid', 'hyoid',
    'vertebrae', 'vertebra', 'spine', 'spinal column', 'cervical vertebrae', 'thoracic vertebrae',
    'lumbar vertebrae', 'atlas', 'axis', 'sacrum', 'coccyx', 'tailbone', 'rib', 'ribs', 'rib cage',
    'sternum', 'breastbone', 'clavicle', 'collarbone', 'scapula', 'shoulder blade', 'humerus', 'radius',
    'ulna', 'carpals', 'metacarpals', 'phalanges', 'finger bones', 'wrist bones', 'scaphoid', 'lunate',
    'trapezium', 'trapezoid', 'capitate', 'hamate', 'pisiform', 'triquetrum', 'pelvis', 'hip bone', 'ilium',
    'ischium', 'pubis', 'femur', 'thigh bone', 'patella', 'kneecap', 'tibia', 'shinbone', 'shin bone',
    'fibula', 'tarsals', 'metatarsals', 'calcaneus', 'heel bone', 'talus', 'navicular', 'cuboid',
    'cuneiform', 'malleus', 'incus', 'stapes', 'hammer', 'anvil', 'stirrup', 'toe bones', 'foot bones',
    'sacroiliac', 'lacrimal bone', 'palatine bone', 'vomer', 'inferior nasal concha', 'floating ribs',
    'true ribs', 'false ribs', 'manubrium', 'xiphoid process', 'acromion', 'olecranon', 'styloid process',
    'greater trochanter', 'lesser trochanter', 'medial malleolus', 'lateral malleolus', 'coracoid process',
    'glenoid', 'iliac crest', 'ischial tuberosity',
  ]),
  'Greek monsters and beasts': new Set([
    'medusa', 'the minotaur', 'minotaur', 'cyclops', 'the cyclops', 'polyphemus', 'the hydra', 'hydra',
    'lernaean hydra', 'cerberus', 'the chimera', 'chimera', 'the sphinx', 'sphinx', 'pegasus', 'the harpies',
    'harpy', 'harpies', 'sirens', 'the sirens', 'scylla', 'charybdis', 'the gorgons', 'gorgon', 'stheno',
    'euryale', 'the sphinx', 'echidna', 'typhon', 'the nemean lion', 'nemean lion', 'the ceryneian hind',
    'ceryneian hind', 'the erymanthian boar', 'erymanthian boar', 'stymphalian birds', 'the cretan bull',
    'cretan bull', 'the mares of diomedes', 'geryon', 'the caucasian eagle', 'ladon', 'the colchian dragon',
    'talos', 'the graeae', 'graeae', 'lamia', 'empusa', 'the manticore', 'manticore', 'griffin', 'gryphon',
    'the centaurs', 'centaur', 'chiron', 'nessus', 'the satyrs', 'satyr', 'pan', 'silenus', 'the gigantes',
    'giants', 'the cyclopes', 'the hecatoncheires', 'the furies', 'furies', 'erinyes', 'the moirai',
    'ophiotaurus', 'the teumessian fox', 'campe', 'python', 'the calydonian boar', 'calydonian boar',
    'argus', 'argus panoptes', 'the sphinx of thebes', 'orthrus', 'phorcys', 'ceto', 'the keres',
    'the golden fleece ram', 'chrysaor', 'the caucasian eagle', 'colchian dragon', 'the nemean lion',
    'the crommyonian sow', 'periphetes', 'sinis', 'sciron', 'cercyon', 'procrustes', 'the sea serpent',
    'ketos', 'the dragon of ares', 'aello', 'ocypete', 'celaeno', 'the stymphalian birds',
  ]),
  'Star Wars Planets': new Set([
    'tatooine', 'coruscant', 'naboo', 'hoth', 'endor', 'dagobah', 'bespin', 'kamino', 'geonosis', 'mustafar',
    'yavin', 'yavin 4', 'alderaan', 'kashyyyk', 'utapau', 'kessel', 'jakku', 'takodana', 'starkiller base',
    'd\'qar', 'crait', 'ahch-to', 'canto bight', 'cantonica', 'exegol', 'pasaana', 'kijimi', 'kef bir',
    'mandalore', 'nevarro', 'sorgan', 'tython', 'corvus', 'nal hutta', 'dathomir', 'lothal', 'malachor',
    'mortis', 'scarif', 'jedha', 'eadu', 'wobani', 'ord mantell', 'ryloth', 'christophsis', 'felucia',
    'saleucami', 'mygeeto', 'cato neimoidia', 'polis massa', 'mimban', 'savareen', 'corellia', 'batuu',
    'onderon', 'concord dawn', 'zeffo', 'bogano', 'bracca', 'kaller', 'ilum', 'chandrila', 'hosnian prime',
    'ajan kloss', 'moraband', 'korriban', 'devaron', 'jelucan', 'lah\'mu', 'vardos', 'pillio', 'sullust',
    'rodia', 'trandosha', 'zygerria', 'raxus', 'serenno', 'florrum', 'teth', 'rishi', 'umbara', 'carlac',
    'lira san', 'garel', 'atollon', 'seelos', 'yavin prime', 'wrea', 'daiyu', 'weesas', 'nur', 'coronet',
  ]),
  'Herbs and spices': new Set([
    'basil', 'oregano', 'thyme', 'rosemary', 'sage', 'parsley', 'cilantro', 'coriander', 'dill', 'mint',
    'peppermint', 'spearmint', 'chives', 'tarragon', 'marjoram', 'bay leaf', 'bay leaves', 'fennel',
    'lemongrass', 'lavender', 'chervil', 'sorrel', 'savory', 'curry leaf', 'kaffir lime leaf', 'epazote',
    'black pepper', 'pepper', 'white pepper', 'cayenne', 'cayenne pepper', 'paprika', 'smoked paprika',
    'chili powder', 'red pepper flakes', 'crushed red pepper', 'cumin', 'coriander seed', 'turmeric',
    'ginger', 'garlic powder', 'onion powder', 'cinnamon', 'nutmeg', 'clove', 'cloves', 'allspice',
    'cardamom', 'star anise', 'anise', 'fennel seed', 'caraway', 'mustard seed', 'poppy seed', 'sesame seed',
    'saffron', 'vanilla', 'mace', 'sumac', 'zaatar', 'garam masala', 'curry powder', 'chinese five spice',
    'old bay', 'italian seasoning', 'herbs de provence', 'pumpkin spice', 'taco seasoning', 'cajun seasoning',
    'jerk seasoning', 'ras el hanout', 'berbere', 'harissa', 'gochugaru', 'shichimi togarashi', 'furikake',
    'asafoetida', 'hing', 'fenugreek', 'ajwain', 'nigella', 'black cumin', 'juniper', 'juniper berries',
    'grains of paradise', 'annatto', 'achiote', 'peppercorn', 'pink peppercorn', 'szechuan pepper',
    'wasabi', 'horseradish', 'galangal', 'turmeric root', 'dried oregano', 'dried basil', 'dried thyme',
    'ground ginger', 'ground cinnamon', 'ground cloves', 'ground cumin', 'chili flakes', 'garlic salt',
    'celery salt', 'seasoning salt', 'msg', 'bouillon', 'stock cube',
  ]),
  'Boy bands': new Set([
    'backstreet boys', 'bsb', 'nsync', 'in sync', 'one direction', '1d', 'the jonas brothers',
    'jonas brothers', 'new kids on the block', 'nkotb', 'boyz ii men', 'bts', '98 degrees', 'westlife',
    'take that', 'the wanted', 'jls', 'blue', 'boyzone', '5 seconds of summer', '5sos', 'big time rush',
    'btr', 'menudo', 'hanson', 'lfo', 'o-town', 'b2k', 'jodeci', 'new edition', 'bell biv devoe',
    'the temptations', 'the jackson 5', 'jackson 5', 'the osmonds', 'the beach boys', 'exo', 'seventeen',
    'stray kids', 'nct', 'nct 127', 'nct dream', 'got7', 'monsta x', 'shinee', 'super junior', 'big bang',
    'bigbang', 'tvxq', 'ateez', 'the boyz', 'tomorrow x together', 'txt', 'enhypen', 'treasure', 'astro',
    'pentagon', 'day6', 'vixx', 'infinite', 'btob', 'winner', 'ikon', '2pm', 'block b', 'sechs kies',
    'east 17', 'five', 'a1', 'hanson', 'dream street', 'no authority', 'youngstown', 'c note',
    'natural', 'us5', 'il divo', 'why dont we', 'why don\'t we', 'prettymuch', 'in real life', 'cnco',
    'mindless behavior', 'new hope club', 'the vamps', 'busted', 'mcfly', 'a-ha', 'color me badd',
    'all-4-one', 'shai', 'silk', 'dru hill', 'ledisi', 'immature',
  ]),
  'Houseplants': new Set([
    'pothos', 'golden pothos', 'monstera', 'monstera deliciosa', 'swiss cheese plant', 'snake plant',
    'mother in laws tongue', 'zz plant', 'spider plant', 'peace lily', 'philodendron', 'heartleaf philodendron',
    'rubber plant', 'rubber tree', 'fiddle leaf fig', 'ficus', 'aloe vera', 'aloe', 'jade plant',
    'succulent', 'cactus', 'echeveria', 'string of pearls', 'string of hearts', 'burros tail', 'haworthia',
    'african violet', 'orchid', 'phalaenopsis', 'moth orchid', 'boston fern', 'maidenhair fern', 'birds nest fern',
    'staghorn fern', 'calathea', 'prayer plant', 'maranta', 'stromanthe', 'dracaena', 'dragon tree',
    'corn plant', 'lucky bamboo', 'chinese evergreen', 'aglaonema', 'dieffenbachia', 'dumb cane', 'croton',
    'anthurium', 'flamingo flower', 'bromeliad', 'air plant', 'tillandsia', 'begonia', 'rex begonia',
    'polka dot plant', 'nerve plant', 'fittonia', 'coleus', 'wandering jew', 'tradescantia', 'inch plant',
    'english ivy', 'ivy', 'grape ivy', 'arrowhead plant', 'syngonium', 'nephthytis', 'kalanchoe',
    'christmas cactus', 'thanksgiving cactus', 'ponytail palm', 'parlor palm', 'areca palm', 'majesty palm',
    'kentia palm', 'cast iron plant', 'norfolk island pine', 'money tree', 'money plant', 'pilea',
    'chinese money plant', 'baby rubber plant', 'peperomia', 'watermelon peperomia', 'hoya', 'wax plant',
    'string of dolphins', 'string of bananas', 'lithops', 'living stones', 'gasteria', 'sedum', 'agave',
    'yucca', 'schefflera', 'umbrella plant', 'tradescantia zebrina', 'oxalis', 'purple shamrock',
    'venus flytrap', 'pitcher plant', 'geranium', 'cyclamen', 'amaryllis', 'poinsettia', 'kentia',
    'boston ivy', 'creeping fig', 'nerve plant', 'goldfish plant', 'lipstick plant', 'ric rac cactus',
  ]),
};
