// expand-broad-4.js
// data/accept-lists-5 batch 1: 20 more broad, open-ended categories that were
// under-expanded (<40 entries). Real answers only, <=3 words, lowercase,
// union-merged into the existing Sets in categoryAnswers.js (never replaces).
// No inventions, no padding. Keys match existing category names exactly.

module.exports = {
  'Electronic music genres': [
    'house', 'deep house', 'tech house', 'progressive house', 'acid house',
    'techno', 'minimal techno', 'detroit techno', 'trance', 'psytrance',
    'progressive trance', 'dubstep', 'brostep', 'drum and bass', 'jungle',
    'breakbeat', 'breakcore', 'ambient', 'dark ambient', 'idm', 'electro',
    'electro house', 'big room', 'hardstyle', 'hardcore', 'gabber', 'happy hardcore',
    'garage', 'uk garage', 'future garage', 'trap', 'future bass', 'downtempo',
    'trip hop', 'glitch', 'synthwave', 'vaporwave', 'chillwave', 'edm',
    'eurodance', 'nu disco', 'disco house', 'moombahton', 'grime', 'footwork',
    'acid', 'chiptune', 'industrial', 'ebm', 'new wave', 'italo disco',
    'liquid dnb', 'neurofunk', 'bassline', 'complextro',
  ],
  'Famous music festivals': [
    'coachella', 'glastonbury', 'lollapalooza', 'bonnaroo', 'tomorrowland',
    'burning man', 'edc', 'ultra', 'ultra music festival', 'sxsw', 'reading',
    'leeds', 'reading and leeds', 'roskilde', 'primavera', 'primavera sound',
    'woodstock', 'isle of wight', 'wireless', 'download', 'rock am ring',
    'sziget', 'fuji rock', 'austin city limits', 'governors ball', 'firefly',
    'electric daisy carnival', 'electric forest', 'movement', 'creamfields',
    'defqon', 'exit', 'mysteryland', 'wacken', 'wacken open air', 'hellfest',
    'pinkpop', 'werchter', 'rock werchter', 'lowlands', 'osheaga', 'stagecoach',
    'life is beautiful', 'made in america', 'lightning in a bottle', 'lost lands',
    'okeechobee', 'shambhala', 'boomtown', 'parklife', 'sonar',
  ],
  'Milk alternatives': [
    'almond milk', 'soy milk', 'oat milk', 'coconut milk', 'rice milk',
    'cashew milk', 'hemp milk', 'pea milk', 'macadamia milk', 'hazelnut milk',
    'flax milk', 'flaxseed milk', 'quinoa milk', 'banana milk', 'walnut milk',
    'pistachio milk', 'tiger nut milk', 'sunflower milk', 'pecan milk',
    'sesame milk', 'spelt milk', 'oat', 'almond', 'soy', 'coconut', 'cashew',
    'hemp', 'pea protein milk', 'potato milk', 'barley milk', 'lupin milk',
    'peanut milk', 'chufa milk', 'horchata', 'brazil nut milk', 'chestnut milk',
    'millet milk', 'amaranth milk', 'chickpea milk', 'fava bean milk', 'sorghum milk',
    'buckwheat milk', 'lupini milk', 'tigernut milk', 'almond breeze', 'soya milk',
    'coconut milk beverage', 'cashew cream',
  ],
  'Types of steak': [
    'ribeye', 'sirloin', 'top sirloin', 'filet mignon', 'tenderloin', 't-bone',
    'porterhouse', 'flank', 'flank steak', 'skirt', 'skirt steak', 'hanger',
    'hanger steak', 'strip', 'new york strip', 'ny strip', 'strip steak',
    'flat iron', 'tomahawk', 'chuck', 'chuck eye', 'round', 'top round',
    'bottom round', 'eye of round', 'tri-tip', 'denver', 'denver steak',
    'picanha', 'brisket', 'short rib', 'flap', 'flap steak', 'rump', 'rump steak',
    'cube steak', 'cowboy steak', 'delmonico', 'bavette', 'coulotte', 'teres major',
    'chateaubriand', 'wagyu', 'kobe', 'prime rib', 'club steak',
  ],
  'Energy drink brands': [
    'red bull', 'monster', 'rockstar', 'bang', 'reign', 'nos', 'full throttle',
    'amp', '5-hour energy', 'celsius', 'ghost', 'c4', 'prime', 'gfuel', 'g fuel',
    'relentless', 'burn', 'mother', 'hype', 'xs', 'v', 'lucozade', 'no fear',
    'venom', 'adrenaline shoc', 'alani nu', 'aspire', 'raze', 'zoa', 'guru',
    'coco loco', 'shark', 'tab energy', 'red thunder', 'rowdy', 'uptime',
    'mtn dew energy', 'game fuel', 'kickstart', 'boost',
  ],
  'Cooking shows': [
    'masterchef', 'top chef', 'hells kitchen', 'chopped', 'the great british bake off',
    'iron chef', 'iron chef america', 'cutthroat kitchen', 'guys grocery games',
    'the bear', 'chefs table', 'nailed it', 'the final table', 'beat bobby flay',
    'diners drive-ins and dives', 'barefoot contessa', 'kitchen nightmares',
    'the french chef', 'good eats', 'giada at home', 'pioneer woman', 'worst cooks in america',
    'the great food truck race', 'sugar rush', 'is it cake', 'crazy delicious',
    'sugar high', 'salt fat acid heat', 'ugly delicious', 'somebody feed phil',
    'the taste', 'my kitchen rules', 'come dine with me', 'ready steady cook',
    'saturday kitchen', 'the chew', 'restaurant impossible', 'bar rescue',
    'from scratch', 'street food', 'the great pottery throw down', 'baking impossible',
    'american barbecue showdown', 'pressure cooker', 'snack vs chef',
  ],
  'Game shows': [
    'jeopardy', 'wheel of fortune', 'the price is right', 'family feud',
    'who wants to be a millionaire', 'deal or no deal', 'the wall', 'press your luck',
    'match game', 'card sharks', 'lets make a deal', 'the newlywed game',
    'the dating game', 'to tell the truth', 'whats my line', 'name that tune',
    'supermarket sweep', 'double dare', 'legends of the hidden temple',
    'are you smarter than a 5th grader', 'cash cab', 'the chase', 'countdown',
    'pointless', 'the weakest link', 'tipping point', 'catchphrase', 'blockbusters',
    'the crystal maze', 'gladiators', 'american gladiators', 'wipeout',
    'minute to win it', 'the joker', 'concentration', 'password', 'pyramid',
    '25000 pyramid', 'hollywood squares', 'jackpot', 'lingo', 'holey moley',
    'floor is lava', 'the masked singer', '1 vs 100', 'nailbiter',
  ],
  'Web browsers': [
    'chrome', 'google chrome', 'firefox', 'mozilla firefox', 'safari', 'edge',
    'microsoft edge', 'opera', 'opera gx', 'brave', 'vivaldi', 'tor', 'tor browser',
    'chromium', 'internet explorer', 'netscape', 'netscape navigator', 'konqueror',
    'maxthon', 'uc browser', 'samsung internet', 'duckduckgo', 'yandex',
    'yandex browser', 'pale moon', 'waterfox', 'epic', 'midori', 'lynx',
    'arc', 'seamonkey', 'librewolf', 'falkon', 'qutebrowser', 'dillo',
    'comodo dragon', 'avast secure browser', 'kiwi browser', 'puffin', 'silk',
    'coc coc', 'aloha', 'ecosia', 'mullvad browser', 'basilisk',
  ],
  'Wild canines': [
    'wolf', 'gray wolf', 'grey wolf', 'red wolf', 'arctic wolf', 'timber wolf',
    'coyote', 'fox', 'red fox', 'arctic fox', 'fennec fox', 'gray fox', 'kit fox',
    'swift fox', 'corsac fox', 'bat-eared fox', 'bengal fox', 'cape fox',
    'tibetan fox', 'jackal', 'golden jackal', 'black-backed jackal', 'side-striped jackal',
    'dingo', 'dhole', 'maned wolf', 'african wild dog', 'painted dog', 'bush dog',
    'raccoon dog', 'tanuki', 'culpeo', 'crab-eating fox', 'ethiopian wolf',
    'darwins fox', 'island fox', 'pampas fox', 'short-eared dog', 'new guinea singing dog',
    'golden wolf', 'eastern wolf', 'mexican wolf', 'blanford fox', 'hoary fox',
  ],
  'Types of coral': [
    'brain coral', 'staghorn coral', 'elkhorn coral', 'table coral', 'fan coral',
    'sea fan', 'pillar coral', 'star coral', 'fire coral', 'soft coral', 'hard coral',
    'mushroom coral', 'bubble coral', 'hammer coral', 'torch coral', 'plate coral',
    'finger coral', 'lettuce coral', 'boulder coral', 'tube coral', 'whip coral',
    'sea whip', 'organ pipe coral', 'gorgonian', 'acropora', 'montipora', 'zoanthid',
    'favia', 'goniopora', 'euphyllia', 'candy cane coral', 'frogspawn coral',
    'birdsnest coral', 'cauliflower coral', 'leather coral', 'toadstool coral',
    'sun coral', 'chalice coral', 'blastomussa', 'trumpet coral', 'bubble tip',
    'anchor coral', 'duncan coral', 'zoanthids', 'black coral',
  ],
  'Types of BBQ meat': [
    'brisket', 'pulled pork', 'pork shoulder', 'pork butt', 'ribs', 'baby back ribs',
    'spare ribs', 'st louis ribs', 'beef ribs', 'short ribs', 'sausage', 'hot links',
    'burnt ends', 'chicken', 'bbq chicken', 'chicken thighs', 'chicken wings',
    'turkey', 'smoked turkey', 'tri-tip', 'beef clod', 'pork belly', 'bacon',
    'ham', 'pastrami', 'lamb', 'lamb shoulder', 'goat', 'cabrito', 'mutton',
    'prime rib', 'pork tenderloin', 'chuck roast', 'picanha', 'kielbasa',
    'andouille', 'bologna', 'smoked bologna', 'boudin', 'jerk chicken', 'pork ribs',
    'beef cheek', 'oxtail', 'chicken quarters', 'whole hog',
  ],
  'Types of melon': [
    'watermelon', 'cantaloupe', 'honeydew', 'muskmelon', 'galia', 'canary melon',
    'crenshaw', 'casaba', 'santa claus melon', 'christmas melon', 'charentais',
    'winter melon', 'bitter melon', 'horned melon', 'kiwano', 'gac', 'sprite melon',
    'sugar melon', 'korean melon', 'crane melon', 'hami melon', 'piel de sapo',
    'toad skin melon', 'persian melon', 'ogen melon', 'sharlyn melon',
    'yellow watermelon', 'seedless watermelon', 'rockmelon', 'apollo melon',
    'sky rocket melon', 'ambrosia melon', 'orange flesh melon', 'french melon',
    'moon and stars watermelon',
  ],
  'Types of rice': [
    'white rice', 'brown rice', 'basmati', 'jasmine', 'arborio', 'sushi rice',
    'long grain', 'short grain', 'medium grain', 'wild rice', 'black rice',
    'forbidden rice', 'red rice', 'sticky rice', 'glutinous rice', 'parboiled rice',
    'converted rice', 'carnaroli', 'bomba rice', 'valencia rice', 'calrose',
    'jasmine brown', 'basmati brown', 'texmati', 'wehani', 'bhutanese red rice',
    'camargue red rice', 'purple rice', 'green rice', 'broken rice', 'rice flour',
    'puffed rice', 'instant rice', 'golden rice', 'paella rice', 'risotto rice',
    'koshihikari', 'jeera rice', 'ponni rice', 'sona masoori',
  ],
  'Types of squash': [
    'butternut', 'butternut squash', 'acorn squash', 'spaghetti squash',
    'zucchini', 'yellow squash', 'summer squash', 'winter squash', 'pumpkin',
    'delicata', 'kabocha', 'hubbard', 'buttercup squash', 'crookneck', 'pattypan',
    'carnival squash', 'sweet dumpling', 'turban squash', 'banana squash',
    'honeynut squash', 'gem squash', 'cushaw', 'calabaza', 'red kuri', 'sugar pumpkin',
    'jack be little', 'blue hubbard', 'golden nugget', 'straightneck', 'marrow',
    'chayote', 'kuri squash', 'fairytale pumpkin', 'cinderella pumpkin', 'cheese pumpkin',
    'green striped cushaw', 'autumn cup', 'tromboncino', 'round zucchini',
  ],
  'Types of pancakes': [
    'buttermilk pancakes', 'blueberry pancakes', 'banana pancakes', 'crepes',
    'silver dollar pancakes', 'dutch baby', 'german pancake', 'potato pancakes',
    'latke', 'blini', 'blintz', 'johnnycake', 'flapjacks', 'griddle cakes',
    'hotcakes', 'buckwheat pancakes', 'protein pancakes', 'ricotta pancakes',
    'lemon ricotta pancakes', 'chocolate chip pancakes', 'pumpkin pancakes',
    'sourdough pancakes', 'oatmeal pancakes', 'japanese souffle pancakes',
    'souffle pancakes', 'dosa', 'okonomiyaki', 'injera', 'pajeon', 'hoecake',
    'pikelet', 'scotch pancake', 'kaiserschmarrn', 'poffertjes', 'aebleskiver',
    'apam balik', 'serabi', 'staffordshire oatcake', 'cottage cheese pancakes',
    'vegan pancakes',
  ],
  'Popular dipping sauces': [
    'ketchup', 'mustard', 'honey mustard', 'ranch', 'bbq sauce', 'barbecue sauce',
    'mayonnaise', 'mayo', 'aioli', 'garlic aioli', 'sriracha', 'buffalo sauce',
    'blue cheese', 'thousand island', 'tartar sauce', 'cocktail sauce',
    'sweet and sour', 'soy sauce', 'teriyaki', 'hoisin', 'peanut sauce', 'satay sauce',
    'tzatziki', 'hummus', 'guacamole', 'salsa', 'queso', 'nacho cheese', 'marinara',
    'chipotle mayo', 'sweet chili sauce', 'plum sauce', 'duck sauce', 'fry sauce',
    'comeback sauce', 'remoulade', 'chimichurri', 'romesco', 'harissa', 'gochujang',
    'ponzu', 'wasabi', 'nam pla', 'tahini', 'chick-fil-a sauce',
  ],
  'Major world deserts': [
    'sahara', 'gobi', 'kalahari', 'namib', 'atacama', 'arabian desert', 'sonoran',
    'mojave', 'chihuahuan', 'great basin', 'thar', 'antarctic', 'antarctic desert',
    'arctic', 'arctic desert', 'patagonian', 'syrian desert', 'great victoria',
    'great sandy', 'gibson desert', 'simpson desert', 'tanami', 'karakum',
    'kyzylkum', 'taklamakan', 'dasht-e kavir', 'dasht-e lut', 'nubian desert',
    'danakil', 'negev', 'sinai', 'death valley', 'painted desert', 'colorado desert',
    'black rock desert', 'registan', 'nefud', 'rub al khali', 'empty quarter',
    'ordos', 'sechura', 'monte desert', 'wahiba sands', 'white desert',
  ],
  'Phone brands': [
    'apple', 'iphone', 'samsung', 'google', 'pixel', 'oneplus', 'xiaomi', 'redmi',
    'poco', 'oppo', 'vivo', 'huawei', 'honor', 'motorola', 'nokia', 'sony',
    'lg', 'htc', 'blackberry', 'asus', 'realme', 'nothing', 'zte', 'tcl', 'alcatel',
    'lenovo', 'meizu', 'infinix', 'tecno', 'itel', 'fairphone', 'cat', 'sharp',
    'panasonic', 'micromax', 'lava', 'ulefone', 'doogee', 'blackview', 'gionee',
    'coolpad', 'leeco', 'essential', 'palm', 'red magic',
  ],
  "Ben & Jerry's flavors": [
    'cherry garcia', 'chunky monkey', 'phish food', 'half baked', 'americone dream',
    'chocolate fudge brownie', 'cookie dough', 'chocolate chip cookie dough',
    'new york super fudge chunk', 'the tonight dough', 'coffee coffee buzzbuzzbuzz',
    'strawberry cheesecake', 'peanut butter cup', 'salted caramel core',
    'boom chocolatta', 'milk and cookies', 'chubby hubby', 'karamel sutra',
    'everything but the', 'red velvet cake', 'triple caramel chunk', 'mint chocolate cookie',
    'coffee toffee bar crunch', 'peanut butter world', 'cinnamon buns', 'brownie batter core',
    'urban bourbon', 'oat of this swirled', 'pistachio pistachio', 'vanilla',
    'chocolate', 'mint chocolate chunk', 'netflix and chilll', 'gimme smore',
    'cannoli', 'save our swirled', 'truffle kerfuffle', 'wich is which',
    'peanut buttah', 'change is brewing', 'topped tiramisu', 'dublin mudslide',
  ],
  'Types of potatoes': [
    'russet', 'yukon gold', 'red potato', 'red bliss', 'fingerling', 'new potato',
    'sweet potato', 'purple potato', 'purple majesty', 'idaho', 'maris piper',
    'king edward', 'kennebec', 'kestrel', 'desiree', 'charlotte', 'jersey royal',
    'nicola', 'rooster', 'baby potato', 'white potato', 'gold potato',
    'adirondack blue', 'german butterball', 'la ratte', 'french fingerling',
    'peruvian purple', 'all blue', 'katahdin', 'norland', 'yellow finn',
    'carola', 'bintje', 'agria', 'vivaldi', 'anya', 'pink fir apple',
    'shetland black', 'russian banana', 'red pontiac',
  ],
};
