// categoryAnswers/expand-broad-2.js
// data/accept-lists-2 — broad under-expanded categories, batch 2 (autonomous 2026-08-26).
// Union-merged via the supplements loop in categoryAnswers.js (adds to the existing Set,
// never replaces). REAL, well-known answers only, all lowercase, <=3 words, deduped by the Set.
// Keys must match existing CATEGORIES exactly (verified against categoryAnswers before wiring).
module.exports = {
  'Jungle animals': [
    'tiger', 'jaguar', 'leopard', 'gorilla', 'chimpanzee', 'orangutan', 'sloth', 'toucan',
    'parrot', 'macaw', 'python', 'anaconda', 'boa constrictor', 'iguana', 'tree frog',
    'poison dart frog', 'tapir', 'capybara', 'ocelot', 'howler monkey', 'spider monkey',
    'lemur', 'gibbon', 'tarantula', 'army ant', 'leafcutter ant', 'piranha', 'caiman',
    'crocodile', 'chameleon', 'gecko', 'king cobra', 'black mamba', 'okapi', 'panther',
    'lynx', 'fruit bat', 'hummingbird', 'coati', 'kinkajou', 'harpy eagle', 'quetzal',
    'mandrill', 'bonobo', 'pangolin', 'sun bear', 'clouded leopard', 'elephant', 'rhinoceros',
    'hippopotamus', 'python', 'macaque', 'lion', 'cheetah', 'antelope', 'gazelle', 'wild boar',
  ],
  'Horror movies': [
    'the shining', 'halloween', 'psycho', 'the exorcist', 'friday the 13th', 'scream', 'it',
    'the conjuring', 'insidious', 'hereditary', 'midsommar', 'get out', 'us', 'the ring',
    'the grudge', 'saw', 'hostel', 'the thing', 'poltergeist', 'carrie', 'the omen',
    "rosemary's baby", 'jaws', 'the babadook', 'sinister', 'annabelle', 'the nun',
    "don't breathe", 'a quiet place', 'the witch', 'it follows', 'the descent', '28 days later',
    'evil dead', 'drag me to hell', "child's play", 'candyman', 'pet sematary', 'misery',
    'nosferatu', 'dracula', 'frankenstein', 'the mummy', 'the fly', 'gremlins', 'the birds',
    'suspiria', 'final destination', 'jeepers creepers', 'wrong turn', 'the strangers',
    'orphan', 'split', 'alien', 'the texas chainsaw', 'nightmare on elm', 'smile', 'barbarian',
  ],
  'Simpsons characters': [
    'homer', 'marge', 'bart', 'lisa', 'maggie', 'ned flanders', 'mr burns', 'smithers', 'moe',
    'barney', 'krusty', 'milhouse', 'nelson', 'ralph wiggum', 'principal skinner', 'apu',
    'chief wiggum', 'comic book guy', 'groundskeeper willie', 'otto', 'lenny', 'carl', 'patty',
    'selma', 'grampa', 'abe simpson', 'sideshow bob', 'kang', 'kodos', 'itchy', 'scratchy',
    'dr hibbert', 'dr nick', 'snake', 'fat tony', 'disco stu', 'gil', 'troy mcclure',
    'lionel hutz', 'kent brockman', 'duffman', 'professor frink', 'martin prince', 'jimbo',
    'kearney', 'dolph', 'rod flanders', 'todd flanders', 'maude flanders', 'agnes skinner',
    'helen lovejoy', 'reverend lovejoy', 'cletus', 'hans moleman', 'jasper',
    "santa's little helper", 'snowball', 'edna krabappel', 'nelson muntz', 'sideshow mel',
  ],
  'Body parts': [
    'head', 'neck', 'shoulder', 'arm', 'elbow', 'wrist', 'hand', 'finger', 'thumb', 'chest',
    'back', 'stomach', 'waist', 'hip', 'leg', 'knee', 'ankle', 'foot', 'toe', 'eye', 'ear',
    'nose', 'mouth', 'lip', 'tongue', 'tooth', 'chin', 'cheek', 'forehead', 'eyebrow',
    'eyelash', 'jaw', 'throat', 'spine', 'rib', 'skull', 'brain', 'heart', 'lung', 'liver',
    'kidney', 'intestine', 'muscle', 'bone', 'skin', 'hair', 'nail', 'heel', 'palm', 'knuckle',
    'shin', 'calf', 'thigh', 'forearm', 'bicep', 'collarbone', 'pelvis', 'femur', 'spleen',
    'gallbladder', 'pancreas', 'bladder', 'artery', 'vein', 'nerve', 'tendon', 'ligament',
  ],
  'Kitchen utensils': [
    'spatula', 'whisk', 'ladle', 'tongs', 'spoon', 'fork', 'knife', 'peeler', 'grater',
    'colander', 'strainer', 'sieve', 'rolling pin', 'can opener', 'bottle opener', 'corkscrew',
    'measuring cup', 'measuring spoon', 'mixing bowl', 'cutting board', 'garlic press',
    'potato masher', 'slotted spoon', 'wooden spoon', 'pizza cutter', 'ice cream scoop',
    'melon baller', 'zester', 'mandoline', 'kitchen shears', 'basting brush', 'meat thermometer',
    'funnel', 'sifter', 'mortar and pestle', 'nutcracker', 'egg beater', 'ladle', 'skimmer',
    'turner', 'butter knife', 'paring knife', 'chef knife', 'bread knife', 'cheese slicer',
    'apple corer', 'pastry brush', 'rolling cutter', 'salad tongs', 'spider strainer',
  ],
  'Tools in a toolbox': [
    'hammer', 'screwdriver', 'wrench', 'pliers', 'saw', 'drill', 'level', 'tape measure',
    'chisel', 'file', 'clamp', 'vise', 'allen wrench', 'socket wrench', 'ratchet', 'mallet',
    'crowbar', 'utility knife', 'hacksaw', 'wire cutter', 'sandpaper', 'nail', 'screw', 'bolt',
    'nut', 'washer', 'stud finder', 'putty knife', 'caulk gun', 'wire stripper', 'soldering iron',
    'hex key', 'torque wrench', 'pipe wrench', 'adjustable wrench', 'phillips screwdriver',
    'flathead screwdriver', 'power drill', 'jigsaw', 'circular saw', 'nail gun', 'staple gun',
    'wrench set', 'chalk line', 'plumb bob', 'awl', 'rasp', 'pry bar', 'nut driver', 'c-clamp',
  ],
  'Things with wheels': [
    'car', 'truck', 'bus', 'bicycle', 'motorcycle', 'scooter', 'skateboard', 'roller skates',
    'wheelbarrow', 'shopping cart', 'wagon', 'stroller', 'wheelchair', 'train', 'tram', 'trolley',
    'go-kart', 'tractor', 'forklift', 'crane', 'bulldozer', 'tank', 'ambulance', 'fire truck',
    'taxi', 'van', 'suv', 'unicycle', 'tricycle', 'rollerblades', 'segway', 'hoverboard',
    'golf cart', 'lawnmower', 'suitcase', 'office chair', 'dolly', 'hand truck', 'rickshaw',
    'chariot', 'skates', 'trailer', 'caravan', 'moped', 'dirt bike', 'atv', 'dump truck',
    'garbage truck', 'tow truck', 'bumper car', 'ferris wheel', 'roller coaster',
  ],
  'Insects': [
    'ant', 'bee', 'wasp', 'hornet', 'butterfly', 'moth', 'beetle', 'ladybug', 'grasshopper',
    'cricket', 'cockroach', 'termite', 'dragonfly', 'damselfly', 'mosquito', 'housefly', 'gnat',
    'flea', 'aphid', 'cicada', 'firefly', 'praying mantis', 'stick insect', 'weevil', 'earwig',
    'silverfish', 'caterpillar', 'locust', 'katydid', 'june bug', 'stink bug', 'bed bug',
    'dung beetle', 'water strider', 'lacewing', 'midge', 'horsefly', 'bumblebee', 'carpenter ant',
    'fire ant', 'honeybee', 'yellow jacket', 'gnat', 'fruit fly', 'boll weevil', 'leaf beetle',
    'ground beetle', 'stag beetle', 'rhinoceros beetle', 'monarch butterfly', 'luna moth',
    'tsetse fly', 'assassin bug', 'leafhopper', 'mayfly', 'walking stick',
  ],
  'Types of cookies': [
    'chocolate chip', 'oatmeal raisin', 'sugar', 'peanut butter', 'snickerdoodle', 'shortbread',
    'gingerbread', 'macaron', 'macaroon', 'biscotti', 'fortune cookie', 'oreo', 'wafer',
    'butter cookie', 'thumbprint', 'sandwich cookie', 'gingersnap', 'molasses', 'lemon',
    'white chocolate macadamia', 'double chocolate', 'no bake', 'lace cookie', 'spritz',
    'russian tea cake', 'linzer', 'florentine', 'meringue', 'fudge', 'brownie', 'blondie',
    'anzac', 'digestive', 'graham cracker', 'nutter butter', 'chips ahoy', 'animal cracker',
    'pinwheel', 'wedding cookie', 'kolache', 'rugelach', 'madeleine', 'pizzelle', 'coconut',
    'toffee', 'caramel', 'mint chocolate', 'crinkle',
  ],
  'Coffee drinks': [
    'espresso', 'latte', 'cappuccino', 'americano', 'macchiato', 'mocha', 'flat white',
    'cortado', 'ristretto', 'lungo', 'affogato', 'frappe', 'cold brew', 'iced coffee', 'nitro',
    'doppio', 'cafe con leche', 'breve', 'red eye', 'irish coffee', 'turkish coffee',
    'cafe au lait', 'cafe cubano', 'caramel macchiato', 'pumpkin spice latte', 'frappuccino',
    'drip coffee', 'pour over', 'french press', 'aeropress', 'espresso con panna', 'cafe bombon',
    'vienna coffee', 'flat black', 'long black', 'black coffee', 'iced latte', 'chai latte',
    'dirty chai', 'mochaccino', 'affogato', 'galao', 'ristretto', 'lungo', 'cafe mocha',
  ],
  'Sandwich types': [
    'blt', 'club', 'grilled cheese', 'reuben', 'philly cheesesteak', 'sub', 'hoagie', 'panini',
    'po boy', 'muffuletta', 'monte cristo', 'sloppy joe', 'pulled pork', 'meatball', 'italian',
    'turkey', 'ham and cheese', 'tuna melt', 'egg salad', 'chicken salad', 'blt', 'cuban',
    'french dip', 'pastrami', 'corned beef', 'gyro', 'shawarma', 'falafel', 'banh mi', 'wrap',
    'panino', 'croque monsieur', 'croque madame', 'lobster roll', 'pb and j', 'veggie',
    'roast beef', 'bologna', 'submarine', 'hero', 'grinder', 'open faced', 'finger sandwich',
    'cucumber sandwich', 'chicken parm', 'eggplant parm', 'bacon egg cheese', 'patty melt',
  ],
  'Venomous or poisonous animals': [
    'cobra', 'rattlesnake', 'black mamba', 'king cobra', 'viper', 'copperhead', 'coral snake',
    'boomslang', 'taipan', 'sea snake', 'scorpion', 'black widow', 'brown recluse', 'funnel web',
    'tarantula', 'box jellyfish', 'portuguese man o war', 'stingray', 'stonefish', 'lionfish',
    'pufferfish', 'blue ringed octopus', 'cone snail', 'poison dart frog', 'cane toad',
    'gila monster', 'komodo dragon', 'platypus', 'bullet ant', 'fire ant', 'centipede',
    'wasp', 'hornet', 'bee', 'deathstalker scorpion', 'inland taipan', 'russell viper',
    'saw scaled viper', 'fer de lance', 'bushmaster', 'gaboon viper', 'sydney funnel web',
    'brazilian wandering spider', 'cottonmouth', 'water moccasin', 'newt', 'monarch caterpillar',
  ],
  'Mythical monsters in pop culture': [
    'dragon', 'werewolf', 'vampire', 'zombie', 'kraken', 'minotaur', 'medusa', 'cyclops',
    'hydra', 'chimera', 'griffin', 'phoenix', 'basilisk', 'cerberus', 'centaur', 'sphinx',
    'goblin', 'troll', 'ogre', 'orc', 'banshee', 'wendigo', 'kelpie', 'gorgon', 'harpy',
    'siren', 'gargoyle', 'golem', 'wraith', 'ghoul', 'mummy', 'frankenstein', 'yeti',
    'bigfoot', 'chupacabra', 'loch ness monster', 'cthulhu', 'balrog', 'basilisk', 'manticore',
    'leviathan', 'behemoth', 'jabberwocky', 'gremlin', 'imp', 'demon', 'djinn', 'fenrir',
    'jormungandr', 'kappa', 'oni', 'tengu', 'naga',
  ],
  'Types of pie': [
    'apple', 'pumpkin', 'pecan', 'cherry', 'blueberry', 'key lime', 'lemon meringue',
    'banana cream', 'coconut cream', 'chocolate cream', 'peach', 'strawberry', 'rhubarb',
    'strawberry rhubarb', 'sweet potato', 'shepherds pie', 'chicken pot pie', 'pot pie',
    'mince', 'mincemeat', 'custard', 'buttermilk', 'chess', 'shoofly', 'boston cream',
    'french silk', 'mississippi mud', 'grasshopper', 'peanut butter', 'pumpkin', 'blackberry',
    'raspberry', 'mixed berry', 'cranberry', 'apricot', 'plum', 'fig', 'walnut', 'maple',
    'sugar cream', 'cottage pie', 'meat pie', 'quiche', 'tart', 'galette', 'hand pie',
  ],
  'Frozen desserts': [
    'ice cream', 'gelato', 'sorbet', 'sherbet', 'frozen yogurt', 'popsicle', 'ice pop',
    'italian ice', 'snow cone', 'sundae', 'banana split', 'ice cream sandwich', 'ice cream cake',
    'soft serve', 'milkshake', 'float', 'granita', 'semifreddo', 'kulfi', 'mochi ice cream',
    'frozen custard', 'affogato', 'baked alaska', 'ice cream cone', 'drumstick', 'fudgesicle',
    'creamsicle', 'push pop', 'dippin dots', 'ice cream float', 'spumoni', 'neapolitan',
    'rocky road', 'shaved ice', 'slushie', 'frozen banana', 'ice cream bar', 'klondike bar',
    'choco taco', 'nitro ice cream', 'gelato affogato', 'bomb pop', 'freeze pop',
  ],
  'Types of tacos': [
    'al pastor', 'carnitas', 'carne asada', 'barbacoa', 'birria', 'fish', 'shrimp', 'chicken',
    'beef', 'pork', 'breakfast', 'chorizo', 'lengua', 'suadero', 'campechano', 'cabeza',
    'tripa', 'adobada', 'pescado', 'camaron', 'pollo', 'bistec', 'nopal', 'soft', 'hard shell',
    'street', 'crispy', 'potato', 'bean', 'ground beef', 'shredded chicken', 'carne guisada',
    'buche', 'chicharron', 'flautas', 'dorados', 'gobernador', 'baja fish', 'walking taco',
    'breakfast taco', 'egg', 'veggie', 'mushroom', 'jackfruit',
  ],
};
