// expand-broad-3.js
// data/accept-lists-3 batch: 20 more broad, open-ended categories that were
// under-expanded (<40 entries). Real answers only, <=3 words, lowercase,
// union-merged into the existing Sets in categoryAnswers.js (never replaces).
// No inventions, no padding. Keys match existing category names exactly.

module.exports = {
  'Marsupials': [
    'kangaroo', 'red kangaroo', 'grey kangaroo', 'eastern grey kangaroo',
    'western grey kangaroo', 'wallaby', 'swamp wallaby', 'agile wallaby',
    'rock wallaby', 'wallaroo', 'koala', 'wombat', 'opossum', 'possum',
    'virginia opossum', 'water opossum', 'mouse opossum', 'quokka',
    'tasmanian devil', 'numbat', 'bandicoot', 'bilby', 'sugar glider',
    'feathertail glider', 'greater glider', 'squirrel glider', 'quoll',
    'cuscus', 'potoroo', 'long-nosed potoroo', 'bettong', 'pademelon',
    'dunnart', 'thylacine', 'tree kangaroo', 'marsupial mole', 'antechinus',
    'ringtail possum', 'brushtail possum', 'honey possum', 'striped possum',
    'yapok', 'kowari', 'planigale', 'mulgara', 'phascogale', 'tammar wallaby',
    'monito del monte',
  ],
  'Primates': [
    'human', 'chimpanzee', 'bonobo', 'gorilla', 'orangutan', 'gibbon',
    'siamang', 'baboon', 'mandrill', 'drill', 'macaque', 'rhesus macaque',
    'japanese macaque', 'lemur', 'ring-tailed lemur', 'tarsier', 'marmoset',
    'pygmy marmoset', 'tamarin', 'golden lion tamarin', 'emperor tamarin',
    'capuchin', 'howler monkey', 'spider monkey', 'squirrel monkey', 'colobus',
    'langur', 'aye-aye', 'loris', 'slow loris', 'galago', 'bushbaby',
    'proboscis monkey', 'vervet monkey', 'gelada', 'guenon', 'mangabey',
    'saki monkey', 'uakari', 'titi monkey', 'night monkey', 'woolly monkey',
    'patas monkey', 'snub-nosed monkey', 'indri', 'sifaka', 'potto',
  ],
  'Cat breeds': [
    'persian', 'siamese', 'maine coon', 'ragdoll', 'bengal', 'sphynx',
    'british shorthair', 'american shorthair', 'abyssinian', 'birman',
    'burmese', 'russian blue', 'scottish fold', 'norwegian forest cat',
    'savannah', 'munchkin', 'devon rex', 'cornish rex', 'oriental shorthair',
    'exotic shorthair', 'himalayan', 'turkish angora', 'turkish van', 'manx',
    'ocicat', 'tonkinese', 'balinese', 'somali', 'chartreux', 'egyptian mau',
    'singapura', 'bombay', 'korat', 'havana brown', 'japanese bobtail',
    'american curl', 'selkirk rex', 'laperm', 'pixiebob', 'snowshoe',
    'ragamuffin', 'nebelung', 'lykoi', 'peterbald', 'cymric', 'chausie',
    'american bobtail', 'khao manee', 'european shorthair', 'siberian',
  ],
  'Butterfly species': [
    'monarch', 'viceroy', 'painted lady', 'red admiral', 'mourning cloak',
    'common buckeye', 'tiger swallowtail', 'black swallowtail',
    'spicebush swallowtail', 'giant swallowtail', 'cabbage white',
    'orange sulphur', 'clouded sulphur', 'cloudless sulphur', 'gulf fritillary',
    'great spangled fritillary', 'zebra longwing', 'julia butterfly',
    'question mark', 'eastern comma', 'american lady', 'west coast lady',
    'karner blue', 'spring azure', 'gray hairstreak', 'silver-spotted skipper',
    'fiery skipper', 'pearl crescent', 'red-spotted purple', 'white admiral',
    'purple emperor', 'peacock butterfly', 'small tortoiseshell', 'brimstone',
    'holly blue', 'common blue', 'meadow brown', 'gatekeeper', 'ringlet',
    'marbled white', 'apollo', 'adonis blue', 'chalkhill blue', 'blue morpho',
    'swallowtail', 'speckled wood', 'glasswing', 'birdwing',
  ],
  'Flowers': [
    'rose', 'tulip', 'daisy', 'sunflower', 'lily', 'orchid', 'daffodil',
    'carnation', 'chrysanthemum', 'marigold', 'petunia', 'pansy', 'violet',
    'iris', 'peony', 'dahlia', 'hydrangea', 'lavender', 'poppy', 'zinnia',
    'begonia', 'geranium', 'snapdragon', 'aster', 'gardenia', 'jasmine',
    'hibiscus', 'lotus', 'magnolia', 'camellia', 'azalea', 'buttercup',
    'bluebell', 'foxglove', 'freesia', 'gladiolus', 'hyacinth', 'lilac',
    'primrose', 'ranunculus', 'sweet pea', 'tuberose', 'anemone', 'crocus',
    'cosmos', 'forget-me-not', 'morning glory', 'water lily', 'calla lily',
    'bird of paradise',
  ],
  'Fruits': [
    'apple', 'banana', 'orange', 'pear', 'peach', 'plum', 'cherry', 'grape',
    'strawberry', 'blueberry', 'raspberry', 'blackberry', 'mango', 'pineapple',
    'watermelon', 'cantaloupe', 'honeydew', 'kiwi', 'papaya', 'guava', 'lychee',
    'pomegranate', 'fig', 'date', 'apricot', 'nectarine', 'lemon', 'lime',
    'grapefruit', 'tangerine', 'clementine', 'coconut', 'passion fruit',
    'dragon fruit', 'star fruit', 'persimmon', 'cranberry', 'gooseberry',
    'currant', 'elderberry', 'mulberry', 'jackfruit', 'durian', 'rambutan',
    'longan', 'plantain', 'quince', 'kumquat', 'boysenberry', 'cherimoya',
  ],
  'Cocktails': [
    'margarita', 'martini', 'mojito', 'cosmopolitan', 'manhattan',
    'old fashioned', 'negroni', 'daiquiri', 'mai tai', 'pina colada',
    'bloody mary', 'mimosa', 'whiskey sour', 'gin and tonic', 'tom collins',
    'sidecar', 'sazerac', 'moscow mule', 'cuba libre', 'screwdriver',
    'tequila sunrise', 'aviation', 'bellini', 'caipirinha', 'gimlet',
    'mint julep', 'white russian', 'black russian', 'mudslide', 'sea breeze',
    'singapore sling', 'french 75', 'americano',
    'boulevardier', 'dark and stormy', 'paloma', 'sangria', 'aperol spritz',
    'kamikaze', 'hurricane', 'zombie', 'vesper', 'rob roy', 'brandy alexander',
    'irish coffee',
  ],
  'Famous landmarks': [
    'eiffel tower', 'statue of liberty', 'great wall', 'taj mahal', 'colosseum',
    'big ben', 'sydney opera house', 'christ the redeemer', 'machu picchu',
    'pyramids of giza', 'sphinx', 'leaning tower', 'stonehenge',
    'mount rushmore', 'golden gate bridge', 'empire state building',
    'burj khalifa', 'tower bridge', 'brandenburg gate', 'arc de triomphe',
    'notre dame', 'sagrada familia', 'acropolis', 'parthenon', 'petra',
    'angkor wat', 'hagia sophia', 'kremlin', 'red square', 'times square',
    'hollywood sign', 'space needle', 'gateway arch', 'chichen itza',
    'neuschwanstein', 'mont saint-michel', 'buckingham palace', 'white house',
    'tower of london', 'london eye', 'brooklyn bridge', 'niagara falls',
    'grand canyon', 'mount fuji', 'forbidden city', 'willis tower',
    'cn tower', 'pantheon', 'louvre',
  ],
  'Famous museums': [
    'louvre', 'british museum', 'metropolitan museum', 'moma', 'guggenheim',
    'prado', 'rijksmuseum', 'uffizi', 'hermitage', 'vatican museums',
    'national gallery', 'tate modern', 'smithsonian', 'getty center',
    'whitney museum', 'van gogh museum', "musee d'orsay", 'pompidou centre',
    'victoria and albert', 'egyptian museum', 'acropolis museum',
    'guggenheim bilbao', 'mauritshuis', 'field museum', 'pergamon museum',
    'brooklyn museum', 'deutsches museum', 'saatchi gallery',
    'courtauld gallery', 'frick collection', "doge's palace", 'topkapi palace',
    'natural history museum', 'science museum', 'tate britain',
    'national portrait gallery', 'kunsthistorisches museum', 'museo reina sofia',
    'palais de tokyo', 'groninger museum', 'mori art museum', 'getty villa',
    'wallace collection', 'serpentine galleries', 'hamburger bahnhof',
    'neues museum', 'altes museum',
  ],
  'Famous explorers': [
    'christopher columbus', 'marco polo', 'ferdinand magellan', 'vasco da gama',
    'james cook', 'amerigo vespucci', 'hernan cortes', 'francisco pizarro',
    'ponce de leon', 'henry hudson', 'john cabot', 'jacques cartier',
    'samuel de champlain', 'roald amundsen', 'robert peary', 'ernest shackleton',
    'robert scott', 'david livingstone', 'henry stanley', 'ibn battuta',
    'zheng he', 'leif erikson', 'bartolomeu dias', 'francis drake',
    'walter raleigh', 'lewis and clark', 'meriwether lewis', 'william clark',
    'sacagawea', 'edmund hillary', 'tenzing norgay', 'jacques cousteau',
    'hernando de soto', 'francisco coronado', 'abel tasman', 'willem barentsz',
    'fridtjof nansen', 'richard byrd', 'matthew henson', 'mungo park',
    'alexander mackenzie', 'thor heyerdahl', 'george vancouver',
    'sebastian cabot',
  ],
  'Classical composers': [
    'bach', 'beethoven', 'mozart', 'chopin', 'tchaikovsky', 'brahms', 'handel',
    'vivaldi', 'haydn', 'schubert', 'wagner', 'verdi', 'liszt', 'mendelssohn',
    'schumann', 'debussy', 'ravel', 'stravinsky', 'mahler', 'dvorak', 'grieg',
    'sibelius', 'rachmaninoff', 'prokofiev', 'shostakovich', 'puccini',
    'rossini', 'bizet', 'strauss', 'elgar', 'holst', 'gershwin', 'copland',
    'bruckner', 'faure', 'satie', 'saint-saens', 'berlioz', 'paganini',
    'scarlatti', 'telemann', 'purcell', 'monteverdi', 'bartok', 'hindemith',
    'glinka', 'mussorgsky', 'rimsky-korsakov', 'borodin', 'respighi',
  ],
  'Types of soup': [
    'chicken noodle', 'tomato', 'minestrone', 'clam chowder', 'french onion',
    'chicken tortilla', 'miso', 'ramen', 'pho', 'gazpacho', 'lentil',
    'split pea', 'potato leek', 'butternut squash', 'mushroom',
    'cream of mushroom', 'vegetable', 'beef barley', 'chili', 'gumbo', 'bisque',
    'lobster bisque', 'borscht', 'wonton', 'egg drop', 'hot and sour',
    'matzo ball', 'chicken and rice', 'broccoli cheddar', 'cream of chicken',
    'black bean', 'white bean', 'corn chowder', 'cabbage', 'pumpkin',
    'carrot ginger', 'tom yum', 'laksa', 'bouillabaisse', 'avgolemono',
    'cullen skink', 'goulash', 'oxtail', 'turkey', 'cauliflower',
    'seafood chowder', 'kimchi jjigae',
  ],
  'Types of bread': [
    'white', 'wheat', 'whole wheat', 'sourdough', 'rye', 'pumpernickel',
    'baguette', 'ciabatta', 'focaccia', 'brioche', 'challah', 'naan', 'pita',
    'tortilla', 'cornbread', 'banana bread', 'multigrain', 'potato bread',
    'italian', 'french', 'bagel', 'english muffin', 'croissant', 'flatbread',
    'soda bread', 'garlic bread', 'milk bread', 'dinner roll', 'pretzel',
    'texas toast', 'sandwich bread', 'whole grain', 'oat bread', 'raisin bread',
    'ezekiel bread', 'marble rye', 'panettone', 'brown bread', 'seeded bread',
    'spelt bread', 'hawaiian roll', 'kaiser roll', 'hoagie roll',
    'corn tortilla', 'roti', 'chapati',
  ],
  'Types of beer': [
    'lager', 'ale', 'pilsner', 'stout', 'porter', 'ipa', 'pale ale',
    'wheat beer', 'amber ale', 'brown ale', 'blonde ale', 'saison',
    'hefeweizen', 'dunkel', 'bock', 'doppelbock', 'marzen', 'kolsch', 'gose',
    'sour beer', 'lambic', 'gueuze', 'barleywine', 'tripel', 'dubbel', 'quad',
    'witbier', 'cream ale', 'red ale', 'scotch ale', 'imperial stout',
    'milk stout', 'oatmeal stout', 'dry stout', 'session ipa', 'double ipa',
    'new england ipa', 'hazy ipa', 'west coast ipa', 'rye beer', 'fruit beer',
    'pumpkin ale', 'oktoberfest', 'vienna lager', 'helles', 'schwarzbier',
    'rauchbier', 'belgian ale', 'english bitter', 'pale lager',
  ],
  'International cuisines': [
    'italian', 'french', 'chinese', 'japanese', 'mexican', 'indian', 'thai',
    'greek', 'spanish', 'korean', 'vietnamese', 'turkish', 'lebanese',
    'moroccan', 'ethiopian', 'german', 'brazilian', 'peruvian', 'argentinian',
    'american', 'cajun', 'cuban', 'jamaican', 'filipino', 'indonesian',
    'malaysian', 'portuguese', 'russian', 'polish', 'hungarian', 'egyptian',
    'persian', 'iranian', 'israeli', 'syrian', 'nigerian', 'ghanaian',
    'caribbean', 'cantonese', 'sichuan', 'tex-mex', 'mediterranean',
    'scandinavian', 'british', 'irish', 'colombian', 'venezuelan', 'tibetan',
    'nepali', 'taiwanese',
  ],
  'Programming languages': [
    'python', 'java', 'javascript', 'c', 'c++', 'c#', 'ruby', 'php', 'swift',
    'kotlin', 'go', 'rust', 'typescript', 'scala', 'perl', 'haskell', 'lua',
    'r', 'matlab', 'objective-c', 'dart', 'elixir', 'erlang', 'clojure',
    'groovy', 'julia', 'fortran', 'cobol', 'pascal', 'assembly', 'bash',
    'powershell', 'sql', 'visual basic', 'f#', 'ocaml', 'scheme', 'lisp',
    'prolog', 'ada', 'smalltalk', 'racket', 'crystal', 'nim', 'zig',
    'solidity', 'delphi', 'vhdl', 'verilog', 'apl',
  ],
  'Reality TV shows': [
    'survivor', 'big brother', 'the bachelor', 'the bachelorette',
    'american idol', 'the voice', 'the real world', 'jersey shore',
    'love island', 'the amazing race', 'project runway', 'top chef',
    "hell's kitchen", 'masterchef', "rupaul's drag race", 'the apprentice',
    'shark tank', 'queer eye', 'the biggest loser', 'americas got talent',
    'temptation island', '90 day fiance', 'dance moms', 'the osbournes',
    'laguna beach', 'the hills', 'real housewives', 'teen mom', 'wife swap',
    'kitchen nightmares', 'cake boss', 'storage wars', 'pawn stars',
    'deadliest catch', 'duck dynasty', 'ice road truckers', 'fear factor',
    'the mole', 'road rules', 'tough as nails', 'naked and afraid',
    'below deck', 'vanderpump rules', 'the ultimatum', 'love is blind',
  ],
  'Types of seafood': [
    'salmon', 'tuna', 'cod', 'halibut', 'shrimp', 'crab', 'lobster', 'oyster',
    'clam', 'mussel', 'scallop', 'squid', 'octopus', 'tilapia', 'trout',
    'mackerel', 'sardine', 'anchovy', 'herring', 'snapper', 'bass', 'sea bass',
    'catfish', 'flounder', 'sole', 'mahi mahi', 'swordfish', 'grouper',
    'haddock', 'pollock', 'crawfish', 'prawn', 'crayfish', 'abalone',
    'sea urchin', 'caviar', 'eel', 'calamari', 'king crab', 'snow crab',
    'dungeness crab', 'blue crab', 'rock lobster', 'langoustine', 'cuttlefish',
    'monkfish', 'red snapper', 'yellowfin tuna', 'rainbow trout', 'whitefish',
  ],
  'Guitar brands': [
    'fender', 'gibson', 'ibanez', 'epiphone', 'gretsch', 'prs',
    'paul reed smith', 'jackson', 'esp', 'ltd', 'schecter', 'martin', 'taylor',
    'yamaha', 'rickenbacker', 'dean', 'washburn', 'guild', 'charvel', 'cort',
    'squier', 'ovation', 'seagull', 'takamine', 'breedlove', 'music man',
    'ernie ball', 'godin', 'kramer', 'bc rich', 'hagstrom', 'danelectro',
    'harmony', 'framus', 'duesenberg', 'eastman', 'larrivee', 'national',
    'tanglewood', 'sigma', 'mitchell', 'peavey', 'kiesel', 'chapman',
    'reverend', 'evh', 'suhr', 'sterling',
  ],
  'Cattle breeds': [
    'angus', 'aberdeen angus', 'red angus', 'black angus', 'hereford',
    'holstein', 'jersey', 'guernsey', 'brahman', 'charolais', 'simmental',
    'limousin', 'texas longhorn', 'highland', 'galloway', 'belted galloway',
    'shorthorn', 'ayrshire', 'brown swiss', 'dexter', 'wagyu', 'chianina',
    'gelbvieh', 'santa gertrudis', 'brangus', 'beefmaster', 'murray grey',
    'devon', 'red poll', 'sussex', 'welsh black', 'piedmontese', 'maine-anjou',
    'salers', 'pinzgauer', 'normande', 'montbeliarde', 'fleckvieh',
    'marchigiana', 'romagnola', 'nelore', 'gir', 'sahiwal', 'droughtmaster',
    'belgian blue', "blonde d'aquitaine", 'corriente', 'white park',
  ],
};
