// categoryAnswers/expand-econ-3.js  (data/accept-lists — batch 3, broad expansion)
// Union-merged supplement. Real members + variants only, <=3 words, deduped case-insensitively.
// Target 150-250 real entries for genuinely broad domains (no padding).
module.exports = {
  'Sitcom Characters': new Set([
    'ross', 'ross geller', 'rachel', 'rachel green', 'monica', 'monica geller', 'chandler',
    'chandler bing', 'joey', 'joey tribbiani', 'phoebe', 'phoebe buffay', 'gunther', 'janice',
    'michael scott', 'dwight', 'dwight schrute', 'jim', 'jim halpert', 'pam', 'pam beesly',
    'andy bernard', 'kevin malone', 'angela', 'oscar', 'stanley', 'creed', 'kelly kapoor', 'ryan',
    'toby', 'phyllis', 'meredith', 'darryl', 'erin', 'holly', 'jan', 'david wallace', 'nellie',
    'robert california', 'leslie knope', 'ron swanson', 'tom haverford', 'april ludgate', 'andy dwyer',
    'ben wyatt', 'chris traeger', 'jerry gergich', 'donna meagle', 'ann perkins', 'jean-ralphio',
    'jake peralta', 'amy santiago', 'rosa diaz', 'terry jeffords', 'captain holt', 'charles boyle',
    'gina linetti', 'hitchcock', 'scully', 'sheldon cooper', 'leonard', 'howard wolowitz', 'raj',
    'penny', 'amy farrah fowler', 'bernadette', 'stuart', 'barney stinson', 'barney', 'ted mosby',
    'ted', 'marshall eriksen', 'marshall', 'lily aldrin', 'lily', 'robin scherbatsky', 'robin',
    'homer simpson', 'homer', 'marge simpson', 'marge', 'bart simpson', 'bart', 'lisa simpson', 'lisa',
    'maggie simpson', 'ned flanders', 'mr burns', 'moe', 'barney gumble', 'krusty', 'milhouse',
    'apu', 'chief wiggum', 'ralph wiggum', 'peter griffin', 'lois griffin', 'stewie', 'stewie griffin',
    'brian griffin', 'chris griffin', 'meg griffin', 'quagmire', 'cleveland', 'joe swanson',
    'eric cartman', 'cartman', 'stan marsh', 'kyle broflovski', 'kenny', 'butters', 'randy marsh',
    'mr garrison', 'towelie', 'archie bunker', 'george jefferson', 'norm', 'cliff clavin', 'sam malone',
    'frasier crane', 'niles', 'roz', 'daphne', 'martin crane', 'george costanza', 'george', 'elaine',
    'elaine benes', 'kramer', 'cosmo kramer', 'newman', 'jerry seinfeld', 'jerry', 'dennis reynolds',
    'mac', 'charlie kelly', 'dee reynolds', 'frank reynolds', 'will smith', 'carlton', 'uncle phil',
    'geoffrey', 'hilary banks', 'ashley banks', 'vivian banks', 'jack pearson', 'al bundy', 'peg bundy',
    'kelly bundy', 'bud bundy', 'jd', 'turk', 'dr cox', 'carla', 'elliot', 'the janitor', 'bob kelso',
    'michael bluth', 'gob', 'buster', 'lucille bluth', 'tobias', 'lindsay', 'george michael', 'maeby',
    'jack donaghy', 'liz lemon', 'tracy jordan', 'kenneth', 'jenna maroney', 'abed', 'troy', 'britta',
    'jeff winger', 'annie', 'shirley', 'pierce', 'chang', 'dean pelton', 'ted lasso', 'roy kent',
    'keeley', 'rebecca welton', 'coach beard', 'nate', 'jamie tartt', 'schmidt', 'nick miller',
    'winston', 'cece', 'jessica day', 'jess', 'coach', 'raymond', 'debra', 'marie barone', 'frank barone',
    'robert barone',
  ]),
  'DC Comics Superheroes': new Set([
    'superman', 'clark kent', 'kal-el', 'batman', 'bruce wayne', 'wonder woman', 'diana prince',
    'the flash', 'flash', 'barry allen', 'wally west', 'green lantern', 'hal jordan', 'john stewart',
    'aquaman', 'arthur curry', 'cyborg', 'victor stone', 'shazam', 'billy batson', 'green arrow',
    'oliver queen', 'black canary', 'martian manhunter', 'zatanna', 'hawkman', 'hawkgirl', 'the atom',
    'ray palmer', 'firestorm', 'blue beetle', 'jaime reyes', 'booster gold', 'plastic man', 'red tornado',
    'doctor fate', 'the spectre', 'nightwing', 'dick grayson', 'robin', 'tim drake', 'jason todd',
    'damian wayne', 'red hood', 'red robin', 'batgirl', 'barbara gordon', 'oracle', 'batwoman',
    'kate kane', 'huntress', 'spoiler', 'stephanie brown', 'orphan', 'cassandra cain', 'supergirl',
    'kara zor-el', 'power girl', 'superboy', 'conner kent', 'steel', 'john henry irons', 'krypto',
    'green lantern kyle', 'kyle rayner', 'guy gardner', 'kid flash', 'impulse', 'bart allen',
    'jesse quick', 'vixen', 'animal man', 'swamp thing', 'john constantine', 'constantine', 'raven',
    'starfire', 'beast boy', 'terra', 'kid devil', 'bumblebee', 'static', 'static shock', 'mister miracle',
    'big barda', 'orion', 'the question', 'renee montoya', 'batwing', 'katana', 'deadman', 'etrigan',
    'the demon', 'ragman', 'sandman', 'wesley dodds', 'starman', 'wildcat', 'hourman', 'doctor mid-nite',
    'jay garrick', 'alan scott', 'wonder girl', 'donna troy', 'cassie sandsmark', 'stargirl', 'courtney whitmore',
    's.t.r.i.p.e.', 'commander steel', 'metamorpho', 'element woman', 'the creeper', 'gangbuster',
    'azrael', 'jean-paul valley', 'huntress helena', 'lobo', 'captain atom', 'bloodwynd', 'obsidian',
    'jade', 'crimson avenger', 'mister terrific', 'michael holt', 'black lightning', 'jefferson pierce',
    'thunder', 'lightning', 'aqualad', 'garth', 'kaldur', 'tempest', 'mera', 'dolphin', 'the ray',
    'phantom stranger', 'zauriel', 'ambush bug', 'g\'nort', 'squire', 'the knight', 'gypsy', 'ice',
    'fire', 'rocket red', 'general glory', 'l-ron',
  ]),
  'Star Wars Characters': new Set([
    'luke skywalker', 'luke', 'darth vader', 'vader', 'anakin skywalker', 'anakin', 'leia', 'princess leia',
    'han solo', 'han', 'chewbacca', 'chewie', 'obi-wan kenobi', 'obi-wan', 'ben kenobi', 'yoda',
    'r2-d2', 'r2d2', 'c-3po', 'c3po', 'darth sidious', 'emperor palpatine', 'palpatine', 'darth maul',
    'count dooku', 'general grievous', 'grievous', 'qui-gon jinn', 'qui-gon', 'padme', 'padme amidala',
    'jar jar binks', 'mace windu', 'boba fett', 'jango fett', 'lando calrissian', 'lando', 'wedge antilles',
    'admiral ackbar', 'wicket', 'ewok', 'jabba the hutt', 'jabba', 'greedo', 'bib fortuna', 'salacious crumb',
    'nien nunb', 'rey', 'finn', 'poe dameron', 'poe', 'kylo ren', 'ben solo', 'bb-8', 'general hux',
    'captain phasma', 'supreme leader snoke', 'snoke', 'maz kanata', 'rose tico', 'dj', 'vice admiral holdo',
    'd-o', 'zorii bliss', 'jannah', 'the mandalorian', 'din djarin', 'mando', 'grogu', 'baby yoda',
    'cara dune', 'greef karga', 'moff gideon', 'kuiil', 'ig-11', 'fennec shand', 'bo-katan', 'ahsoka tano',
    'ahsoka', 'ezra bridger', 'kanan jarrus', 'hera syndulla', 'sabine wren', 'zeb', 'chopper', 'thrawn',
    'grand admiral thrawn', 'captain rex', 'commander cody', 'clone trooper', 'stormtrooper', 'jyn erso',
    'cassian andor', 'k-2so', 'chirrut imwe', 'baze malbus', 'bodhi rook', 'saw gerrera', 'director krennic',
    'grand moff tarkin', 'tarkin', 'general veers', 'admiral piett', 'shmi skywalker', 'owen lars',
    'beru lars', 'biggs darklighter', 'general dodonna', 'mon mothma', 'bail organa', 'jocasta nu',
    'ki-adi-mundi', 'plo koon', 'kit fisto', 'aayla secura', 'shaak ti', 'luminara unduli', 'barriss offee',
    'even piell', 'eeth koth', 'agen kolar', 'yaddle', 'asajj ventress', 'savage opress', 'cad bane',
    'hondo ohnaka', 'the grand inquisitor', 'reva', 'the third sister', 'enfys nest', 'qi\'ra', 'l3-37',
    'val', 'rio durant', 'dryden vos', 'watto', 'sebulba', 'nute gunray', 'wat tambor', 'poggle the lesser',
    'sio bibble', 'captain panaka', 'dexter jettster', 'zam wesell', 'taun we', 'lama su',
  ]),
  'Mexican food dishes': new Set([
    'taco', 'tacos', 'taco al pastor', 'tacos al pastor', 'carne asada', 'carnitas', 'barbacoa',
    'burrito', 'burritos', 'chimichanga', 'quesadilla', 'quesadillas', 'enchilada', 'enchiladas',
    'tamale', 'tamales', 'nachos', 'guacamole', 'guac', 'salsa', 'pico de gallo', 'queso', 'chile relleno',
    'chiles rellenos', 'tostada', 'tostadas', 'sope', 'sopes', 'huarache', 'gordita', 'gorditas',
    'flauta', 'flautas', 'taquito', 'taquitos', 'fajita', 'fajitas', 'mole', 'mole poblano', 'pozole',
    'menudo', 'birria', 'birria tacos', 'tortilla soup', 'elote', 'esquites', 'tlayuda', 'cemita',
    'torta', 'tortas', 'tacos de lengua', 'tacos de carnitas', 'tacos dorados', 'chilaquiles',
    'huevos rancheros', 'migas', 'machaca', 'cochinita pibil', 'tinga', 'chorizo', 'refried beans',
    'frijoles', 'arroz', 'mexican rice', 'spanish rice', 'ceviche', 'aguachile', 'camarones', 'fish tacos',
    'shrimp tacos', 'al pastor', 'tacos de pescado', 'nopales', 'tacos de birria', 'consomme', 'menudo rojo',
    'caldo de res', 'sopa de fideo', 'tortilla chips', 'churro', 'churros', 'tres leches', 'flan',
    'conchas', 'pan dulce', 'buñuelos', 'sopapilla', 'sopapillas', 'horchata', 'agua fresca', 'jarritos',
    'michelada', 'margarita', 'paloma', 'tostones', 'empanada', 'empanadas', 'chalupa', 'chalupas',
    'molletes', 'queso fundido', 'chile verde', 'chile colorado', 'pozole verde', 'pozole rojo', 'menudo blanco',
    'tacos de asada', 'tacos de suadero', 'suadero', 'lengua', 'tripas', 'buche', 'cabeza', 'chicharron',
    'chicharrones', 'tacos de pollo', 'pollo asado', 'carne guisada', 'picadillo', 'rajas', 'calabacitas',
    'nopalitos', 'frijoles charros', 'frijoles refritos', 'arroz con pollo', 'mexican street corn',
    'tacos de canasta', 'gorditas de nata', 'pambazo', 'tacos de camaron', 'aguas frescas', 'tamarindo',
    'jamaica', 'atole', 'champurrado', 'capirotada', 'arroz con leche', 'paletas', 'raspados',
  ]),
  'Vegetables': new Set([
    'carrot', 'carrots', 'potato', 'potatoes', 'tomato', 'tomatoes', 'onion', 'onions', 'garlic',
    'broccoli', 'brocoli', 'cauliflower', 'cabbage', 'lettuce', 'spinach', 'kale', 'celery', 'cucumber',
    'cucumbers', 'zucchini', 'squash', 'butternut squash', 'pumpkin', 'eggplant', 'aubergine', 'pepper',
    'peppers', 'bell pepper', 'bell peppers', 'jalapeno', 'jalapeño', 'chili pepper', 'corn', 'peas',
    'green beans', 'string beans', 'asparagus', 'artichoke', 'artichokes', 'beet', 'beets', 'beetroot',
    'radish', 'radishes', 'turnip', 'turnips', 'parsnip', 'parsnips', 'rutabaga', 'sweet potato',
    'sweet potatoes', 'yam', 'yams', 'okra', 'brussels sprouts', 'brussel sprouts', 'leek', 'leeks',
    'scallion', 'scallions', 'green onion', 'shallot', 'shallots', 'chard', 'swiss chard', 'collard greens',
    'mustard greens', 'arugula', 'watercress', 'endive', 'radicchio', 'fennel', 'bok choy', 'napa cabbage',
    'snow peas', 'snap peas', 'sugar snap peas', 'lima beans', 'edamame', 'bean sprouts', 'mushroom',
    'mushrooms', 'ginger', 'horseradish', 'jicama', 'kohlrabi', 'daikon', 'water chestnut', 'bamboo shoots',
    'cassava', 'taro', 'plantain', 'chayote', 'tomatillo', 'romaine', 'iceberg lettuce', 'butter lettuce',
    'red cabbage', 'acorn squash', 'spaghetti squash', 'yellow squash', 'delicata squash', 'kabocha',
    'red pepper', 'green pepper', 'yellow pepper', 'poblano', 'serrano', 'habanero', 'anaheim pepper',
    'banana pepper', 'pimento', 'baby carrots', 'new potatoes', 'russet potato', 'red potato', 'yukon gold',
    'fingerling potato', 'purple potato', 'chives', 'watercress', 'dandelion greens', 'nettle',
    'purslane', 'sorrel', 'rapini', 'broccolini', 'broccoli rabe', 'romanesco', 'cardoon', 'salsify',
    'sunchoke', 'jerusalem artichoke',
  ]),
  'Trees': new Set([
    'oak', 'oak tree', 'maple', 'maple tree', 'pine', 'pine tree', 'birch', 'willow', 'weeping willow',
    'elm', 'ash', 'beech', 'cedar', 'redwood', 'sequoia', 'giant sequoia', 'douglas fir', 'fir', 'spruce',
    'cypress', 'juniper', 'poplar', 'aspen', 'quaking aspen', 'sycamore', 'walnut', 'chestnut', 'hickory',
    'pecan', 'hazelnut', 'almond', 'cherry', 'cherry tree', 'apple', 'apple tree', 'pear', 'peach', 'plum',
    'apricot', 'fig', 'olive', 'olive tree', 'lemon', 'lime', 'orange', 'orange tree', 'grapefruit',
    'mango', 'avocado', 'banana', 'coconut', 'coconut palm', 'palm', 'palm tree', 'date palm', 'baobab',
    'mahogany', 'teak', 'ebony', 'rosewood', 'bamboo', 'eucalyptus', 'acacia', 'magnolia', 'dogwood',
    'redbud', 'crabapple', 'hawthorn', 'holly', 'yew', 'ginkgo', 'sequoia', 'joshua tree', 'banyan',
    'rubber tree', 'mangrove', 'catalpa', 'linden', 'basswood', 'hornbeam', 'cottonwood', 'buckeye',
    'horse chestnut', 'sweetgum', 'tulip tree', 'sassafras', 'persimmon', 'mulberry', 'quince', 'pomegranate',
    'jacaranda', 'flame tree', 'poinciana', 'cypress', 'larch', 'tamarack', 'hemlock', 'balsam fir',
    'blue spruce', 'white pine', 'scots pine', 'loblolly pine', 'ponderosa pine', 'lodgepole pine',
    'sugar maple', 'red maple', 'silver maple', 'japanese maple', 'norway maple', 'white oak', 'red oak',
    'live oak', 'pin oak', 'bur oak', 'cork oak', 'weeping cherry', 'kapok', 'ironwood', 'gum tree',
    'monkey puzzle', 'sandalwood', 'balsa', 'boxwood', 'laurel', 'bay laurel', 'myrtle', 'oleander',
    'wisteria', 'lilac', 'witch hazel', 'serviceberry', 'hackberry', 'mimosa',
  ]),
  'Mythical creatures': new Set([
    'dragon', 'dragons', 'unicorn', 'unicorns', 'phoenix', 'griffin', 'gryphon', 'centaur', 'minotaur',
    'medusa', 'cyclops', 'pegasus', 'chimera', 'hydra', 'kraken', 'mermaid', 'merman', 'siren', 'sirens',
    'fairy', 'fairies', 'pixie', 'elf', 'elves', 'dwarf', 'dwarves', 'goblin', 'goblins', 'troll', 'trolls',
    'ogre', 'orc', 'orcs', 'gnome', 'leprechaun', 'banshee', 'werewolf', 'werewolves', 'vampire', 'vampires',
    'zombie', 'ghost', 'ghosts', 'ghoul', 'wraith', 'poltergeist', 'basilisk', 'wyvern', 'cockatrice',
    'manticore', 'sphinx', 'harpy', 'harpies', 'satyr', 'faun', 'nymph', 'naiad', 'dryad', 'gorgon',
    'cerberus', 'cyclopes', 'giant', 'giants', 'titan', 'titans', 'yeti', 'bigfoot', 'sasquatch', 'wendigo',
    'chupacabra', 'loch ness monster', 'nessie', 'jackalope', 'kelpie', 'selkie', 'leviathan', 'behemoth',
    'golem', 'gargoyle', 'imp', 'demon', 'demons', 'djinn', 'genie', 'ifrit', 'roc', 'thunderbird',
    'quetzalcoatl', 'kitsune', 'tengu', 'oni', 'yokai', 'kappa', 'kirin', 'qilin', 'jorogumo', 'nekomata',
    'dullahan', 'changeling', 'brownie', 'boggart', 'redcap', 'will-o-the-wisp', 'jinn', 'salamander',
    'undine', 'sylph', 'hippogriff', 'hippocampus', 'ouroboros', 'amphisbaena', 'lamia', 'echidna',
    'typhon', 'scylla', 'charybdis', 'cyclops polyphemus', 'nemean lion', 'stymphalian birds', 'ceryneian hind',
    'lernaean hydra', 'firebird', 'baba yaga', 'krampus', 'valkyrie', 'fenrir', 'jormungandr', 'nidhogg',
    'huldra', 'nisse', 'draugr', 'rusalka', 'domovoi', 'leshy', 'baku', 'nue', 'gashadokuro', 'shapeshifter',
    'lich', 'skeleton', 'mummy', 'frankenstein', 'incubus', 'succubus', 'gremlin', 'gremlins', 'brownie',
    'cait sith', 'pooka', 'bunyip', 'drop bear', 'thunderbird', 'wendigo', 'skinwalker',
  ]),
  'Ocean animals': new Set([
    'shark', 'sharks', 'great white shark', 'hammerhead shark', 'tiger shark', 'whale', 'whales',
    'blue whale', 'humpback whale', 'sperm whale', 'orca', 'killer whale', 'dolphin', 'dolphins',
    'porpoise', 'octopus', 'squid', 'giant squid', 'cuttlefish', 'nautilus', 'jellyfish', 'jelly',
    'starfish', 'sea star', 'sea urchin', 'sea cucumber', 'crab', 'crabs', 'hermit crab', 'king crab',
    'lobster', 'shrimp', 'prawn', 'krill', 'barnacle', 'clam', 'clams', 'oyster', 'oysters', 'mussel',
    'mussels', 'scallop', 'snail', 'sea snail', 'conch', 'sea slug', 'nudibranch', 'coral', 'anemone',
    'sea anemone', 'sponge', 'sea sponge', 'stingray', 'manta ray', 'ray', 'eel', 'moray eel', 'electric eel',
    'seahorse', 'sea horse', 'pufferfish', 'blowfish', 'clownfish', 'angelfish', 'butterflyfish', 'lionfish',
    'grouper', 'snapper', 'tuna', 'bluefin tuna', 'swordfish', 'marlin', 'sailfish', 'barracuda', 'mackerel',
    'sardine', 'anchovy', 'herring', 'cod', 'haddock', 'halibut', 'flounder', 'sole', 'salmon', 'trout',
    'catfish', 'sea turtle', 'green sea turtle', 'leatherback turtle', 'loggerhead turtle', 'seal', 'seals',
    'sea lion', 'walrus', 'manatee', 'dugong', 'sea otter', 'penguin', 'penguins', 'pelican', 'seagull',
    'albatross', 'cormorant', 'puffin', 'narwhal', 'beluga whale', 'gray whale', 'minke whale', 'right whale',
    'fin whale', 'pilot whale', 'bottlenose dolphin', 'spinner dolphin', 'whale shark', 'nurse shark',
    'bull shark', 'mako shark', 'reef shark', 'lemon shark', 'goblin shark', 'basking shark', 'megalodon',
    'anglerfish', 'viperfish', 'gulper eel', 'giant isopod', 'horseshoe crab', 'sand dollar', 'brittle star',
    'mantis shrimp', 'krill', 'plankton', 'copepod', 'sea dragon', 'leafy sea dragon', 'weedy sea dragon',
    'triggerfish', 'parrotfish', 'wrasse', 'damselfish', 'goby', 'blenny', 'remora', 'tang', 'surgeonfish',
    'moorish idol', 'batfish', 'sunfish', 'mola mola', 'stonefish', 'scorpionfish', 'wolffish',
  ]),
  'Lord of the Rings characters': new Set([
    'frodo', 'frodo baggins', 'sam', 'samwise', 'samwise gamgee', 'gandalf', 'gandalf the grey',
    'gandalf the white', 'aragorn', 'strider', 'legolas', 'gimli', 'boromir', 'merry', 'meriadoc',
    'pippin', 'peregrin took', 'bilbo', 'bilbo baggins', 'gollum', 'smeagol', 'sauron', 'saruman',
    'gríma', 'wormtongue', 'grima wormtongue', 'elrond', 'galadriel', 'celeborn', 'arwen', 'eowyn',
    'eomer', 'theoden', 'denethor', 'faramir', 'treebeard', 'tom bombadil', 'goldberry', 'the witch-king',
    'witch king', 'nazgul', 'ringwraith', 'ringwraiths', 'shelob', 'gothmog', 'the balrog', 'balrog',
    'radagast', 'radagast the brown', 'thranduil', 'haldir', 'glorfindel', 'gil-galad', 'isildur',
    'elendil', 'anarion', 'thorin', 'thorin oakenshield', 'balin', 'dwalin', 'fili', 'kili', 'oin',
    'gloin', 'bombur', 'bofur', 'bifur', 'dori', 'nori', 'ori', 'beorn', 'bard', 'bard the bowman',
    'smaug', 'azog', 'bolg', 'the great goblin', 'goblin king', 'grishnakh', 'ugluk', 'lurtz', 'sharku',
    'mouth of sauron', 'celebrimbor', 'feanor', 'fingolfin', 'morgoth', 'melkor', 'ungoliant', 'earendil',
    'luthien', 'beren', 'turin', 'hurin', 'tuor', 'idril', 'maedhros', 'maglor', 'thingol', 'melian',
    'ecthelion', 'glorfindel', 'rosie cotton', 'rosie', 'lobelia', 'ted sandyman', 'farmer maggot',
    'butterbur', 'barliman butterbur', 'shadowfax', 'bill the pony', 'the fellowship', 'quickbeam',
    'fangorn', 'deagol', 'gorbag', 'shagrat', 'snaga', 'mablung', 'damrod', 'beregond', 'ioreth',
    'hama', 'gamling', 'grimbold', 'erkenbrand', 'halbarad', 'elladan', 'elrohir', 'gildor',
  ]),
  'Horror Movie Characters': new Set([
    'freddy krueger', 'freddy', 'jason voorhees', 'jason', 'michael myers', 'leatherface', 'chucky',
    'ghostface', 'sidney prescott', 'gale weathers', 'dewey', 'randy', 'pennywise', 'georgie', 'bill denbrough',
    'beverly marsh', 'norman bates', 'marion crane', 'hannibal lecter', 'clarice starling', 'buffalo bill',
    'jigsaw', 'john kramer', 'amanda young', 'nancy thompson', 'tommy jarvis', 'laurie strode',
    'dr loomis', 'sam loomis', 'annie', 'lynda', 'tina', 'regan macneil', 'father karras', 'father merrin',
    'chris macneil', 'carrie white', 'sue snell', 'billy nolan', 'margaret white', 'ellen ripley', 'ripley',
    'ash williams', 'ash', 'annie wilkes', 'paul sheldon', 'jack torrance', 'wendy torrance', 'danny torrance',
    'dick hallorann', 'damien thorn', 'father brennan', 'rosemary woodhouse', 'guy woodhouse', 'the babadook',
    'amelia', 'samuel', 'samara', 'rachel keller', 'aidan', 'kayako', 'toshio', 'karen davis', 'annabelle',
    'ed warren', 'lorraine warren', 'father merrin', 'valak', 'sister irene', 'gabe', 'adelaide wilson',
    'red', 'chris washington', 'rose armitage', 'rod williams', 'the tethered', 'grace le domas', 'daniel',
    'thomasin', 'black phillip', 'dani ardor', 'christian', 'pelle', 'josh', 'mark', 'the entity', 'lily',
    'art the clown', 'victoria', 'sam', 'carrie', 'brahms', 'greta', 'esther', 'kate coleman', 'john coleman',
    'megan', 'gemma', 'katie', 'micah', 'kristi', 'annie graham', 'peter graham', 'charlie graham',
    'steve graham', 'joan', 'sadie', 'wednesday', 'the shape', 'stu macher', 'billy loomis', 'roman bridger',
    'jill roberts', 'kirby reed', 'tara carpenter', 'sam carpenter', 'amber freeman', 'chad meeks-martin',
    'mindy meeks-martin', 'kevin mccallister',
  ]),
  'Animated TV Shows': new Set([
    'the simpsons', 'family guy', 'south park', 'american dad', 'bobs burgers', "bob's burgers",
    'king of the hill', 'futurama', 'rick and morty', 'archer', 'bojack horseman', 'big mouth',
    'f is for family', 'disenchantment', 'the great north', 'solar opposites', 'spongebob',
    'spongebob squarepants', 'rugrats', 'hey arnold', 'the wild thornberrys', 'doug', 'ren and stimpy',
    'rocko\'s modern life', 'catdog', 'aaahh real monsters', 'the fairly oddparents', 'jimmy neutron',
    'danny phantom', 'invader zim', 'avatar the last airbender', 'the legend of korra', 'teenage mutant ninja turtles',
    'tmnt', 'dexter\'s laboratory', 'the powerpuff girls', 'powerpuff girls', 'johnny bravo', 'cow and chicken',
    'ed edd n eddy', 'courage the cowardly dog', 'samurai jack', 'foster\'s home for imaginary friends',
    'codename kids next door', 'the grim adventures of billy and mandy', 'billy and mandy', 'chowder',
    'the marvelous misadventures of flapjack', 'adventure time', 'regular show', 'the amazing world of gumball',
    'steven universe', 'clarence', 'we bare bears', 'over the garden wall', 'craig of the creek',
    'infinity train', 'gravity falls', 'phineas and ferb', 'kim possible', 'american dragon jake long',
    'the proud family', 'lilo and stitch the series', 'recess', 'pepper ann', 'gargoyles', 'ducktales',
    'darkwing duck', 'chip n dale rescue rangers', 'tailspin', 'goof troop', 'the wonderful world of mickey mouse',
    'looney tunes', 'tom and jerry', 'scooby doo', 'the flintstones', 'the jetsons', 'yogi bear',
    'the smurfs', 'he-man', 'she-ra', 'thundercats', 'transformers', 'g.i. joe', 'x-men the animated series',
    'spider-man the animated series', 'batman the animated series', 'justice league', 'teen titans',
    'teen titans go', 'young justice', 'ben 10', 'generator rex', 'star wars the clone wars', 'star wars rebels',
    'bluey', 'peppa pig', 'paw patrol', 'dora the explorer', 'blues clues', 'arthur', 'wild kratts',
    'the loud house', 'sanjay and craig', 'harvey beaks', 'pig goat banana cricket', 'total drama island',
    '6teen', 'stoked', 'my little pony', 'winx club', 'w.i.t.c.h', 'daria', 'beavis and butthead',
    'aqua teen hunger force', 'metalocalypse', 'robot chicken', 'the venture bros', 'superjail',
    'harley quinn', 'primal', 'castlevania', 'arcane', 'love death and robots', 'hazbin hotel',
    'helluva boss', 'the owl house', 'amphibia', 'star vs the forces of evil', 'wander over yonder',
  ]),
};
