// categoryAnswers/expand-econ-1.js  (data/accept-lists — batch 1)
// Union-merged SUPPLEMENT (registered in categoryAnswers.js's `supplements` list, so
// these ADD to the existing curated lists rather than replacing them). Only genuinely
// real members + common variants (plurals / lowercase / partial names / alt spellings),
// all <= 3 words, deduped case-insensitively. Broad, mainstream domains chosen for high
// confidence — NO padding with obscure or invented entries (quality rule).
module.exports = {
  // Broad, well-known TV comedies (US + UK + animated sitcoms). ~130 real titles.
  'Sitcoms': new Set([
    'friends', 'seinfeld', 'the office', 'the office us', 'the office uk', 'parks and recreation',
    'parks and rec', '30 rock', 'community', 'brooklyn nine nine', 'brooklyn 99', 'b99',
    'arrested development', "it's always sunny", 'always sunny', "it's always sunny in philadelphia",
    'curb your enthusiasm', 'curb', 'cheers', 'frasier', 'how i met your mother', 'himym',
    'the big bang theory', 'big bang theory', 'young sheldon', 'modern family', 'new girl',
    'the good place', 'superstore', 'scrubs', 'that 70s show', "that '70s show", 'that 90s show',
    'malcolm in the middle', 'everybody loves raymond', 'king of queens', 'the king of queens',
    'two and a half men', 'will and grace', 'fresh prince', 'the fresh prince of bel air',
    'fresh prince of bel air', 'family matters', 'full house', 'fuller house', 'home improvement',
    'married with children', 'roseanne', 'the conners', 'blackish', 'black-ish', 'the goldbergs',
    'spin city', 'mom', 'mike and molly', 'the middle', 'happy days', 'i love lucy',
    'the honeymooners', 'mash', 'm*a*s*h', 'taxi', 'night court', 'wkrp in cincinnati',
    "three's company", 'the mary tyler moore show', 'murphy brown', 'the golden girls', 'golden girls',
    'designing women', 'sanford and son', 'the jeffersons', 'good times', 'all in the family',
    'welcome back kotter', 'laverne and shirley', 'mork and mindy', "gilligan's island",
    'the brady bunch', 'bewitched', 'the andy griffith show', 'the dick van dyke show',
    'fawlty towers', 'blackadder', 'only fools and horses', 'the it crowd', 'it crowd', 'peep show',
    'the inbetweeners', 'mr bean', 'are you being served', "dad's army", 'absolutely fabulous',
    'ab fab', 'the vicar of dibley', 'gavin and stacey', 'spaced', 'black books', 'coupling',
    'red dwarf', 'keeping up appearances', 'one foot in the grave', 'veep', 'silicon valley',
    'ted lasso', 'abbott elementary', "schitt's creek", 'schitts creek', 'what we do in the shadows',
    'barry', 'atlanta', 'master of none', 'insecure', 'girls', 'broad city',
    'unbreakable kimmy schmidt', 'grace and frankie', 'the marvelous mrs maisel', 'mrs maisel',
    'hacks', 'only murders in the building', 'pen15', 'dead to me', 'workaholics', 'portlandia',
    'key and peele', "chappelle's show", 'kenan', 'the neighborhood', 'happy endings', 'cougar town',
    'the mindy project', 'the simpsons', 'family guy', "bob's burgers", 'bobs burgers',
    'king of the hill', 'futurama', 'american dad', 'the drew carey show', 'everybody hates chris',
    'my name is earl', 'raising hope', 'the office space', 'ghosts', 'ghosts uk', 'derry girls',
    'the good life', 'seinfeld', 'martin', 'living single', 'a different world', 'the cosby show',
    'family ties', 'growing pains', 'diff\'rent strokes', 'the facts of life', 'saved by the bell',
    'boy meets world', 'girl meets world', 'sabrina the teenage witch', 'hannah montana',
    'wizards of waverly place', 'suite life of zack and cody', "drake and josh",
  ]),

  // Real animated feature films (Disney / Pixar / DreamWorks / Illumination / studio Ghibli /
  // Sony / classic + international). ~140 real titles.
  'Animated Movies': new Set([
    'toy story', 'toy story 2', 'toy story 3', 'toy story 4', 'finding nemo', 'finding dory',
    'the incredibles', 'incredibles 2', 'monsters inc', 'monsters university', 'up', 'wall-e', 'wall e',
    'ratatouille', 'brave', 'inside out', 'inside out 2', 'coco', 'soul', 'luca', 'turning red',
    'onward', 'the good dinosaur', 'a bugs life', "a bug's life", 'cars', 'cars 2', 'cars 3',
    'elemental', 'lightyear', 'the lion king', 'aladdin', 'beauty and the beast', 'the little mermaid',
    'cinderella', 'snow white', 'sleeping beauty', 'pinocchio', 'dumbo', 'bambi', 'peter pan',
    'lady and the tramp', 'one hundred and one dalmatians', '101 dalmatians', 'the jungle book',
    'the aristocats', 'robin hood', 'the fox and the hound', 'the great mouse detective',
    'the little mermaid', 'the rescuers', 'oliver and company', 'the hunchback of notre dame',
    'hercules', 'mulan', 'tarzan', 'the emperors new groove', "the emperor's new groove", 'lilo and stitch',
    'treasure planet', 'brother bear', 'home on the range', 'chicken little', 'meet the robinsons',
    'bolt', 'the princess and the frog', 'tangled', 'wreck-it ralph', 'ralph breaks the internet',
    'frozen', 'frozen 2', 'big hero 6', 'zootopia', 'moana', 'moana 2', 'raya and the last dragon',
    'encanto', 'strange world', 'wish', 'fantasia', 'the sword in the stone', 'the black cauldron',
    'shrek', 'shrek 2', 'shrek the third', 'shrek forever after', 'puss in boots',
    'puss in boots the last wish', 'how to train your dragon', 'how to train your dragon 2',
    'kung fu panda', 'kung fu panda 2', 'kung fu panda 3', 'kung fu panda 4', 'madagascar',
    'madagascar 2', 'madagascar 3', 'penguins of madagascar', 'the croods', 'trolls', 'trolls world tour',
    'megamind', 'monsters vs aliens', 'over the hedge', 'bee movie', 'antz', 'the prince of egypt',
    'spirit stallion of the cimarron', 'the road to el dorado', 'sinbad', 'flushed away',
    'rise of the guardians', 'home', 'the boss baby', 'abominable', 'spirit untamed',
    'the bad guys', 'ruby gillman', 'despicable me', 'despicable me 2', 'despicable me 3',
    'despicable me 4', 'minions', 'minions the rise of gru', 'the secret life of pets',
    'the secret life of pets 2', 'sing', 'sing 2', 'the lorax', 'the grinch', 'hop',
    'spirited away', 'my neighbor totoro', 'princess mononoke', "howl's moving castle",
    'kikis delivery service', "kiki's delivery service", 'ponyo', 'castle in the sky', 'nausicaa',
    'the wind rises', 'grave of the fireflies', 'the boy and the heron', 'spider-man into the spider-verse',
    'into the spider-verse', 'spider-man across the spider-verse', 'across the spider-verse',
    'the mitchells vs the machines', 'cloudy with a chance of meatballs', 'hotel transylvania',
    'the lego movie', 'the lego batman movie', 'rango', 'happy feet', 'the polar express',
    'coraline', 'paranorman', 'the boxtrolls', 'kubo and the two strings', 'corpse bride',
    'the nightmare before christmas', 'james and the giant peach', 'isle of dogs', 'fantastic mr fox',
    'the iron giant', 'anastasia', 'balto', 'the land before time', 'an american tail',
    'watership down', 'the secret of nimh', 'akira', 'your name', 'weathering with you',
    'the wild robot', 'klaus', 'the sea beast', 'nimona', 'wallace and gromit',
    'chicken run', 'shaun the sheep movie',
  ]),

  // Real Indian dishes (North + South + street food + sweets). ~150 real dishes.
  'Indian food dishes': new Set([
    'biryani', 'chicken biryani', 'mutton biryani', 'hyderabadi biryani', 'veg biryani', 'samosa',
    'samosas', 'aloo samosa', 'pakora', 'pakoras', 'onion bhaji', 'bhaji', 'naan', 'garlic naan',
    'butter naan', 'roti', 'chapati', 'paratha', 'aloo paratha', 'puri', 'poori', 'bhatura',
    'chole bhature', 'dosa', 'masala dosa', 'plain dosa', 'rava dosa', 'idli', 'idly', 'vada',
    'medu vada', 'uttapam', 'upma', 'poha', 'dal', 'daal', 'dal makhani', 'dal tadka', 'chana masala',
    'chole', 'rajma', 'kadhi', 'sambar', 'rasam', 'butter chicken', 'murgh makhani', 'chicken tikka',
    'chicken tikka masala', 'tikka masala', 'tandoori chicken', 'chicken 65', 'chicken korma', 'korma',
    'rogan josh', 'lamb rogan josh', 'vindaloo', 'chicken vindaloo', 'saag', 'palak paneer', 'saag paneer',
    'paneer', 'paneer tikka', 'paneer butter masala', 'shahi paneer', 'matar paneer', 'kadai paneer',
    'malai kofta', 'kofta', 'aloo gobi', 'aloo matar', 'baingan bharta', 'bhindi masala', 'jeera rice',
    'pulao', 'pilau', 'veg pulao', 'kheer', 'gulab jamun', 'jalebi', 'jalebis', 'rasgulla', 'rasmalai',
    'barfi', 'burfi', 'kaju katli', 'ladoo', 'laddu', 'besan ladoo', 'motichoor ladoo', 'halwa',
    'gajar halwa', 'carrot halwa', 'suji halwa', 'peda', 'mysore pak', 'sandesh', 'kulfi', 'falooda',
    'lassi', 'mango lassi', 'sweet lassi', 'salted lassi', 'masala chai', 'chai', 'filter coffee',
    'pani puri', 'gol gappa', 'golgappa', 'puchka', 'bhel puri', 'sev puri', 'dahi puri', 'papdi chaat',
    'aloo tikki', 'ragda pattice', 'vada pav', 'pav bhaji', 'misal pav', 'dabeli', 'kachori',
    'raj kachori', 'dhokla', 'khaman', 'thepla', 'khandvi', 'fafda', 'khakhra', 'handvo', 'undhiyu',
    'gujarati thali', 'thali', 'rajma chawal', 'kadhi chawal', 'khichdi', 'khichdi', 'dal baati',
    'baati', 'litti chokha', 'sarson ka saag', 'makki di roti', 'amritsari kulcha', 'kulcha',
    'chicken curry', 'fish curry', 'goan fish curry', 'prawn curry', 'egg curry', 'keema', 'keema matar',
    'nihari', 'haleem', 'seekh kebab', 'shami kebab', 'galouti kebab', 'kathi roll', 'frankie',
    'egg roll', 'tandoori roti', 'laccha paratha', 'malabar paratha', 'appam', 'idiyappam', 'puttu',
    'avial', 'thoran', 'kerala fish curry', 'chettinad chicken', 'pongal', 'lemon rice', 'curd rice',
    'bisi bele bath', 'ven pongal', 'coconut chutney', 'mint chutney', 'raita', 'boondi raita',
    'gobi manchurian', 'chilli chicken', 'chilli paneer', 'hakka noodles', 'schezwan fried rice',
    'modak', 'shrikhand', 'basundi', 'phirni', 'rabri', 'malpua', 'imarti', 'ghevar', 'soan papdi',
    'chikki', 'namak para', 'mathri', 'chakli', 'murukku', 'sev', 'chivda',
  ]),

  // Real, well-known HORROR-FILM monsters/villains (movie only, no TV). ~120 real entries.
  'Horror Movie Monsters': new Set([
    'freddy krueger', 'freddy', 'jason voorhees', 'jason', 'michael myers', 'leatherface', 'pinhead',
    'chucky', 'ghostface', 'pennywise', 'it', 'dracula', 'count dracula', 'frankenstein',
    "frankenstein's monster", 'the mummy', 'the wolfman', 'wolfman', 'the werewolf', 'werewolf',
    'creature from the black lagoon', 'gill-man', 'the blob', 'the fly', 'seth brundle', 'brundlefly',
    'the thing', 'xenomorph', 'the alien', 'the predator', 'predator', 'norman bates', 'hannibal lecter',
    'jigsaw', 'billy the puppet', 'samara', 'the ring girl', 'the grudge', 'kayako', 'toshio',
    'pazuzu', 'the exorcist', 'regan', 'annabelle', 'the nun', 'valak', 'the babadook', 'babadook',
    'pyramid head', 'the tall man', 'candyman', 'the creeper', 'jeepers creepers', 'trick r treat sam',
    'sam', 'art the clown', 'terrifier', 'slender man', 'the boogeyman', 'bughuul', 'sinister',
    'krampus', 'the leprechaun', 'leprechaun', 'the djinn', 'wishmaster', 'gremlins', 'stripe',
    'the chupacabra', 'chupacabra', 'the wendigo', 'wendigo', 'the invisible man', 'mr hyde',
    'dr jekyll', 'the phantom', 'phantom of the opera', 'nosferatu', 'count orlok', 'the vampire',
    'vampires', 'the zombie', 'zombies', 'deadites', 'the deadites', 'the reanimated', 'herbert west',
    'swamp thing', 'the toxic avenger', 'the headless horseman', 'carrie', 'carrie white', 'damien',
    'the omen', 'rosemary\'s baby', 'the poltergeist', 'poltergeist', 'the pale man', 'the faun',
    'godzilla', 'king kong', 'kong', 'the kraken', 'the graboids', 'graboids', 'the mist creatures',
    'cthulhu', 'the reaper', 'grim reaper', 'the entity', 'the shape', 'the gentlemen',
    'the tooth fairy', 'the crawlers', 'the descent creatures', 'the birds', 'cujo', 'christine',
    'the car', 'bruce the shark', 'jaws', 'the great white', 'anaconda', 'the giant spider',
    'arachnophobia', 'the puppet master', 'the ventriloquist dummy', 'nurse ratched', 'the shark',
    'esther', 'orphan', 'the strangers', 'the purge masks', 'ma', 'm3gan', 'megan', 'smile entity',
    'the smiling man', 'the medusa', 'the gorgon', 'the golem', 'the dybbuk',
  ]),
};
