// expansion.js
// Supplemental accept-list entries that are UNION-MERGED into the existing
// category Sets (see categoryAnswers.js) to push every existing category past
// 200 valid answers. Kept separate so the original theme files stay readable.
// Same standard: 1-3 word noun answers for list categories, short on-tone
// phrases for the phrase categories; school-appropriate; common misspellings
// and abbreviations included. (Pixar movies is intentionally NOT here: only
// ~30 Pixar films exist, so it stays a documented finite exception.)
// All entries lowercase. Duplicates with the base sets are harmless (Set union).
module.exports = {
  'Things with a drive-through': new Set([
    'in n out', 'in-n-out', 'whataburger', 'sonic', 'dairy queen', 'dq', 'culvers', 'jack in the box', 'del taco', 'carls jr', 'hardees', 'white castle', 'checkers', 'rallys', 'bojangles', 'zaxbys', 'raising canes', 'canes', 'el pollo loco', 'popeyes', 'churchs chicken', 'long john silvers', 'captain ds', 'krystal', 'steak n shake', 'freddys', 'five guys', 'mcdonalds', 'burger king', 'wendys', 'taco bell', 'kfc', 'chick fil a', 'arbys', 'panda express', 'qdoba', 'wingstop', 'pizza hut', 'dominos', 'little caesars', 'papa johns', 'jollibee', 'baskin robbins', 'dutch bros', 'dunkin', 'dunkin donuts', 'tim hortons', 'krispy kreme', 'smoothie king', 'jamba juice', 'sheetz', 'wawa', 'quiktrip', 'a pharmacy', 'pharmacy', 'cvs pharmacy', 'walgreens pharmacy', 'a bank', 'bank teller', 'atm', 'car wash', 'liquor store', 'coffee shop', 'a vaccine clinic', 'covid testing', 'library book drop', 'a vegas wedding chapel', 'wedding chapel', 'biscuitville', 'cookout', 'shake shack', 'wienerschnitzel', 'taco johns', 'runza', 'braums', 'portillos', 'crumbl', 'crumbl cookies', 'scooters coffee', 'biggby', 'caribou coffee', 'sheetz coffee'
  ]),
  'Things you do when the WiFi goes out': new Set([
    'panic', 'restart the router', 'unplug the router', 'call comcast', 'call the wifi company', 'yell at the router', 'blame your sibling', 'blame your brother', 'blame your parents', 'check if its just you', 'use your data', 'turn on a hotspot', 'use mobile hotspot', 'go outside', 'touch grass', 'stare at the wall', 'take a nap', 'do homework', 'actually do homework', 'read a book', 'clean your room', 'talk to your family', 'reset the modem', 'move closer to the router', 'sit by the router', 'check the cables', 'refresh the page', 'rage quit', 'cry', 'scream into a pillow', 'play offline games', 'play solitaire', 'play minecraft offline', 'play the dino game', 'chrome dino game', 'watch downloaded netflix', 'reorganize your phone', 'delete apps', 'contemplate life', 'question everything', 'stare at the loading wheel', 'toggle airplane mode', 'forget the network', 'reconnect to wifi', 'unplug everything', 'count the router lights', 'go to bed early', 'drive to mcdonalds', 'go to the library', 'use the neighbors wifi', 'guess the neighbors password', 'flip the breaker', 'check the outage map', 'tweet about it', 'complain in the group chat', 'wave your phone around', 'walk around for signal', 'stand on one leg', 'hold the phone up high', 'pray', 'give up', 'eat a snack', 'pace around', 'bother the dog', 'stare out the window', 'reset everything twice', 'wait ten minutes', 'check every device'
  ]),
  'Florida man headlines': new Set([
    'florida man steals a bus', 'florida man wrestles a python', 'florida man eats a competitors car', 'florida man rides a cow', 'florida man punches a swan', 'florida man arrested at walmart', 'florida man steals a golf cart', 'florida man fights a peacock', 'florida man trapped in a vending machine', 'florida man steals a boat', 'florida man caught with a goat', 'florida man rides a horse drunk', 'florida man throws a chair at the ocean', 'florida man arrested for noodling', 'florida man steals a llama', 'florida man caught in a chimney', 'florida man fights a mailbox', 'florida man bites a cop', 'florida man eats a stop sign', 'florida man steals a lawn flamingo', 'florida man rides a shopping cart', 'florida man arrested for juggling knives', 'florida man caught wrestling a pig', 'florida man steals a snake', 'florida man dressed as a pirate', 'florida man challenges a swan to a fight', 'florida man trades a gator for a six pack', 'florida man crashes a parade float', 'florida man steals a fire truck', 'florida man fights a parking meter', 'florida man caught riding a manatee', 'florida man eats a parking sign', 'florida man arrested at a buffet again', 'florida man steals a hot air balloon', 'florida man caught with a raccoon in his shirt', 'florida man fights a garden gnome', 'florida man arrested for racing a train', 'florida man steals a zoo animal', 'florida man caught swimming in a fountain', 'florida man rides a jet ski into a store', 'florida man throws a fish at a cop', 'florida man arrested for selling fake tickets', 'florida man caught living in a treehouse', 'florida man steals a cop car', 'florida man fights a scarecrow', 'florida man arrested for crop circles', 'florida man rides a unicycle on the highway', 'florida man steals a parade balloon', 'florida man caught feeding gators hot dogs', 'florida man arrested for honking too much', 'florida man fights a pelican', 'florida man steals an entire reef', 'florida man caught surfing on a car', 'florida man arrested for moon howling', 'florida man bites a parking attendant', 'florida man steals a snow cone truck', 'florida man caught riding a gator down main street', 'florida man throws a coconut at a cop', 'florida man arrested for dancing in traffic', 'florida man steals a school mascot costume'
  ]),
  'Things confiscated by a teacher': new Set([
    'phone', 'cell phone', 'airpods', 'earbuds', 'headphones', 'fidget spinner', 'fidget toy', 'pop it', 'slime', 'silly putty', 'rubber band', 'paper football', 'note', 'a passed note', 'gum', 'candy', 'snacks', 'chips', 'energy drink', 'soda', 'water bottle', 'a laser pointer', 'laser pointer', 'a squirt gun', 'water gun', 'nerf gun', 'nerf darts', 'a yo yo', 'yo yo', 'pokemon cards', 'trading cards', 'baseball cards', 'a comic book', 'comic book', 'a magazine', 'a deck of cards', 'playing cards', 'dice', 'a phone charger', 'charger', 'a hat', 'a hood', 'a beanie', 'sunglasses', 'a skateboard', 'a hoverboard', 'a bouncy ball', 'a stress ball', 'a stapler', 'a marker', 'permanent marker', 'a sharpie', 'a whoopee cushion', 'silly string', 'a slingshot', 'spitballs', 'a paper airplane', 'a drawing', 'a doodle', 'a switchblade comb', 'a vape', 'vape', 'a lighter', 'a phone case', 'a stuffed animal', 'a beyblade', 'beyblade', 'a tamagotchi', 'a game boy', 'a nintendo switch', 'switch', 'a fidget cube', 'a magic 8 ball', 'a kazoo', 'a recorder', 'a slinky', 'a rubiks cube', 'a hacky sack', 'makeup', 'a mirror', 'nail polish', 'a selfie stick', 'a megaphone'
  ]),
  "Things in a 2010 kid's bedroom": new Set([
    'silly bandz', 'a wii', 'wii', 'a nintendo ds', 'nintendo ds', 'a psp', 'psp', 'an ipod touch', 'ipod touch', 'an ipod nano', 'club penguin', 'a webkinz', 'webkinz', 'a beyblade', 'beyblade', 'a nerf gun', 'nerf gun', 'a razor scooter', 'razor scooter', 'heelys', 'a justin bieber poster', 'justin bieber poster', 'a jonas brothers poster', 'a hannah montana poster', 'a high school musical poster', 'silly putty', 'a tamagotchi', 'bakugan', 'a moshi monster', 'moshi monsters', 'zhu zhu pets', 'a furby', 'furby', 'a bratz doll', 'bratz dolls', 'monster high dolls', 'monster high', 'a littlest pet shop', 'littlest pet shop', 'a build a bear', 'build a bear', 'pillow pets', 'a pillow pet', 'a snuggie', 'snuggie', 'a lava lamp', 'lava lamp', 'a bean bag chair', 'glow in the dark stars', 'a poster wall', 'an mp3 player', 'a flip phone', 'a sidekick', 'a blackberry', 'a wii remote', 'mario kart wii', 'just dance', 'rock band', 'guitar hero', 'a guitar hero guitar', 'a dsi', 'pokemon platinum', 'an xbox 360', 'xbox 360', 'a ps3', 'ps3', 'gushers', 'capri sun', 'a chevron pattern', 'a peace sign poster', 'duct tape wallet', 'rainbow loom', 'loom bands', 'an aero bed', 'sticky hands', 'a slap bracelet', 'slap bracelets', 'gel pens', 'a diary with a lock', 'silly bands', 'a smiley face rug', 'wall decals'
  ]),
  'What the dog ate': new Set([
    'my homework', 'homework', 'a shoe', 'shoes', 'a sock', 'socks', 'the couch', 'a couch cushion', 'a pillow', 'a remote', 'the tv remote', 'a phone', 'a phone charger', 'a charger', 'a wallet', 'cash', 'money', 'a dollar bill', 'a sandwich', 'a whole pizza', 'pizza', 'a chocolate bar', 'chocolate', 'grapes', 'an onion', 'a chicken bone', 'the trash', 'garbage', 'a diaper', 'a crayon', 'crayons', 'a marker', 'a sharpie', 'a pen', 'a pencil', 'an eraser', 'a book', 'a textbook', 'glasses', 'sunglasses', 'a tv cord', 'a wire', 'an earbud', 'an airpod', 'airpods', 'a stuffed animal', 'a toy', 'a squeaky toy', 'a ball', 'a tennis ball', 'a sock again', 'a hairbrush', 'a hair tie', 'a hearing aid', 'retainer', 'a retainer', 'dentures', 'a tampon', 'a bar of soap', 'soap', 'a bath bomb', 'a candle', 'lipstick', 'a tube of toothpaste', 'a roll of toilet paper', 'toilet paper', 'a face mask', 'a glove', 'a mitten', 'a hat', 'a flip flop', 'a slipper', 'a christmas ornament', 'an ornament', 'tinsel', 'a battery', 'a button', 'a magnet', 'a rock', 'mulch', 'a stick', 'dirt', 'a bee', 'a lizard', 'gum', 'a whole birthday cake', 'a stick of butter'
  ]),
  'Things at a gas station bathroom': new Set([
    'a broken sink', 'a broken lock', 'no toilet paper', 'an out of order sign', 'a wet floor', 'a wet floor sign', 'a flickering light', 'a single key', 'a key on a giant spoon', 'a key on a hubcap', 'a key on a board', 'a paper towel jam', 'an empty soap dispenser', 'a clogged toilet', 'graffiti', 'a sticky floor', 'a strange smell', 'a weird smell', 'a vending machine', 'a condom machine', 'a hand dryer', 'a broken hand dryer', 'a leaky faucet', 'a cracked mirror', 'a foggy mirror', 'one working stall', 'an out of order stall', 'a flickering bulb', 'a moth', 'a fly', 'a spider', 'a roach', 'a cockroach', 'a puddle', 'a mop bucket', 'a yellow caution sign', 'a chain on the toilet', 'a toilet that wont flush', 'an automatic flush gone wild', 'a janitors closet', 'a code on the door', 'a keypad lock', 'a buy something to use sign', 'rust', 'mystery stains', 'a single ply roll', 'an empty roll', 'a trash overflow', 'an overflowing trash can', 'a broken stall door', 'no stall door', 'a draft', 'a cold floor', 'a buzzing light', 'a air freshener', 'a urinal cake', 'a sign about employees washing hands', 'a tip jar', 'a swinging door', 'a squeaky door', 'a leak in the ceiling', 'a ceiling stain', 'a window painted shut', 'an ancient soap bar', 'a flyer for a band', 'a missing pet flyer', 'a phone number on the wall', 'a coat hook', 'no coat hook', 'a baby changing table', 'a broken changing table', 'a faucet that wont turn off', 'cold water only', 'no hot water', 'a bucket catching a drip'
  ]),
  'Cryptids in the woods at night': new Set([
    'bigfoot', 'sasquatch', 'the mothman', 'mothman', 'a skinwalker', 'skinwalker', 'the jersey devil', 'jersey devil', 'a wendigo', 'wendigo', 'chupacabra', 'the chupacabra', 'a dogman', 'dogman', 'the loch ness monster', 'nessie', 'a yeti', 'yeti', 'the abominable snowman', 'a goatman', 'goatman', 'the flatwoods monster', 'a banshee', 'banshee', 'a will o the wisp', 'the rake', 'rake', 'slenderman', 'a hellhound', 'hellhound', 'the beast of bray road', 'a swamp monster', 'swamp thing', 'the lizard man', 'lizard man', 'a thunderbird', 'thunderbird', 'the ozark howler', 'a shadow person', 'shadow people', 'the fresno nightcrawler', 'nightcrawler', 'a pukwudgie', 'pukwudgie', 'the snallygaster', 'a kelpie', 'the bunyip', 'mongolian death worm', 'the mokele mbembe', 'a wechuge', 'the dover demon', 'champ', 'the lake champlain monster', 'a chuchunya', 'the enfield monster', 'a glowing eyes', 'a pair of red eyes', 'a tall figure', 'a howling', 'a growl in the dark', 'a snapping twig', 'footsteps behind you', 'a deer with too many eyes', 'a screaming in the trees', 'an owl that isnt an owl', 'something watching you', 'a deformed deer', 'the not deer', 'not deer', 'a cackling laugh', 'a humanoid figure', 'a creature on all fours', 'a pale crawler', 'an upright dog', 'a winged figure', 'two glowing dots'
  ]),
  'Things a substitute teacher says': new Set([
    'im just the sub', 'i dont know the lesson plan', 'your teacher left a note', 'theres a worksheet', 'do the worksheet', 'find your seat', 'where do you normally sit', 'is this your assigned seat', 'i dont believe you', 'nice try', 'your teacher didnt mention that', 'i wasnt born yesterday', 'settle down', 'lets get started', 'attendance first', 'raise your hand if youre here', 'whats your name', 'i cant pronounce this', 'help me with the names', 'no phones please', 'put the phone away', 'your teacher will hear about this', 'im writing names down', 'im leaving a note', 'i have a list', 'youre on the list', 'be good for me', 'i just need to get through today', 'free period is not a thing', 'no you dont have a free period', 'sure your teacher lets you do that', 'i find that hard to believe', 'quiet down please', 'lets keep it down', 'eyes up here', 'work quietly', 'theres a movie', 'we can watch a movie if youre good', 'finish your work first', 'whoever talks loses the movie', 'i used to be a teacher', 'back in my day', 'one at a time', 'dont all talk at once', 'i only have so much patience', 'this is my first day', 'go easy on me', 'i need a volunteer', 'who can help me', 'wheres the bathroom pass', 'one person at a time for the bathroom', 'sign out if you leave', 'be back in five', 'the bell doesnt dismiss you i do', 'i dismiss you not the bell', 'have a seat', 'lower your voice', 'thats enough', 'im not playing today', 'try me', 'do i look new to you', 'your reputation precedes you'
  ]),
  "Ways to get sent to the principal's office": new Set([
    'talking back', 'cussing', 'cursing', 'fighting', 'throwing a chair', 'starting a food fight', 'a food fight', 'cheating', 'cheating on a test', 'plagiarism', 'skipping class', 'ditching', 'being late again', 'too many tardies', 'dress code violation', 'breaking dress code', 'vaping', 'vaping in the bathroom', 'smoking', 'pulling the fire alarm', 'a prank gone wrong', 'graffiti', 'vandalism', 'drawing on a desk', 'throwing food', 'throwing paper', 'using your phone', 'phone in class', 'talking in class', 'not stopping talking', 'disrespecting a teacher', 'mouthing off', 'rolling your eyes', 'making a teacher cry', 'a senior prank', 'pranking the teacher', 'a stink bomb', 'setting off a stink bomb', 'bringing a pet to school', 'releasing crickets', 'a paper airplane', 'spitballs', 'a viral video', 'filming a fight', 'starting a rumor', 'name calling', 'bullying', 'cutting the lunch line', 'sneaking out', 'leaving campus', 'forging a note', 'forging a signature', 'a fake doctors note', 'lying to a teacher', 'sleeping in class', 'refusing to work', 'walking out', 'slamming a door', 'flipping a desk', 'a tiktok prank', 'doing a prank', 'tagging a locker', 'breaking a window', 'a science experiment gone wrong', 'wandering the halls', 'no hall pass', 'skipping detention', 'showing up to detention late', 'a dress code repeat offender'
  ]),
  'Things your weird aunt posts on Facebook': new Set([
    'minion memes', 'a minion meme', 'good morning angels', 'sending prayers', 'thoughts and prayers', 'an essential oils ad', 'essential oils', 'a chain message', 'a chain letter', 'copy and paste this', 'type amen', 'amen if you agree', 'a conspiracy theory', 'a fake news article', 'an inspirational quote', 'a live laugh love quote', 'live laugh love', 'a sunset photo', 'a photo of her food', 'a recipe nobody asked for', 'a crockpot recipe', 'a wine glass meme', 'its wine o clock', 'a long political rant', 'a rant about the youth', 'kids these days', 'a vague status', 'feeling blessed', 'so done with today', 'sending love', 'a happy birthday to herself', 'a fundraiser', 'a gofundme', 'a mlm pitch', 'join my team', 'ask me how', 'a herbalife post', 'a lularoe post', 'a giveaway scam', 'share to win', 'comment to enter', 'an old chain photo', 'a blurry selfie', 'a selfie with a filter', 'a dog filter selfie', 'a misspelled rant', 'all caps everything', 'a too much information post', 'an oversharing post', 'a passive aggressive status', 'a vaguebook post', 'a missing person hoax', 'a kidnapping warning', 'a fake amber alert', 'a free gift card scam', 'a fake bill gates giveaway', 'a knockoff designer ad', 'a psychic reading ad', 'a horoscope', 'a religious chain post', 'a coffee cup quote', 'a throwback photo', 'tagging the wrong person', 'a happy anniversary to a stranger', 'a cryptic song lyric', 'a sad emoji status', 'praying hands emojis', 'a 20 year old meme', 'a forwarded video'
  ]),
  'Excuses for not texting back': new Set([
    'my phone died', 'i fell asleep', 'i didnt see it', 'i was busy', 'i forgot', 'i thought i replied', 'i did reply in my head', 'i was driving', 'i was at work', 'no service', 'bad signal', 'my notifications were off', 'do not disturb was on', 'i was in class', 'i was studying', 'i left my phone at home', 'i left it in the car', 'my phone was on silent', 'i was showering', 'i was eating', 'i was with family', 'i was at the gym', 'i got distracted', 'i was about to', 'i meant to', 'i was napping', 'my battery was at one percent', 'i was charging it', 'i didnt have my charger', 'my wifi was down', 'i ran out of data', 'i was in a meeting', 'i was at practice', 'my mom took my phone', 'i got grounded', 'i was sick', 'i was sleeping early', 'i was watching a show', 'i lost track of time', 'i was gaming', 'i didnt know what to say', 'i was overthinking my reply', 'i was busy all day', 'my dog needed me', 'i was babysitting', 'i had no signal at work', 'i was on a flight', 'airplane mode', 'i was at a funeral', 'i had a family emergency', 'my phone froze', 'my phone glitched', 'the text didnt send', 'i thought it sent', 'autocorrect was acting up', 'i was reading it but couldnt type', 'i left you on read by accident', 'i swear i answered', 'my screen was cracked', 'my phone was updating', 'i dropped my phone in water'
  ]),
  'Things in a final boss arena': new Set([
    'lava pits', 'a lava floor', 'spikes', 'spike traps', 'a giant throne', 'a glowing portal', 'a health bar', 'a giant health bar', 'pillars', 'crumbling pillars', 'floating platforms', 'a save point', 'a checkpoint', 'a glowing rune', 'glowing runes', 'a bottomless pit', 'a bottomless chasm', 'chains', 'broken chains', 'a giant door', 'a locked door', 'torches', 'flaming torches', 'a dramatic skybox', 'storm clouds', 'lightning', 'a blood moon', 'a giant moon', 'creepy statues', 'statues', 'a circular platform', 'a glowing floor', 'magic circles', 'a summoning circle', 'minions', 'adds', 'a phase two', 'phase 2', 'a cutscene trigger', 'an ominous voice', 'a giant sword', 'a giant weapon', 'treasure behind the boss', 'a chest after the fight', 'falling debris', 'falling rocks', 'a collapsing floor', 'a shrinking arena', 'an arena that closes in', 'poison gas', 'green fog', 'an evil throne room', 'a cathedral', 'a volcano', 'a void', 'the void', 'a starry abyss', 'a glowing weak point', 'a weak spot', 'a shield phase', 'an invincibility phase', 'a rage mode', 'a second health bar', 'a dramatic music change', 'epic music', 'a boss intro card', 'a name drop', 'a giant eye', 'tentacles', 'an ancient altar', 'crystals', 'glowing crystals', 'a barrier', 'a force field', 'no escape', 'a sealed exit', 'fog walls', 'a fog wall'
  ]),
  'Things that are technically legal but feel illegal': new Set([
    'jaywalking', 'speeding a little', 'going 5 over', 'u turns', 'a u turn', 'eating before paying', 'eating grapes at the store', 'parking weird', 'taking extra samples', 'extra free samples', 'returning worn clothes', 'wearing pajamas in public', 'driving barefoot', 'sleeping in your car', 'taking hotel toiletries', 'taking the free pens', 'taking the mints', 'splitting a meal', 'using a fake name at starbucks', 'cutting your own bangs', 'leaving without tipping', 'reclining your seat on a plane', 'bringing your own snacks to a movie', 'sneaking snacks into a movie', 'using someones netflix', 'sharing a password', 'taking a penny from the tray', 'leaving a penny', 'using the express lane with extra items', 'self checkout with a cart', 'feeding pigeons', 'collecting rainwater', 'rolling through a stop sign', 'a rolling stop', 'merging late', 'using a handicap stall', 'double dipping at home', 'returning something after using it', 'tasting grapes', 'opening a snack before buying', 'parking in two spots', 'taking the last free sample tray', 'crossing against the light', 'turning right on red', 'driving in the bike lane briefly', 'taking ketchup packets', 'hoarding ketchup packets', 'taking napkins by the handful', 'asking for water then getting soda', 'using the bathroom without buying', 'browsing without buying', 'test driving with no intent to buy', 'flossing in public', 'clipping nails in public', 'wearing socks with sandals', 'eating in the cereal aisle', 'sampling bulk candy', 'taking the aux without asking', 'reading magazines at the store', 'sitting in first class to wait', 'taking extra condiments', 'parking in a fire lane for a second', 'idling in a spot', 'leaving a shopping cart out'
  ]),
  'Things that hit different at night': new Set([
    'sad songs', 'a deep conversation', 'overthinking', 'a 2am snack', 'cold water', 'a shower', 'leftover pizza', 'cereal', 'cereal in the dark', 'old memories', 'looking at old photos', 'texting your ex', 'random thoughts', 'a good playlist', 'a drive', 'a late night drive', 'fast food', 'a milkshake', 'silence', 'rain sounds', 'thunderstorms', 'a phone call', 'a face time', 'gaming', 'a horror movie', 'youtube rabbit holes', 'an existential crisis', 'remembering embarrassing moments', 'cringe memories', 'planning your whole life', 'deciding to change everything', 'a snack run', 'instant noodles', 'ramen', 'a candle', 'fairy lights', 'a good book', 'journaling', 'staring at the ceiling', 'the ceiling fan', 'city lights', 'the moon', 'stargazing', 'a warm blanket', 'hot chocolate', 'tea', 'a warm bath', 'lofi music', 'rewatching a comfort show', 'an emotional movie', 'crying for no reason', 'a heart to heart', 'missing someone', 'nostalgia', 'a midnight walk', 'empty streets', 'a quiet house', 'the hum of the fridge', 'a deep playlist', 'slow songs', 'a long text', 'voice memos', 'an old movie', 'gas station snacks', 'a drive thru run', 'overthinking a text', 'replaying conversations'
  ]),
  'Excuses for not doing your homework': new Set([
    'my dog ate it', 'i forgot', 'i left it at home', 'i lost it', 'i didnt know it was due', 'i thought it was tomorrow', 'my printer broke', 'the printer was out of ink', 'my wifi was down', 'my laptop died', 'my computer crashed', 'i had a game', 'i had practice', 'i was sick', 'i had a doctors appointment', 'i had to babysit', 'i was busy', 'i ran out of time', 'i fell asleep', 'i did it but left it at home', 'i emailed it but it didnt send', 'the file got corrupted', 'my account logged me out', 'the website was down', 'canvas was down', 'google classroom glitched', 'it didnt save', 'i saved it in the wrong place', 'i did the wrong page', 'i didnt understand it', 'i didnt have the materials', 'i lost the worksheet', 'someone took my binder', 'my locker was jammed', 'i thought it was optional', 'i was absent', 'i missed that day', 'no one told me', 'it wasnt on the board', 'my brother spilled juice on it', 'my little sister scribbled on it', 'the baby ripped it', 'it flew out the car window', 'i left it on the bus', 'my mom threw it away', 'we had a family emergency', 'i had chores all night', 'my power went out', 'a storm knocked out the power', 'i was at my dads', 'i left it at my moms', 'i forgot my charger', 'my tablet broke', 'autocorrect messed it up', 'i did it in my head', 'i ran out of paper', 'my pencil broke', 'i couldnt find a pen', 'i thought you collected it next week', 'i was helping my parents', 'i had work'
  ]),
  'Pokemon from Gen 1': new Set([
    'pikachu', 'raichu', 'bulbasaur', 'ivysaur', 'venusaur', 'charmander', 'charmeleon', 'charizard', 'squirtle', 'wartortle', 'blastoise', 'caterpie', 'metapod', 'butterfree', 'weedle', 'kakuna', 'beedrill', 'pidgey', 'pidgeotto', 'pidgeot', 'rattata', 'raticate', 'spearow', 'fearow', 'ekans', 'arbok', 'sandshrew', 'sandslash', 'nidoran', 'nidorina', 'nidoqueen', 'nidorino', 'nidoking', 'clefairy', 'clefable', 'vulpix', 'ninetales', 'jigglypuff', 'wigglytuff', 'zubat', 'golbat', 'oddish', 'gloom', 'vileplume', 'paras', 'parasect', 'venonat', 'venomoth', 'diglett', 'dugtrio', 'meowth', 'persian', 'psyduck', 'golduck', 'mankey', 'primeape', 'growlithe', 'arcanine', 'poliwag', 'poliwhirl', 'poliwrath', 'abra', 'kadabra', 'alakazam', 'machop', 'machoke', 'machamp', 'bellsprout', 'weepinbell', 'victreebel', 'tentacool', 'tentacruel', 'geodude', 'graveler', 'golem', 'ponyta', 'rapidash', 'slowpoke', 'slowbro', 'magnemite', 'magneton', 'farfetchd', 'doduo', 'dodrio', 'seel', 'dewgong', 'grimer', 'muk', 'shellder', 'cloyster', 'gastly', 'haunter', 'gengar', 'onix', 'drowzee', 'hypno', 'krabby', 'kingler', 'voltorb', 'electrode', 'exeggcute', 'exeggutor', 'cubone', 'marowak', 'hitmonlee', 'hitmonchan', 'lickitung', 'koffing', 'weezing', 'rhyhorn', 'rhydon', 'chansey', 'tangela', 'kangaskhan', 'horsea', 'seadra', 'goldeen', 'seaking', 'staryu', 'starmie', 'mr mime', 'scyther', 'jynx', 'electabuzz', 'magmar', 'pinsir', 'tauros', 'magikarp', 'gyarados', 'lapras', 'ditto', 'eevee', 'vaporeon', 'jolteon', 'flareon', 'porygon', 'omanyte', 'omastar', 'kabuto', 'kabutops', 'aerodactyl', 'snorlax', 'articuno', 'zapdos', 'moltres', 'dratini', 'dragonair', 'dragonite', 'mewtwo', 'mew'
  ]),
  'Fast food chains': new Set([
    'mcdonalds', 'burger king', 'wendys', 'taco bell', 'kfc', 'chick fil a', 'popeyes', 'subway', 'arbys', 'sonic', 'dairy queen', 'in n out', 'whataburger', 'five guys', 'shake shack', 'culvers', 'jack in the box', 'carls jr', 'hardees', 'del taco', 'white castle', 'checkers', 'rallys', 'raising canes', 'canes', 'zaxbys', 'bojangles', 'churchs chicken', 'chipotle', 'qdoba', 'moes', 'panda express', 'panera', 'jimmy johns', 'jersey mikes', 'firehouse subs', 'wingstop', 'buffalo wild wings', 'bdubs', 'dominos', 'pizza hut', 'papa johns', 'little caesars', 'dominos pizza', 'jollibee', 'el pollo loco', 'long john silvers', 'captain ds', 'krystal', 'steak n shake', 'freddys', 'portillos', 'cookout', 'biscuitville', 'runza', 'braums', 'wienerschnitzel', 'taco johns', 'dunkin', 'dunkin donuts', 'tim hortons', 'krispy kreme', 'starbucks', 'dutch bros', 'auntie annes', 'cinnabon', 'baskin robbins', 'dairy queen grill', 'noodles and company', 'blaze pizza', 'mod pizza', 'marcos pizza', 'cicis', 'cicis pizza', 'sbarro', 'fuddruckers', 'smashburger', 'a&w', 'wienerschnitzel', 'taco bueno', 'fazolis', 'pollo tropical', 'bojangles famous chicken', 'church s', 'wing street'
  ]),
  'First things you do when you wake up': new Set([
    'check my phone', 'hit snooze', 'turn off the alarm', 'check notifications', 'scroll tiktok', 'check instagram', 'check snapchat', 'check texts', 'go back to sleep', 'stretch', 'yawn', 'rub my eyes', 'stare at the ceiling', 'lay in bed', 'doomscroll', 'check the time', 'panic about the time', 'brush my teeth', 'pee', 'go to the bathroom', 'drink water', 'get coffee', 'make coffee', 'eat breakfast', 'feed the dog', 'feed the cat', 'check the weather', 'pet the dog', 'open the curtains', 'turn on the light', 'complain about being tired', 'groan', 'check my streaks', 'reply to texts', 'check email', 'check the group chat', 'wash my face', 'shower', 'take a shower', 'get dressed', 'pick an outfit', 'make my bed', 'check my calendar', 'plan my day', 'snooze again', 'lie there', 'overthink', 'check the news', 'check sports scores', 'turn off do not disturb', 'silence my second alarm', 'reach for my phone', 'roll over', 'pull the covers up', 'wonder what day it is', 'remember i have school', 'remember i have work', 'dread the day', 'stretch and crack my back', 'check my dreams', 'tell someone my dream', 'drink the water by my bed', 'find my glasses', 'put in my contacts', 'check my reflection', 'weigh myself', 'do my skincare', 'take my meds', 'take my vitamins'
  ]),
  'Things a mom yells from another room': new Set([
    'whos at the door', 'answer the door', 'is the oven off', 'did you lock the door', 'turn off the stove', 'the laundrys done', 'switch the laundry', 'fold the towels', 'walk the dog', 'let the dog out', 'let the dog in', 'is your bag packed', 'dont forget your lunch', 'youre gonna miss the bus', 'the bus is coming', 'are you up', 'are you awake', 'its time to get up', 'were leaving soon', 'put your shoes on now', 'grab your jacket', 'did you brush your hair', 'wash behind your ears', 'use soap this time', 'flush the toilet', 'put the seat down', 'whos in the bathroom', 'how long are you gonna be', 'save some hot water', 'turn off the water', 'stop wasting water', 'close the garage', 'shut the garage door', 'whos car is that', 'whats burning', 'do you smell that', 'check the oven', 'the timers going off', 'get the door', 'phones for you', 'its for you', 'come set the table', 'wash your hands first', 'no snacks before dinner', 'youll spoil your dinner', 'dinner in ten', 'come help me', 'bring me my phone', 'wheres the remote', 'turn the tv down', 'its too loud', 'are you doing homework', 'show me your grades', 'did you study', 'youre on that phone again', 'get off the game', 'one more hour then bed', 'lights out in ten', 'why are you still awake', 'go to sleep', 'stop jumping on the bed', 'youre gonna break something', 'be careful up there', 'dont run with that', 'put that down', 'leave the cat alone'
  ]),
  'Red flags in a dating profile': new Set([
    'loves drama', 'no pictures', 'only group photos', 'a fish photo', 'holding a fish', 'a gym selfie', 'only gym selfies', 'married but looking', 'still living with an ex', 'dont catch feelings', 'no strings attached', 'i dont do labels', 'just here for fun', 'ask my mom about me', 'looking for a sugar baby', 'venmo me', 'cashapp in bio', 'follow my onlyfans', 'crypto bro', 'asks for money', 'too good to be true', 'a verified scammer vibe', 'spells everything wrong', 'all bad grammar', 'no bio', 'empty bio', 'just a height', 'just emojis', 'six foot four if that matters', 'mentions height too much', 'my ex is crazy', 'all my exes are crazy', 'i hate drama but', 'i tell it like it is', 'not looking for anything serious', 'i ghost easily', 'red flag emoji', 'lots of red flags', 'a knife photo', 'a gun photo', 'posing with a tiger', 'a tiger selfie', 'face never shown', 'sunglasses in every pic', 'a car selfie', 'flexing money', 'cash in hand', 'bragging about money', 'lives with parents at 40', 'unemployed and proud', 'no job listed', 'mentions their body count', 'rates exes', 'trash talks all women', 'trash talks all men', 'super clingy already', 'love bombs immediately', 'asks to move to whatsapp fast', 'wont video chat', 'avoids meeting up', 'too many filters', 'catfish vibes', 'a decade old photo', 'mentions their lawyer', 'on probation', 'just got out', 'asks your address right away', 'wants to skip the talking stage'
  ]),
  'The DMV experience': new Set([
    'long lines', 'a long wait', 'a take a number ticket', 'a number ticket', 'now serving b47', 'waiting for hours', 'a slow line', 'one window open', 'a closed window', 'a lunch break sign', 'be back in 30', 'wrong paperwork', 'missing a document', 'forgot a form', 'a rude employee', 'a grumpy worker', 'a bad photo', 'an awful license photo', 'a flash that blinds you', 'no smiling allowed', 'a written test', 'the driving test', 'parallel parking', 'failing the test', 'a clipboard', 'fill out this form', 'take a number', 'sit and wait', 'uncomfortable chairs', 'plastic chairs', 'a ticket machine', 'a broken ticket machine', 'a vending machine', 'flickering lights', 'fluorescent lights', 'a tv playing nothing', 'an outdated poster', 'a wanted poster', 'cash only', 'card not accepted', 'an out of order sign', 'a system is down sign', 'the system is down', 'come back tomorrow', 'a different line for that', 'wrong line', 'youre in the wrong line', 'a confusing sign', 'no parking', 'a full parking lot', 'a screaming kid', 'a crying baby', 'someone arguing', 'an angry customer', 'a person yelling', 'a slow typist', 'a stamp', 'lots of stamps', 'a signature here', 'sign here', 'initial here', 'a fingerprint', 'an eye test', 'read line four', 'a renewal notice', 'an expired registration', 'a temporary paper license', 'a paper plate', 'a sticker for your plate', 'a registration sticker'
  ]),
  "Things in an emo kid's room (2008)": new Set([
    'band posters', 'a my chemical romance poster', 'mcr poster', 'a fall out boy poster', 'a panic at the disco poster', 'black walls', 'black paint', 'a checkered belt', 'studded belt', 'skinny jeans', 'black skinny jeans', 'converse', 'black converse', 'vans', 'eyeliner', 'guyliner', 'a side bang', 'hair straightener', 'a flat iron', 'a sidekick', 'a black ipod', 'an ipod with screamo', 'cd cases', 'a stack of cds', 'a black hoodie', 'fingerless gloves', 'a studded bracelet', 'spiked bracelets', 'a bvb poster', 'black veil brides', 'a sleeping with sirens poster', 'pierce the veil', 'a guitar', 'an electric guitar', 'a bass guitar', 'song lyrics on the wall', 'sharpie lyrics', 'a corkboard of concert tickets', 'concert tickets', 'ticket stubs', 'a hot topic bag', 'hot topic everything', 'invader zim stuff', 'a gir plushie', 'jthm', 'a black bedspread', 'red and black everything', 'a skull pillow', 'a ouija board', 'a razor poster', 'dyed black hair', 'manic panic', 'colored hair dye', 'snakebites', 'fake piercings', 'a lip ring', 'gauges', 'a chain wallet', 'a messenger bag', 'sharpie doodles', 'doodles on shoes', 'a journal', 'a diary', 'depressing poetry', 'sad poetry', 'a webcam', 'a myspace top 8', 'myspace', 'a photobooth selfie', 'a mirror selfie', 'a black and white photo', 'a single red rose', 'fake blood', 'a tripp pants', 'tripp pants', 'arm warmers', 'a beanie'
  ]),
  'Things you whisper in a library': new Set([
    'wheres the bathroom', 'is this seat taken', 'do you have a charger', 'whats the wifi password', 'can i borrow a pen', 'what page are we on', 'im so bored', 'i forgot my book', 'can we leave yet', 'is it almost over', 'shh', 'be quiet', 'keep it down', 'lower your voice', 'sorry', 'excuse me', 'can you move over', 'is this taken', 'are you using this', 'where is the section', 'wheres the history section', 'do they have this book', 'is it checked out', 'how do i find this', 'whats the call number', 'where do i check out', 'can i renew this', 'is this due back', 'how late are we open', 'when does it close', 'i need to print', 'wheres the printer', 'is the printer broken', 'do i need a card', 'can i get a library card', 'i lost my card', 'i have a late fee', 'how much do i owe', 'can i use a computer', 'is this computer free', 'is anyone sitting here', 'can i sit here', 'this is taken', 'do you have an outlet', 'wheres an outlet', 'my laptops dying', 'can i copy your notes', 'did you do the homework', 'whats the assignment', 'i didnt study', 'were so cooked', 'this is so quiet', 'i can hear myself think', 'someones snoring', 'someones eating in here', 'thats not allowed', 'were gonna get shushed', 'the librarians coming', 'act natural', 'put your phone away', 'turn your phone down', 'mute your video', 'use headphones', 'i need to focus', 'lets study somewhere else', 'this chairs broken', 'its cold in here', 'can we get food after'
  ]),
  'Things found in a frat house': new Set([
    'a ping pong table', 'beer pong table', 'red solo cups', 'a keg', 'an empty keg', 'a beer pong setup', 'a flat screen tv', 'a sticky floor', 'a broken couch', 'a stained couch', 'a futon', 'a bean bag', 'a foosball table', 'a pool table', 'a dartboard', 'an american flag', 'a tapestry', 'a neon sign', 'a beer sign', 'composite photos', 'a composite', 'greek letters', 'letters on the wall', 'a paddle', 'a fraternity paddle', 'a trophy', 'an intramural trophy', 'a mini fridge', 'a full fridge of beer', 'pizza boxes', 'empty pizza boxes', 'solo cup pyramid', 'a beer can pyramid', 'a tower of cans', 'a handle of vodka', 'an empty handle', 'a jungle juice cooler', 'a cooler', 'a trash can full of cans', 'sticky counters', 'a single roll of paper towels', 'a grill', 'a broken grill', 'a basketball hoop', 'a mini hoop', 'a corn hole set', 'cornhole boards', 'lawn chairs', 'a hammock', 'a slip n slide', 'a kiddie pool', 'a speaker', 'a giant speaker', 'a bluetooth speaker', 'a sound system', 'a disco ball', 'led lights', 'a smoke detector with no battery', 'a fire pit', 'a porch couch', 'a couch on the porch', 'a mattress on the floor', 'a single bed sheet', 'no curtains', 'a flag for a curtain', 'sports jerseys', 'a jersey on the wall', 'a street sign', 'a stolen street sign', 'a traffic cone', 'a shopping cart', 'a beer helmet', 'a funnel', 'a beer funnel', 'a shotgun tool', 'a bottle opener', 'a half eaten pizza', 'a forgotten textbook', 'an unopened textbook'
  ]),
  'Things you say when you stub your toe': new Set([
    'ow', 'ouch', 'oww', 'a word i learned online', 'a bad word', 'a curse word', 'son of a', 'are you kidding me', 'why', 'why me', 'not again', 'every time', 'who put that there', 'what was that', 'oh my gosh', 'oh my god', 'oh come on', 'really', 'seriously', 'i hate this', 'i hate everything', 'that hurt', 'that really hurt', 'owie', 'frick', 'fudge', 'shoot', 'dang it', 'dang', 'darn it', 'crap', 'oof', 'ah', 'aaah', 'aghhh', 'nooo', 'bro', 'dude', 'man down', 'i think its broken', 'is it bleeding', 'i lost a toe', 'my pinky toe', 'not the pinky toe', 'the corner got me', 'stupid table', 'stupid couch', 'stupid door', 'i felt that in my soul', 'i saw stars', 'i need a minute', 'give me a sec', 'whyd they put that there', 'who moved that', 'limping now', 'i cant walk', 'rip my toe', 'that was the corner', 'right in the toe', 'every single time', 'i always do that', 'classic me', 'pain', 'agony', 'help', 'mommy', 'jesus take the wheel', 'sweet mother', 'good grief', 'for the love of', 'come ON', 'are you serious right now'
  ]),
  'Car brands': new Set([
    'toyota', 'honda', 'ford', 'chevy', 'chevrolet', 'nissan', 'jeep', 'dodge', 'ram', 'gmc', 'buick', 'cadillac', 'lincoln', 'chrysler', 'tesla', 'bmw', 'mercedes', 'mercedes benz', 'audi', 'volkswagen', 'vw', 'porsche', 'volvo', 'subaru', 'mazda', 'mitsubishi', 'lexus', 'acura', 'infiniti', 'hyundai', 'kia', 'genesis', 'fiat', 'alfa romeo', 'maserati', 'ferrari', 'lamborghini', 'lambo', 'bugatti', 'mclaren', 'rolls royce', 'bentley', 'aston martin', 'jaguar', 'land rover', 'range rover', 'mini', 'mini cooper', 'smart', 'hummer', 'pontiac', 'saturn', 'oldsmobile', 'mercury', 'plymouth', 'saab', 'suzuki', 'isuzu', 'datsun', 'lotus', 'lucid', 'rivian', 'polestar', 'fisker', 'koenigsegg', 'pagani', 'peugeot', 'renault', 'citroen', 'opel', 'skoda', 'seat', 'dacia', 'vauxhall', 'holden', 'byd', 'nio', 'geely', 'lada', 'scion', 'maybach', 'rolls', 'caterham', 'morgan', 'de tomaso', 'delorean', 'studebaker', 'packard', 'amc', 'eagle', 'daewoo', 'tata', 'mahindra', 'great wall', 'wuling'
  ]),
  'Things your parents text you': new Set([
    'call me', 'call me now', 'where are you', 'when are you coming home', 'pick up the phone', 'answer your phone', 'why arent you answering', 'are you alive', 'text me when you get there', 'let me know youre safe', 'drive safe', 'be home by 10', 'dinners ready', 'whats your eta', 'on my way', 'omw', 'i love you', 'love you', 'proud of you', 'did you eat', 'have you eaten', 'eat something', 'did you do your homework', 'how was school', 'how was your day', 'we need to talk', 'see me when you get home', 'youre in trouble', 'who is this', 'how do i send a picture', 'how do i delete this', 'whats this app', 'can you help me with my phone', 'the wifi isnt working', 'the tv isnt working', 'how do i screenshot', 'a random thumbs up', 'a thumbs up', 'k', 'ok', 'okay', 'a single period', 'lol', 'a misused emoji', 'too many emojis', 'a forwarded chain text', 'a forwarded meme', 'a blurry photo', 'a photo of the dog', 'a photo of nothing', 'an accidental photo', 'a voice memo', 'a 2 minute voicemail', 'call your grandma', 'wish your aunt happy birthday', 'pick up milk', 'grab bread on the way', 'can you get groceries', 'whats the wifi password again', 'i cant find the remote', 'the printer is broken', 'come downstairs', 'come help me', 'bring in the groceries', 'take out the trash', 'feed the dog', 'walk the dog', 'are you still awake', 'go to bed', 'text me when you wake up'
  ]),
  'Apps on your phone right now': new Set([
    'tiktok', 'instagram', 'snapchat', 'youtube', 'spotify', 'netflix', 'discord', 'reddit', 'twitter', 'x', 'facebook', 'messenger', 'whatsapp', 'imessage', 'messages', 'phone', 'camera', 'photos', 'gallery', 'safari', 'chrome', 'google', 'gmail', 'maps', 'google maps', 'apple maps', 'waze', 'uber', 'lyft', 'doordash', 'uber eats', 'grubhub', 'venmo', 'cash app', 'paypal', 'zelle', 'apple pay', 'amazon', 'shein', 'temu', 'ebay', 'pinterest', 'tumblr', 'bereal', 'twitch', 'hulu', 'disney plus', 'hbo max', 'max', 'prime video', 'apple music', 'soundcloud', 'pandora', 'audible', 'kindle', 'duolingo', 'quizlet', 'photomath', 'canvas', 'google classroom', 'schoology', 'notes', 'calculator', 'clock', 'weather', 'calendar', 'reminders', 'wallet', 'settings', 'app store', 'play store', 'find my', 'life360', 'roblox', 'minecraft', 'candy crush', 'subway surfers', 'clash royale', 'among us', 'genshin impact', 'pokemon go', 'wordle', 'capcut', 'vsco', 'lightroom', 'facetune', 'pic collage', 'google docs', 'google drive', 'microsoft word', 'onedrive', 'zoom', 'teams', 'linkedin', 'starbucks', 'mcdonalds', 'chick fil a', 'target', 'walmart', 'nike', 'robinhood', 'coinbase', 'flashlight', 'voice memos'
  ]),
  'Shoe brands': new Set([
    'nike', 'adidas', 'jordan', 'air jordan', 'crocs', 'vans', 'converse', 'puma', 'reebok', 'new balance', 'nb', 'under armour', 'asics', 'skechers', 'timberland', 'timbs', 'ugg', 'uggs', 'birkenstock', 'birkenstocks', 'doc martens', 'dr martens', 'hey dude', 'hey dudes', 'sperry', 'sperrys', 'clarks', 'fila', 'champion', 'yeezy', 'yeezys', 'balenciaga', 'gucci', 'louis vuitton', 'lv', 'prada', 'versace', 'dior', 'off white', 'golden goose', 'salomon', 'hoka', 'on', 'on cloud', 'on running', 'brooks', 'saucony', 'merrell', 'columbia', 'keen', 'teva', 'chacos', 'oofos', 'allbirds', 'veja', 'cole haan', 'steve madden', 'aldo', 'dr scholls', 'sketchers', 'kswiss', 'k swiss', 'diadora', 'lacoste', 'tommy hilfiger', 'polo', 'ralph lauren', 'sketcher', 'heelys', 'skate shoes', 'dc', 'dc shoes', 'etnies', 'vans old skool', 'air force ones', 'air force 1', 'af1', 'air max', 'dunks', 'nike dunks', 'sb dunks', 'jordan 1', 'jordan 4', 'chuck taylors', 'all stars', 'stan smith', 'superstar', 'samba', 'gazelle', 'forum', 'campus', 'sambas', 'new balance 550', 'new balance 990', '550s', '990s', 'reebok classic', 'puma suede', 'asics gel', 'onitsuka tiger', 'palladium', 'sorel', 'bearpaw', 'minnetonka', 'rothys', 'toms', 'native', 'native shoes'
  ]),
  'Things in an Amazon package': new Set([
    'bubble wrap', 'an air pillow', 'air pillows', 'packing peanuts', 'a way too big box', 'a tiny item in a huge box', 'brown paper', 'crumpled paper', 'a packing slip', 'no packing slip', 'a return label', 'tape everywhere', 'so much tape', 'a smile logo', 'the amazon arrow', 'a phone charger', 'a phone case', 'a screen protector', 'usb cables', 'a charging cable', 'earbuds', 'a ring light', 'a phone stand', 'a popsocket', 'batteries', 'aaa batteries', 'a power bank', 'a usb hub', 'a kindle', 'a fire stick', 'an echo dot', 'an alexa', 'a smart plug', 'led strip lights', 'led lights', 'fairy lights', 'a water bottle', 'a stanley cup dupe', 'a phone tripod', 'a selfie ring', 'a laptop sleeve', 'a mouse', 'a mousepad', 'a keyboard', 'a webcam', 'a gaming headset', 'a controller', 'a hdmi cable', 'a wall mount', 'command strips', 'velcro strips', 'zip ties', 'a tool kit', 'a multitool', 'a tape measure', 'a label maker', 'storage bins', 'drawer organizers', 'a shoe rack', 'vacuum bags', 'a lint roller', 'a back scratcher', 'a heating pad', 'a neck pillow', 'a blanket', 'a hoodie', 'socks', 'a pack of socks', 'a t shirt', 'leggings', 'a phone grip', 'fake plants', 'a planner', 'sticky notes', 'highlighters', 'pens', 'a journal', 'a book', 'a board game', 'a fidget toy', 'vitamins', 'protein powder', 'a water filter', 'replacement parts', 'a wrong item', 'someone elses order', 'a dented box', 'a crushed box'
  ]),
  'Things in a Costco': new Set([
    'free samples', 'a giant cart', 'an oversized cart', 'a flatbed cart', 'a 48 pack of water', 'a pallet of water', 'bulk paper towels', 'a huge pack of toilet paper', 'a tower of toilet paper', 'a rotisserie chicken', 'a $5 chicken', 'a $1.50 hot dog', 'the food court', 'a giant pizza', 'a churro', 'a giant muffin', 'muffins', 'a sheet cake', 'a costco cake', 'a giant teddy bear', 'the big bear', 'a kirkland everything', 'kirkland brand', 'kirkland water', 'a 5 pound bag of cheese', 'a wheel of cheese', 'a tub of mayo', 'a giant ketchup', 'a vat of mayo', 'a 3 pound bag of chips', 'bulk snacks', 'a flat of soda', 'a case of soda', 'a 30 pack', 'a 36 pack of eggs', 'bulk eggs', 'a tire center', 'tires', 'a gas station', 'cheap gas', 'a pharmacy', 'an optical center', 'glasses', 'hearing aids', 'a hot tub', 'a shed', 'a kayak', 'a tv', 'a giant tv', 'a treadmill', 'patio furniture', 'a mattress', 'a generator', 'a vacuum', 'a coffee maker', 'an air fryer', 'a stand mixer', 'a giant nutella', 'a giant peanut butter', 'a vat of pickles', 'bulk protein bars', 'a pack of 48 granola bars', 'a giant bag of frozen fruit', 'frozen berries', 'a slab of salmon', 'a giant steak', 'a meat section', 'a tray of cookies', 'a bag of 60 cookies', 'a giant trail mix', 'bulk nuts', 'a 2 pound bag of gummy bears', 'a book table', 'a clothing table', 'kirkland jeans', 'socks in bulk', 'a free sample of pizza', 'a sample lady', 'a membership card', 'a receipt checker', 'someone checking your receipt', 'a long checkout line'
  ]),
  'YouTube video categories': new Set([
    'unboxing', 'unboxings', 'a haul', 'shopping haul', 'a vlog', 'daily vlog', 'a tutorial', 'how to', 'a reaction', 'reaction video', 'a review', 'product review', 'a prank', 'prank video', 'a challenge', 'gaming', 'a lets play', 'a walkthrough', 'a speedrun', 'a montage', 'a gameplay', 'a tier list', 'a ranking', 'a story time', 'storytime', 'a get ready with me', 'grwm', 'a what i eat in a day', 'a day in my life', 'a morning routine', 'a night routine', 'a mukbang', 'a taste test', 'a try not to laugh', 'a try not to', 'a compilation', 'a fail compilation', 'a top 10', 'a top 5', 'a documentary', 'a video essay', 'a deep dive', 'a podcast', 'an asmr', 'asmr', 'a study with me', 'a tier maker', 'a diy', 'a craft', 'a cooking video', 'a recipe', 'a baking video', 'a workout', 'a fitness video', 'a transformation', 'a makeover', 'a room tour', 'a house tour', 'a car review', 'a tech review', 'a phone review', 'a comparison', 'a vs video', 'a debunk', 'a conspiracy', 'a true crime', 'an explainer', 'a tutorial', 'a beginners guide', 'a 24 hour challenge', 'a last to leave', 'a hide and seek', 'a tour', 'a behind the scenes', 'a bloopers', 'a q and a', 'a qanda', 'a draw my life', 'a face reveal', 'an apology video', 'a clickbait thumbnail', 'a music video', 'a cover', 'a lyric video', 'a shorts', 'a youtube short', 'a stream highlight', 'a highlight reel', 'a meme review', 'a tier list video', 'a build', 'a satisfying video', 'a slime video'
  ]),
  'Subscription services': new Set([
    'netflix', 'hulu', 'disney plus', 'disney+', 'hbo max', 'max', 'amazon prime', 'prime video', 'apple tv', 'apple tv plus', 'peacock', 'paramount plus', 'paramount+', 'spotify', 'apple music', 'youtube premium', 'youtube music', 'amazon music', 'tidal', 'pandora', 'soundcloud go', 'audible', 'kindle unlimited', 'crunchyroll', 'funimation', 'discovery plus', 'espn plus', 'espn+', 'starz', 'showtime', 'amc plus', 'sling', 'sling tv', 'youtube tv', 'fubo', 'hbo', 'xbox game pass', 'game pass', 'ps plus', 'playstation plus', 'nintendo switch online', 'ea play', 'twitch turbo', 'patreon', 'onlyfans', 'icloud', 'icloud plus', 'google one', 'dropbox', 'microsoft 365', 'office 365', 'adobe creative cloud', 'canva pro', 'chatgpt plus', 'duolingo plus', 'super duolingo', 'grammarly', 'lastpass', 'nordvpn', 'expressvpn', 'amazon prime student', 'doordash dashpass', 'dashpash', 'uber one', 'instacart plus', 'walmart plus', 'costco membership', 'sams club', 'amazon fresh', 'hellofresh', 'blue apron', 'factor', 'home chef', 'dollar shave club', 'birchbox', 'ipsy', 'fabfitfun', 'stitch fix', 'barkbox', 'chewy autoship', 'planet fitness', 'la fitness', 'peloton', 'apple fitness plus', 'masterclass', 'skillshare', 'coursera', 'the new york times', 'nyt', 'wall street journal', 'a magazine subscription', 'gym membership', 'a meal kit', 'a box subscription', 'a coffee subscription'
  ]),
  'Things that come in a vending machine': new Set([
    'the bag that gets stuck', 'chips', 'doritos', 'cheetos', 'lays', 'fritos', 'pretzels', 'a candy bar', 'snickers', 'twix', 'kit kat', 'reeses', 'm&ms', 'skittles', 'starburst', 'gum', 'mints', 'a soda', 'coke', 'pepsi', 'sprite', 'dr pepper', 'mountain dew', 'a water bottle', 'water', 'gatorade', 'powerade', 'an energy drink', 'red bull', 'monster', 'juice', 'an arizona tea', 'iced tea', 'cookies', 'oreos', 'crackers', 'cheez its', 'goldfish', 'a granola bar', 'a protein bar', 'trail mix', 'peanuts', 'a honey bun', 'a little debbie', 'pop tarts', 'a rice krispie treat', 'fruit snacks', 'beef jerky', 'a slim jim', 'ramen', 'a cup of noodles', 'instant noodles', 'popcorn', 'a churro', 'ice cream', 'a drumstick', 'an ice cream sandwich', 'a klondike bar', 'a coffee', 'hot chocolate', 'a sandwich', 'a microwave meal', 'a banana', 'an apple', 'a healthy snack', 'sunflower seeds', 'a pickle', 'fruit cups', 'animal crackers', 'nutter butters', 'a payday', 'a butterfinger', 'a 3 musketeers', 'sour patch kids', 'swedish fish', 'nerds', 'airheads', 'a giant gummy', 'phone chargers', 'a charger', 'earbuds', 'umbrellas', 'tampons', 'condoms', 'hot fries', 'andy capp', 'a stuck snack', 'two snacks at once', 'something expired'
  ]),
  'Things a gym bro says': new Set([
    'do you even lift', 'how much you bench', 'whats your max', 'you mire', 'we go jim', 'lets get this bread', 'one more rep', 'just one more rep', 'no pain no gain', 'rise and grind', 'beast mode', 'lock in', 'time to get swole', 'gains', 'chasing gains', 'leg day', 'never skip leg day', 'its leg day', 'i dont skip leg day', 'are you using this', 'how many sets you got left', 'mind muscle connection', 'feel the pump', 'the pump is real', 'light weight baby', 'aint nothing but a peanut', 'yeah buddy', 'protein is life', 'gotta hit my macros', 'whats your split', 'push pull legs', 'we ball', 'bulk season', 'im bulking', 'im cutting', 'cutting season', 'dirty bulk', 'i need my pre workout', 'pre workout hit different', 'send it', 'lets go', 'spot me', 'can you spot me', 'good set', 'good lift', 'go heavy or go home', 'leave your ego at the door', 'curls for the girls', 'sun is out guns out', 'do you sell protein', 'whey protein', 'shaker bottle', 'wheres the squat rack', 'someones hogging the rack', 'dont curl in the squat rack', 're rack your weights', 'put your weights back', 'natty or not', 'im natty', 'thats my set', 'i was using that', 'leg day tomorrow', 'gym is my therapy', 'the grind never stops', 'rest is for the weak', 'eat sleep lift repeat', 'lets get freaky', 'time under tension', 'progressive overload', 'i hit a pr', 'new pr', 'pr today'
  ]),
  'Things you yell at a sports game': new Set([
    'defense', 'lets go', 'come on', 'shoot it', 'pass the ball', 'run', 'go go go', 'travel', 'thats a foul', 'foul', 'are you blind ref', 'come on ref', 'terrible call', 'bad call', 'open your eyes ref', 'youre kidding me', 'thats holding', 'pass interference', 'thats a penalty', 'offside', 'hes offside', 'we want a touchdown', 'touchdown', 'goal', 'score', 'home run', 'strike him out', 'swing', 'catch it', 'block that shot', 'box out', 'rebound', 'hustle', 'move your feet', 'get back on defense', 'man down', 'wide open', 'hes wide open', 'shoot the ball', 'dont shoot', 'no no no yes', 'airball', 'brick', 'and one', 'bang', 'get him', 'tackle him', 'dont let him score', 'hold the line', 'pump fake', 'fast break', 'lets go team', 'we got this', 'finish it', 'one more point', 'lock it down', 'theyre cheating', 'rigged', 'this is rigged', 'boooo', 'boo', 'overrated', 'air ball', 'sieve', 'you suck ref', 'put him in', 'sub him out', 'take him out', 'wake up', 'play harder', 'where was the foul', 'thats a yellow card', 'red card', 'penalty kick', 'free throw', 'lets go defense', 'd up', 'swish', 'nothing but net', 'let him have it', 'over here im open', 'right here'
  ]),
  'Things in a divorced dad\'s apartment': new Set([
    'a massive recliner', 'a single recliner', 'a leather sectional', 'a 75 inch tv', 'a soundbar', 'a gaming setup', 'a gaming pc', 'an xbox', 'a ps5', 'a beer fridge', 'a kegerator', 'a single plate', 'two forks', 'a half empty fridge', 'condiments and beer', 'a pizza box tower', 'a stack of pizza boxes', 'a takeout graveyard', 'a sad kitchen table', 'a single bar stool', 'a tv tray dinner', 'a frozen dinner', 'protein shakes', 'a blender bottle', 'a dartboard', 'a neon beer sign', 'a sports memorabilia wall', 'a signed jersey', 'a framed jersey', 'a man cave', 'a recliner with cup holders', 'a beer cozy', 'a bottle opener on the wall', 'a wall mounted bottle opener', 'a fish tank', 'a single fern', 'a dead plant', 'a fake plant', 'an air mattress', 'a futon for the kids', 'sad bunk beds', 'a single toothbrush', 'one towel', 'a half roll of paper towels', 'a george foreman grill', 'an air fryer', 'a keurig', 'a mini fridge', 'a card table', 'folding chairs', 'a bean bag', 'a poster of a sports car', 'a scarface poster', 'a motorcycle', 'a harley', 'a pool table', 'a foosball table', 'a bar cart', 'cheap whiskey', 'a humidor', 'a vape', 'a gun safe', 'a treadmill used as a coat rack', 'a coat rack', 'an empty bookshelf', 'a tv on a milk crate', 'milk crates', 'cinder block shelves', 'la croix', 'monster energy', 'a case of beer', 'an empty handle', 'tools in the living room', 'a toolbox', 'a projector', 'a tv on the floor', 'a single picture of the kids', 'a sad framed photo', 'instant ramen', 'hot pockets', 'hungry man dinners', 'a microwave', 'paper plates', 'plastic forks'
  ]),
  'Things you google at 3am': new Set([
    'is cereal a soup', 'am i dying', 'why cant i sleep', 'how to fall asleep fast', 'what time is it in japan', 'how far is the moon', 'can dogs see color', 'is a hot dog a sandwich', 'how many people are awake right now', 'what happens when you die', 'is the universe infinite', 'how do planes stay up', 'why is the sky dark', 'what is the meaning of life', 'how long can you go without sleep', 'do fish sleep', 'how do i know if im in love', 'what does my dream mean', 'why did i do that', 'what should i do with my life', 'how to be successful', 'how much money does a youtuber make', 'is he texting back', 'why hasnt he texted back', 'how to text back', 'symptoms of', 'do i have a fever', 'is this normal', 'how to stop overthinking', 'how to be happy', 'what is a black hole', 'are aliens real', 'is bigfoot real', 'how old is the earth', 'how big is the ocean', 'whats at the bottom of the ocean', 'can you hear in space', 'how many calories in', 'is it bad to eat at night', 'why am i hungry', 'whats open right now', 'late night food near me', '24 hour food near me', 'how to cut your own hair', 'should i cut my own hair', 'how to get rich quick', 'is time travel possible', 'parallel universe', 'do parallel universes exist', 'how do i know if i have a phobia', 'why do we yawn', 'why do cats purr', 'can you die from a broken heart', 'what is sleep paralysis', 'how to lucid dream', 'random facts', 'fun facts', 'how tall is the eiffel tower', 'how to whistle', 'why is my eye twitching', 'is my house haunted', 'how to summon', 'what time does the sun rise', 'how to glow up', 'how to be a better person', 'should i text my ex', 'i miss someone', 'how to forget someone'
  ]),
  'Things you dip in ranch': new Set([
    'literally everything', 'pizza', 'wings', 'chicken wings', 'fries', 'chicken nuggets', 'nuggets', 'chicken tenders', 'mozzarella sticks', 'celery', 'carrots', 'cucumbers', 'baby carrots', 'broccoli', 'cauliflower', 'a salad', 'a sandwich', 'a quesadilla', 'tacos', 'burritos', 'a hot dog', 'a corn dog', 'onion rings', 'tater tots', 'hash browns', 'a baked potato', 'crackers', 'chips', 'doritos', 'pretzels', 'breadsticks', 'garlic bread', 'a hamburger', 'a wrap', 'egg rolls', 'jalapeno poppers', 'fried pickles', 'a pickle', 'popcorn chicken', 'a burrito bowl', 'cheese curds', 'a soft pretzel', 'pizza rolls', 'bagel bites', 'a grilled cheese', 'fish sticks', 'shrimp', 'calamari', 'a sub', 'cold pizza', 'leftover pizza', 'a slice', 'cheese sticks', 'a chicken sandwich', 'a spicy chicken sandwich', 'a buffalo wrap', 'cauliflower wings', 'ranch on ranch', 'a spoon', 'their finger', 'a chicken patty', 'pasta', 'mac and cheese', 'a baked potato', 'sweet potato fries', 'curly fries', 'waffle fries', 'crinkle fries', 'tortilla chips', 'nachos', 'a quesadilla', 'a burrito', 'a taquito', 'a chimichanga', 'cheesy bread', 'pizza crust', 'the crust', 'a stuffed crust', 'a soft taco', 'veggies', 'raw veggies', 'a veggie tray'
  ]),
  "Foods that shouldn't exist but do": new Set([
    'candy corn', 'circus peanuts', 'fruitcake', 'black licorice', 'aspic', 'jello salad', 'a meat jello', 'spam', 'liver and onions', 'haggis', 'head cheese', 'blood sausage', 'durian', 'pickle ice cream', 'mayonnaise ice cream', 'a pickle pizza', 'pineapple on pizza', 'ketchup ice cream', 'mustard ice cream', 'a turducken', 'deep fried butter', 'deep fried oreos', 'deep fried coke', 'deep fried twinkie', 'a chocolate covered grasshopper', 'chocolate covered ants', 'cricket flour', 'cricket protein bars', 'balut', 'lutefisk', 'surstromming', 'casu marzu', 'jellied eels', 'a scotch egg', 'pickled pigs feet', 'pig ears', 'chitterlings', 'rocky mountain oysters', 'a corn dog with cheese', 'a pizza cone', 'a ramen burger', 'a donut burger', 'a cheeseburger in a can', 'spaghetti tacos', 'a pizza burger', 'a cheese in a can', 'squeeze cheese', 'easy cheese', 'a fluffernutter', 'peeps', 'stale peeps', 'a candy corn oreo', 'a hot dog flavored soda', 'a pickle flavored soda', 'bacon soda', 'a turkey soda', 'cotton candy grapes', 'a glow in the dark candy', 'a ghost pepper chip', 'a one chip challenge', 'a habanero lollipop', 'scorpion lollipop', 'a cricket lollipop', 'edible glitter', 'gold flakes on food', 'a 24k gold steak', 'a rainbow bagel', 'unicorn food', 'a freakshake', 'a 5000 calorie sundae', 'a pizza flavored ice cream', 'sardine ice cream', 'corn flavored anything', 'a chicken in a can', 'whole chicken in a can', 'a hamburger in a can', 'a full english in a can', 'spray pancakes', 'pancake in a can', 'a deep fried stick of butter', 'mountain dew flavored doritos'
  ]),
  'Things teachers always say': new Set([
    'were waiting', 'eyes up here', 'eyes on me', 'this will be on the test', 'were not leaving until its quiet', 'i can wait', 'ill wait', 'is that a phone i see', 'put it away', 'phones away', 'no phones in my class', 'theres no talking', 'turn to page', 'open your books', 'take out a pencil', 'no pencil no problem', 'i have extra pencils', 'pop quiz', 'clear your desks', 'eyes on your own paper', 'no cheating', 'this is independent work', 'work quietly', 'raise your hand', 'dont call out', 'one at a time', 'we dont shout out answers', 'is there a question or a comment', 'save it for after class', 'see me after class', 'thats a detention', 'do you want a referral', 'should i call your parents', 'im calling home', 'i wasnt born yesterday', 'nice try', 'theres no such thing as a stupid question', 'the bell doesnt dismiss you i do', 'i dismiss you not the bell', 'youre not in trouble i just want to talk', 'were behind schedule', 'we have a lot to cover', 'pay attention', 'focus', 'lock in', 'this is important', 'write this down', 'youll need this later', 'this counts for a grade', 'late work loses points', 'no late work', 'turn it in by friday', 'due tomorrow', 'no extensions', 'read the directions', 'did you read the directions', 'show your work', 'no work no credit', 'use complete sentences', 'in your own words', 'partner up', 'find a partner', 'group work time', 'youll be graded on this', 'spit out the gum', 'no gum in class', 'sit down', 'have a seat', 'wheres your homework', 'we have a sub tomorrow', 'be good for the sub', 'were doing a fire drill', 'this is a quiz not a test', 'study for the test', 'review your notes'
  ]),
  'Foods that are better cold the next day': new Set([
    'cold pizza', 'pizza', 'leftover pizza', 'lasagna', 'spaghetti', 'pasta', 'mac and cheese', 'fried chicken', 'cold fried chicken', 'meatloaf', 'chinese food', 'cold lo mein', 'fried rice', 'pad thai', 'curry', 'chili', 'soup', 'stew', 'pot roast', 'a casserole', 'enchiladas', 'tacos', 'a burrito', 'taco bell', 'a quesadilla', 'cornbread', 'a baked potato', 'mashed potatoes', 'meatballs', 'a meatball sub', 'a sub', 'a sandwich', 'a club sandwich', 'cold cuts', 'a bagel sandwich', 'cold fries', 'mozzarella sticks', 'cold chicken nuggets', 'leftover wings', 'cold wings', 'a burger', 'a cheeseburger', 'a grilled cheese', 'a calzone', 'a stromboli', 'cold ramen', 'cold noodles', 'cold soba', 'sushi', 'a rice bowl', 'fried fish', 'fish and chips', 'a pot pie', 'shepherds pie', 'baked ziti', 'stuffed shells', 'cold dumplings', 'leftover dim sum', 'general tsos', 'orange chicken', 'sweet and sour chicken', 'cold quiche', 'a frittata', 'cold meatza', 'birria tacos', 'pulled pork', 'a brisket', 'bbq', 'ribs', 'cold ribs', 'cold mac', 'a cold rotisserie chicken', 'leftover steak', 'cold steak', 'a leftover sub', 'cold lasagna', 'cold chili', 'cold curry', 'cold dumplings', 'cold spring rolls', 'cold pad see ew', 'cold biryani', 'leftover thai food', 'leftover indian food', 'leftover mexican food'
  ]),
  'Valid excuses for being late': new Set([
    'traffic', 'bad traffic', 'an accident on the highway', 'a car accident', 'a flat tire', 'my car wouldnt start', 'dead battery', 'i ran out of gas', 'i missed the bus', 'the bus was late', 'the train was delayed', 'a train blocked the road', 'a detour', 'road construction', 'a road closure', 'an accident', 'i overslept', 'my alarm didnt go off', 'my alarm didnt ring', 'i hit snooze too many times', 'the power went out', 'a power outage', 'my phone died', 'i couldnt find parking', 'no parking', 'a long line', 'the elevator was broken', 'i got lost', 'gps took me the wrong way', 'wrong turn', 'a family emergency', 'a doctor appointment ran long', 'i had to drop off my sibling', 'i had to walk the dog', 'my dog got out', 'i locked myself out', 'i lost my keys', 'i couldnt find my keys', 'i couldnt find my shoes', 'i spilled coffee on myself', 'i had to change', 'a wardrobe malfunction', 'i forgot something and went back', 'i had to turn around', 'bad weather', 'snow', 'ice on the roads', 'a storm', 'flooding', 'a tree fell', 'a deer in the road', 'an animal crossed', 'a funeral', 'a flight delay', 'tsa took forever', 'i was helping someone', 'i stopped to help a stranger', 'a slow driver', 'a car broke down in front of me', 'i got pulled over', 'a cop pulled me over', 'a parade', 'a marathon blocked the street', 'a protest', 'the line at starbucks', 'i couldnt log in', 'the wifi was down', 'my computer crashed', 'i had a meeting run over', 'a previous class ran late'
  ]),
  'Ways to die in Minecraft': new Set([
    'a creeper', 'a creeper at night', 'fall damage', 'falling off a cliff', 'lava', 'swimming in lava', 'drowning', 'a skeleton', 'a zombie', 'a spider', 'an enderman', 'the void', 'falling in the void', 'tnt', 'your own tnt', 'a bed in the nether', 'a respawn anchor', 'the wither', 'the ender dragon', 'a ghast', 'a blaze', 'a phantom', 'starving', 'hunger', 'a cactus', 'a sweet berry bush', 'lightning', 'freezing in powder snow', 'an anvil', 'mining straight down', 'digging straight up', 'a piston crusher', 'a magma block', 'a campfire', 'a wither rose', 'a drowned', 'a trident', 'a pillager', 'a ravager', 'a witch', 'a guardian', 'an elder guardian', 'a shulker', 'levitation', 'a warden', 'a sonic boom', 'a breeze', 'a hoglin', 'a piglin', 'a piglin brute', 'a zoglin', 'a silverfish', 'a vex', 'an evoker', 'an iron golem', 'an angry wolf pack', 'a polar bear', 'a goat', 'getting rammed off a cliff', 'a llama spit', 'bees', 'a pufferfish', 'an elytra crash', 'flying into a wall', 'a firework rocket', 'running out of elytra', 'an end crystal', 'falling off an end pillar', 'a fall in a ravine', 'a lava pocket', 'a cave in', 'a mob grinder', 'friendly fire', 'your own dog', 'thorns armor', 'a trapped chest', 'fire', 'burning to death', 'a fall from a high place', 'a nether portal in lava', 'getting pushed into lava', 'a baby zombie', 'a husk', 'a stray', 'a bogged', 'a creaking', 'a wind charge'
  ]),
  'Disney villains': new Set([
    'scar', 'maleficent', 'ursula', 'jafar', 'gaston', 'cruella de vil', 'cruella', 'captain hook', 'the evil queen', 'queen grimhilde', 'hades', 'frollo', 'judge frollo', 'mother gothel', 'gothel', 'lady tremaine', 'the queen of hearts', 'shere khan', 'kaa', 'prince hans', 'hans', 'yzma', 'dr facilier', 'the shadow man', 'governor ratcliffe', 'ratcliffe', 'clayton', 'shan yu', 'the horned king', 'madame medusa', 'amos slade', 'percival mcleach', 'sykes', 'ratigan', 'professor ratigan', 'chernabog', 'the firebird', 'oogie boogie', 'pete', 'the big bad wolf', 'stromboli', 'monstro', 'honest john', 'the coachman', 'si and am', 'diablo', 'gaston and lefou', 'lefou', 'the headless horseman', 'brom bones', 'edgar', 'edgar the butler', 'man', 'the hunter', 'aunt sarah', 'wiggins', 'iago', 'the magic mirror', 'flotsam and jetsam', 'morgana', 'mor du', 'mordu', 'randall', 'randall boggs', 'henry j waternoose', 'waternoose', 'syndrome', 'mr waternoose', 'lotso', 'lots o huggin bear', 'stinky pete', 'al mcwhiggin', 'al', 'emperor zurg', 'zurg', 'hopper', 'charles muntz', 'muntz', 'ernesto de la cruz', 'ernesto', 'chick hicks', 'professor z', 'miles axlerod', 'king candy', 'turbo', 'lord shen', 'tai lung', 'kai', 'the toad', 'darla', 'bruce the shark', 'te ka', 'tamatoa', 'namaari', 'bowler hat guy', 'the queen of hearts', 'horned king', 'bill sykes', 'gantu', 'dr hamsterviel', 'evil emperor zurg'
  ]),
  'Worst superpowers': new Set([
    'talking to fish', 'turning invisible only when no one looks', 'super slow speed', 'flight one inch off the ground', 'shooting useless lasers', 'controlling traffic lights', 'turning water into slightly warmer water', 'super smell', 'smelling fear', 'always knowing the time', 'mild telekinesis', 'moving a paperclip', 'glowing slightly', 'changing tv channels with your mind', 'spawning a single sock', 'summoning expired coupons', 'turning into a chair', 'breathing underwater for ten seconds', 'invisibility for your left hand', 'super strength in your pinky', 'reading minds of houseplants', 'talking to pigeons', 'making it rain indoors', 'predicting yesterdays weather', 'always stepping in gum', 'turning grapes into raisins', 'tying shoes instantly', 'parallel parking perfectly', 'never finding parking', 'always hitting red lights', 'super hearing of your own heartbeat', 'teleporting one foot left', 'shrinking to slightly smaller', 'growing one inch', 'controlling dust', 'turning milk sour', 'making toast slightly warm', 'super speed but only backwards', 'flight but only while sneezing', 'turning into a slightly bigger version of yourself', 'mind control over your own thumbs', 'invisibility but your clothes stay', 'x ray vision of empty boxes', 'talking to dead batteries', 'super taste of expired food', 'summoning a single fly', 'aging milk', 'making elevators slower', 'controlling the volume of whispers', 'turning left only', 'unlimited paper cuts', 'sweating on command', 'crying glitter', 'super itchiness', 'sneezing fire but only ash', 'controlling the wifi but making it worse', 'time travel five seconds forward', 'reading the last page of any book', 'knowing spoilers', 'making any food slightly colder', 'turning invisible only in the dark', 'super jump of two inches', 'healing paper cuts slowly', 'summoning lukewarm coffee', 'detecting nearby mondays', 'talking to lamps', 'controlling escalators that are broken', 'making it slightly windy', 'turning red lights redder', 'super burping', 'hiccups on demand'
  ]),
  'Things you put on toast': new Set([
    'butter', 'an alarming amount of butter', 'jam', 'jelly', 'grape jelly', 'strawberry jam', 'peanut butter', 'pb and j', 'nutella', 'honey', 'cream cheese', 'avocado', 'avocado toast', 'mashed avocado', 'cinnamon sugar', 'cinnamon', 'sugar', 'marmalade', 'apple butter', 'almond butter', 'cookie butter', 'biscoff', 'speculoos', 'lemon curd', 'maple syrup', 'a fried egg', 'scrambled eggs', 'a poached egg', 'bacon', 'cheese', 'melted cheese', 'a slice of cheese', 'grilled cheese', 'tomato', 'sliced tomato', 'smashed peas', 'beans', 'baked beans', 'beans on toast', 'mushrooms', 'sauteed mushrooms', 'smoked salmon', 'lox', 'hummus', 'ricotta', 'mozzarella', 'pesto', 'olive oil', 'garlic butter', 'garlic', 'everything bagel seasoning', 'a banana', 'banana slices', 'strawberries', 'blueberries', 'apple slices', 'a drizzle of honey', 'whipped cream', 'sprinkles', 'chocolate spread', 'marshmallow fluff', 'fluff', 'a fluffernutter', 'cottage cheese', 'tuna', 'tuna salad', 'egg salad', 'chicken salad', 'sausage gravy', 'jam and butter', 'mascarpone', 'brie', 'goat cheese', 'fig jam', 'a sunny side up egg', 'salt and pepper', 'sea salt', 'chili crisp', 'sriracha', 'hot sauce', 'ketchup', 'mayo', 'vegemite', 'marmite', 'crunchy peanut butter', 'creamy peanut butter', 'sunbutter', 'tahini', 'apple sauce', 'a poptart filling', 'condensed milk'
  ]),
  'School cafeteria foods': new Set([
    'chicken nuggets', 'nuggets', 'a square pizza', 'rectangle pizza', 'pizza', 'a personal pizza', 'a cheeseburger', 'a hamburger', 'a hot dog', 'a corn dog', 'corn dogs', 'chicken patty', 'a chicken sandwich', 'chicken tenders', 'chicken fingers', 'popcorn chicken', 'mystery meat', 'sloppy joes', 'a sloppy joe', 'tater tots', 'french fries', 'curly fries', 'crinkle fries', 'mashed potatoes', 'mac and cheese', 'spaghetti', 'a walking taco', 'nachos', 'nacho cheese', 'a soft pretzel', 'a pretzel', 'a uncrustable', 'uncrustables', 'a pb and j', 'a turkey sandwich', 'a sub', 'a wrap', 'a salad', 'a salad bar', 'a side salad', 'green beans', 'canned corn', 'corn', 'peas', 'mixed vegetables', 'broccoli', 'a fruit cup', 'fruit cocktail', 'canned peaches', 'mandarin oranges', 'applesauce', 'an apple', 'a banana', 'an orange', 'jello', 'a jello cup', 'pudding', 'a pudding cup', 'a cookie', 'a giant cookie', 'a rice krispie treat', 'a brownie', 'a cinnamon roll', 'milk', 'chocolate milk', 'a milk carton', 'strawberry milk', 'juice', 'a juice box', 'an icee', 'an ice cream cup', 'a drumstick', 'an ice cream sandwich', 'goldfish', 'a granola bar', 'animal crackers', 'graham crackers', 'a string cheese', 'cheese stick', 'a bagel', 'a breakfast for lunch', 'pancakes', 'french toast sticks', 'a biscuit', 'a roll', 'a dinner roll', 'garlic bread', 'breadsticks', 'a calzone', 'a taco', 'a burrito', 'a quesadilla', 'rice', 'fried rice', 'orange chicken', 'egg rolls', 'soup', 'tomato soup', 'chili'
  ]),
  'Roblox games': new Set([
    'adopt me', 'brookhaven', 'tower of hell', 'bloxburg', 'welcome to bloxburg', 'arsenal', 'murder mystery 2', 'mm2', 'jailbreak', 'piggy', 'doors', 'rainbow friends', 'natural disaster survival', 'work at a pizza place', 'mega obby', 'a obby', 'an obby', 'flee the facility', 'royale high', 'pet simulator', 'pet simulator x', 'pet sim 99', 'blox fruits', 'blox piece', 'king legacy', 'anime fighting simulator', 'all star tower defense', 'tower defense simulator', 'bee swarm simulator', 'mining simulator', 'lumber tycoon', 'lumber tycoon 2', 'theme park tycoon', 'restaurant tycoon', 'retail tycoon', 'meepcity', 'meep city', 'club roblox', 'livetopia', 'bubble gum simulator', 'build a boat for treasure', 'build a boat', 'super bomb survival', 'super golf', 'the floor is lava', 'hide and seek extreme', 'speed run 4', 'be crushed by a speeding wall', 'survive the killer', 'breaking point', 'phantom forces', 'big paintball', 'bad business', 'da hood', 'evade', 'pressure', 'the mimic', 'apeirophobia', 'eviction notice', 'epic minigames', 'dead silence', 'a dusty trip', 'a dusty trip', 'fisch', 'blade ball', 'rivals', 'combat warriors', 'criminality', 'untitled tag game', 'tag game', 'pls donate', 'dress to impress', 'dti', 'fashion famous', 'wacky wizards', 'sharkbite', 'sharkbite 2', 'car crushers', 'car crushers 2', 'vehicle simulator', 'driving empire', 'jailbreak racing', 'mad city', 'super hero tycoon', 'two player superhero tycoon', 'clicker simulator', 'anime adventures', 'anime defenders', 'grow a garden', 'steal a brainrot', 'forsaken', '99 nights in the forest'
  ]),
  'Things the weird kid did in class': new Set([
    'ate glue', 'ate a glue stick', 'ate paste', 'ate a crayon', 'ate paper', 'chewed on a pencil', 'ate an eraser', 'licked the desk', 'licked a window', 'put a marker up his nose', 'sniffed markers', 'ate boogers', 'picked his nose', 'wiped it on the desk', 'barked', 'meowed', 'made cat noises', 'made weird noises', 'hummed constantly', 'talked to himself', 'talked to his pencil', 'named his eraser', 'brought a pet rock', 'brought a frog', 'kept a bug in his desk', 'collected bugs', 'drew on himself', 'drew on the desk', 'colored on his arm', 'wore a cape', 'wore a costume', 'wore sunglasses inside', 'kept his hood up', 'slept under the desk', 'hid under the desk', 'sat under the table', 'rocked back and forth', 'tipped his chair back', 'fell out of his chair', 'spun in his chair', 'crawled on the floor', 'pretended to be a dinosaur', 'roared', 'made dinosaur noises', 'ran around the room', 'flapped his arms', 'pretended to fly', 'stared at the wall', 'stared at you', 'laughed at nothing', 'cried for no reason', 'screamed randomly', 'yelled out answers', 'corrected the teacher', 'argued with the teacher', 'raised his hand to say nothing', 'told a long story', 'overshared', 'told everyone his dream', 'brought weird snacks', 'ate something raw', 'put gum in his hair', 'stuck gum under the desk', 'collected pencil shavings', 'sharpened his pencil to nothing', 'broke crayons on purpose', 'hoarded snacks', 'kept food in his desk', 'had a messy desk', 'smelled markers', 'tasted glue again', 'put glue on his hands to peel it', 'peeled dried glue', 'made glue skin', 'stapled his papers a hundred times', 'colored outside the lines on purpose'
  ])
};
