module.exports = {
  "McDonald's menu items": new Set([
    "big mac",
    "mcnuggets",
    "chicken mcnuggets",
    "mcflurry",
    "mcdouble",
    "quarter pounder",
    "quarter pounder with cheese",
    "double quarter pounder",
    "mcchicken",
    "filet o fish",
    "filet-o-fish",
    "fish fillet",
    "fries",
    "french fries",
    "world famous fries",
    "large fries",
    "medium fries",
    "small fries",
    "happy meal",
    "mcrib",
    "hash brown",
    "hashbrown",
    "hash browns",
    "apple pie",
    "baked apple pie",
    "hot apple pie",
    "mcgriddle",
    "mcgriddles",
    "egg mcmuffin",
    "sausage mcmuffin",
    "sausage mcmuffin with egg",
    "shamrock shake",
    "cheeseburger",
    "double cheeseburger",
    "hamburger",
    "mcdouble cheeseburger",
    "mccrispy",
    "mcspicy",
    "spicy mcchicken",
    "spicy chicken sandwich",
    "crispy chicken sandwich",
    "deluxe crispy chicken",
    "mcwrap",
    "snack wrap",
    "chicken snack wrap",
    "mcgriddle sandwich",
    "bacon egg and cheese biscuit",
    "sausage biscuit",
    "biscuit",
    "sausage burrito",
    "breakfast burrito",
    "big breakfast",
    "big breakfast with hotcakes",
    "hotcakes",
    "pancakes",
    "mcgriddle bacon egg cheese",
    "fruit and maple oatmeal",
    "oatmeal",
    "sweet tea",
    "unsweetened tea",
    "iced tea",
    "coffee",
    "mccafe",
    "mccafe coffee",
    "iced coffee",
    "frappe",
    "mocha frappe",
    "caramel frappe",
    "latte",
    "cappuccino",
    "americano",
    "hot chocolate",
    "mocha",
    "caramel macchiato",
    "espresso",
    "coke",
    "coca cola",
    "diet coke",
    "sprite",
    "fanta",
    "fanta orange",
    "dr pepper",
    "hi-c",
    "hi-c orange",
    "orange hi-c",
    "sweet n sour sauce",
    "sweet and sour sauce",
    "bbq sauce",
    "barbecue sauce",
    "honey mustard",
    "honey mustard sauce",
    "ranch",
    "creamy ranch",
    "spicy buffalo sauce",
    "buffalo sauce",
    "ketchup",
    "mustard",
    "tartar sauce",
    "big mac sauce",
    "special sauce",
    "mayo",
    "sweet chili sauce",
    "mighty wings",
    "chicken wings",
    "mcnugget sauce",
    "chicken selects",
    "ranch snack wrap",
    "grilled chicken sandwich",
    "mctato",
    "mcveggie",
    "mcaloo tikki",
    "maharaja mac",
    "chicken maharaja mac",
    "mcspicy paneer",
    "mclobster",
    "mclobster roll",
    "mcbaguette",
    "croque mcdo",
    "royale with cheese",
    "mcroyal",
    "grand big mac",
    "mac jr",
    "double big mac",
    "triple cheeseburger",
    "big tasty",
    "bacon clubhouse",
    "clubhouse burger",
    "angus burger",
    "third pounder",
    "sirloin third pounder",
    "mighty kids meal",
    "mcdonaldland cookies",
    "mcdonaldland",
    "cookies",
    "chocolate chip cookie",
    "chocolate chip cookies",
    "oreo mcflurry",
    "m&m mcflurry",
    "mnm mcflurry",
    "reeses mcflurry",
    "sundae",
    "hot fudge sundae",
    "caramel sundae",
    "strawberry sundae",
    "mcsundae",
    "soft serve",
    "vanilla cone",
    "ice cream cone",
    "ice cream",
    "kiddie cone",
    "mcdonalds cone",
    "baked goods",
    "cinnamon roll",
    "cinnamon melts",
    "apple slices",
    "apple slices snack",
    "go-gurt",
    "yogurt",
    "side salad",
    "caesar salad",
    "premium salad",
    "southwest salad",
    "bacon ranch salad",
    "grilled chicken salad",
    "fruit n yogurt parfait",
    "yogurt parfait",
    "parfait",
    "milk",
    "chocolate milk",
    "apple juice",
    "orange juice",
    "minute maid orange juice",
    "honey",
    "jam",
    "grape jam",
    "strawberry jam",
    "syrup",
    "mcgriddle syrup",
    "ketchup packet",
    "salt packet",
    "mclean deluxe",
    "arch deluxe",
    "mcpizza",
    "mcdonalds pizza",
    "mcdlt",
    "hula burger",
    "onion nuggets",
    "cheese danish",
    "danish",
    "fruit and walnut salad",
    "snack size fries",
    "mcnugget 4 piece",
    "6 piece nuggets",
    "10 piece nuggets",
    "20 piece nuggets",
    "40 piece nuggets",
    "sausage patty",
    "scrambled eggs",
    "english muffin",
    "mcdonalds coffee",
    "seasonal pie",
    "pumpkin pie",
    "cherry pie",
    "strawberry pie",
    "holiday pie",
    "mcfloat",
    "root beer float",
    "mcskillet burrito",
    "steak egg and cheese bagel",
    "bagel",
    "spicy chicken mcnuggets",
    "glazed chicken mcnuggets",
    "sweet and spicy nuggets",
  ]),
  'Things you dip in ranch': new Set([
    "pizza",
    "pizza crust",
    "wings",
    "buffalo wings",
    "chicken wings",
    "carrots",
    "baby carrots",
    "fries",
    "french fries",
    "celery",
    "chicken tenders",
    "chicken strips",
    "chicken nuggets",
    "nuggets",
    "broccoli",
    "jalapeno poppers",
    "jalapeno",
    "mozzarella sticks",
    "cheese sticks",
    "cauliflower",
    "cucumbers",
    "cucumber",
    "bell peppers",
    "peppers",
    "cherry tomatoes",
    "tomatoes",
    "onion rings",
    "tater tots",
    "hash browns",
    "potato wedges",
    "wedges",
    "fried pickles",
    "pickles",
    "pretzels",
    "soft pretzels",
    "pretzel bites",
    "bread",
    "breadsticks",
    "garlic bread",
    "crackers",
    "tortilla chips",
    "chips",
    "potato chips",
    "corn chips",
    "french bread",
    "baguette",
    "crostini",
    "everything",
    "more ranch",
    "cheese curds",
    "fried cheese curds",
    "quesadilla",
    "taquitos",
    "egg rolls",
    "spring rolls",
    "mini corn dogs",
    "corn dogs",
    "popcorn chicken",
    "chicken popcorn",
    "tacos",
    "burritos",
    "baked potato",
    "sweet potato fries",
    "curly fries",
    "waffle fries",
    "crinkle fries",
    "steak fries",
    "fish sticks",
    "fish fingers",
    "fried shrimp",
    "shrimp",
    "calamari",
    "fried zucchini",
    "zucchini",
    "asparagus",
    "green beans",
    "snap peas",
    "snow peas",
    "radishes",
    "sugar snap peas",
    "grape tomatoes",
    "cheese",
    "string cheese",
    "cheese cubes",
    "salami",
    "pepperoni",
    "sausage",
    "kielbasa",
    "bratwurst",
    "hot dogs",
    "sliders",
    "burgers",
    "hamburger",
    "cheeseburger",
    "grilled cheese",
    "quesadillas",
    "nachos",
    "loaded fries",
    "buffalo cauliflower",
    "cauliflower wings",
    "artichoke",
    "artichoke hearts",
    "mushrooms",
    "fried mushrooms",
    "onion straws",
    "blooming onion",
    "funyuns",
    "doritos",
    "cheetos",
    "fritos",
    "sun chips",
    "ruffles",
    "pita",
    "pita bread",
    "naan",
    "flatbread",
    "tortilla",
    "wraps",
    "lettuce wraps",
    "spinach",
    "kale chips",
    "veggie tray",
    "crudites",
    "romaine",
    "iceberg lettuce",
    "salad",
    "cobb salad",
    "wedge salad",
    "ranch on salad",
    "tater tots casserole",
    "hot pockets",
    "pizza rolls",
    "bagel bites",
    "totinos",
    "stuffed mushrooms",
    "stuffed peppers",
    "mini quiche",
    "deviled eggs",
    "hard boiled eggs",
    "scrambled eggs",
    "bacon",
    "fried chicken",
    "chicken fingers",
    "chicken sandwich",
    "gyros",
    "falafel",
    "hummus chips",
    "cheez-its",
    "goldfish",
    "saltines",
    "ritz crackers",
    "wheat thins",
    "triscuits",
    "graham crackers",
    "animal crackers",
    "cornbread",
    "biscuits",
    "rolls",
    "dinner rolls",
    "croutons",
    "bagel chips",
    "plantain chips",
    "veggie straws",
    "kettle chips",
    "pita chips",
    "everything bagel",
    "english muffin",
    "toast",
    "texas toast",
    "cheese bread",
    "jalapeno cheese bread",
    "pizza bagels",
    "stromboli",
    "calzone",
    "empanadas",
    "pierogies",
    "dumplings",
    "wontons",
    "crab rangoon",
    "fried tofu",
    "tofu",
  ]),
  'Foods that are better cold the next day': new Set([
    "pizza",
    "cold pizza",
    "lasagna",
    "spaghetti",
    "fried chicken",
    "cold fried chicken",
    "meatloaf",
    "chili",
    "beef stew",
    "stew",
    "curry",
    "chicken curry",
    "beef curry",
    "thai curry",
    "gumbo",
    "jambalaya",
    "pot roast",
    "roast beef",
    "brisket",
    "pulled pork",
    "bbq",
    "barbecue ribs",
    "ribs",
    "casserole",
    "tuna casserole",
    "green bean casserole",
    "mac and cheese",
    "macaroni and cheese",
    "potato salad",
    "macaroni salad",
    "pasta salad",
    "coleslaw",
    "slaw",
    "fried rice",
    "lo mein",
    "chow mein",
    "pad thai",
    "sushi",
    "cold sesame noodles",
    "sesame noodles",
    "ramen",
    "stir fry",
    "general tsos chicken",
    "orange chicken",
    "sweet and sour pork",
    "kung pao chicken",
    "dumplings",
    "potstickers",
    "egg rolls",
    "spring rolls",
    "fried rice with egg",
    "cold cuts",
    "deli meat",
    "ham",
    "turkey",
    "roast turkey",
    "leftover turkey",
    "thanksgiving leftovers",
    "stuffing",
    "cranberry sauce",
    "mashed potatoes",
    "gravy",
    "sweet potatoes",
    "sweet potato casserole",
    "deviled eggs",
    "hard boiled eggs",
    "quiche",
    "frittata",
    "cold cut sandwich",
    "sandwich",
    "meatball sub",
    "meatballs",
    "spaghetti and meatballs",
    "baked ziti",
    "penne",
    "rigatoni",
    "ziti",
    "stuffed shells",
    "manicotti",
    "enchiladas",
    "tamales",
    "burritos",
    "quesadilla",
    "tacos",
    "taco meat",
    "nachos",
    "refried beans",
    "black beans",
    "baked beans",
    "cornbread",
    "fried fish",
    "cold salmon",
    "salmon",
    "poke",
    "ceviche",
    "shrimp cocktail",
    "crab cakes",
    "fritters",
    "falafel",
    "hummus",
    "baba ganoush",
    "tabbouleh",
    "grain salad",
    "quinoa salad",
    "lentil soup",
    "minestrone",
    "split pea soup",
    "bean soup",
    "chicken soup",
    "matzo ball soup",
    "borscht",
    "gazpacho",
    "cucumber salad",
    "caprese salad",
    "greek salad",
    "cobb salad",
    "tabouli",
    "ratatouille",
    "eggplant parmesan",
    "chicken parmesan",
    "veal parmesan",
    "parmigiana",
    "shepherds pie",
    "cottage pie",
    "beef wellington",
    "corned beef",
    "corned beef and cabbage",
    "pastrami",
    "kielbasa",
    "bratwurst",
    "sausage and peppers",
    "stuffed peppers",
    "stuffed cabbage",
    "cabbage rolls",
    "kimchi",
    "banchan",
    "japchae",
    "bibimbap",
    "bulgogi",
    "korean bbq",
    "kalbi",
    "biryani",
    "tikka masala",
    "butter chicken",
    "saag",
    "dal",
    "chana masala",
    "samosas",
    "pakora",
    "naan",
    "roti",
    "paratha",
    "aloo gobi",
    "palak paneer",
    "paneer",
    "pho",
    "banh mi",
    "cold noodles",
    "rice pudding",
    "bread pudding",
    "cheesecake",
    "tiramisu",
    "trifle",
    "fruit salad",
    "ambrosia",
    "jello",
    "carrot cake",
    "banana bread",
    "zucchini bread",
    "cinnamon rolls",
    "apple pie",
    "pecan pie",
    "pumpkin pie",
    "key lime pie",
    "brownies",
    "cookies",
    "cold brew",
    "watermelon",
    "leftover chinese food",
    "chinese leftovers",
    "indian leftovers",
    "cold cuts platter",
    "antipasto",
    "charcuterie",
    "cold cuts and cheese",
    "muffuletta",
    "italian sub",
    "grinder",
  ]),
  "Gas station food you'd actually eat": new Set([
    "hot dog",
    "gas station hot dog",
    "roller hot dog",
    "taquitos",
    "roller taquitos",
    "corn dog",
    "corn dogs",
    "pizza slice",
    "gas station pizza",
    "slice of pizza",
    "nachos",
    "cheese nachos",
    "chips",
    "potato chips",
    "doritos",
    "cheetos",
    "fritos",
    "lays",
    "ruffles",
    "pringles",
    "sun chips",
    "funyuns",
    "takis",
    "hot fries",
    "andy capp hot fries",
    "combos",
    "gardettos",
    "chex mix",
    "beef jerky",
    "jerky",
    "slim jim",
    "slim jims",
    "beef sticks",
    "pepperoni stick",
    "meat stick",
    "string cheese",
    "cheese stick",
    "babybel",
    "cheese cubes",
    "hard boiled eggs",
    "deviled eggs",
    "donuts",
    "glazed donut",
    "chocolate donut",
    "powdered donuts",
    "mini donuts",
    "hostess donuts",
    "honey buns",
    "honey bun",
    "cinnamon roll",
    "danish",
    "muffin",
    "blueberry muffin",
    "banana nut muffin",
    "twinkies",
    "ding dongs",
    "ho hos",
    "zingers",
    "cupcakes",
    "little debbie",
    "oatmeal cream pie",
    "nutty buddy",
    "swiss rolls",
    "star crunch",
    "cosmic brownies",
    "fudge rounds",
    "cookies",
    "chips ahoy",
    "oreos",
    "famous amos",
    "grandmas cookies",
    "rice krispie treat",
    "rice krispies treat",
    "granola bar",
    "nature valley bar",
    "clif bar",
    "protein bar",
    "cliff bar",
    "candy bar",
    "snickers",
    "twix",
    "kit kat",
    "reeses",
    "reeses cups",
    "m&ms",
    "mnms",
    "milky way",
    "three musketeers",
    "butterfinger",
    "hundred grand",
    "crunch bar",
    "hersheys",
    "hershey bar",
    "payday",
    "baby ruth",
    "almond joy",
    "mounds",
    "100 grand",
    "skittles",
    "starburst",
    "sour patch kids",
    "swedish fish",
    "gummy bears",
    "gummy worms",
    "haribo",
    "nerds",
    "airheads",
    "laffy taffy",
    "tootsie roll",
    "jolly ranchers",
    "lifesavers",
    "mentos",
    "tic tacs",
    "altoids",
    "gum",
    "trident",
    "extra gum",
    "5 gum",
    "big red",
    "juicy fruit",
    "bubble gum",
    "slushie",
    "slurpee",
    "icee",
    "frozen coke",
    "fountain drink",
    "soda",
    "coke",
    "pepsi",
    "mountain dew",
    "dr pepper",
    "sprite",
    "gatorade",
    "powerade",
    "red bull",
    "monster",
    "monster energy",
    "rockstar",
    "5 hour energy",
    "vitamin water",
    "water",
    "coffee",
    "gas station coffee",
    "cappuccino machine coffee",
    "hot cocoa",
    "iced tea",
    "sweet tea",
    "arizona iced tea",
    "arizona green tea",
    "snapple",
    "yoo-hoo",
    "chocolate milk",
    "milk",
    "ice cream",
    "ice cream sandwich",
    "drumstick",
    "klondike bar",
    "push pop",
    "bomb pop",
    "popsicle",
    "fudgesicle",
    "choco taco",
    "banana",
    "apple",
    "orange",
    "trail mix",
    "peanuts",
    "sunflower seeds",
    "david sunflower seeds",
    "cashews",
    "mixed nuts",
    "pistachios",
    "pork rinds",
    "chicharrones",
    "pretzels",
    "rold gold",
    "soft pretzel",
    "bagel",
    "breakfast sandwich",
    "breakfast burrito",
    "biscuit sandwich",
    "sausage biscuit",
    "croissant",
    "egg sandwich",
    "fresh fruit cup",
    "fruit cup",
    "yogurt",
    "go-gurt",
    "string cheese snack",
    "lunchables",
    "cup noodles",
    "ramen",
    "instant ramen",
    "microwave burrito",
    "white castle frozen",
    "hot pocket",
    "hot pockets",
    "jalapeno poppers",
    "mozzarella sticks",
    "chicken tenders",
    "fried chicken",
    "wings",
    "gas station fried chicken",
    "krispy krunchy chicken",
    "champs chicken",
    "spicy chicken",
  ]),
  'Things you put on toast': new Set([
    "butter",
    "margarine",
    "jam",
    "strawberry jam",
    "grape jam",
    "raspberry jam",
    "apricot jam",
    "jelly",
    "grape jelly",
    "marmalade",
    "orange marmalade",
    "honey",
    "peanut butter",
    "almond butter",
    "cashew butter",
    "sunflower butter",
    "nutella",
    "chocolate spread",
    "cookie butter",
    "biscoff",
    "cinnamon sugar",
    "cinnamon and sugar",
    "brown sugar",
    "maple syrup",
    "syrup",
    "golden syrup",
    "avocado",
    "mashed avocado",
    "smashed avocado",
    "guacamole",
    "cream cheese",
    "whipped cream cheese",
    "ricotta",
    "cottage cheese",
    "mascarpone",
    "clotted cream",
    "sour cream",
    "greek yogurt",
    "hummus",
    "tahini",
    "baba ganoush",
    "pesto",
    "tapenade",
    "olive tapenade",
    "sun-dried tomatoes",
    "tomato",
    "sliced tomato",
    "cherry tomatoes",
    "cucumber",
    "cucumber slices",
    "radish",
    "radishes",
    "egg",
    "fried egg",
    "scrambled egg",
    "poached egg",
    "soft boiled egg",
    "egg salad",
    "tuna salad",
    "chicken salad",
    "smoked salmon",
    "lox",
    "gravlax",
    "sardines",
    "anchovies",
    "mackerel",
    "bacon",
    "bacon bits",
    "ham",
    "prosciutto",
    "salami",
    "pepperoni",
    "turkey",
    "cheese",
    "cheddar",
    "cheddar cheese",
    "swiss cheese",
    "brie",
    "goat cheese",
    "feta",
    "mozzarella",
    "gouda",
    "provolone",
    "american cheese",
    "melted cheese",
    "grilled cheese",
    "beans",
    "baked beans",
    "refried beans",
    "mushrooms",
    "sauteed mushrooms",
    "spinach",
    "sauteed spinach",
    "arugula",
    "microgreens",
    "sprouts",
    "kimchi",
    "sauerkraut",
    "pickles",
    "pickled onions",
    "red onion",
    "onion",
    "caramelized onions",
    "garlic",
    "garlic butter",
    "herb butter",
    "everything bagel seasoning",
    "sesame seeds",
    "chia seeds",
    "flax seeds",
    "hemp seeds",
    "pumpkin seeds",
    "sunflower seeds",
    "granola",
    "banana",
    "banana slices",
    "strawberries",
    "sliced strawberries",
    "blueberries",
    "raspberries",
    "blackberries",
    "figs",
    "fig jam",
    "sliced apple",
    "apple butter",
    "pear",
    "peaches",
    "mango",
    "kiwi",
    "grapes",
    "raisins",
    "dates",
    "prunes",
    "apricots",
    "lemon curd",
    "orange curd",
    "custard",
    "whipped cream",
    "cool whip",
    "chocolate chips",
    "sprinkles",
    "powdered sugar",
    "caramel",
    "caramel sauce",
    "dulce de leche",
    "vegemite",
    "marmite",
    "promite",
    "clotted cream and jam",
    "cream and jam",
    "beans on toast",
    "scrambled eggs and cheese",
    "ham and cheese",
    "avocado and egg",
    "pb and j",
    "peanut butter and jelly",
    "peanut butter and banana",
    "nutella and banana",
    "honey and butter",
    "butter and sugar",
    "garlic and herb",
    "balsamic glaze",
    "olive oil",
    "extra virgin olive oil",
    "chili crisp",
    "chili oil",
    "sriracha",
    "hot sauce",
    "mustard",
    "dijon mustard",
    "mayo",
    "aioli",
    "ketchup",
    "relish",
    "pico de gallo",
    "salsa",
    "corn relish",
    "chutney",
    "mango chutney",
    "apple sauce",
    "applesauce",
    "lemon zest",
    "sea salt",
    "flaky salt",
    "pepper",
    "red pepper flakes",
    "oregano",
    "basil",
    "fresh basil",
    "thyme",
    "rosemary",
    "chives",
    "parsley",
    "dill",
    "mint",
    "everything seasoning",
  ]),
  'School cafeteria foods': new Set([
    "pizza",
    "rectangle pizza",
    "square pizza",
    "pizza day",
    "cheese pizza",
    "pepperoni pizza",
    "chicken nuggets",
    "nuggets",
    "chicken patty",
    "chicken sandwich",
    "chicken tenders",
    "popcorn chicken",
    "chicken fingers",
    "corn dog",
    "corndog",
    "hot dog",
    "hamburger",
    "cheeseburger",
    "sloppy joe",
    "sloppy joes",
    "mystery meat",
    "meatloaf",
    "salisbury steak",
    "spaghetti",
    "spaghetti and meatballs",
    "mac and cheese",
    "macaroni and cheese",
    "grilled cheese",
    "grilled cheese and tomato soup",
    "tomato soup",
    "chicken noodle soup",
    "chili",
    "chili and cinnamon roll",
    "tacos",
    "taco day",
    "walking tacos",
    "nachos",
    "nacho grande",
    "burrito",
    "quesadilla",
    "taco salad",
    "rice",
    "spanish rice",
    "beans",
    "refried beans",
    "mashed potatoes",
    "mashed potatoes and gravy",
    "tater tots",
    "french fries",
    "fries",
    "crinkle fries",
    "curly fries",
    "onion rings",
    "hash browns",
    "corn",
    "creamed corn",
    "green beans",
    "peas",
    "carrots",
    "mixed vegetables",
    "steamed broccoli",
    "broccoli",
    "side salad",
    "salad bar",
    "lettuce",
    "coleslaw",
    "applesauce",
    "fruit cup",
    "mixed fruit cup",
    "peaches",
    "pears",
    "mandarin oranges",
    "pineapple",
    "grapes",
    "apple",
    "banana",
    "orange",
    "fruit snacks",
    "raisins",
    "jello",
    "jello cup",
    "pudding",
    "pudding cup",
    "chocolate pudding",
    "rice krispie treat",
    "cookies",
    "chocolate chip cookie",
    "sugar cookie",
    "brownie",
    "cake",
    "birthday cake",
    "cupcake",
    "ice cream",
    "ice cream cup",
    "ice cream sandwich",
    "push pop",
    "dixie cup",
    "popsicle",
    "frozen yogurt",
    "milk",
    "chocolate milk",
    "strawberry milk",
    "white milk",
    "milk carton",
    "juice box",
    "apple juice",
    "orange juice",
    "fruit punch",
    "capri sun",
    "water",
    "cornbread",
    "dinner roll",
    "roll",
    "biscuit",
    "breadstick",
    "garlic bread",
    "pretzel",
    "soft pretzel",
    "pretzel and cheese",
    "cheese sauce",
    "string cheese",
    "goldfish",
    "graham crackers",
    "animal crackers",
    "saltines",
    "crackers",
    "peanut butter and jelly",
    "pb and j",
    "uncrustables",
    "sun butter sandwich",
    "turkey sandwich",
    "ham sandwich",
    "bologna sandwich",
    "cheese sandwich",
    "sub sandwich",
    "hoagie",
    "wrap",
    "chicken wrap",
    "caesar wrap",
    "yogurt",
    "go-gurt",
    "yogurt parfait",
    "granola bar",
    "cheese stick",
    "baby carrots",
    "celery sticks",
    "ranch",
    "ranch dressing",
    "ketchup",
    "mustard",
    "fish sticks",
    "fish nuggets",
    "fish patty",
    "filet sandwich",
    "frito pie",
    "walking taco",
    "enchiladas",
    "fajitas",
    "stir fry",
    "fried rice",
    "orange chicken",
    "egg roll",
    "ramen",
    "macaroni salad",
    "pasta salad",
    "potato salad",
    "baked potato",
    "loaded potato",
    "chicken alfredo",
    "alfredo",
    "penne pasta",
    "ravioli",
    "lasagna",
    "stuffed crust pizza",
    "calzone",
    "pizza pocket",
    "hot pocket",
    "bagel",
    "bagel and cream cheese",
    "muffin",
    "blueberry muffin",
    "cinnamon roll",
    "pancakes",
    "waffles",
    "french toast",
    "french toast sticks",
    "breakfast pizza",
    "breakfast burrito",
    "scrambled eggs",
    "sausage",
    "bacon",
    "cereal",
    "cereal bowl",
    "oatmeal",
    "grits",
    "yogurt cup",
  ]),
  "Foods that shouldn't exist but do": new Set([
    "candy corn",
    "spray cheese",
    "easy cheese",
    "cheese in a can",
    "jello salad",
    "jell-o salad",
    "lime jello salad",
    "turducken",
    "deep fried butter",
    "fried butter",
    "pickle juice",
    "pickle juice slushie",
    "unicorn frappuccino",
    "peeps",
    "peeps marshmallow",
    "fruitcake",
    "circus peanuts",
    "jellied cranberry",
    "canned cranberry sauce",
    "aspic",
    "tomato aspic",
    "meat jello",
    "head cheese",
    "scrapple",
    "spam",
    "spam musubi",
    "vienna sausages",
    "potted meat",
    "deviled ham",
    "liverwurst",
    "blood sausage",
    "blood pudding",
    "black pudding",
    "haggis",
    "balut",
    "century egg",
    "thousand year egg",
    "lutefisk",
    "surstromming",
    "casu marzu",
    "durian",
    "stinky tofu",
    "natto",
    "fermented shark",
    "hakarl",
    "rocky mountain oysters",
    "fried twinkie",
    "deep fried oreo",
    "deep fried oreos",
    "deep fried coke",
    "deep fried kool-aid",
    "deep fried snickers",
    "deep fried pickle",
    "deep fried bubblegum",
    "chocolate covered bacon",
    "chocolate covered crickets",
    "chocolate covered ants",
    "cricket flour",
    "cricket protein bar",
    "mealworm",
    "grasshopper tacos",
    "bacon soda",
    "ranch soda",
    "ketchup chips",
    "all dressed chips",
    "dill pickle chips",
    "pickle flavored",
    "cotton candy grapes",
    "grapple",
    "grapples",
    "pluot",
    "cronut",
    "ramen burger",
    "sushi burrito",
    "pizza cone",
    "spaghetti tacos",
    "pickle pizza",
    "mac and cheese pizza",
    "ramen pizza",
    "cauliflower pizza",
    "cauliflower rice",
    "cauliflower wings",
    "banana ketchup",
    "tomato ketchup ice cream",
    "ketchup ice cream",
    "mayochup",
    "mayonnaise ice cream",
    "squid ink pasta",
    "squid ink ice cream",
    "charcoal ice cream",
    "black ice cream",
    "activated charcoal latte",
    "gold leaf",
    "edible gold",
    "gold covered steak",
    "glitter beer",
    "edible glitter",
    "unicorn poop",
    "unicorn poop cookies",
    "rainbow bagel",
    "rainbow grilled cheese",
    "bagel seasoning everything",
    "peeps oreos",
    "candy cane oreos",
    "swedish fish oreos",
    "cotton candy oreos",
    "hot dog stuffed crust",
    "pickle soda",
    "kale chips",
    "seaweed snacks",
    "seaweed chips",
    "cauliflower gnocchi",
    "beet ketchup",
    "jellied eels",
    "spam fries",
    "twinkie wiener sandwich",
    "fool's gold loaf",
    "peanut butter and pickle sandwich",
    "fluffernutter",
    "marshmallow fluff",
    "grape soda jelly",
    "bacon jam",
    "bacon flavored everything",
    "bacon ice cream",
    "garlic ice cream",
    "wasabi ice cream",
    "jalapeno ice cream",
    "corn ice cream",
    "cheese ice cream",
    "lobster ice cream",
    "hot dog ice cream",
    "ranch ice cream",
    "mac and cheese ice cream",
    "beer ice cream",
    "dorito loco taco",
    "doritos locos tacos",
    "cheeto burrito",
    "flamin hot funnel cake",
    "pizza fries",
    "chili cheese fritos",
    "pickle in a pouch",
    "pickled pigs feet",
    "pigs feet",
    "tripe",
    "menudo",
    "chitlins",
    "chitterlings",
    "ox tongue",
    "beef tongue",
    "tongue tacos",
    "brain tacos",
    "liver and onions",
    "gizzards",
    "chicken feet",
    "duck feet",
    "jellyfish salad",
    "sea cucumber",
    "escargot",
    "frog legs",
    "alligator",
    "kangaroo",
    "ostrich egg",
    "quail eggs",
    "ant eggs",
    "escamoles",
    "fried tarantula",
    "scorpion lollipop",
    "cricket lollipop",
    "worm lollipop",
    "tequila lollipop",
    "mealworm chips",
    "jello pretzel salad",
    "watergate salad",
    "cool whip salad",
    "cookie salad",
    "snickers salad",
    "frog eye salad",
    "ambrosia salad",
    "seven layer salad",
    "green goddess everything",
    "ranch water",
    "pumpkin spice everything",
    "pumpkin spice spam",
    "pumpkin spice latte",
    "peeps milk",
    "peeps flavored milk",
  ]),
  'Things at a buffet nobody touches': new Set([
    "jello",
    "red jello",
    "green jello",
    "jello cubes",
    "jello salad",
    "ambrosia salad",
    "fruit salad",
    "canned fruit",
    "fruit cocktail",
    "fruit cocktail cup",
    "mandarin oranges",
    "cottage cheese",
    "cottage cheese with fruit",
    "prunes",
    "stewed prunes",
    "plain lettuce",
    "iceberg lettuce",
    "wilted lettuce",
    "plain salad",
    "limp salad",
    "bean sprouts",
    "raw bean sprouts",
    "pickled beets",
    "beets",
    "canned beets",
    "pickled eggs",
    "hard boiled eggs",
    "deviled eggs",
    "liver",
    "chopped liver",
    "liver and onions",
    "gizzards",
    "chicken gizzards",
    "chicken livers",
    "tripe",
    "menudo",
    "sweetbreads",
    "tongue",
    "head cheese",
    "aspic",
    "tomato aspic",
    "gelatin mold",
    "molded salad",
    "watergate salad",
    "five cup salad",
    "seven layer salad",
    "seafood salad",
    "imitation crab",
    "krab salad",
    "crab salad",
    "tuna salad",
    "tuna casserole",
    "creamed corn",
    "creamed spinach",
    "stewed tomatoes",
    "canned green beans",
    "mushy peas",
    "peas and carrots",
    "boiled carrots",
    "steamed cabbage",
    "boiled cabbage",
    "brussels sprouts",
    "lima beans",
    "succotash",
    "okra",
    "stewed okra",
    "collard greens",
    "turnip greens",
    "mustard greens",
    "beet salad",
    "three bean salad",
    "four bean salad",
    "kidney beans",
    "garbanzo beans",
    "chickpea salad",
    "macaroni salad",
    "ambrosia",
    "tapioca pudding",
    "tapioca",
    "rice pudding",
    "bread pudding",
    "bread and butter pudding",
    "prune juice",
    "watery scrambled eggs",
    "powdered scrambled eggs",
    "rubbery eggs",
    "cold scrambled eggs",
    "sausage links sitting too long",
    "mystery meat",
    "salisbury steak",
    "gray meatloaf",
    "liver pate",
    "sardines",
    "pickled herring",
    "herring",
    "anchovies",
    "jellied eels",
    "oysters",
    "raw oysters",
    "clams",
    "mussels",
    "octopus salad",
    "squid salad",
    "seaweed salad",
    "kelp salad",
    "sea cucumber",
    "jellyfish",
    "escargot",
    "snails",
    "caviar",
    "fish eggs",
    "roe",
    "cold cuts",
    "bologna",
    "olive loaf",
    "head cheese loaf",
    "liverwurst",
    "spam",
    "vienna sausages",
    "potted meat",
    "canned ham",
    "soggy fries",
    "cold fries",
    "stale bread",
    "dry dinner rolls",
    "hard rolls",
    "crackers",
    "saltines",
    "plain crackers",
    "wilted vegetables",
    "raw cauliflower",
    "raw broccoli",
    "plain celery",
    "plain carrots",
    "radishes",
    "raw onion slices",
    "pickle slices",
    "relish tray",
    "olive tray",
    "black olives",
    "green olives",
    "pimento olives",
    "pearl onions",
    "pickled okra",
    "pickled cauliflower",
    "giardiniera",
    "sauerkraut",
    "kimchi",
    "cabbage rolls",
    "stuffed cabbage",
    "stuffed peppers",
    "cold stuffed peppers",
    "cold rice",
    "fried rice gone cold",
    "lo mein dried out",
    "crusty mashed potatoes",
    "gravy skin",
    "congealed gravy",
    "cold gravy",
    "lukewarm soup",
    "cream of mushroom soup",
    "minestrone",
    "split pea soup",
    "clam chowder",
    "gazpacho",
    "cold borscht",
    "cucumber salad",
    "wilted spinach",
    "wilted greens",
    "plain cottage cheese",
    "ranch dressing puddle",
    "french dressing",
    "russian dressing",
    "thousand island",
    "blue cheese chunks",
    "powdered donuts",
    "stale donuts",
    "fruitcake",
    "figgy pudding",
    "sugar free jello",
    "diet pudding",
    "melon balls",
    "honeydew",
    "honeydew melon",
    "cantaloupe rinds",
    "watermelon rind",
    "pickled watermelon rind",
    "soggy salad bar croutons",
    "old bacon bits",
    "imitation bacon bits",
    "plain pasta",
    "overcooked pasta",
    "mushy pasta",
    "cold pizza crust",
    "pizza bones",
    "stale bread sticks",
    "hard breadsticks",
    "cafeteria style green bean casserole",
    "scalloped potatoes that sat out",
    "cold scalloped potatoes",
  ]),
  'Midnight snack choices': new Set([
    "cereal",
    "bowl of cereal",
    "cold cereal",
    "leftover pizza",
    "cold pizza",
    "pizza",
    "ice cream",
    "ice cream straight from the carton",
    "ben and jerrys",
    "pint of ice cream",
    "ice cream sandwich",
    "popsicle",
    "cookies",
    "chocolate chip cookies",
    "oreos",
    "oreo",
    "milk and cookies",
    "chips",
    "potato chips",
    "doritos",
    "cheetos",
    "pringles",
    "tortilla chips",
    "nachos",
    "loaded nachos",
    "popcorn",
    "microwave popcorn",
    "buttered popcorn",
    "crackers",
    "cheese and crackers",
    "cheese",
    "string cheese",
    "cheese stick",
    "leftovers",
    "cold leftovers",
    "cold chinese food",
    "chinese leftovers",
    "fried rice",
    "lo mein",
    "ramen",
    "instant ramen",
    "cup noodles",
    "cup o noodles",
    "mac and cheese",
    "easy mac",
    "kraft mac and cheese",
    "spaghetti",
    "cold spaghetti",
    "leftover pasta",
    "pasta",
    "buttered noodles",
    "grilled cheese",
    "grilled cheese sandwich",
    "peanut butter and jelly",
    "pb and j",
    "peanut butter",
    "peanut butter from the jar",
    "peanut butter sandwich",
    "toast",
    "buttered toast",
    "cinnamon toast",
    "nutella",
    "nutella from the jar",
    "nutella sandwich",
    "bananas",
    "banana",
    "apple",
    "apple slices",
    "orange",
    "grapes",
    "strawberries",
    "fruit",
    "yogurt",
    "greek yogurt",
    "yogurt cup",
    "pudding",
    "pudding cup",
    "jello",
    "applesauce",
    "granola bar",
    "protein bar",
    "trail mix",
    "mixed nuts",
    "peanuts",
    "almonds",
    "cashews",
    "pistachios",
    "pretzels",
    "pretzel rods",
    "goldfish",
    "cheez-its",
    "graham crackers",
    "animal crackers",
    "rice cakes",
    "granola",
    "muffin",
    "blueberry muffin",
    "leftover cake",
    "cake",
    "slice of cake",
    "brownie",
    "brownies",
    "donut",
    "donuts",
    "honey bun",
    "pop tarts",
    "pop tart",
    "toaster strudel",
    "waffle",
    "frozen waffle",
    "eggo",
    "pancakes",
    "leftover pancakes",
    "scrambled eggs",
    "fried egg",
    "egg sandwich",
    "quesadilla",
    "cheese quesadilla",
    "burrito",
    "microwave burrito",
    "taco bell",
    "hot pocket",
    "hot pockets",
    "pizza rolls",
    "bagel bites",
    "totinos pizza rolls",
    "mozzarella sticks",
    "chicken nuggets",
    "dino nuggets",
    "tendies",
    "tater tots",
    "frozen fries",
    "french fries",
    "leftover fries",
    "corn dog",
    "frozen corn dog",
    "mini corn dogs",
    "hummus and chips",
    "hummus",
    "veggies and ranch",
    "carrots and ranch",
    "celery and peanut butter",
    "ants on a log",
    "smoothie",
    "milkshake",
    "chocolate milk",
    "hot chocolate",
    "tea",
    "chamomile tea",
    "warm milk",
    "glass of milk",
    "soda",
    "leftover wings",
    "chicken wings",
    "cold wings",
    "rotisserie chicken",
    "leftover chicken",
    "cold fried chicken",
    "fried chicken",
    "sub sandwich",
    "deli sandwich",
    "sandwich",
    "ham sandwich",
    "turkey sandwich",
    "leftover burger",
    "cheeseburger",
    "slim jim",
    "beef jerky",
    "lunchables",
    "gushers",
    "fruit snacks",
    "gummy bears",
    "gummy worms",
    "candy",
    "candy bar",
    "chocolate",
    "chocolate bar",
    "m&ms",
    "snickers",
    "kit kat",
    "reeses",
    "skittles",
    "sour patch kids",
    "marshmallows",
    "smores",
    "cheese ball",
    "cheese dip",
    "queso",
    "salsa and chips",
    "guacamole",
    "avocado toast",
    "leftover takeout",
    "takeout",
    "sushi",
    "leftover sushi",
    "dumplings",
    "leftover dumplings",
    "egg rolls",
    "spring rolls",
    "fortune cookies",
    "wonton soup",
    "cold cuts",
    "pickles",
    "pickle",
    "olives",
    "crackers and cheese",
  ]),
  "Foods you eat with your hands but probably shouldn't": new Set([
    "spaghetti",
    "soup",
    "ice cream",
    "mashed potatoes",
    "cereal",
    "yogurt",
    "oatmeal",
    "grits",
    "macaroni and cheese",
    "mac and cheese",
    "ramen",
    "ramen noodles",
    "pho",
    "lo mein",
    "fried rice",
    "rice",
    "sticky rice",
    "risotto",
    "mashed sweet potatoes",
    "gravy",
    "beef stew",
    "stew",
    "chili",
    "soup with noodles",
    "chicken noodle soup",
    "tomato soup",
    "clam chowder",
    "gumbo",
    "jambalaya",
    "curry",
    "chicken curry",
    "tikka masala",
    "butter chicken",
    "dal",
    "saag",
    "stir fry",
    "beans",
    "baked beans",
    "refried beans",
    "chili con carne",
    "scrambled eggs",
    "over easy eggs",
    "poached eggs",
    "egg yolk",
    "runny eggs",
    "pudding",
    "chocolate pudding",
    "jello",
    "jell-o",
    "custard",
    "flan",
    "creme brulee",
    "tapioca",
    "tapioca pudding",
    "rice pudding",
    "bread pudding",
    "applesauce",
    "mashed bananas",
    "fruit salad",
    "ambrosia",
    "whipped cream",
    "cottage cheese",
    "ricotta",
    "sour cream",
    "queso",
    "cheese dip",
    "fondue",
    "cheese fondue",
    "chocolate fondue",
    "molten lava cake",
    "lava cake",
    "soft serve",
    "milkshake",
    "smoothie",
    "slushie",
    "frozen yogurt",
    "gelato",
    "sorbet",
    "sherbet",
    "honey",
    "peanut butter",
    "nutella",
    "jam",
    "jelly",
    "syrup",
    "maple syrup",
    "caramel",
    "caramel sauce",
    "hot fudge",
    "gravy boat",
    "au jus",
    "broth",
    "bone broth",
    "ramen broth",
    "miso soup",
    "egg drop soup",
    "wonton soup",
    "hot and sour soup",
    "minestrone",
    "split pea soup",
    "lentil soup",
    "bean soup",
    "chowder",
    "bisque",
    "lobster bisque",
    "cream of mushroom",
    "borscht",
    "gazpacho",
    "cold soup",
    "spaghetti and meatballs",
    "fettuccine alfredo",
    "alfredo",
    "carbonara",
    "linguine",
    "penne",
    "rigatoni",
    "ravioli",
    "gnocchi",
    "tortellini",
    "lasagna",
    "baked ziti",
    "spaghetti sauce",
    "marinara",
    "bolognese",
    "pasta with sauce",
    "buttered noodles",
    "noodles",
    "udon",
    "soba",
    "pad thai",
    "drunken noodles",
    "dan dan noodles",
    "cold sesame noodles",
    "japchae",
    "glass noodles",
    "rice noodles",
    "biryani",
    "jollof rice",
    "paella",
    "congee",
    "porridge",
    "cream of wheat",
    "malt o meal",
    "polenta",
    "creamed corn",
    "creamed spinach",
    "collard greens",
    "gumbo z herbes",
    "etouffee",
    "crawfish etouffee",
    "shrimp and grits",
    "poke bowl",
    "poke",
    "ceviche",
    "menudo",
    "posole",
    "pozole",
    "tom yum",
    "laksa",
    "khao soi",
    "massaman curry",
    "green curry",
    "red curry",
    "yellow curry",
    "panang curry",
    "vindaloo",
    "korma",
    "rogan josh",
    "chana masala",
    "aloo gobi",
    "palak paneer",
    "matar paneer",
    "chicken tikka masala",
    "dosa filling",
    "sambar",
    "rasam",
    "kheer",
    "gulab jamun syrup",
    "rice and gravy",
    "biscuits and gravy",
    "sausage gravy",
    "cream gravy",
    "beef gravy",
    "mushroom gravy",
    "stroganoff",
    "beef stroganoff",
    "goulash",
    "beef bourguignon",
    "coq au vin",
    "cassoulet",
    "ratatouille",
    "shepherds pie filling",
    "cottage pie",
    "pot pie filling",
    "chicken pot pie",
    "beef pot pie",
    "frosting",
    "cake batter",
    "cookie dough",
    "brownie batter",
    "melted cheese",
    "nacho cheese",
    "fondue cheese",
    "raclette",
  ]),
};
