module.exports = {
  'SpongeBob characters': new Set([
    'spongebob', 'spongebob squarepants', 'sponge bob', 'bob esponja',
    'patrick', 'patrick star', 'patrick the star', 'patty',
    'squidward', 'squidward tentacles', 'squid',
    'sandy', 'sandy cheeks',
    'plankton', 'sheldon plankton', 'sheldon j plankton', 'sheldon j. plankton',
    'mr krabs', 'mr. krabs', 'eugene krabs', 'eugene h krabs', 'eugene h. krabs', 'mister krabs',
    'gary', 'gary the snail',
    'mrs puff', 'mrs. puff', 'misses puff',
    'pearl', 'pearl krabs',
    'larry', 'larry the lobster',
    'karen', 'karen plankton', 'computer wife',
    'mermaid man', 'mermaidman',
    'barnacle boy', 'barnacleboy',
    'king neptune', 'neptune',
    'flying dutchman', 'the flying dutchman',
    'patchy', 'patchy the pirate',
    'potty', 'potty the parrot',
    'bubble bass',
    'old man jenkins', 'man ray', 'manray', 'the dirty bubble', 'dirty bubble',
    'squilliam', 'squilliam fancyson',
    'mama krabs', 'mrs krabs',
    'grandma squarepants', 'grandma', 'mr squarepants', 'mrs squarepants', 'harold squarepants', 'margaret squarepants',
    'puff daddy', 'jellyfish', 'jellyfishes', 'kevin', 'kevin the sea cucumber',
    'doodlebob', 'doodle bob',
    'spongegar', 'primitive sponge',
    'fred', 'fred the fish', 'my leg guy', 'my leg',
    'nat peterson', 'tom', 'harold', 'frank', 'evelyn',
    'nancy', 'sadie', 'sadie rechid', 'tom smith',
    'scooter',
    'flatts', 'flatts the flounder',
    'mrs tentacles', 'squidwards mother',
    'grandma plankton', 'clamu', 'mystery', 'mystery the seahorse',
    'puffy fluffy', 'lord poltergeist',
    'french narrator', 'the french narrator', 'narrator',
    'bubble buddy',
    'wormy', 'mini krabs',
    'kelpy g', 'kelpy g.',
    'don the whale', 'lady upturn',
    'bart', 'bart the fish',
    'incidental', 'incidentals',
    'shubie',
    'reg', 'reg the bouncer',
    'monroe', 'monroe timmy',
    'johnny elaine', 'pretty patty',
    'plankton cousins', 'clem',
    'percy', 'billy',
    'no name', 'roger',
    'realistic fish head', 'perch perkins', 'perch', 'johnny krill',
    'old man walker',
    'betsy krabs',
    'sea bear', 'the sea bear', 'sea rhinoceros',
    'alaskan bull worm', 'alaskan bull worm wormy',
    'tubelets',
    'queen jellyfish', 'queen amphitrite', 'mindy', 'princess mindy',
    'dennis', 'cyclops', 'the cyclops',
    'victor', 'the algae are always greener',
    'goofy goober',
    'tina', 'fillet', 'shelley', 'sam star', 'samantha star',
    'herb star', 'margie star', 'gary the snail',
    'snellie', 'snellie the snail',
    'old man jenkins',
    'tartar sauce', 'pat', 'lou',
    'flying dutchmans crew',
    'gus', 'sergeant sam',
    'salty spitoon',
    'mr doodles', 'jim', 'old jim',
    'sea urchin', 'urchins',
    'chum', 'chumbucket worker',
    'hooky', 'the hooks',
    'krusty krab employees',
    'baby spongebob', 'todd',
    'aquatic adventures', 'fish customer', 'anchovies', 'the anchovies',
    'mable monica', 'mable', 'monica',
    'tom orange', 'fish bystander',
    'larrys cousins',
    'jenny', 'rube', 'rube the fish',
    'archie', 'old fishes',
    'old gus',
    'patrar', 'patrick spongebob',
    'sea chimps', 'super weenie hut juniors',
    'normal',
    'flotsam', 'jetsam',
    'glove world mascot', 'glovey glove',
    'mr scaredy pants',
    'donny', 'kenny the cat', 'kenny',
    'grubby grouper',
    'el diablo', 'spongebob clone',
    'narlene', 'sandys cousin', 'narlene cheeks',
    'randy', 'randy cheeks',
    'old salty',
    'lou the hot dog vendor'
  ]),

  'Minecraft mobs': new Set([
    'creeper', 'creepers', 'charged creeper',
    'zombie', 'zombies', 'baby zombie', 'zombie villager', 'husk', 'drowned',
    'skeleton', 'skeletons', 'stray', 'wither skeleton', 'wither skeletons', 'bogged',
    'spider', 'spiders', 'cave spider', 'cave spiders',
    'enderman', 'endermen', 'endermite',
    'slime', 'slimes', 'magma cube', 'magma cubes',
    'witch', 'witches',
    'zombie pigman', 'zombie pigmen', 'zombified piglin', 'zombified piglins',
    'piglin', 'piglins', 'piglin brute', 'piglin brutes',
    'hoglin', 'hoglins', 'zoglin', 'zoglins',
    'ghast', 'ghasts', 'happy ghast',
    'blaze', 'blazes',
    'wither', 'the wither',
    'ender dragon', 'enderdragon', 'dragon',
    'shulker', 'shulkers',
    'guardian', 'guardians', 'elder guardian', 'elder guardians',
    'phantom', 'phantoms',
    'silverfish', 'silverfishes',
    'pillager', 'pillagers',
    'vindicator', 'vindicators',
    'evoker', 'evokers',
    'vex', 'vexes',
    'ravager', 'ravagers',
    'illusioner', 'illusioners',
    'warden', 'the warden',
    'zombie horse', 'skeleton horse',
    'cow', 'cows', 'mooshroom', 'mooshrooms', 'mushroom cow',
    'pig', 'pigs',
    'sheep', 'sheeps',
    'chicken', 'chickens',
    'horse', 'horses', 'donkey', 'donkeys', 'mule', 'mules',
    'llama', 'llamas', 'trader llama',
    'wolf', 'wolves', 'dog',
    'cat', 'cats', 'ocelot', 'ocelots',
    'rabbit', 'rabbits', 'killer bunny', 'the killer bunny',
    'fox', 'foxes',
    'bee', 'bees',
    'panda', 'pandas',
    'polar bear', 'polar bears',
    'turtle', 'turtles',
    'dolphin', 'dolphins',
    'cod', 'salmon', 'pufferfish', 'tropical fish', 'fish',
    'squid', 'squids', 'glow squid', 'glow squids',
    'bat', 'bats',
    'parrot', 'parrots',
    'villager', 'villagers', 'wandering trader',
    'iron golem', 'iron golems',
    'snow golem', 'snow golems', 'snowman',
    'goat', 'goats',
    'axolotl', 'axolotls',
    'frog', 'frogs', 'tadpole', 'tadpoles',
    'allay', 'allays',
    'sniffer', 'sniffers',
    'camel', 'camels',
    'armadillo', 'armadillos',
    'breeze', 'breezes',
    'strider', 'striders',
    'glow squid',
    'cod fish',
    'baby villager',
    'wither boss',
    'guardian fish',
    'mooshroom cow',
    'brown mooshroom', 'red mooshroom',
    'jockey', 'spider jockey', 'chicken jockey', 'skeleton trap horse',
    'giant', 'the giant',
    'creaking', 'the creaking',
    'baby cow', 'baby pig', 'baby sheep', 'baby chicken',
    'tamed wolf', 'tamed cat',
    'elder guardian',
    'magma slime',
    'wither skeleton jockey',
    'snow golem snowman',
    'enderman tall',
    'pink sheep', 'jeb sheep', 'jeb_',
    'baby horse', 'foal',
    'baby llama',
    'baby panda',
    'baby fox',
    'baby turtle',
    'baby polar bear',
    'baby goat',
    'baby axolotl',
    'baby frog',
    'sea turtle',
    'cave spider jockey',
    'wandering trader llama',
    'zombie villager farmer',
    'piglin bartering',
    'nether mob',
    'overworld mob',
    'end mob',
    'hostile mob',
    'passive mob',
    'neutral mob',
    'tameable mob',
    'utility mob',
    'boss mob',
    'flying mob',
    'undead mob',
    'arthropod',
    'illager', 'illagers',
    'raid mob',
    'aquatic mob'
  ]),

  'Pokemon from Gen 1': new Set([
    'bulbasaur', 'ivysaur', 'venusaur',
    'charmander', 'charmeleon', 'charizard',
    'squirtle', 'wartortle', 'blastoise',
    'caterpie', 'metapod', 'butterfree',
    'weedle', 'kakuna', 'beedrill',
    'pidgey', 'pidgeotto', 'pidgeot',
    'rattata', 'raticate',
    'spearow', 'fearow',
    'ekans', 'arbok',
    'pikachu', 'raichu',
    'sandshrew', 'sandslash',
    'nidoran', 'nidoran-f', 'nidoran-m', 'nidoran female', 'nidoran male',
    'nidorina', 'nidoqueen',
    'nidorino', 'nidoking',
    'clefairy', 'clefable',
    'vulpix', 'ninetales',
    'jigglypuff', 'wigglytuff',
    'zubat', 'golbat',
    'oddish', 'gloom', 'vileplume',
    'paras', 'parasect',
    'venonat', 'venomoth',
    'diglett', 'dugtrio',
    'meowth', 'persian',
    'psyduck', 'golduck',
    'mankey', 'primeape',
    'growlithe', 'arcanine',
    'poliwag', 'poliwhirl', 'poliwrath',
    'abra', 'kadabra', 'alakazam',
    'machop', 'machoke', 'machamp',
    'bellsprout', 'weepinbell', 'victreebel',
    'tentacool', 'tentacruel',
    'geodude', 'graveler', 'golem',
    'ponyta', 'rapidash',
    'slowpoke', 'slowbro',
    'magnemite', 'magneton',
    'farfetchd', "farfetch'd", 'farfetch d',
    'doduo', 'dodrio',
    'seel', 'dewgong',
    'grimer', 'muk',
    'shellder', 'cloyster',
    'gastly', 'haunter', 'gengar',
    'onix',
    'drowzee', 'hypno',
    'krabby', 'kingler',
    'voltorb', 'electrode',
    'exeggcute', 'exeggutor',
    'cubone', 'marowak',
    'hitmonlee', 'hitmonchan',
    'lickitung',
    'koffing', 'weezing',
    'rhyhorn', 'rhydon',
    'chansey',
    'tangela',
    'kangaskhan',
    'horsea', 'seadra',
    'goldeen', 'seaking',
    'staryu', 'starmie',
    'mr mime', 'mr. mime', 'mr-mime', 'mister mime',
    'scyther',
    'jynx',
    'electabuzz',
    'magmar',
    'pinsir',
    'tauros',
    'magikarp', 'gyarados',
    'lapras',
    'ditto',
    'eevee', 'vaporeon', 'jolteon', 'flareon',
    'porygon',
    'omanyte', 'omastar',
    'kabuto', 'kabutops',
    'aerodactyl',
    'snorlax',
    'articuno', 'zapdos', 'moltres',
    'dratini', 'dragonair', 'dragonite',
    'mewtwo', 'mew'
  ]),

  'Things you can do in GTA': new Set([
    'drive', 'drive a car', 'drive cars', 'driving',
    'steal a car', 'steal cars', 'carjack', 'carjacking', 'jack a car',
    'rob a store', 'rob a bank', 'rob banks', 'rob people', 'robbery', 'heist', 'heists', 'do a heist',
    'shoot', 'shoot people', 'shoot guns', 'gunfight', 'gunfights',
    'fly a plane', 'fly planes', 'fly a helicopter', 'fly helicopters', 'fly a jet', 'flying',
    'ride a bike', 'ride a motorcycle', 'ride bikes', 'motorcycle',
    'drive a tank', 'drive tanks', 'tank',
    'race', 'racing', 'street race', 'street racing', 'do races',
    'parachute', 'parachuting', 'skydive', 'skydiving', 'base jump',
    'go to the strip club', 'visit the strip club',
    'buy weapons', 'buy guns', 'go to ammu-nation', 'ammunation', 'ammu nation',
    'play golf', 'golf',
    'play tennis', 'tennis',
    'play darts', 'darts',
    'go bowling', 'bowling',
    'do yoga', 'yoga',
    'go to the gym', 'work out', 'exercise',
    'swim', 'swimming', 'scuba dive', 'scuba diving', 'dive',
    'go fishing', 'fishing',
    'play arcade games', 'arcade',
    'gamble', 'gambling', 'go to the casino', 'casino', 'play poker', 'play blackjack', 'play slots', 'play roulette',
    'buy a house', 'buy property', 'buy properties', 'buy a business', 'buy an apartment',
    'buy clothes', 'shop for clothes', 'go shopping', 'shopping',
    'get a haircut', 'haircut', 'go to the barber',
    'get a tattoo', 'tattoo', 'tattoos',
    'customize your car', 'mod your car', 'go to los santos customs', 'los santos customs', 'lscustoms',
    'paint your car', 'spray your car',
    'wash your car', 'car wash',
    'call a friend', 'hang out with friends', 'go on a date',
    'eat', 'eat food', 'buy food', 'go to a restaurant', 'order food',
    'drink', 'get drunk', 'go to a bar', 'go to a club', 'nightclub',
    'smoke', 'do drugs', 'sell drugs', 'drug deals',
    'fight', 'punch people', 'melee', 'beat up people',
    'evade police', 'run from cops', 'escape the police', 'get a wanted level', 'lose the cops',
    'get arrested', 'go to jail', 'get busted',
    'die', 'go to the hospital', 'respawn',
    'cause chaos', 'cause mayhem', 'go on a rampage', 'rampage',
    'blow up cars', 'blow things up', 'use explosives', 'throw grenades', 'plant bombs',
    'use cheats', 'enter cheat codes', 'spawn vehicles',
    'play missions', 'do missions', 'story missions', 'do jobs', 'jobs',
    'free roam', 'explore the map', 'explore the city',
    'collect collectibles', 'find hidden packages', 'spaceship parts', 'letter scraps',
    'do stunts', 'stunt jumps', 'do stunt jumps',
    'ride a jet ski', 'jet ski', 'drive a boat', 'drive boats', 'sail',
    'drive a bus', 'be a taxi driver', 'drive a taxi', 'taxi',
    'become a vigilante', 'become a paramedic', 'become a firefighter',
    'play as a character', 'switch characters', 'change characters',
    'walk around', 'jog', 'run', 'sprint',
    'climb', 'parkour',
    'take selfies', 'use snapmatic', 'take photos', 'photography',
    'watch tv', 'watch movies', 'go to the cinema', 'go to the movies',
    'listen to the radio', 'change radio stations', 'listen to music',
    'browse the internet', 'use your phone', 'check email',
    'play minigames', 'minigames',
    'do trick shots',
    'rob convenience stores', 'rob gas stations',
    'pick up hookers', 'hire prostitutes',
    'go to the airport', 'airport',
    'do wheelies', 'do donuts', 'drift', 'drifting',
    'jump off buildings', 'jump off a bridge', 'cliff dive',
    'use the train', 'ride the train', 'drive the train',
    'fly the blimp', 'blimp',
    'play online', 'play with friends', 'gta online', 'online',
    'start a business', 'run a business', 'sell cars',
    'do bounty hunting', 'become a bounty hunter',
    'race motorcycles', 'race cars', 'race boats', 'race planes',
    'play deathmatch', 'team deathmatch', 'capture the flag',
    'rob an armored truck', 'rob the security van',
    'attack pedestrians', 'run over people', 'hit pedestrians',
    'cause a traffic jam', 'crash cars',
    'use a parachute off mount chiliad', 'climb mount chiliad', 'mount chiliad',
    'visit vinewood', 'go to vinewood',
    'visit the beach', 'go to the beach',
    'find easter eggs', 'find the ghost', 'find bigfoot', 'find the loch ness monster',
    'do a triathlon', 'run a marathon',
    'play heists with crew', 'set up heists',
    'buy a yacht', 'yacht',
    'buy a plane', 'buy a helicopter', 'buy vehicles',
    'use armor', 'put on body armor',
    'heal up', 'use a med kit',
    'spray graffiti', 'tag walls',
    'become a cop killer', 'fight the army', 'fight the military',
    'use a flamethrower', 'use a minigun', 'use a rocket launcher', 'use a sniper rifle',
    'ride in a limo', 'limo',
    'go off-roading', 'off road',
    'play hide and seek', 'play modes',
    'crash a plane', 'crash a helicopter',
    'rob a jewelry store', 'jewelry heist',
    'do the lifeinvader mission', 'social media',
    'invest in stocks', 'trade stocks', 'stock market',
    'rob a fleeca bank',
    'do prep missions', 'do setups',
    'sell stolen cars', 'deliver cars',
    'become a pilot',
    'use jetpack', 'jetpack',
    'ride a quad bike', 'quad bike', 'atv',
    'go to a music festival', 'go to a concert',
    'meditate', 'sleep', 'save the game'
  ]),

  'Fortnite skins': new Set([
    'jonesy', 'agent jonesy', 'the foundation', 'rebel',
    'renegade raider', 'aerial assault trooper', 'black knight', 'raven', 'red knight', 'blue squire',
    'skull trooper', 'ghoul trooper', 'pink ghoul trooper', 'purple skull trooper',
    'peely', 'agent peely', 'p-1000',
    'fishstick', 'fish stick', 'world cup fishstick',
    'midas', 'golden midas', 'ghost midas', 'shadow midas',
    'meowscles', 'kit', 'shadow meowscles',
    'skye', 'tntina', 'brutus', 'maya',
    'travis scott', 'astronomical', 'astro jack', 'cactus jack',
    'marshmello', 'marshmallow',
    'ariana grande', 'rift tour ariana',
    'the weeknd',
    'naruto', 'sasuke', 'sakura', 'kakashi', 'itachi', 'gaara', 'hinata', 'orochimaru', 'might guy',
    'goku', 'vegeta', 'bulma', 'beerus', 'piccolo', 'gohan',
    'spider-man', 'spiderman', 'miles morales', 'spider gwen', 'spider-gwen',
    'venom', 'carnage', 'green goblin',
    'deadpool', 'cable',
    'wolverine', 'storm', 'mystique',
    'thanos',
    'iron man', 'tony stark', 'captain america', 'thor', 'star-lord', 'star lord', 'groot', 'gamora',
    'black widow', 'doctor doom', 'silver surfer',
    'batman', 'the dark knight', 'catwoman', 'harley quinn', 'joker', 'aquaman', 'the flash', 'superman', 'wonder woman', 'green arrow',
    'master chief', 'kratos',
    'lara croft', 'aloy',
    'ryu', 'chun-li', 'chun li', 'cammy', 'blanka', 'guile', 'sakura street fighter',
    'lebron james', 'neymar jr', 'neymar', 'harry kane', 'marco reus',
    'ali-a', 'lachlan', 'ninja', 'loserfruit', 'tfue', 'bugha',
    'the mandalorian', 'mando', 'baby yoda', 'grogu', 'boba fett', 'luke skywalker', 'darth vader', 'darth maul', 'stormtrooper', 'kylo ren', 'rey', 'the mandalorian beskar',
    'predator', 'alien xenomorph', 'xenomorph', 'ripley',
    'john wick', 'the reaper', 'reaper',
    'rick sanchez', 'morty',
    'ariana', 'lebron',
    'drift', 'omega', 'the visitor', 'ice king', 'dire', 'lynx', 'a.i.m.', 'aim',
    'calamity', 'sgt winter', 'sergeant winter',
    'ragnarok', 'the prisoner', 'snowfoot',
    'cuddle team leader', 'pink bear', 'fennix',
    'raptor', 'rex', 'tricera ops', 'triceratops',
    'leviathan', 'dj yonder', 'dj bop', 'beef boss', 'tomatohead', 'durrr burger',
    'doggo', 'guff', 'doggo doggy',
    'brite bomber', 'brite gunner', 'bunny brawler', 'rabbit raider',
    'love ranger', 'cupid',
    'dark voyager', 'liteshow', 'galaxy', 'galaxy skin', 'ikonik', 'ikonik skin',
    'wonder', 'glow', 'eon', 'rogue agent', 'double helix',
    'wildcat', 'royale knight',
    'nog ops', 'crackshot', 'codename elf', 'merry marauder', 'ginger gunner',
    'sgt green clover', 'fireworks team leader',
    'banner', 'banner brigade',
    'fortnite chicken', 'chicken',
    'lil whip', 'gunner',
    'crystal', 'sparkle specialist', 'aura', 'guild',
    'recon expert', 'recon scout', 'wild card', 'wildcard',
    'elite agent', 'special forces', 'rust lord',
    'tomato temple', 'remix peely', 'agent peely',
    'fennix the fox', 'lt evergreen',
    'big chuggus',
    'lexa', 'jules', 'doggo',
    'mancake', 'cluck',
    'lobby bot',
    'orin', 'spire assassin',
    'kondor', 'menace', 'pumpkin',
    'oro', 'the golden ruler',
    'machinist', 'jonesy the first',
    'siona', 'reese', 'dummy',
    'kymera', 'the alien', 'doctor slone',
    'fabio sparklemane', 'unicorn', 'cuddlepool',
    'spider-knight', 'spider knight',
    'omega knight',
    'jennifer walters', 'she-hulk', 'she hulk',
    'wolverine zero',
    'piccolo',
    'snake eyes', 'gi joe',
    'street fighter',
    'naruto kurama',
    'omni-man', 'omni man', 'invincible',
    'spawn',
    'rick grimes', 'michonne', 'daryl', 'the walking dead',
    'kratos god of war',
    'family guy peter', 'peter griffin',
    'solid snake', 'snake',
    'ahsoka tano', 'ahsoka',
    'optimus prime', 'megatron', 'transformers',
    'goku black',
    'gilgamesh', 'eikthyrnir',
    'fall guy', 'fall guys',
    'jujutsu kaisen', 'gojo', 'satoru gojo', 'yuji itadori', 'megumi', 'nobara',
    'eren yeager', 'mikasa', 'levi', 'attack on titan',
    'mecha team leader', 'mecha cuddle master'
  ]),

  'Mario power-ups and items': new Set([
    'super mushroom', 'mushroom', 'mushrooms', 'red mushroom',
    'fire flower', 'fireflower', 'fire flowers',
    'ice flower', 'iceflower',
    'super star', 'star', 'invincibility star', 'starman', 'super star invincibility',
    'super leaf', 'tanooki leaf', 'leaf',
    'tanooki suit', 'tanuki suit',
    'frog suit',
    'hammer suit',
    'penguin suit',
    'propeller mushroom', 'propeller suit',
    'mini mushroom', 'mega mushroom',
    'cape feather', 'cape', 'feather',
    'p-wing', 'p wing',
    'cloud flower', 'spring mushroom',
    'rainbow star', 'red star',
    'boomerang flower', 'boomerang suit',
    'gold flower', 'golden flower',
    'bell', 'super bell', 'cat bell', 'lucky bell',
    'double cherry', 'cherry',
    'super acorn', 'acorn', 'flying squirrel',
    'goomba mask',
    'fire mario', 'cape mario', 'tanooki mario', 'cat mario', 'frog mario',
    'one up mushroom', '1-up mushroom', '1up mushroom', '1 up mushroom', 'green mushroom', 'extra life mushroom',
    'poison mushroom',
    'super crown', 'crown',
    'wonder flower',
    'elephant fruit', 'elephant mario', 'drill mushroom', 'bubble flower',
    'mega mushroom',
    'starman', 'invincibility',
    'coin', 'coins', 'gold coin', 'red coin', 'red coins', 'blue coin',
    'star coin', 'star coins', 'big coin',
    'power star', 'power stars', 'grand star', 'grand stars',
    'shine sprite', 'shine sprites', 'shine',
    'green shell', 'green koopa shell', 'koopa shell',
    'red shell', 'red shells',
    'blue shell', 'spiny shell', 'blue spiny shell',
    'banana', 'banana peel', 'bananas',
    'mushroom kart', 'triple mushroom',
    'bob-omb', 'bob omb', 'bobomb',
    'fake item box', 'item box',
    'lightning', 'lightning bolt', 'thunderbolt',
    'bullet bill', 'bullet bill item',
    'boo', 'boo item',
    'golden mushroom', 'mushroom cannon',
    'fire flower kart',
    'super horn',
    'crazy eight', 'crazy 8',
    'piranha plant', 'piranha plant pot', 'potted piranha plant',
    'boomerang', 'boomerang flower',
    'star bit', 'star bits',
    'life mushroom', 'gold star',
    'spin drill', 'drill',
    'cloud', 'lakitu cloud', 'jet cloud',
    'flower', 'flowers',
    'key', 'keys', 'big key',
    'p-switch', 'p switch', 'p block',
    'pow block', 'pow',
    'spring', 'trampoline',
    'warp pipe', 'pipe', 'warp box',
    'vine', 'beanstalk',
    'block', 'question block', 'brick block', '? block', 'item block',
    'flagpole', 'flag',
    'yoshi egg', 'yoshi',
    'baby yoshi', 'fire yoshi', 'balloon yoshi', 'bubble yoshi',
    'kuribo shoe', 'goomba shoe', 'shoe',
    'fire bar',
    'starman invincibility',
    'mega star', 'lightning bolt',
    'wing cap', 'metal cap', 'vanish cap', 'cap',
    'water', 'fludd', 'f.l.u.d.d.',
    'rocket nozzle', 'turbo nozzle', 'hover nozzle',
    'gold ring',
    'fire orb',
    'health mushroom', 'heart', 'hearts',
    'badge', 'badges',
    'maple syrup', 'mushroom potion', 'potion',
    'snifit', 'flower power',
    'ice skate',
    'mega mushroom item',
    'lakitu',
    'blooper', 'blooper item',
    'pow block item',
    'spiny',
    'super feather', 'p balloon', 'balloon',
    'whistle', 'magic whistle', 'warp whistle',
    'super acorn item',
    'lucky bell item'
  ]),

  'Disney villains': new Set([
    'maleficent',
    'ursula', 'ursula the sea witch',
    'jafar',
    'scar',
    'gaston',
    'captain hook', 'hook',
    'cruella', 'cruella de vil', 'cruella deville',
    'the evil queen', 'evil queen', 'grimhilde', 'the queen',
    'queen of hearts',
    'hades', 'hades the god of the underworld',
    'frollo', 'judge claude frollo', 'claude frollo',
    'shere khan',
    'kaa',
    'mother gothel', 'gothel',
    'lady tremaine', 'the wicked stepmother', 'stepmother',
    'governor ratcliffe', 'ratcliffe',
    'yzma',
    'doctor facilier', 'dr facilier', 'dr. facilier', 'the shadow man', 'shadow man',
    'prince hans', 'hans',
    'king candy', 'turbo',
    'lots-o-huggin bear', 'lotso', 'lots o huggin bear',
    'syndrome', 'buddy pine',
    'randall', 'randall boggs',
    'henry j waternoose', 'waternoose',
    'hopper',
    'sid', 'sid phillips',
    'stinky pete', 'the prospector',
    'al', 'al mcwhiggin',
    'gabby gabby',
    'charles muntz', 'muntz',
    'ernesto de la cruz', 'ernesto',
    'bellwether', 'mayor bellwether',
    'tamatoa',
    'te ka', 'te fiti',
    'amos slade',
    'percival mcleach', 'mcleach',
    'sykes', 'bill sykes',
    'ratigan', 'professor ratigan',
    'horned king', 'the horned king',
    'madam mim', 'madame mim',
    'pete', 'peg leg pete', 'black pete',
    'the big bad wolf', 'big bad wolf',
    'chernabog',
    'monstro',
    'stromboli',
    'the coachman', 'coachman',
    'honest john', 'foulfellow',
    'gideon',
    'si and am', 'si', 'am',
    'the rat', 'lady and the tramp rat',
    'aunt sarah',
    'diablo', 'diablo the raven',
    'the goons', 'maleficents goons',
    'sir hiss',
    'prince john',
    'the sheriff of nottingham', 'sheriff of nottingham',
    'edgar', 'edgar balthazar', 'edgar the butler',
    'madame medusa', 'medusa',
    'mr snoops', 'snoops',
    'brutus and nero',
    'flotsam and jetsam', 'flotsam', 'jetsam',
    'the wicked stepsisters', 'anastasia', 'drizella',
    'lucifer', 'lucifer the cat',
    'the queen of hearts card soldiers',
    'oogie boogie',
    'lock shock and barrel', 'lock', 'shock', 'barrel',
    'clayton', 'william clayton',
    'sabor',
    'jafar genie', 'jafar as a genie',
    'iago',
    'razoul',
    'the magic mirror',
    'the headless horseman', 'headless horseman',
    'mr toad villains', 'mr winkie', 'winkie',
    'the toughs', 'weasels',
    'cy-bug', 'cy bugs',
    'gaston lefou', 'lefou',
    'forte', 'maestro forte',
    'jasper and horace', 'jasper', 'horace',
    'professor z', 'mater villain',
    'miles axlerod', 'axlerod',
    'auto', 'auto wall-e',
    'zira', 'kovu villain', 'nuka', 'vitani',
    'banzai', 'shenzi', 'ed', 'the hyenas', 'hyenas',
    'mor du', 'mordu', "mor'du",
    'darla', 'darla finding nemo',
    'bruce', 'bruce the shark',
    'screenslaver', 'the screenslaver',
    'evelyn deavor',
    'the firebird',
    'the queen grimhilde',
    'namaari',
    'druun', 'the druun',
    'bowler hat guy',
    'dor-15', 'doris',
    'lyle tiberius rourke', 'rourke', 'commander rourke',
    'helga sinclair', 'helga',
    'the grand duke of owls', 'grand duke of owls',
    'the cauldron born', 'cauldron born'
  ]),

  'Pixar movies': new Set([
    'toy story',
    'toy story 2', 'toy story two',
    'toy story 3', 'toy story three',
    'toy story 4', 'toy story four',
    'a bugs life', "a bug's life", 'a bugs life movie',
    'monsters inc', 'monsters inc.', 'monsters incorporated', "monsters, inc",
    'monsters university',
    'finding nemo',
    'finding dory',
    'the incredibles', 'incredibles',
    'incredibles 2', 'the incredibles 2', 'incredibles two',
    'cars',
    'cars 2', 'cars two',
    'cars 3', 'cars three',
    'ratatouille',
    'wall-e', 'wall e', 'walle', 'wall·e',
    'up',
    'brave',
    'inside out',
    'inside out 2', 'inside out two',
    'coco',
    'the good dinosaur',
    'soul',
    'luca',
    'turning red',
    'lightyear', 'buzz lightyear movie',
    'onward',
    'elemental',
    'elio'
  ]),

  'Things in Hogwarts': new Set([
    'the sorting hat', 'sorting hat',
    'the great hall', 'great hall',
    'gryffindor', 'gryffindor common room', 'gryffindor house', 'gryffindor tower',
    'slytherin', 'slytherin common room', 'slytherin house', 'slytherin dungeon',
    'hufflepuff', 'hufflepuff common room', 'hufflepuff house',
    'ravenclaw', 'ravenclaw common room', 'ravenclaw house', 'ravenclaw tower',
    'the four houses', 'house points', 'house cup',
    'moving staircases', 'the staircases', 'staircases', 'grand staircase',
    'moving portraits', 'portraits', 'the portraits', 'talking portraits',
    'the fat lady', 'fat lady portrait',
    'the bloody baron', 'bloody baron',
    'nearly headless nick', 'nearly-headless nick', 'sir nicholas',
    'the grey lady', 'grey lady',
    'the fat friar', 'fat friar',
    'peeves', 'peeves the poltergeist',
    'moaning myrtle', 'myrtle',
    'ghosts', 'the hogwarts ghosts',
    'the forbidden forest', 'forbidden forest',
    'the whomping willow', 'whomping willow',
    'the black lake', 'black lake', 'the great lake', 'the lake',
    'the chamber of secrets', 'chamber of secrets',
    'the basilisk', 'basilisk',
    'the room of requirement', 'room of requirement',
    'the restricted section', 'restricted section',
    'the library', 'hogwarts library',
    'the astronomy tower', 'astronomy tower',
    'the owlery', 'owlery',
    'the quidditch pitch', 'quidditch pitch', 'quidditch field',
    'quidditch', 'the golden snitch', 'golden snitch', 'snitch',
    'bludgers', 'bludger', 'the quaffle', 'quaffle',
    'brooms', 'broomsticks', 'nimbus 2000', 'firebolt',
    'the hospital wing', 'hospital wing',
    'dumbledores office', "dumbledore's office", 'the headmasters office',
    'the headmaster', 'dumbledore', 'albus dumbledore',
    'fawkes', 'fawkes the phoenix', 'the phoenix',
    'the pensieve', 'pensieve',
    'the sorcerers stone', "sorcerer's stone", 'philosophers stone', "philosopher's stone",
    'the mirror of erised', 'mirror of erised',
    'the goblet of fire', 'goblet of fire',
    'the triwizard tournament', 'triwizard tournament',
    'the marauders map', "marauder's map", 'marauders map',
    'platform nine and three quarters', 'platform 9 3/4', 'platform nine three quarters',
    'the hogwarts express', 'hogwarts express',
    'the kitchens', 'hogwarts kitchens', 'kitchens',
    'house elves', 'house-elves', 'dobby', 'winky',
    'the dungeons', 'dungeons',
    'the potions classroom', 'potions class', 'potions classroom',
    'the great hall ceiling', 'enchanted ceiling',
    'floating candles', 'the floating candles',
    'the prefects bathroom', "prefect's bathroom", 'prefects bathroom',
    'the gargoyle', 'the stone gargoyle',
    'suits of armor', 'suits of armour', 'the suits of armor',
    'secret passages', 'hidden passages', 'secret passageways',
    'the trophy room', 'trophy room',
    'the entrance hall', 'entrance hall',
    'the common rooms', 'common rooms',
    'dormitories', 'the dormitories',
    'the gamekeepers hut', "hagrid's hut", 'hagrids hut',
    'hagrid', 'rubeus hagrid',
    'professor mcgonagall', 'mcgonagall', 'minerva mcgonagall',
    'professor snape', 'snape', 'severus snape',
    'professor flitwick', 'flitwick',
    'professor sprout', 'sprout',
    'madam pomfrey', 'pomfrey',
    'madam hooch', 'hooch',
    'filch', 'argus filch',
    'mrs norris', 'mrs. norris',
    'the caretaker',
    'students', 'witches and wizards', 'wizards', 'witches',
    'wands', 'a wand', 'wand',
    'spells', 'magic', 'charms',
    'potions', 'cauldrons', 'a cauldron',
    'owls', 'pet owls', 'hedwig',
    'cats', 'toads', 'rats', 'pets',
    'the sorting ceremony', 'sorting ceremony',
    'the feast', 'the welcoming feast', 'feasts',
    'butterbeer',
    'chocolate frogs', 'chocolate frog',
    'bertie botts every flavour beans', 'bertie botts beans',
    'pumpkin juice', 'pumpkin pasties',
    'the trolley', 'the food trolley', 'trolley witch',
    'classrooms', 'the classrooms',
    'the herbology greenhouse', 'greenhouses', 'the greenhouses',
    'mandrakes', 'mandrake', 'the mandrakes',
    'the defence against the dark arts classroom', 'defense against the dark arts',
    'the transfiguration classroom', 'transfiguration class',
    'the charms classroom', 'charms class',
    'the divination classroom', 'divination tower', 'divination',
    'the clock tower', 'clock tower',
    'the bell tower', 'bell tower',
    'the boathouse', 'boathouse',
    'the courtyard', 'courtyards', 'the courtyards',
    'the viaduct', 'viaduct bridge', 'the bridge', 'wooden bridge',
    'the dark tower',
    'the grand piano',
    'paintings', 'magical paintings',
    'enchanted objects', 'magical objects',
    'the vanishing cabinet', 'vanishing cabinet',
    'a deluminator', 'the deluminator',
    'time-turner', 'time turner', 'the time-turner',
    'the invisibility cloak', 'invisibility cloak',
    'gobstones', 'wizards chess', "wizard's chess", 'exploding snap',
    'the train station', 'hogsmeade station',
    'the howler', 'howlers',
    'remembrall', 'a remembrall',
    'the standard book of spells', 'spell books', 'spellbooks',
    'the daily prophet', 'wizarding newspaper'
  ]),

  'Roblox games': new Set([
    'adopt me', 'adopt me!',
    'brookhaven', 'brookhaven rp',
    'tower of hell', 'toh',
    'blox fruits', 'bloxfruits',
    'pet simulator', 'pet simulator x', 'pet simulator 99', 'pet sim x', 'pet sim 99',
    'arsenal',
    'murder mystery 2', 'mm2', 'murder mystery',
    'jailbreak',
    'mad city',
    'natural disaster survival',
    'work at a pizza place', 'pizza place',
    'meepcity', 'meep city',
    'royale high', 'royale high school',
    'bee swarm simulator',
    'piggy',
    'doors',
    'rainbow friends',
    'flee the facility',
    'the maze',
    'welcome to bloxburg', 'bloxburg',
    'theme park tycoon', 'theme park tycoon 2',
    'restaurant tycoon', 'restaurant tycoon 2',
    'retail tycoon', 'retail tycoon 2',
    'lumber tycoon', 'lumber tycoon 2',
    'mining simulator', 'mining simulator 2',
    'build a boat for treasure', 'build a boat',
    'tower defense simulator', 'tds',
    'all star tower defense', 'astd',
    'anime adventures',
    'anime fighting simulator',
    'shindo life', 'shinobi life', 'shinobi life 2',
    'project slayers',
    'demon fall', 'demonfall',
    'king legacy',
    'grand piece online', 'gpo',
    'a one piece game', 'aopg',
    'pls donate',
    'dress to impress', 'dti',
    'fashion famous',
    'super hero tycoon',
    'a dusty trip',
    'a hero clicker',
    'evade',
    'untitled tag game', 'utg',
    'hide and seek extreme',
    'epic minigames',
    'super bomb survival',
    'speed run 4', 'speed run',
    'be a parkour ninja',
    'parkour',
    'the floor is lava',
    'survive the killer', 'std',
    'kat', 'knife ability test',
    'phantom forces',
    'counter blox',
    'big paintball', 'big paintball 2',
    'bad business',
    'criminality',
    'da hood',
    'the strongest battlegrounds',
    'untitled boxing game',
    'blade ball',
    'rivals',
    'combat warriors',
    'kaiju universe',
    'deepwoken',
    'rogue lineage',
    'world zero',
    'dungeon quest',
    'vesteria',
    'fantastic frontier',
    'islands', 'skyblock', 'roblox skyblock',
    'creatures of sonaria',
    'dragon adventures',
    'horse valley',
    'wild horse islands',
    'feline frenzy',
    'farm world',
    'horse world',
    'wolves life',
    'wolf life',
    'the wild west',
    'frontier justice',
    'westbound',
    'liberty county',
    'emergency response liberty county', 'erlc',
    'greenville',
    'driving empire',
    'car dealership tycoon',
    'ultimate driving',
    'vehicle legends',
    'pet sim',
    'clicker simulator',
    'strongman simulator',
    'lifting simulator',
    'arm wrestling simulator',
    'unboxing simulator',
    'fishing simulator',
    'fisch',
    'sols rng', "sol's rng",
    'cart ride into',
    'obby', 'obbies',
    'mega easy obby',
    'escape the obby',
    'escape grandmas house obby',
    'guess the emoji',
    'wacky wizards',
    'eat bricks',
    'pet swarm simulator',
    'ninja legends',
    'saber simulator',
    'bubble gum simulator',
    'magnet simulator',
    'snow shoveling simulator',
    'treasure quest',
    'swordburst online', 'swordburst 2',
    'one fruit simulator',
    'haze piece',
    'fruit battlegrounds',
    'anime last stand',
    'sonic speed simulator',
    'speed city',
    'club roblox',
    'overlook bay',
    'livetopia',
    'world of stands',
    'your bizarre adventure', 'yba',
    'a bizarre day', 'abd',
    'project jojo',
    'heroes online',
    'my hero mania',
    'heroes battlegrounds',
    'anime warriors',
    'tower battles',
    'zombie attack',
    'zombie rush',
    'apocalypse rising',
    'survive and kill the killers',
    'jailbreak roblox',
    'prison life',
    'redwood prison',
    'mad paintball',
    'super golf',
    'roblox bedwars', 'bedwars',
    'islands roblox',
    'lumber tycoon',
    'theme park',
    'super power training simulator',
    'dragon ball rage',
    'dragon ball z final stand',
    'pokemon brick bronze',
    'loomian legacy',
    'monsters of etheria',
    'pet trainer tycoon',
    'tapping legends',
    'clicking simulator'
  ])
};
