module.exports = {
  'Things teachers always say': new Set([
    'spit out your gum',
    'eyes up here',
    'this will be on the test',
    'were not leaving until its quiet',
    'i can wait',
    'is that your phone',
    'we have a sub today',
    'turn to page',
    'no talking',
    'show your work',
    'theres no bathroom pass',
    'quiet down',
    'settle down',
    'pay attention',
    'pop quiz',
    'clear your desk',
    'take out a pencil',
    'put your phone away',
    'no cell phones',
    'phones in the basket',
    'raise your hand',
    'dont call out',
    'one at a time',
    'work in pairs',
    'find a partner',
    'theres no talking during the test',
    'eyes on your own paper',
    'no cheating',
    'this is your warning',
    'this is your last warning',
    'do i need to separate you',
    'do we have a problem',
    'is there something you want to share with the class',
    'whats so funny',
    'care to share with the rest of us',
    'do you want to teach the class',
    'sit down',
    'stay in your seat',
    'walk dont run',
    'inside voices',
    'use your inside voice',
    'lower your voice',
    'i shouldnt have to repeat myself',
    'i wont say it again',
    'were waiting',
    'im waiting',
    'the bell doesnt dismiss you i do',
    'the bell is just a suggestion',
    'youre not done yet',
    'finish your work',
    'pencils down',
    'pens down',
    'eyes forward',
    'face the front',
    'turn around',
    'stop talking',
    'shh',
    'be quiet',
    'thats enough',
    'enough',
    'knock it off',
    'cut it out',
    'last call',
    'name on your paper',
    'put your name on it',
    'dont forget your name',
    'read the directions',
    'follow the directions',
    'did you read the question',
    'reread the question',
    'use complete sentences',
    'in your own words',
    'no late work',
    'this is due tomorrow',
    'this is due friday',
    'homework is on the board',
    'check the board',
    'its on the syllabus',
    'check the syllabus',
    'i posted it online',
    'check the website',
    'study tonight',
    'study for the test',
    'review your notes',
    'take notes',
    'are you taking notes',
    'write this down',
    'copy this down',
    'this is important',
    'pay close attention',
    'this is on the final',
    'open your books',
    'close your books',
    'put your books away',
    'line up',
    'single file line',
    'no running in the halls',
    'walk in the halls',
    'wait for the bell',
    'in your seats when the bell rings',
    'be in your seat',
    'youre tardy',
    'youre late',
    'wheres your pass',
    'do you have a pass',
    'where were you',
    'see me after class',
    'stay after class',
    'go to the office',
    'go see the principal',
    'im writing you up',
    'detention',
    'thats a detention',
    'one more time',
    'do you want detention',
    'spit it out',
    'speak up',
    'i cant hear you',
    'louder please',
    'enunciate',
    'slow down',
    'take your time',
    'hurry up',
    'lets go',
    'eyes on me',
    'all eyes on me',
    'give me your attention',
    'i need everyones attention',
    'attention please',
    'may i have your attention',
    'turn to your neighbor',
    'discuss with your partner',
    'group up',
    'get in groups',
    'no groups of four',
    'partner up',
    'theres no i in team',
    'work together',
    'help each other',
    'be respectful',
    'respect each other',
    'be kind',
    'no bullying',
    'use kind words',
    'apologize',
    'say youre sorry',
    'thats not appropriate',
    'watch your language',
    'that language is not okay',
    'we dont say that here',
    'thats not school appropriate',
    'hands to yourself',
    'keep your hands to yourself',
    'no touching',
    'personal space',
    'give them space',
    'sharpen your pencil before class',
    'no sharpening during the test',
    'i hear talking',
    'i still hear talking',
    'someone is talking',
    'this is not a free period',
    'this is not lunch',
    'this is not recess',
    'do your work',
    'get to work',
    'lets get started',
    'open to chapter',
    'were starting now',
    'class has started',
    'class is in session',
    'put that away',
    'no food in class',
    'no gum',
    'spit out your candy',
    'no drinks in the lab',
    'wrap it up',
    'finish up',
    'time is almost up',
    'five minutes left',
    'one minute left',
    'time',
    'pass your papers forward',
    'pass them up',
    'leave it on my desk',
    'turn it in',
    'hand it in',
  ]),

  'Things your parents text you': new Set([
    'call me',
    'where are you',
    'whats your password for netflix',
    'how do i send a picture',
    'love mom',
    'dinners ready',
    'did you eat',
    'be safe',
    'k',
    'call when you land',
    'call when you get there',
    'text me when youre there',
    'let me know youre safe',
    'are you home',
    'are you on your way',
    'when are you coming home',
    'what time will you be home',
    'home soon',
    'almost home',
    'on my way',
    'omw',
    'pick up milk',
    'we need milk',
    'grab bread on the way home',
    'can you pick up your brother',
    'pick up your sister',
    'did you feed the dog',
    'walk the dog',
    'take out the trash',
    'did you do your homework',
    'have you done your homework',
    'clean your room',
    'your room is a mess',
    'do the dishes',
    'unload the dishwasher',
    'fold the laundry',
    'did you make your bed',
    'love you',
    'love you too',
    'miss you',
    'thinking of you',
    'proud of you',
    'so proud',
    'good luck today',
    'good luck on your test',
    'how was school',
    'how was your day',
    'how did it go',
    'how was work',
    'whats up',
    'you there',
    'hello',
    'you awake',
    'are you up',
    'good morning',
    'good night',
    'sweet dreams',
    'sleep well',
    'wake up',
    'time to get up',
    'youre going to be late',
    'dont be late',
    'drive safe',
    'text me when you park',
    'who are you with',
    'where are you going',
    'with who',
    'be home by ten',
    'be home before dark',
    'curfew is ten',
    'whos driving',
    'is there a parent there',
    'call if you need a ride',
    'i can pick you up',
    'do you need money',
    'i sent you money',
    'check your account',
    'i venmoed you',
    'did you get it',
    'did you see my text',
    'did you get my message',
    'why arent you answering',
    'answer your phone',
    'pick up your phone',
    'i called you',
    'call me back',
    'its mom',
    'its dad',
    'this is mom',
    'how do i screenshot',
    'how do i forward this',
    'whats the wifi password',
    'is this a scam',
    'i think i got hacked',
    'someone is texting me weird',
    'how do i delete this',
    'my phone is full',
    'how do i clear space',
    'whats your address again',
    'send me your address',
    'whats the dogs vet number',
    'do you have plans this weekend',
    'are you free sunday',
    'come over for dinner',
    'grandma says hi',
    'grandma is asking about you',
    'aunt linda says hello',
    'happy birthday',
    'happy birthday sweetie',
    'happy holidays',
    'merry christmas',
    'happy new year',
    'be good',
    'behave',
    'make good choices',
    'dont do anything stupid',
    'call if you need anything',
    'im here if you need me',
    'just checking in',
    'checking in',
    'everything ok',
    'are you ok',
    'is everything alright',
    'whats wrong',
    'you seem off',
    'we need to talk',
    'see you soon',
    'see you tonight',
    'see you at dinner',
    'dont forget your jacket',
    'bring a jacket',
    'its cold out',
    'wear a coat',
    'bundle up',
    'did you take your medicine',
    'take your vitamins',
    'drink water',
    'stay hydrated',
    'get some rest',
    'go to bed',
    'dont stay up too late',
    'lights out',
    'turn off the lights',
    'lock the door',
    'did you lock the door',
    'set the alarm',
    'is the door locked',
    'i love you so much',
    'cant wait to see you',
    'travel safe',
    'have fun',
    'be careful',
    'watch the weather',
    'theres a storm coming',
    'drive slow',
    'roads are icy',
    'text me updates',
    'keep me posted',
    'let me know',
    'lmk',
    'whats the plan',
    'whats going on',
    'fyi',
    'thanks honey',
    'thank you sweetie',
    'ok thanks',
    'got it',
    'will do',
  ]),

  'Things a gym bro says': new Set([
    'you even lift',
    'its leg day',
    'we go jim',
    'one more rep',
    'protein',
    'no pain no gain',
    'are you using this',
    'spot me',
    'do you even',
    'rest day is for the weak',
    'we go gym',
    'you mirin',
    'do you even lift',
    'how much you bench',
    'whats your max',
    'whats your pr',
    'new pr',
    'pr today',
    'lets get this bread',
    'lets get it',
    'lets go',
    'time to get swole',
    'gains',
    'all about those gains',
    'no days off',
    'rise and grind',
    'beast mode',
    'go beast mode',
    'lock in',
    'time to lock in',
    'send it',
    'we ball',
    'light weight',
    'lightweight baby',
    'aint nothing but a peanut',
    'push push push',
    'one more',
    'last one',
    'all you',
    'its all you bro',
    'i got you',
    'i got you bro',
    'you got this',
    'dig deep',
    'leave it all here',
    'no excuses',
    'excuses dont build muscle',
    'pain is weakness leaving the body',
    'embrace the pain',
    'feel the burn',
    'time under tension',
    'mind muscle connection',
    'squeeze at the top',
    'control the negative',
    'full range of motion',
    'go to failure',
    'train till failure',
    'drop set',
    'super set',
    'hit it again',
    'reset',
    'breathe',
    'brace your core',
    'tighten up',
    'keep your back straight',
    'drive through your heels',
    'chest up',
    'eyes forward',
    'explode up',
    'slow on the way down',
    'load the bar',
    'add a plate',
    'throw on another plate',
    'two plates',
    'three plates',
    'are you done with that',
    'mind if i work in',
    'can i work in',
    'how many sets you got left',
    'you almost done',
    'i just need it for a sec',
    'just one set',
    'is this taken',
    'is anyone using this',
    'rerack your weights',
    'put your weights back',
    'wipe down the bench',
    'curls for the girls',
    'sun is out guns out',
    'never skip arm day',
    'never skip leg day',
    'dont skip legs',
    'chicken legs',
    'check out these gains',
    'feeling pumped',
    'getting a pump',
    'the pump is real',
    'i live for the pump',
    'preworkout hits different',
    'did you take pre',
    'where is my shaker',
    'pass the protein',
    'gotta hit my macros',
    'whats your macros',
    'bulking season',
    'im bulking',
    'im cutting',
    'cutting season',
    'dirty bulk',
    'eat big to get big',
    'eat clean train mean',
    'chicken and rice',
    'meal prep sunday',
    'gotta hit my steps',
    'never miss a monday',
    'monday is chest day',
    'its push day',
    'its pull day',
    'push pull legs',
    'leg day is the worst',
    'i cant feel my legs',
    'cant walk tomorrow',
    'doms are real',
    'so sore',
    'feeling it today',
    'good set',
    'good lift',
    'nice rep',
    'thats a clean rep',
    'beautiful',
    'lets run it back',
    'run it back',
    'again',
    'one more set',
    'finish strong',
    'leave nothing in the tank',
    'empty the tank',
    'go heavy or go home',
    'go hard or go home',
    'no pain all gain is a lie',
    'trust the process',
    'consistency is key',
    'show up',
    'just show up',
    'the gym is my therapy',
    'gym is life',
    'gains over everything',
    'rest is for the weak',
    'sleep is for the weak',
    'eat sleep train repeat',
    'we lift',
    'we grind',
    'grind never stops',
    'stay hard',
    'stay hungry',
    'feed the machine',
    'time to feed',
    'get those reps in',
    'reps for days',
    'volume baby',
    'time to grow',
    'muscles need a reason to grow',
    'gotta earn it',
    'you earned that',
    'respect the grind',
    'wheys good',
    'mass gainer',
    'creatine loading',
    'are you natty',
    'natty or not',
    'stay natty',
  ]),

  'Things you say when you stub your toe': new Set([
    'ow',
    'ouch',
    'son of a',
    'mother',
    'why',
    'right in the corner',
    'dang it',
    'shoot',
    'ah',
    'who put that there',
    'crap',
    'ouchie',
    'oww',
    'owie',
    'oof',
    'agh',
    'argh',
    'ugh',
    'gah',
    'eek',
    'yeow',
    'yowza',
    'yikes',
    'oh no',
    'oh man',
    'oh come on',
    'come on',
    'are you kidding me',
    'you have got to be kidding me',
    'seriously',
    'really',
    'for real',
    'not again',
    'every time',
    'every single time',
    'why me',
    'why now',
    'of course',
    'great',
    'just great',
    'wonderful',
    'perfect',
    'fantastic',
    'son of a biscuit',
    'sugar',
    'fudge',
    'dang',
    'darn',
    'darn it',
    'dang it all',
    'gosh',
    'gosh darn it',
    'good grief',
    'for the love of',
    'oh for the love of',
    'mother of pearl',
    'cheese and crackers',
    'what the heck',
    'heck',
    'flip',
    'frick',
    'fricking corner',
    'stupid corner',
    'stupid table',
    'stupid chair',
    'dumb table',
    'dumb couch',
    'who moved the couch',
    'why is that there',
    'who left this here',
    'that hurt',
    'that really hurt',
    'that hurt so bad',
    'it hurts',
    'it really hurts',
    'my toe',
    'my poor toe',
    'not my toe',
    'my little toe',
    'my pinky toe',
    'right on the pinky',
    'pinky toe again',
    'i think its broken',
    'i broke my toe',
    'its definitely broken',
    'i felt that in my soul',
    'i felt that one',
    'right in the bone',
    'down to the bone',
    'i need to sit down',
    'i have to sit down',
    'give me a second',
    'hold on',
    'one second',
    'breathe through it',
    'just breathe',
    'walk it off',
    'gotta walk it off',
    'im fine',
    'im okay',
    'im good',
    'no im not okay',
    'im not fine',
    'help',
    'somebody help',
    'i cant walk',
    'i cant move',
    'dont touch it',
    'do not touch me',
    'leave me alone',
    'give me a minute',
    'im dying',
    'this is the end',
    'goodbye world',
    'tell my family i love them',
    'why does this always happen',
    'cursed corner',
    'i hate this house',
    'i hate that table',
    'move that thing',
    'someone move it',
    'whose idea was this',
    'whoa',
    'whoo',
    'sheesh',
    'jeez',
    'jeez louise',
    'criminy',
    'good lord',
    'oh lord',
    'lord have mercy',
    'have mercy',
    'mercy',
    'make it stop',
    'when will it stop',
    'the throbbing',
    'its throbbing',
    'so much throbbing',
    'right in the funny bone of my foot',
    'no no no',
    'nope',
    'nope nope nope',
    'absolutely not',
    'i quit',
    'im done',
    'thats it',
    'that does it',
    'i cant',
    'i literally cant',
    'why is everything in my way',
    'who designed this room',
    'too dark in here',
    'i couldnt see',
    'i didnt see it',
    'it came out of nowhere',
    'ambushed',
    'it got me',
    'got me again',
    'every dang time',
    'hopping on one foot',
    'gripping my foot',
    'silent scream',
    'cant even scream',
    'biting my lip',
    'counting to ten',
    'shake it off',
  ]),

  'Things you whisper in a library': new Set([
    'shh',
    'be quiet',
    'wheres the bathroom',
    'can i borrow a pencil',
    'is this seat taken',
    'sorry',
    'do you have the charger',
    'shush',
    'quiet down',
    'keep it down',
    'lower your voice',
    'not so loud',
    'too loud',
    'whisper',
    'use your library voice',
    'people are studying',
    'be respectful',
    'is anyone sitting here',
    'is this taken',
    'mind if i sit here',
    'can i sit here',
    'can you watch my stuff',
    'watch my laptop',
    'save my seat',
    'i found a quiet spot',
    'this spot is taken',
    'is there an outlet',
    'wheres an outlet',
    'do you have a charger',
    'can i borrow your charger',
    'whats the wifi password',
    'is the wifi working',
    'my laptops dying',
    'im at five percent',
    'do you have a pen',
    'can i borrow a pen',
    'do you have an extra pencil',
    'got a highlighter',
    'can i borrow some paper',
    'do you have scrap paper',
    'where are the books',
    'where is this section',
    'how do i find this book',
    'wheres the fiction section',
    'where do i check out',
    'where is the front desk',
    'is the printer working',
    'how do i print',
    'wheres the printer',
    'do they have a copier',
    'how much to print',
    'i need to print something',
    'can you help me find this',
    'do you work here',
    'where can i study',
    'are there study rooms',
    'is there a quiet room',
    'how do i reserve a room',
    'this room is booked',
    'can we use this room',
    'are these chairs free',
    'scoot over',
    'can you scoot',
    'excuse me',
    'pardon me',
    'sorry to bother you',
    'real quick question',
    'just one second',
    'hold on let me grab my stuff',
    'be right back',
    'watch my seat',
    'im stepping out',
    'getting water',
    'getting coffee',
    'do they allow drinks',
    'no food allowed',
    'is food okay in here',
    'i need a break',
    'lets take a break',
    'want to grab a snack',
    'im so tired',
    'im falling asleep',
    'this is so boring',
    'i cant focus',
    'i have a test tomorrow',
    'i havent studied at all',
    'im so behind',
    'i need to cram',
    'help me study',
    'quiz me',
    'whats the answer to this',
    'do you get this',
    'i dont understand this',
    'can you explain this',
    'are you in this class',
    'did you do the reading',
    'what chapter are we on',
    'when is this due',
    'whats on the test',
    'did you take notes',
    'can i see your notes',
    'send me your notes',
    'what did the professor say',
    'i missed class',
    'what did i miss',
    'gum',
    'want some gum',
    'thanks',
    'thank you',
    'no problem',
    'youre welcome',
    'sorry again',
    'my bad',
    'oops',
    'shh somebodys coming',
    'be quiet shes looking',
    'hes staring at us',
    'we are being too loud',
    'lets move',
    'lets find another spot',
    'too crowded',
    'so crowded today',
    'no seats anywhere',
    'i cant find a seat',
    'lets sit upstairs',
    'is it quieter upstairs',
    'the basement is quiet',
    'second floor is silent',
    'someone is snoring',
    'i can hear your music',
    'turn down your headphones',
    'your typing is so loud',
    'youre tapping your pen',
    'stop clicking your pen',
    'whats that smell',
    'are you eating in here',
    'put your phone on silent',
    'silence your phone',
    'your phone is buzzing',
    'turn off your ringer',
    'answer that outside',
    'take the call outside',
    'go talk in the hall',
    'meet me at the entrance',
    'ill be by the door',
    'text me when youre done',
    'almost finished',
    'five more minutes',
    'one more chapter',
    'i need to focus',
    'leave me alone im studying',
    'cant talk now',
    'later okay',
    'see you outside',
    'good luck on your test',
    'we got this',
    'i need coffee',
    'i need a nap',
    'when does the library close',
    'what time do they close',
    'theyre closing soon',
    'last call they said',
    'we have to leave',
    'pack up',
    'lets pack up',
  ]),

  'Things you yell at a sports game': new Set([
    'defense',
    'lets go',
    'come on ref',
    'youre blind',
    'shoot',
    'run',
    'air ball',
    'we want a touchdown',
    'boo',
    'lets go team',
    'go go go',
    'move',
    'pass it',
    'pass the ball',
    'shoot it',
    'shoot the ball',
    'take the shot',
    'dunk it',
    'block that',
    'get the rebound',
    'box out',
    'guard him',
    'cover him',
    'man up',
    'switch',
    'help defense',
    'press them',
    'full court press',
    'hustle',
    'hustle back',
    'get back on d',
    'play defense',
    'lock him up',
    'stop him',
    'dont let him score',
    'foul him',
    'thats a foul',
    'that was a foul',
    'are you serious ref',
    'call it both ways',
    'open your eyes ref',
    'ref youre terrible',
    'worst call ever',
    'thats a bad call',
    'bad call',
    'horrible call',
    'rigged',
    'this is rigged',
    'cheaters',
    'travel',
    'thats traveling',
    'double dribble',
    'carry',
    'thats a carry',
    'three seconds',
    'over the back',
    'offsides',
    'that was offsides',
    'holding',
    'thats holding',
    'pass interference',
    'thats interference',
    'fumble',
    'pick it up',
    'recover it',
    'get the ball',
    'go for it',
    'go for two',
    'kick the field goal',
    'punt it',
    'first down',
    'we need a first down',
    'we need a stop',
    'we need a basket',
    'we need a goal',
    'score',
    'put it in',
    'in the net',
    'top corner',
    'top shelf',
    'shoot it already',
    'take the open shot',
    'youre wide open',
    'hes wide open',
    'whos guarding him',
    'somebody guard him',
    'where is the defense',
    'wake up defense',
    'come on guys',
    'come on now',
    'lets go boys',
    'lets go girls',
    'you got this',
    'finish it',
    'close it out',
    'seal the win',
    'dont let up',
    'keep pushing',
    'keep going',
    'dont give up',
    'never give up',
    'fight',
    'fight for it',
    'win it',
    'we want a win',
    'we want a goal',
    'overtime baby',
    'lets go to overtime',
    'one more point',
    'two minute drill',
    'run the clock',
    'kill the clock',
    'time out',
    'call time out',
    'we need a time out',
    'sub him out',
    'bring in the bench',
    'put me in coach',
    'coach put him in',
    'bench him',
    'take him out',
    'hes tired',
    'give him a break',
    'great play',
    'what a play',
    'beautiful pass',
    'nice shot',
    'good catch',
    'great catch',
    'whatta hit',
    'that was clean',
    'unbelievable',
    'no way',
    'are you kidding',
    'how did he miss that',
    'how do you miss that',
    'wide open and you miss',
    'butterfingers',
    'catch the ball',
    'hold onto it',
    'dont drop it',
    'eyes on the ball',
    'watch the ball',
    'heads up',
    'look out',
    'incoming',
    'duck',
    'wooo',
    'yeah',
    'lets gooo',
    'thats what im talking about',
    'now were talking',
    'finally',
    'about time',
    'attaboy',
    'attagirl',
    'thatta way',
    'way to go',
    'great job',
    'good hustle',
    'nice hustle',
    'keep it up',
    'were winning',
    'we got em',
    'were so back',
    'comeback time',
    'rally',
    'lets rally',
    'one more stop',
    'd up',
    'lock it down',
    'no easy buckets',
    'make em work',
  ]),

  'First things you do when you wake up': new Set([
    'check phone',
    'hit snooze',
    'pee',
    'brush teeth',
    'coffee',
    'stretch',
    'scroll instagram',
    'turn off alarm',
    'lay there',
    'check the time',
    'look at the clock',
    'check notifications',
    'check texts',
    'read texts',
    'reply to texts',
    'check email',
    'check my messages',
    'open instagram',
    'open tiktok',
    'scroll tiktok',
    'check twitter',
    'scroll twitter',
    'check snapchat',
    'open snapchat',
    'check social media',
    'doomscroll',
    'rub my eyes',
    'yawn',
    'groan',
    'roll over',
    'go back to sleep',
    'fall back asleep',
    'snooze again',
    'hit snooze again',
    'snooze five more minutes',
    'lie in bed',
    'stay in bed',
    'stare at the ceiling',
    'lay in the dark',
    'just lay there',
    'wonder what day it is',
    'remember what day it is',
    'realize im late',
    'panic',
    'jump out of bed',
    'sit up',
    'stand up',
    'stretch my arms',
    'crack my back',
    'crack my neck',
    'wiggle my toes',
    'feel around for my phone',
    'find my phone',
    'unplug my phone',
    'check the weather',
    'check the news',
    'turn on the light',
    'open the curtains',
    'open the blinds',
    'let the light in',
    'squint at the light',
    'cover my eyes',
    'pull the covers back over my head',
    'make the bed',
    'leave the bed unmade',
    'go to the bathroom',
    'use the bathroom',
    'splash water on my face',
    'wash my face',
    'brush my hair',
    'fix my hair',
    'look in the mirror',
    'shower',
    'take a shower',
    'jump in the shower',
    'put in contacts',
    'put on glasses',
    'find my glasses',
    'drink water',
    'chug water',
    'get a glass of water',
    'make coffee',
    'start the coffee',
    'pour coffee',
    'drink coffee',
    'make tea',
    'put the kettle on',
    'eat breakfast',
    'make breakfast',
    'skip breakfast',
    'grab a snack',
    'feed the dog',
    'feed the cat',
    'let the dog out',
    'walk the dog',
    'take my meds',
    'take my vitamins',
    'take my medicine',
    'check my to do list',
    'plan my day',
    'think about my day',
    'dread the day',
    'dread going to work',
    'hit the alarm one more time',
    'wonder why im tired',
    'complain about being tired',
    'wish i could sleep more',
    'pray for five more minutes',
    'turn on the news',
    'turn on music',
    'put on a playlist',
    'open the fridge',
    'stare into the fridge',
    'pick out clothes',
    'get dressed',
    'find something to wear',
    'put on clothes',
    'change',
    'put on slippers',
    'put on socks',
    'find my slippers',
    'sit on the edge of the bed',
    'sit there for a minute',
    'gather myself',
    'take a deep breath',
    'mentally prepare',
    'check my reflection',
    'wash up',
    'rinse my mouth',
    'use mouthwash',
    'floss',
    'put on deodorant',
    'do my skincare',
    'wash my hands',
    'check the mirror again',
    'stretch my legs',
    'do a little stretch',
    'touch my toes',
    'open the window',
    'get some air',
    'breathe',
    'remember my dream',
    'try to remember my dream',
    'tell someone my dream',
    'check on the kids',
    'check on the baby',
    'make the kids breakfast',
    'pack lunches',
    'start the kettle',
    'turn off the fan',
    'turn on the heat',
    'check the temperature',
    'put on a robe',
    'shuffle to the kitchen',
    'stumble to the bathroom',
    'flip on the coffee maker',
    'reach for my phone',
    'set a new alarm',
    'check my calendar',
    'see what meetings i have',
  ]),

  'Things you do when the WiFi goes out': new Set([
    'restart the router',
    'unplug it',
    'check other devices',
    'call the company',
    'use data',
    'panic',
    'go outside',
    'blame someone',
    'stare at the wall',
    'unplug the router',
    'plug it back in',
    'unplug the modem',
    'restart the modem',
    'reset the router',
    'turn it off and on',
    'turn it off and back on',
    'wait for the lights to blink',
    'watch the blinking lights',
    'check the router lights',
    'count the blinking lights',
    'jiggle the cables',
    'check the cables',
    'unplug everything',
    'check the connections',
    'wiggle the cord',
    'press the reset button',
    'hold the reset button',
    'check if its just me',
    'ask if anyone elses is working',
    'ask the family if theirs works',
    'yell who broke the internet',
    'blame the kids',
    'blame my roommate',
    'blame the cat',
    'check the bill',
    'see if i paid the bill',
    'wonder if i forgot to pay',
    'check the outage map',
    'google the outage',
    'search is the wifi down',
    'check down detector',
    'tweet at the company',
    'call customer service',
    'wait on hold',
    'sit on hold forever',
    'talk to a robot',
    'press one for english',
    'scream at the automated menu',
    'switch to mobile data',
    'use my hotspot',
    'turn on my hotspot',
    'turn off wifi on my phone',
    'use cellular',
    'check my data usage',
    'worry about my data',
    'ration my data',
    'reconnect to the network',
    'forget the network',
    'rejoin the wifi',
    'retype the password',
    'check the wifi password',
    'try a different network',
    'move closer to the router',
    'stand next to the router',
    'hold my phone in the air',
    'walk around looking for signal',
    'find the best signal spot',
    'go stand by the window',
    'refresh the page',
    'hit refresh',
    'refresh again',
    'reload the page',
    'wait',
    'just wait',
    'wait it out',
    'give it a minute',
    'count to sixty',
    'pace around',
    'sigh loudly',
    'complain',
    'whine about it',
    'get frustrated',
    'lose my mind',
    'throw my hands up',
    'stare at the loading screen',
    'watch the spinning wheel',
    'watch it buffer',
    'wait for it to load',
    'give up',
    'do something else',
    'go for a walk',
    'touch grass',
    'read a book',
    'clean the house',
    'do the dishes',
    'do laundry',
    'do homework',
    'do chores',
    'actually be productive',
    'find a hobby',
    'pick up a book',
    'play a board game',
    'play cards',
    'talk to my family',
    'have a conversation',
    'go to a cafe',
    'use the cafe wifi',
    'go to the library',
    'work from the library',
    'find free wifi',
    'mooch off the neighbors wifi',
    'guess the neighbors password',
    'ask the neighbor for their password',
    'take a nap',
    'go to sleep early',
    'stare at the ceiling',
    'reflect on life',
    'realize how addicted i am',
    'feel disconnected',
    'feel anxious',
    'check my phone anyway',
    'keep tapping the screen',
    'open apps that dont work',
    'try to load instagram',
    'try anyway',
    'pray it comes back',
    'bargain with the router',
    'whisper to the router',
    'beg the router',
    'pat the router',
    'move the router',
    'dust off the router',
    'check if its plugged in',
    'realize it was unplugged',
    'find out someone tripped the cord',
    'check the breaker',
    'check if the power is out',
    'light a candle just in case',
    'wait for tech support',
    'schedule a technician',
    'book a service call',
    'order a new router',
    'consider switching providers',
    'threaten to cancel',
    'finally it comes back',
    'celebrate when it returns',
    'thank the wifi gods',
    'do absolutely nothing',
    'stare into space',
    'contemplate existence',
  ]),

  'Things that hit different at night': new Set([
    'overthinking',
    'shower thoughts',
    'sad songs',
    'midnight snacks',
    'old text messages',
    'existential dread',
    'random memories',
    'youtube rabbit holes',
    'overthinking everything',
    'thinking about your ex',
    'texting your ex',
    'wanting to text your ex',
    'old photos',
    'looking at old pictures',
    'scrolling through old messages',
    'reading old conversations',
    'cringe memories',
    'embarrassing memories',
    'remembering that one thing you said',
    'replaying awkward moments',
    'thinking about everyone youve lost touch with',
    'missing old friends',
    'missing people',
    'nostalgia',
    'childhood memories',
    'thinking about the past',
    'regret',
    'regretting your choices',
    'questioning your life choices',
    'wondering where it all went wrong',
    'life decisions',
    'big life questions',
    'thinking about the future',
    'worrying about the future',
    'fear of the future',
    'wondering whats the point',
    'thinking about space',
    'how big the universe is',
    'are we alone in the universe',
    'thinking about death',
    'mortality',
    'realizing time is passing',
    'how fast time goes',
    'getting older',
    'thinking about your age',
    'random anxiety',
    'anxiety spikes',
    'sudden sadness',
    'feeling lonely',
    'loneliness',
    'feeling everything at once',
    'all your emotions',
    'deep thoughts',
    'philosophical thoughts',
    'random epiphanies',
    'sudden clarity',
    'understanding song lyrics',
    'really feeling the music',
    'a good playlist',
    'lofi beats',
    'rainy night vibes',
    'the sound of rain',
    'thunderstorms',
    'a cool breeze',
    'fresh air at night',
    'looking at the stars',
    'stargazing',
    'the moon',
    'a full moon',
    'city lights',
    'driving at night',
    'late night drives',
    'an empty highway',
    'streetlights passing by',
    'a long walk',
    'late night walks',
    'comfort food',
    'a warm meal',
    'ice cream',
    'cereal at midnight',
    'leftovers at 2am',
    'ordering food late',
    'a warm shower',
    'a hot bath',
    'fresh sheets',
    'clean sheets',
    'a cold pillow',
    'the cold side of the pillow',
    'a cozy blanket',
    'being warm under the covers',
    'rain on the window',
    'wind outside',
    'silence',
    'total quiet',
    'the quiet of the house',
    'everyone else asleep',
    'being the only one awake',
    'a deep conversation',
    'talking until 3am',
    'late night phone calls',
    'voice memos',
    'heart to hearts',
    'opening up',
    'vulnerable conversations',
    'a movie that makes you cry',
    'sad movies',
    'romance movies',
    'a really good book',
    'reading late',
    'getting lost in a story',
    'video essays',
    'documentaries',
    'true crime',
    'conspiracy theories',
    'wikipedia at midnight',
    'googling random things',
    'late night thoughts',
    'planning your whole life',
    'making big plans',
    'sudden motivation',
    'inspiration',
    'creative ideas',
    'wanting to start over',
    'wanting to change your life',
    'deciding to be a better person',
    'gratitude',
    'feeling grateful',
    'appreciating the little things',
    'hope',
    'random hope',
    'a sudden craving',
    'craving something sweet',
    'craving fast food',
    'a midnight snack run',
    'coffee at midnight',
    'tea before bed',
    'warm milk',
    'hot chocolate',
    'candlelight',
    'dim lighting',
    'fairy lights',
    'a good smell',
    'the smell of rain',
    'campfire smell',
    'cuddling',
    'a hug',
    'being held',
    'someones heartbeat',
    'falling asleep on a call',
    'pillow talk',
    'whispering in the dark',
    'feeling small',
    'feeling everything deeply',
    'crying for no reason',
    'random tears',
    'laughing at nothing',
    'the giggles at 2am',
    'delirium from being tired',
  ]),

  'Excuses for not texting back': new Set([
    'i fell asleep',
    'i didnt see it',
    'my phone died',
    'i was gonna reply',
    'i thought i did',
    'i was busy',
    'i forgot',
    'no signal',
    'i was driving',
    'i was at work',
    'i was in a meeting',
    'i was in class',
    'i was in the shower',
    'i was eating',
    'i was sleeping',
    'i just woke up',
    'i passed out',
    'i dozed off',
    'i took a nap',
    'i was napping',
    'my phone was on silent',
    'my phone was on do not disturb',
    'i had it on dnd',
    'my notifications were off',
    'i never got the text',
    'it never came through',
    'the text didnt deliver',
    'it didnt go through',
    'i thought i replied',
    'i swear i answered',
    'i replied in my head',
    'i drafted a reply',
    'i started to reply',
    'i meant to reply',
    'i was about to text you',
    'i was just about to',
    'i had it open and forgot',
    'i opened it and got distracted',
    'i got sidetracked',
    'i got distracted',
    'something came up',
    'i got pulled away',
    'i had to run',
    'i had to go',
    'i was running errands',
    'i was out and about',
    'i lost track of time',
    'time got away from me',
    'i lost my phone',
    'i couldnt find my phone',
    'my phone was in the other room',
    'i left my phone at home',
    'i left it in the car',
    'i left it on the charger',
    'my phone was charging',
    'i was at zero percent',
    'my battery died',
    'i had no charger',
    'i ran out of battery',
    'i had no service',
    'i had no reception',
    'i was out of signal',
    'i was in a dead zone',
    'i was in the basement',
    'i was on a flight',
    'i was on airplane mode',
    'i forgot to take it off airplane mode',
    'i was traveling',
    'i was on the road',
    'i was on the subway',
    'i had no wifi',
    'my wifi was down',
    'i was swamped',
    'i was slammed at work',
    'work was crazy',
    'i had a long day',
    'i was exhausted',
    'i was so tired',
    'i crashed early',
    'i went to bed early',
    'i fell asleep early',
    'i was knocked out',
    'i was busy all day',
    'my day was insane',
    'it was a hectic day',
    'i had family stuff',
    'i was with family',
    'i was hanging with friends',
    'i was out with friends',
    'i was on a date',
    'i was at the gym',
    'i was working out',
    'i was studying',
    'i had homework',
    'i had a deadline',
    'i was grinding',
    'i had a lot going on',
    'life has been crazy',
    'things have been hectic',
    'ive been overwhelmed',
    'ive been stressed',
    'im so sorry i forgot',
    'i totally spaced',
    'it slipped my mind',
    'it completely slipped my mind',
    'i blanked',
    'i went ghost by accident',
    'i didnt mean to leave you on read',
    'i didnt mean to ignore you',
    'i wasnt ignoring you',
    'i promise i wasnt ghosting you',
    'i thought i sent it',
    'i thought i hit send',
    'autocorrect ate my reply',
    'my message didnt save',
    'i typed it but forgot to send',
    'i wrote it out and never sent it',
    'i saw it but couldnt reply then',
    'i was gonna call instead',
    'i figured id call later',
    'i wanted to reply properly',
    'i needed time to think',
    'i didnt know what to say',
    'i was overthinking my reply',
    'i was figuring out a response',
    'i needed to check my schedule first',
    'i was waiting to hear back from someone',
    'i wanted to give you a real answer',
    'i kept meaning to get back to you',
    'i had a million tabs open',
    'my brain forgot',
    'my memory is terrible',
    'i have the worst memory',
    'i get distracted so easily',
    'my notifications got buried',
    'it got lost in my notifications',
    'i have too many group chats',
    'i missed it in the chaos',
    'i didnt hear it buzz',
    'i never heard the notification',
    'it was on vibrate',
    'i was in a movie',
    'i was at the movies',
    'i was at a concert',
    'i was at an event',
    'i was at a wedding',
    'i was at a funeral',
    'i was sick',
    'i wasnt feeling well',
    'i was in bed sick',
    'i had a headache',
    'i needed a mental break',
    'i was taking a break from my phone',
    'i was doing a digital detox',
    'i was off the grid',
    'i was camping',
    'i had no phone all weekend',
  ]),
};
